PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZACCDTUOM CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZACCDTUOM-WERKS .
    FIELD ZACCDTUOM-MATNR .
    FIELD ZACCDTUOM-MEINS .
    FIELD ZACCDTUOM-UMREZ1 .
    FIELD ZACCDTUOM-UMREN1 .
    FIELD ZACCDTUOM-MEINH1 .
    FIELD ZACCDTUOM-UMREZ2 .
    FIELD ZACCDTUOM-UMREN2 .
    FIELD ZACCDTUOM-MEINH2 .
    FIELD ZACCDTUOM-UMREZ3 .
    FIELD ZACCDTUOM-UMREN3 .
    FIELD ZACCDTUOM-MEINH3 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZACCDTUOM-WERKS .
    FIELD ZACCDTUOM-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
