*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZALOKTR01TOP.                     " Global Data
  INCLUDE LZALOKTR01UXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZALOKTR01F00                           . " subprograms
  INCLUDE LZALOKTR01I00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZALOKTR01F...                     " Subprograms
* INCLUDE LZALOKTR01O...                     " PBO-Modules
* INCLUDE LZALOKTR01I...                     " PAI-Modules
