*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZALOKTR02TOP.                     " Global Data
  INCLUDE LZALOKTR02UXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZALOKTR02F00                           . " subprograms
  INCLUDE LZALOKTR02I00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZALOKTR02F...                     " Subprograms
* INCLUDE LZALOKTR02O...                     " PBO-Modules
* INCLUDE LZALOKTR02I...                     " PAI-Modules
