PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZALOKTR01 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZALOKTR01-BUKRS .
    FIELD ZALOKTR01-GJAHR .
    FIELD ZALOKTR01-REVTYP .
    FIELD ZALOKTR01-ZGRP .
    FIELD ZALOKTR01-ZSGRP .
    FIELD ZALOKTR01-KOSTL .
    FIELD ZALOKTR01-FACTOR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZALOKTR01-BUKRS .
    FIELD ZALOKTR01-GJAHR .
    FIELD ZALOKTR01-REVTYP .
    FIELD ZALOKTR01-ZGRP .
    FIELD ZALOKTR01-ZSGRP .
    FIELD ZALOKTR01-KOSTL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
