*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBDCDT02TOP.                      " Global Data
  INCLUDE LZBDCDT02UXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBDCDT02F00                            . " subprograms
  INCLUDE LZBDCDT02I00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBDCDT02F...                      " Subprograms
* INCLUDE LZBDCDT02O...                      " PBO-Modules
* INCLUDE LZBDCDT02I...                      " PAI-Modules
