*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBDCDT01TOP.                      " Global Data
  INCLUDE LZBDCDT01UXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBDCDT01F00                            . " subprograms
  INCLUDE LZBDCDT01I00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBDCDT01F...                      " Subprograms
* INCLUDE LZBDCDT01O...                      " PBO-Modules
* INCLUDE LZBDCDT01I...                      " PAI-Modules
