PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBDCDT02 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBDCDT02-COONO .
    FIELD ZBDCDT02-POSNR .
    FIELD ZBDCDT02-MATNR .
    FIELD ZBDCDT02-EBELN_FC .
    FIELD ZBDCDT02-VBELN_FC .
    FIELD ZBDCDT02-EBELN_MK .
    FIELD ZBDCDT02-VBELN_MK .
    FIELD ZBDCDT02-EBELN_AL .
    FIELD ZBDCDT02-VBELN_AL .
    FIELD ZBDCDT02-ZENDM .
    FIELD ZBDCDT02-ZDCSTS .
    FIELD ZBDCDT02-COODT .
    FIELD ZBDCDT02-COOTM .
    FIELD ZBDCDT02-COONM .
    FIELD ZBDCDT02-MEINS .
    FIELD ZBDCDT02-ZQTY .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBDCDT02-COONO .
    FIELD ZBDCDT02-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
