PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBDCDT01 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBDCDT01-ZPOTYP .
    FIELD ZBDCDT01-DBTABNAME .
    FIELD ZBDCDT01-FIELDNAME .
    FIELD ZBDCDT01-NUMB .
    FIELD ZBDCDT01-SIGN .
    FIELD ZBDCDT01-OPTI .
    FIELD ZBDCDT01-LOW .
    FIELD ZBDCDT01-HIGH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBDCDT01-ZPOTYP .
    FIELD ZBDCDT01-DBTABNAME .
    FIELD ZBDCDT01-FIELDNAME .
    FIELD ZBDCDT01-NUMB .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
