PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCLNUMBER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCLNUMBER-KDGRP .
    FIELD ZCLNUMBER-DATAB .
    FIELD ZCLNUMBER-DATBI .
    FIELD ZCLNUMBER-MATKL .
    FIELD ZCLNUMBER-SKPNR .
    FIELD ZCLNUMBER-CLNR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCLNUMBER-KDGRP .
    FIELD ZCLNUMBER-DATAB .
    FIELD ZCLNUMBER-DATBI .
    FIELD ZCLNUMBER-MATKL .
    FIELD ZCLNUMBER-SKPNR .
    FIELD ZCLNUMBER-CLNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
