*&---------------------------------------------------------------------*
*&  Include           ZCO_RCOGMTOP
*&---------------------------------------------------------------------*
TABLES : caufv, sscrfields.

CLASS : lcl_application DEFINITION DEFERRED.

TYPES : BEGIN OF ty_out,
          mark,
          icon(4),
          plnbez    TYPE caufv-plnbez,
          aufnr     TYPE caufv-aufnr,
          charg     TYPE afpo-charg,
          stlal     TYPE afko-stlal,
          stktx     TYPE stko-stktx,
          verid     TYPE afpo-verid,
          megbtr    TYPE covp-megbtr,
          gamng     TYPE caufv-gamng,
          meinh     TYPE covp-meinh,
          raact     TYPE covp-wkgbtr,
          paact     TYPE covp-wkgbtr,
          laact     TYPE covp-wkgbtr,
          nlact     TYPE covp-wkgbtr,
          waers     TYPE tka01-waers,
          toact     TYPE covp-wkgbtr,
          raacu     TYPE covp-wkgbtr,
          paacu     TYPE covp-wkgbtr,
          laacu     TYPE covp-wkgbtr,
          nlacu     TYPE covp-wkgbtr,
          toacu     TYPE covp-wkgbtr,
          rastd     TYPE covp-wkgbtr,
          pastd     TYPE covp-wkgbtr,
          lastd     TYPE covp-wkgbtr,
          nlstd     TYPE covp-wkgbtr,
          tostd     TYPE covp-wkgbtr,
          rastu     TYPE covp-wkgbtr,
          pastu     TYPE covp-wkgbtr,
          lastu     TYPE covp-wkgbtr,
          nlstu     TYPE covp-wkgbtr,
          tostu     TYPE covp-wkgbtr,
          lahac     TYPE covp-wkgbtr,
          nlhac     TYPE covp-wkgbtr,
          lahst     TYPE covp-wkgbtr,
          nlhst     TYPE covp-wkgbtr,
          rlaac     TYPE p DECIMALS 2,
          rnlac     TYPE p DECIMALS 2,
          rlast     TYPE p DECIMALS 2,
          rnlst     TYPE p DECIMALS 2,
          total     TYPE covp-wkgbtr,
          topct     TYPE p DECIMALS 2,
          indi1(4),
          sttxt     TYPE bsvx-sttxt,
          style     TYPE lvc_t_styl,
          color     TYPE lvc_t_scol,
        END OF ty_out.

DATA : ok_code           TYPE sy-ucomm,
       gs_exclude        TYPE ui_functions,
       g_customcont      TYPE REF TO cl_gui_custom_container,
       g_splitter        TYPE REF TO cl_gui_splitter_container,
       g_splitter1       TYPE REF TO cl_gui_splitter_container,
       g_contain01       TYPE REF TO cl_gui_container,
       g_contain02       TYPE REF TO cl_gui_container,
       g_contain03       TYPE REF TO cl_gui_container,
       g_contain04       TYPE REF TO cl_gui_container,
       g_tabgrid         TYPE REF TO cl_gui_alv_grid,
       event_receiver    TYPE REF TO lcl_application,
       selected          VALUE 'X',
       gv_repid          LIKE sy-repid,
       gs_variant        LIKE disvariant,
       gs_layout_alv     TYPE lvc_s_layo,
       gt_main_sort      TYPE lvc_t_sort WITH HEADER LINE,
       gt_main_fieldcat  TYPE lvc_t_fcat,
       gs_stable         TYPE lvc_s_stbl,
       gs_toolbar        TYPE stb_button,
       gr_hierseq        TYPE REF TO cl_salv_hierseq_table,
       gr_table          TYPE REF TO cl_salv_table,
       g_handle_alv      TYPE i,
       gt_bapiret2       TYPE STANDARD TABLE OF bapiret2.

DATA : gt_out            TYPE STANDARD TABLE OF ty_out.

DATA : gr_datum          TYPE RANGE OF sy-datum,
       gt_caufv          TYPE STANDARD TABLE OF caufv,
       gt_afko           TYPE STANDARD TABLE OF afko,
       gt_afpo           TYPE STANDARD TABLE OF afpo,
       gt_stko           TYPE STANDARD TABLE OF stko,
       gt_covp           TYPE STANDARD TABLE OF covp,
       gt_xcovp          TYPE STANDARD TABLE OF covp,
       gt_cosp           TYPE STANDARD TABLE OF cosp,
       gt_coss           TYPE STANDARD TABLE OF coss,
       gt_resb           TYPE STANDARD TABLE OF resb,
       gt_mbew           TYPE STANDARD TABLE OF mbew,
       gt_fmbew          TYPE STANDARD TABLE OF mbew,
       gt_ckmlcr         TYPE STANDARD TABLE OF ckmlcr,
       gt_mara           TYPE STANDARD TABLE OF mara,
       gt_ckmlprkeph     TYPE STANDARD TABLE OF ckmlprkeph,
       gt_mlcd           TYPE STANDARD TABLE OF mlcd,
       gt_keko           TYPE STANDARD TABLE OF keko,
       gt_jcds           TYPE STANDARD TABLE OF jcds.

DATA : gv_waers          TYPE tka01-waers.
