*&---------------------------------------------------------------------*
*&  Include           ZDG2FI_F0013TOP
*&---------------------------------------------------------------------*
TABLES: sscrfields,mara,mkal,plpo,crhd.

TYPE-POOLS: truxs.

TYPES: BEGIN OF g_ty_s_event,
         user_command                 TYPE char1,
         before_user_command          TYPE char1,
         after_user_command           TYPE char1,
         double_click                 TYPE char1,
         hotspot_click                TYPE char1,
         button_click                 TYPE char1,
         onf1                         TYPE char1,
         onf4                         TYPE char1,
         menu_button                  TYPE char1,
         toolbar                      TYPE char1,
         context_menu_request         TYPE char1,
         ondrag                       TYPE char1,
         ondrop                       TYPE char1,
         ondropcomplete               TYPE char1,
         ondropgetflavor              TYPE char1,
         subtotal_text                TYPE char1,
         data_changed                 TYPE char1,
         data_changed_finished        TYPE char1,
         after_refresh                TYPE char1,
         delayed_callback             TYPE char1,
         delayed_changed_sel_callback TYPE char1,
         top_of_page                  TYPE char1,
         end_of_list                  TYPE char1,
         print_top_of_page            TYPE char1,
         print_end_of_page            TYPE char1,
         print_top_of_list            TYPE char1,
         print_end_of_list            TYPE char1,
       END   OF g_ty_s_event,

       BEGIN OF g_ty_s_onf4,
         register        TYPE char1,
         get_before      TYPE char1,
         change_after    TYPE char1,
         internal_format TYPE char1,
       END   OF g_ty_s_onf4,

       BEGIN OF g_ty_s_test,
         select_amount      TYPE i,
         no_info_popup      TYPE char1,
         info_popup_once    TYPE char1,
         events_info_popup  TYPE lvc_fname OCCURS 0,
         application_events TYPE char1,
         event              TYPE g_ty_s_event,
         onf4               TYPE g_ty_s_onf4,
         button_fields      TYPE lvc_fname OCCURS 0,
         hotspot_fields     TYPE lvc_fname OCCURS 0,
         onf1_fields        TYPE lvc_fname OCCURS 0,
         onf4_fields        TYPE lvc_fname OCCURS 0,
         bypassing_buffer   TYPE char1,
         buffer_active      TYPE char1,
       END   OF g_ty_s_test.

* Refrence Objects To Alv Grid & Custom Container Classes
DATA: g_container TYPE scrfname VALUE 'CONTAINER',
      g_grid      TYPE REF TO cl_gui_alv_grid,
*      g_handler   TYPE REF TO lcl_event_responder,
*      g_event_handler TYPE REF TO lcl_event_handler,
      g_custom_container TYPE REF TO cl_gui_custom_container,
      gt_fieldcat TYPE lvc_t_fcat WITH HEADER LINE,
      gt_sort     TYPE lvc_t_sort WITH HEADER LINE,
      gs_layout   TYPE lvc_s_layo,
      gv_repid    LIKE sy-repid,
      gs_variant  TYPE disvariant,
      gt_exclude  TYPE ui_functions,
      e_object    TYPE REF TO cl_alv_event_toolbar_set.

DATA: gs_test TYPE g_ty_s_test.

DATA: gv_row      TYPE lvc_s_row,
      gv_column   TYPE lvc_s_col,
      gv_row_num  TYPE lvc_s_roid.

DATA:
* Reference to document
       dg_dyndoc_id       TYPE REF TO cl_dd_document,
* Reference to split container
       dg_splitter        TYPE REF TO cl_gui_splitter_container,
* Reference to grid container
       dg_parent_grid     TYPE REF TO cl_gui_container,
* Reference to html container
       dg_html_cntrl      TYPE REF TO cl_gui_html_viewer,
* Reference to html container
       dg_parent_html     TYPE REF TO cl_gui_container.

DATA: BEGIN OF gt_out OCCURS 0.
DATA:   werks   TYPE werks_d,
        plnnr   TYPE plnnr,
        matnr   TYPE matnr,
        maktx   TYPE maktx,
        arbpl   TYPE arbpl,
        arbid   TYPE objektid,
        ltxa1   TYPE ltxa1,
        ktext   TYPE cr_ktext,
        ktext_up TYPE cr_ktextup,
        kostl   TYPE kostl,
        ltext   TYPE kltxt,
        mctxt   TYPE mcds3,
        vge02   TYPE vgwrteh,
        vgw02   TYPE vgwrt,
        vge03   TYPE vgwrteh,
        vgw03   TYPE vgwrt,
        vge04   TYPE vgwrteh,
        vgw04   TYPE vgwrt,
        labor   TYPE vgwrt,
        nlabor  TYPE vgwrt,
        meinh   TYPE vorme,
        umren   TYPE cp_umren,
        bmsch   TYPE bmsch,
        umrez   TYPE cp_umrez,
*        chbox       TYPE char1,
*        celltab     TYPE lvc_t_styl,
      END OF gt_out.

DATA: BEGIN OF gt_outsum OCCURS 0,
        werks   TYPE werks_d,
        plnnr   TYPE plnnr,
        matnr   TYPE matnr,
        maktx   TYPE maktx,
        meinh   TYPE vorme,
        umren   TYPE cp_umren,
        bmsch   TYPE bmsch,
        mksp    TYPE char50,
        labor1  TYPE vgwrt,
        nlabor1 TYPE vgwrt,
        labor2  TYPE vgwrt,
        nlabor2 TYPE vgwrt,
        labor3  TYPE vgwrt,
        nlabor3 TYPE vgwrt,
        labor4  TYPE vgwrt,
        nlabor4 TYPE vgwrt,
        labor5  TYPE vgwrt,
        nlabor5 TYPE vgwrt,
        labor6  TYPE vgwrt,
        nlabor6 TYPE vgwrt,
        labor7  TYPE vgwrt,
        nlabor7 TYPE vgwrt,
        labor8  TYPE vgwrt,
        nlabor8 TYPE vgwrt,
        labor9  TYPE vgwrt,
        nlabor9 TYPE vgwrt,
        labor10  TYPE vgwrt,
        nlabor10 TYPE vgwrt,
        labor11  TYPE vgwrt,
        nlabor11 TYPE vgwrt,
        labor12  TYPE vgwrt,
        nlabor12 TYPE vgwrt,
        labor13  TYPE vgwrt,
        nlabor13 TYPE vgwrt,
        labor14  TYPE vgwrt,
        nlabor14 TYPE vgwrt,
        labor15  TYPE vgwrt,
        nlabor15 TYPE vgwrt,
        labor16  TYPE vgwrt,
        nlabor16 TYPE vgwrt,
        labor17  TYPE vgwrt,
        nlabor17 TYPE vgwrt,
        labor18  TYPE vgwrt,
        nlabor18 TYPE vgwrt,
        labor19  TYPE vgwrt,
        nlabor19 TYPE vgwrt,
        labor20  TYPE vgwrt,
        nlabor20 TYPE vgwrt,
        labor21  TYPE vgwrt,
        nlabor21 TYPE vgwrt,
        labor22  TYPE vgwrt,
        nlabor22 TYPE vgwrt,
        labor23  TYPE vgwrt,
        nlabor23 TYPE vgwrt,
        labor24  TYPE vgwrt,
        nlabor24 TYPE vgwrt,
        labor25  TYPE vgwrt,
        nlabor25 TYPE vgwrt,
        labor26  TYPE vgwrt,
        nlabor26 TYPE vgwrt,
        labor27  TYPE vgwrt,
        nlabor27 TYPE vgwrt,
        labor28  TYPE vgwrt,
        nlabor28 TYPE vgwrt,
        labor29  TYPE vgwrt,
        nlabor29 TYPE vgwrt,
        labor30  TYPE vgwrt,
        nlabor30 TYPE vgwrt,
        labor31  TYPE vgwrt,
        nlabor31 TYPE vgwrt,
        labor32  TYPE vgwrt,
        nlabor32 TYPE vgwrt,
        labor33  TYPE vgwrt,
        nlabor33 TYPE vgwrt,
        labor34  TYPE vgwrt,
        nlabor34 TYPE vgwrt,
        labor35  TYPE vgwrt,
        nlabor35 TYPE vgwrt,
        labor36  TYPE vgwrt,
        nlabor36 TYPE vgwrt,
        labor37  TYPE vgwrt,
        nlabor37 TYPE vgwrt,
        labor38  TYPE vgwrt,
        nlabor38 TYPE vgwrt,
        labor39  TYPE vgwrt,
        nlabor39 TYPE vgwrt,
        labor40  TYPE vgwrt,
        nlabor40 TYPE vgwrt,
        labor41  TYPE vgwrt,
        nlabor41 TYPE vgwrt,
        labor42  TYPE vgwrt,
        nlabor42 TYPE vgwrt,
        labor43  TYPE vgwrt,
        nlabor43 TYPE vgwrt,
        labor44  TYPE vgwrt,
        nlabor44 TYPE vgwrt,
        labor45  TYPE vgwrt,
        nlabor45 TYPE vgwrt,
        labor46  TYPE vgwrt,
        nlabor46 TYPE vgwrt,
        labor47  TYPE vgwrt,
        nlabor47 TYPE vgwrt,
        labor48  TYPE vgwrt,
        nlabor48 TYPE vgwrt,
        labor49  TYPE vgwrt,
        nlabor49 TYPE vgwrt,
        labor50  TYPE vgwrt,
        nlabor50 TYPE vgwrt,
        labortot  TYPE vgwrt,
        nlabortot TYPE vgwrt,
      END OF gt_outsum.

DATA: BEGIN OF gt_kostl OCCURS 0,
        nomor   TYPE char3,
        kostl   TYPE kostl,
        ltext   TYPE kltxt,
        mctxt   TYPE mcds3,
       END OF gt_kostl.

DATA: gt_mkal TYPE TABLE OF mkal WITH HEADER LINE,
      gt_plpo TYPE TABLE OF plpo WITH HEADER LINE,
      gt_plpo2 TYPE TABLE OF plpo WITH HEADER LINE,
      gt_plpo3 TYPE TABLE OF plpo WITH HEADER LINE,
      gt_plas TYPE TABLE OF plas WITH HEADER LINE,
      gt_crhd TYPE TABLE OF crhd WITH HEADER LINE,
      gt_crtx TYPE TABLE OF crtx WITH HEADER LINE,
      gt_crco TYPE TABLE OF crco WITH HEADER LINE,
      gt_cskt TYPE TABLE OF cskt WITH HEADER LINE,
      gt_makt TYPE TABLE OF makt WITH HEADER LINE,
      gt_mksp TYPE TABLE OF dd07v WITH HEADER LINE.

DATA : gt_plmz  TYPE STANDARD TABLE OF plmz,
       gt_stko  TYPE STANDARD TABLE OF stko.

FIELD-SYMBOLS: <fs_out>    LIKE gt_out,
               <fs_outsum> LIKE gt_outsum.
