*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCODT009TOP.                      " Global Data
  INCLUDE LZCODT009UXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCODT009F00                            . " subprograms
  INCLUDE LZCODT009I00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCODT009F...                      " Subprograms
* INCLUDE LZCODT009O...                      " PBO-Modules
* INCLUDE LZCODT009I...                      " PAI-Modules
