PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCODT009 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCODT009-BUKRS .
    FIELD ZCODT009-WERKS .
    FIELD ZCODT009-BDATJ .
    FIELD ZCODT009-POPER .
    FIELD ZCODT009-MATNR .
    FIELD ZCODT009-ZUSER .
    FIELD ZCODT009-TGLPRS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCODT009-BUKRS .
    FIELD ZCODT009-WERKS .
    FIELD ZCODT009-BDATJ .
    FIELD ZCODT009-POPER .
    FIELD ZCODT009-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
