PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCODT012 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCODT012-BUKRS .
    FIELD ZCODT012-GSBER .
    FIELD ZCODT012-GJAHR .
    FIELD ZCODT012-PERAF .
    FIELD ZCODT012-ANLN1 .
    FIELD ZCODT012-ANLN2 .
    FIELD ZCODT012-KOSTL .
    FIELD ZCODT012-INVZU .
    FIELD ZCODT012-TYPBZ .
    FIELD ZCODT012-WWSEC .
    FIELD ZCODT012-WWTRZ .
    FIELD ZCODT012-AMOUNT .
    FIELD ZCODT012-WAERS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCODT012-BUKRS .
    FIELD ZCODT012-GSBER .
    FIELD ZCODT012-GJAHR .
    FIELD ZCODT012-PERAF .
    FIELD ZCODT012-ANLN1 .
    FIELD ZCODT012-ANLN2 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
