PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCORETAX0009 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCORETAX0009-MASATX .
    FIELD ZCORETAX0009-BELNR .
    FIELD ZCORETAX0009-NONR .
    FIELD ZCORETAX0009-BUDAT .
    FIELD ZCORETAX0009-DPP .
    FIELD ZCORETAX0009-DPPLAIN .
    FIELD ZCORETAX0009-PPN .
    FIELD ZCORETAX0009-WAERS .
    FIELD ZCORETAX0009-SGTXT .
    FIELD ZCORETAX0009-AEDAT .
    FIELD ZCORETAX0009-AEZET .
    FIELD ZCORETAX0009-AENAM .
    FIELD ZCORETAX0009-ZFILENAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCORETAX0009-MASATX .
    FIELD ZCORETAX0009-BELNR .
    FIELD ZCORETAX0009-NONR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
