PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCORETAX0002 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCORETAX0002-NAME .
    FIELD ZCORETAX0002-VALUE .
    FIELD ZCORETAX0002-KIND .
    FIELD ZCORETAX0002-ZTYPE .
    FIELD ZCORETAX0002-ZFORMAT .
    FIELD ZCORETAX0002-STATUS .
    FIELD ZCORETAX0002-NOURUT .
    FIELD ZCORETAX0002-NOPARENT .
    FIELD ZCORETAX0002-NODESPARENT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCORETAX0002-NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
