PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCORETAX0005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCORETAX0005-BUKRS .
    FIELD ZCORETAX0005-TYPE .
    FIELD ZCORETAX0005-MASATX .
    FIELD ZCORETAX0005-VKBUR .
    FIELD ZCORETAX0005-ZUONR .
    FIELD ZCORETAX0005-BELNR .
    FIELD ZCORETAX0005-NONR .
    FIELD ZCORETAX0005-FAKTURNO .
    FIELD ZCORETAX0005-PENANDATANGAN .
    FIELD ZCORETAX0005-STATUS_FAKTUR .
    FIELD ZCORETAX0005-TGLPRS .
    FIELD ZCORETAX0005-FILES .
    FIELD ZCORETAX0005-ERNAM .
    FIELD ZCORETAX0005-ERDAT .
    FIELD ZCORETAX0005-ERZET .
    FIELD ZCORETAX0005-BUYERTIN .
    FIELD ZCORETAX0005-BUYERDOCUMENT .
    FIELD ZCORETAX0005-NPWPPEMBELI .
    FIELD ZCORETAX0005-NAMAPEMBELI .
    FIELD ZCORETAX0005-DPP .
    FIELD ZCORETAX0005-DPPLAIN .
    FIELD ZCORETAX0005-PPN .
    FIELD ZCORETAX0005-PPNBM .
    FIELD ZCORETAX0005-REFERENSI .
    FIELD ZCORETAX0005-AEDAT .
    FIELD ZCORETAX0005-AEZET .
    FIELD ZCORETAX0005-AENAM .
    FIELD ZCORETAX0005-ZFILENAME .
    FIELD ZCORETAX0005-ESIGNSTATUS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCORETAX0005-BUKRS .
    FIELD ZCORETAX0005-TYPE .
    FIELD ZCORETAX0005-MASATX .
    FIELD ZCORETAX0005-VKBUR .
    FIELD ZCORETAX0005-ZUONR .
    FIELD ZCORETAX0005-BELNR .
    FIELD ZCORETAX0005-NONR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
