PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCORETAX0007 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCORETAX0007-BUKRS .
    FIELD ZCORETAX0007-SIGN .
    FIELD ZCORETAX0007-ZOPTION .
    FIELD ZCORETAX0007-LOW .
    FIELD ZCORETAX0007-HIGH .
    FIELD ZCORETAX0007-BSCHL .
    FIELD ZCORETAX0007-STATUS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCORETAX0007-BUKRS .
    FIELD ZCORETAX0007-SIGN .
    FIELD ZCORETAX0007-ZOPTION .
    FIELD ZCORETAX0007-LOW .
    FIELD ZCORETAX0007-HIGH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
