*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDGFIDT006TOP.                    " Global Data
  INCLUDE LZDGFIDT006UXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDGFIDT006F00                          . " subprograms
  INCLUDE LZDGFIDT006I00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDGFIDT006F...                    " Subprograms
* INCLUDE LZDGFIDT006O...                    " PBO-Modules
* INCLUDE LZDGFIDT006I...                    " PAI-Modules
