PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDGPPEDT007 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDGPPEDT007-ORDTY .
    FIELD ZDGPPEDT007-AUFNR .
    FIELD ZDGPPEDT007-EBELP .
    FIELD ZDGPPEDT007-WERKS .
    FIELD ZDGPPEDT007-MATNR .
    FIELD ZDGPPEDT007-CHARG .
    FIELD ZDGPPEDT007-WIPMG .
    FIELD ZDGPPEDT007-GLTRP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDGPPEDT007-ORDTY .
    FIELD ZDGPPEDT007-AUFNR .
    FIELD ZDGPPEDT007-EBELP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
