*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDGPPEDT007TOP.                   " Global Data
  INCLUDE LZDGPPEDT007UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDGPPEDT007F00                         . " subprograms
  INCLUDE LZDGPPEDT007I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDGPPEDT007F...                   " Subprograms
* INCLUDE LZDGPPEDT007O...                   " PBO-Modules
* INCLUDE LZDGPPEDT007I...                   " PAI-Modules
