PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDGPPEDT003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDGPPEDT003-MATNR .
    FIELD ZDGPPEDT003-WERKS .
    FIELD ZDGPPEDT003-BEDAE .
    FIELD ZDGPPEDT003-VERSB .
    FIELD ZDGPPEDT003-PBDNR .
    FIELD ZDGPPEDT003-PDATU .
    FIELD ZDGPPEDT003-PLNMG .
    FIELD ZDGPPEDT003-ENTMG .
    FIELD ZDGPPEDT003-WIPMG .
    FIELD ZDGPPEDT003-DATUM .
    FIELD ZDGPPEDT003-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDGPPEDT003-MATNR .
    FIELD ZDGPPEDT003-WERKS .
    FIELD ZDGPPEDT003-BEDAE .
    FIELD ZDGPPEDT003-VERSB .
    FIELD ZDGPPEDT003-PBDNR .
    FIELD ZDGPPEDT003-PDATU .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
