PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDMPPPDT001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDMPPPDT001-ZNRP .
    FIELD ZDMPPPDT001-ZTITLE .
    FIELD ZDMPPPDT001-ZPASSWORD .
    FIELD ZDMPPPDT001-WERKS .
    FIELD ZDMPPPDT001-DATEIN .
    FIELD ZDMPPPDT001-TIMEIN .
    FIELD ZDMPPPDT001-DATEOUT .
    FIELD ZDMPPPDT001-TIMEOUT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDMPPPDT001-ZNRP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
