PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPPPDT012 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPPPDT012-AUFPL .
    FIELD ZTSPPPDT012-APLZL .
    FIELD ZTSPPPDT012-STATS .
    FIELD ZTSPPPDT012-VORNR .
    FIELD ZTSPPPDT012-ACTWH .
    FIELD ZTSPPPDT012-AUFNR .
    FIELD ZTSPPPDT012-ROOMS .
    FIELD ZTSPPPDT012-DATES .
    FIELD ZTSPPPDT012-TIMES .
    FIELD ZTSPPPDT012-DATEF .
    FIELD ZTSPPPDT012-TIMEF .
    FIELD ZTSPPPDT012-OPERATOR .
    FIELD ZTSPPPDT012-PENGAWAS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPPPDT012-AUFPL .
    FIELD ZTSPPPDT012-APLZL .
    FIELD ZTSPPPDT012-STATS .
    FIELD ZTSPPPDT012-VORNR .
    FIELD ZTSPPPDT012-ACTWH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
