*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZF63GTYPETOP.                     " Global Data
  INCLUDE LZF63GTYPEUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZF63GTYPEF00                           . " subprograms
  INCLUDE LZF63GTYPEI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZF63GTYPEF...                     " Subprograms
* INCLUDE LZF63GTYPEO...                     " PBO-Modules
* INCLUDE LZF63GTYPEI...                     " PAI-Modules
