PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63MASTERKEND CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63MASTERKEND-BUKRS .
    FIELD ZF63MASTERKEND-GSBER .
    FIELD ZF63MASTERKEND-VKBUR .
    FIELD ZF63MASTERKEND-ZIDKE .
    FIELD ZF63MASTERKEND-BUZEI .
    FIELD ZF63MASTERKEND-GTYPE .
    FIELD ZF63MASTERKEND-ZNOPOL .
    FIELD ZF63MASTERKEND-ZNORANGKA .
    FIELD ZF63MASTERKEND-ANLN1 .
    FIELD ZF63MASTERKEND-ANLN2 .
    FIELD ZF63MASTERKEND-JNSKEND .
    FIELD ZF63MASTERKEND-TXT50 .
    FIELD ZF63MASTERKEND-ZUJHR .
    FIELD ZF63MASTERKEND-ANSWL .
    FIELD ZF63MASTERKEND-LOEVM .
    FIELD ZF63MASTERKEND-KETERANGAN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63MASTERKEND-BUKRS .
    FIELD ZF63MASTERKEND-GSBER .
    FIELD ZF63MASTERKEND-VKBUR .
    FIELD ZF63MASTERKEND-ZIDKE .
    FIELD ZF63MASTERKEND-BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
