PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TRNDTL2 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TRNDTL2-BUKRS .
    FIELD ZF63TRNDTL2-GSBER .
    FIELD ZF63TRNDTL2-VKBUR .
    FIELD ZF63TRNDTL2-GTYPE .
    FIELD ZF63TRNDTL2-ZIDVC .
    FIELD ZF63TRNDTL2-TYPE .
    FIELD ZF63TRNDTL2-BUZEI .
    FIELD ZF63TRNDTL2-GJAHR .
    FIELD ZF63TRNDTL2-BUDAT .
    FIELD ZF63TRNDTL2-BLDAT .
    FIELD ZF63TRNDTL2-XBLNR .
    FIELD ZF63TRNDTL2-MEINS .
    FIELD ZF63TRNDTL2-MENGE .
    FIELD ZF63TRNDTL2-SPEED .
    FIELD ZF63TRNDTL2-KMSTR .
    FIELD ZF63TRNDTL2-KMEND .
    FIELD ZF63TRNDTL2-ZNOPOL .
    FIELD ZF63TRNDTL2-DESCRIPTION .
    FIELD ZF63TRNDTL2-WAERS .
    FIELD ZF63TRNDTL2-TARIF .
    FIELD ZF63TRNDTL2-PERSENTASE .
    FIELD ZF63TRNDTL2-WRBTR .
    FIELD ZF63TRNDTL2-KOSTL .
    FIELD ZF63TRNDTL2-SHKZG .
    FIELD ZF63TRNDTL2-WWSFR .
    FIELD ZF63TRNDTL2-WWPOS .
    FIELD ZF63TRNDTL2-WWPFN .
    FIELD ZF63TRNDTL2-VBUND .
    FIELD ZF63TRNDTL2-TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TRNDTL2-BUKRS .
    FIELD ZF63TRNDTL2-GSBER .
    FIELD ZF63TRNDTL2-VKBUR .
    FIELD ZF63TRNDTL2-GTYPE .
    FIELD ZF63TRNDTL2-ZIDVC .
    FIELD ZF63TRNDTL2-TYPE .
    FIELD ZF63TRNDTL2-BUZEI .
    FIELD ZF63TRNDTL2-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
