PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63PDDKLK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63PDDKLK-BUKRS .
    FIELD ZF63PDDKLK-VKBUR .
    FIELD ZF63PDDKLK-GSBER .
    FIELD ZF63PDDKLK-TYPE .
    FIELD ZF63PDDKLK-ITEM .
    FIELD ZF63PDDKLK-JABATPD .
    FIELD ZF63PDDKLK-WAERS .
    FIELD ZF63PDDKLK-TRF_INAP .
    FIELD ZF63PDDKLK-TRF_HARI .
    FIELD ZF63PDDKLK-DATAB .
    FIELD ZF63PDDKLK-DATBI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63PDDKLK-BUKRS .
    FIELD ZF63PDDKLK-VKBUR .
    FIELD ZF63PDDKLK-GSBER .
    FIELD ZF63PDDKLK-TYPE .
    FIELD ZF63PDDKLK-ITEM .
    FIELD ZF63PDDKLK-JABATPD .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
