PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TRNSHP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TRNSHP-BUKRS .
    FIELD ZF63TRNSHP-GSBER .
    FIELD ZF63TRNSHP-VKBUR .
    FIELD ZF63TRNSHP-GTYPE .
    FIELD ZF63TRNSHP-EXPNR .
    FIELD ZF63TRNSHP-TKNUM .
    FIELD ZF63TRNSHP-GJAHR .
    FIELD ZF63TRNSHP-ERDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TRNSHP-BUKRS .
    FIELD ZF63TRNSHP-GSBER .
    FIELD ZF63TRNSHP-VKBUR .
    FIELD ZF63TRNSHP-GTYPE .
    FIELD ZF63TRNSHP-EXPNR .
    FIELD ZF63TRNSHP-TKNUM .
    FIELD ZF63TRNSHP-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
