PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63MASTER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63MASTER-BUKRS .
    FIELD ZF63MASTER-GSBER .
    FIELD ZF63MASTER-VKBUR .
    FIELD ZF63MASTER-GTYPE .
    FIELD ZF63MASTER-ZIDNO .
    FIELD ZF63MASTER-PERNR .
    FIELD ZF63MASTER-LIFNR .
    FIELD ZF63MASTER-ZNOPOL .
    FIELD ZF63MASTER-ZNORANGKA .
    FIELD ZF63MASTER-ANLN1 .
    FIELD ZF63MASTER-ANLN2 .
    FIELD ZF63MASTER-JNSKEND .
    FIELD ZF63MASTER-TXT50 .
    FIELD ZF63MASTER-ZUJHR .
    FIELD ZF63MASTER-ANSWL .
    FIELD ZF63MASTER-SNAME .
    FIELD ZF63MASTER-KOSTL .
    FIELD ZF63MASTER-WWPFN .
    FIELD ZF63MASTER-WWSFR .
    FIELD ZF63MASTER-WWPOS .
    FIELD ZF63MASTER-VBUND .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63MASTER-BUKRS .
    FIELD ZF63MASTER-GSBER .
    FIELD ZF63MASTER-VKBUR .
    FIELD ZF63MASTER-GTYPE .
    FIELD ZF63MASTER-ZIDNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
