PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TRNDTL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TRNDTL-BUKRS .
    FIELD ZF63TRNDTL-GSBER .
    FIELD ZF63TRNDTL-VKBUR .
    FIELD ZF63TRNDTL-GTYPE .
    FIELD ZF63TRNDTL-EXPNR .
    FIELD ZF63TRNDTL-TYPE .
    FIELD ZF63TRNDTL-BUZEI .
    FIELD ZF63TRNDTL-GJAHR .
    FIELD ZF63TRNDTL-BUDAT .
    FIELD ZF63TRNDTL-BLDAT .
    FIELD ZF63TRNDTL-XBLNR .
    FIELD ZF63TRNDTL-MEINS .
    FIELD ZF63TRNDTL-MENGE .
    FIELD ZF63TRNDTL-SPEED .
    FIELD ZF63TRNDTL-KMSTR .
    FIELD ZF63TRNDTL-KMEND .
    FIELD ZF63TRNDTL-DESCRIPTION .
    FIELD ZF63TRNDTL-WAERS .
    FIELD ZF63TRNDTL-TARIF .
    FIELD ZF63TRNDTL-WRBTR .
    FIELD ZF63TRNDTL-KOSTL .
    FIELD ZF63TRNDTL-SHKZG .
    FIELD ZF63TRNDTL-WWSFR .
    FIELD ZF63TRNDTL-WWPOS .
    FIELD ZF63TRNDTL-VBUND .
    FIELD ZF63TRNDTL-TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TRNDTL-BUKRS .
    FIELD ZF63TRNDTL-GSBER .
    FIELD ZF63TRNDTL-VKBUR .
    FIELD ZF63TRNDTL-GTYPE .
    FIELD ZF63TRNDTL-EXPNR .
    FIELD ZF63TRNDTL-TYPE .
    FIELD ZF63TRNDTL-BUZEI .
    FIELD ZF63TRNDTL-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
