PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63KMHEXP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63KMHEXP-GTYPE .
    FIELD ZF63KMHEXP-FIELD1 .
    FIELD ZF63KMHEXP-TYPE .
    FIELD ZF63KMHEXP-ITEM .
    FIELD ZF63KMHEXP-SPMON .
    FIELD ZF63KMHEXP-SPEED .
    FIELD ZF63KMHEXP-KMSTR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63KMHEXP-GTYPE .
    FIELD ZF63KMHEXP-FIELD1 .
    FIELD ZF63KMHEXP-TYPE .
    FIELD ZF63KMHEXP-ITEM .
    FIELD ZF63KMHEXP-SPMON .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
