PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TRNHDR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TRNHDR-BUKRS .
    FIELD ZF63TRNHDR-GSBER .
    FIELD ZF63TRNHDR-VKBUR .
    FIELD ZF63TRNHDR-GTYPE .
    FIELD ZF63TRNHDR-EXPNR .
    FIELD ZF63TRNHDR-GJAHR .
    FIELD ZF63TRNHDR-ZIDNO .
    FIELD ZF63TRNHDR-ZIDVC .
    FIELD ZF63TRNHDR-ZNOPOL .
    FIELD ZF63TRNHDR-XBLNR .
    FIELD ZF63TRNHDR-BKTXT .
    FIELD ZF63TRNHDR-WAERS .
    FIELD ZF63TRNHDR-WRBTR .
    FIELD ZF63TRNHDR-SHKZG .
    FIELD ZF63TRNHDR-ERNAM .
    FIELD ZF63TRNHDR-ERDAT .
    FIELD ZF63TRNHDR-ERZET .
    FIELD ZF63TRNHDR-REKANAN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TRNHDR-BUKRS .
    FIELD ZF63TRNHDR-GSBER .
    FIELD ZF63TRNHDR-VKBUR .
    FIELD ZF63TRNHDR-GTYPE .
    FIELD ZF63TRNHDR-EXPNR .
    FIELD ZF63TRNHDR-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
