*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZF63MASTERTOP.                    " Global Data
  INCLUDE LZF63MASTERUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZF63MASTERF00                          . " subprograms
  INCLUDE LZF63MASTERI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZF63MASTERF...                    " Subprograms
* INCLUDE LZF63MASTERO...                    " PBO-Modules
* INCLUDE LZF63MASTERI...                    " PAI-Modules
