PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63GTYPE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63GTYPE-GTYPE .
    FIELD ZF63GTYPE-BUKRS .
    FIELD ZF63GTYPE-DESCRIPTION .
    FIELD ZF63GTYPE-UMSKZ .
    FIELD ZF63GTYPE-BLART .
    FIELD ZF63GTYPE-ADV_BLART .
    FIELD ZF63GTYPE-BSCHL .
    FIELD ZF63GTYPE-ADV_BSCHL .
    FIELD ZF63GTYPE-MJ_BSCHL .
    FIELD ZF63GTYPE-WAERS .
    FIELD ZF63GTYPE-STATUS .
    FIELD ZF63GTYPE-HKONT .
    FIELD ZF63GTYPE-VBUND .
    FIELD ZF63GTYPE-JEADV .
    FIELD ZF63GTYPE-SALESMAN .
    FIELD ZF63GTYPE-VENDOR .
    FIELD ZF63GTYPE-CUSTOMER .
    FIELD ZF63GTYPE-SHIPMENT .
    FIELD ZF63GTYPE-LFA1 .
    FIELD ZF63GTYPE-ADVANCE .
    FIELD ZF63GTYPE-ZNOPOL .
    FIELD ZF63GTYPE-MEMOJURNAL .
    FIELD ZF63GTYPE-TOADV .
    FIELD ZF63GTYPE-LTEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63GTYPE-GTYPE .
    FIELD ZF63GTYPE-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
