PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TRNVCH CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TRNVCH-BUKRS .
    FIELD ZF63TRNVCH-GSBER .
    FIELD ZF63TRNVCH-VKBUR .
    FIELD ZF63TRNVCH-GTYPE .
    FIELD ZF63TRNVCH-ZIDVC .
    FIELD ZF63TRNVCH-VJAHR .
    FIELD ZF63TRNVCH-GJAHR .
    FIELD ZF63TRNVCH-BELNR .
    FIELD ZF63TRNVCH-BUDAT .
    FIELD ZF63TRNVCH-BLDAT .
    FIELD ZF63TRNVCH-GJAHRPADV .
    FIELD ZF63TRNVCH-BELNRPADV .
    FIELD ZF63TRNVCH-BUDATPADV .
    FIELD ZF63TRNVCH-BLDATPADV .
    FIELD ZF63TRNVCH-XBLNR .
    FIELD ZF63TRNVCH-BKTXT .
    FIELD ZF63TRNVCH-BSCHL .
    FIELD ZF63TRNVCH-HKONT .
    FIELD ZF63TRNVCH-WAERS .
    FIELD ZF63TRNVCH-WRBTR .
    FIELD ZF63TRNVCH-ADV_GJAHR .
    FIELD ZF63TRNVCH-ADV_BELNR .
    FIELD ZF63TRNVCH-ERNAM .
    FIELD ZF63TRNVCH-ERDAT .
    FIELD ZF63TRNVCH-ERZET .
    FIELD ZF63TRNVCH-USERPOST .
    FIELD ZF63TRNVCH-TGLPOST .
    FIELD ZF63TRNVCH-JAMPOST .
    FIELD ZF63TRNVCH-GJAHRREV .
    FIELD ZF63TRNVCH-BELNRREV .
    FIELD ZF63TRNVCH-BUDATREV .
    FIELD ZF63TRNVCH-GJAHRPADVREV .
    FIELD ZF63TRNVCH-BELNRPADVREV .
    FIELD ZF63TRNVCH-BUDATPADVREV .
    FIELD ZF63TRNVCH-USERREV .
    FIELD ZF63TRNVCH-TGLREV .
    FIELD ZF63TRNVCH-JAMREV .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TRNVCH-BUKRS .
    FIELD ZF63TRNVCH-GSBER .
    FIELD ZF63TRNVCH-VKBUR .
    FIELD ZF63TRNVCH-GTYPE .
    FIELD ZF63TRNVCH-ZIDVC .
    FIELD ZF63TRNVCH-VJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
