PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TYPEEXP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TYPEEXP-BUKRS .
    FIELD ZF63TYPEEXP-GTYPE .
    FIELD ZF63TYPEEXP-TYPE .
    FIELD ZF63TYPEEXP-ACCTYPE .
    FIELD ZF63TYPEEXP-DESCRIPTION .
    FIELD ZF63TYPEEXP-ZSUM .
    FIELD ZF63TYPEEXP-ZOBLIG .
    FIELD ZF63TYPEEXP-ZTEXT .
    FIELD ZF63TYPEEXP-ZDKLK .
    FIELD ZF63TYPEEXP-ZHARIAN .
    FIELD ZF63TYPEEXP-ZVBUND .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TYPEEXP-BUKRS .
    FIELD ZF63TYPEEXP-GTYPE .
    FIELD ZF63TYPEEXP-TYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
