*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZF63JABATMASTERTOP.               " Global Data
  INCLUDE LZF63JABATMASTERUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZF63JABATMASTERF00                     . " subprograms
  INCLUDE LZF63JABATMASTERI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZF63JABATMASTERF...               " Subprograms
* INCLUDE LZF63JABATMASTERO...               " PBO-Modules
* INCLUDE LZF63JABATMASTERI...               " PAI-Modules
