PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TRNSHP2 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TRNSHP2-BUKRS .
    FIELD ZF63TRNSHP2-GSBER .
    FIELD ZF63TRNSHP2-VKBUR .
    FIELD ZF63TRNSHP2-GTYPE .
    FIELD ZF63TRNSHP2-ZIDVC .
    FIELD ZF63TRNSHP2-ZNOPOL .
    FIELD ZF63TRNSHP2-TKNUM .
    FIELD ZF63TRNSHP2-GJAHR .
    FIELD ZF63TRNSHP2-ERDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TRNSHP2-BUKRS .
    FIELD ZF63TRNSHP2-GSBER .
    FIELD ZF63TRNSHP2-VKBUR .
    FIELD ZF63TRNSHP2-GTYPE .
    FIELD ZF63TRNSHP2-ZIDVC .
    FIELD ZF63TRNSHP2-ZNOPOL .
    FIELD ZF63TRNSHP2-TKNUM .
    FIELD ZF63TRNSHP2-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
