PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63MASTERPERSON CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63MASTERPERSON-BUKRS .
    FIELD ZF63MASTERPERSON-GSBER .
    FIELD ZF63MASTERPERSON-VKBUR .
    FIELD ZF63MASTERPERSON-ZIDNO .
    FIELD ZF63MASTERPERSON-GTYPE .
    FIELD ZF63MASTERPERSON-ZIDKE .
    FIELD ZF63MASTERPERSON-PERNR .
    FIELD ZF63MASTERPERSON-LIFNR .
    FIELD ZF63MASTERPERSON-KUNNR .
    FIELD ZF63MASTERPERSON-NAME1 .
    FIELD ZF63MASTERPERSON-KATR1 .
    FIELD ZF63MASTERPERSON-KOSTL .
    FIELD ZF63MASTERPERSON-WWPFN .
    FIELD ZF63MASTERPERSON-WWSFR .
    FIELD ZF63MASTERPERSON-WWPOS .
    FIELD ZF63MASTERPERSON-VBUND .
    FIELD ZF63MASTERPERSON-JABATPD .
    FIELD ZF63MASTERPERSON-KETERANGAN .
    FIELD ZF63MASTERPERSON-DELIVERY_ID .
    FIELD ZF63MASTERPERSON-JNSVENDOR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63MASTERPERSON-BUKRS .
    FIELD ZF63MASTERPERSON-GSBER .
    FIELD ZF63MASTERPERSON-VKBUR .
    FIELD ZF63MASTERPERSON-ZIDNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
