*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZF63MASTERKENDTOP.                " Global Data
  INCLUDE LZF63MASTERKENDUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZF63MASTERKENDF00                      . " subprograms
  INCLUDE LZF63MASTERKENDI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZF63MASTERKENDF...                " Subprograms
* INCLUDE LZF63MASTERKENDO...                " PBO-Modules
* INCLUDE LZF63MASTERKENDI...                " PAI-Modules
