PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TYTPEEXPDESC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TYTPEEXPDESC-GTYPE .
    FIELD ZF63TYTPEEXPDESC-TYPE .
    FIELD ZF63TYTPEEXPDESC-ITEM .
    FIELD ZF63TYTPEEXPDESC-DESCRIPTION .
    FIELD ZF63TYTPEEXPDESC-LTEXT .
    FIELD ZF63TYTPEEXPDESC-MEINS .
    FIELD ZF63TYTPEEXPDESC-WAERS .
    FIELD ZF63TYTPEEXPDESC-SPEED .
    FIELD ZF63TYTPEEXPDESC-ZSTRF .
    FIELD ZF63TYTPEEXPDESC-ZENDF .
    FIELD ZF63TYTPEEXPDESC-HKONT .
    FIELD ZF63TYTPEEXPDESC-ZAMNT .
    FIELD ZF63TYTPEEXPDESC-ZPERCEN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TYTPEEXPDESC-GTYPE .
    FIELD ZF63TYTPEEXPDESC-TYPE .
    FIELD ZF63TYTPEEXPDESC-ITEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
