PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZF63TRNHDR2 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZF63TRNHDR2-BUKRS .
    FIELD ZF63TRNHDR2-GSBER .
    FIELD ZF63TRNHDR2-VKBUR .
    FIELD ZF63TRNHDR2-GTYPE .
    FIELD ZF63TRNHDR2-GJAHR .
    FIELD ZF63TRNHDR2-ZIDVC .
    FIELD ZF63TRNHDR2-ZIDVC2 .
    FIELD ZF63TRNHDR2-ZIDNO .
    FIELD ZF63TRNHDR2-BKTXT .
    FIELD ZF63TRNHDR2-WAERS .
    FIELD ZF63TRNHDR2-WRBTR .
    FIELD ZF63TRNHDR2-SHKZG .
    FIELD ZF63TRNHDR2-REKANAN .
    FIELD ZF63TRNHDR2-ERNAM .
    FIELD ZF63TRNHDR2-ERDAT .
    FIELD ZF63TRNHDR2-ERZET .
    FIELD ZF63TRNHDR2-GJAHRPADV .
    FIELD ZF63TRNHDR2-BELNRPADV .
    FIELD ZF63TRNHDR2-BUDATPADV .
    FIELD ZF63TRNHDR2-BLDATPADV .
    FIELD ZF63TRNHDR2-XBLNRADV .
    FIELD ZF63TRNHDR2-GJAHRPEXP .
    FIELD ZF63TRNHDR2-BELNRPEXP .
    FIELD ZF63TRNHDR2-BUDATPEXP .
    FIELD ZF63TRNHDR2-BLDATPEXP .
    FIELD ZF63TRNHDR2-XBLNREXP .
    FIELD ZF63TRNHDR2-ADV_GJAHR .
    FIELD ZF63TRNHDR2-ADV_BELNR .
    FIELD ZF63TRNHDR2-USERPOST .
    FIELD ZF63TRNHDR2-TGLPOST .
    FIELD ZF63TRNHDR2-JAMPOST .
    FIELD ZF63TRNHDR2-GJAHRPADVREV .
    FIELD ZF63TRNHDR2-BELNRPADVREV .
    FIELD ZF63TRNHDR2-BUDATPADVREV .
    FIELD ZF63TRNHDR2-GJAHRPEXPREV .
    FIELD ZF63TRNHDR2-BELNRPEXPREV .
    FIELD ZF63TRNHDR2-BUDATPEXPREV .
    FIELD ZF63TRNHDR2-USERREV .
    FIELD ZF63TRNHDR2-TGLREV .
    FIELD ZF63TRNHDR2-JAMREV .
    FIELD ZF63TRNHDR2-HKONT .
    FIELD ZF63TRNHDR2-TRANSACTION_ID .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZF63TRNHDR2-BUKRS .
    FIELD ZF63TRNHDR2-GSBER .
    FIELD ZF63TRNHDR2-VKBUR .
    FIELD ZF63TRNHDR2-GTYPE .
    FIELD ZF63TRNHDR2-GJAHR .
    FIELD ZF63TRNHDR2-ZIDVC .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
