*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZF63TRNDTL2TOP.                   " Global Data
  INCLUDE LZF63TRNDTL2UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZF63TRNDTL2F00                         . " subprograms
  INCLUDE LZF63TRNDTL2I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZF63TRNDTL2F...                   " Subprograms
* INCLUDE LZF63TRNDTL2O...                   " PBO-Modules
* INCLUDE LZF63TRNDTL2I...                   " PAI-Modules
