*&---------------------------------------------------------------------*
*&  Include           ZF_TTFTOP
*&---------------------------------------------------------------------*

TABLES : sscrfields, kna1, bsid, zftransttf, knvv.

CLASS : lcl_application DEFINITION DEFERRED.

TYPES : BEGIN OF ty_date,
          datum      TYPE sy-datum,
        END OF ty_date.

TYPES : BEGIN OF ty_out,
          bukrs      TYPE bsid-bukrs,
          vkbur      TYPE knvv-vkbur,
          nomorttf   TYPE zfttfno-nomorttf,
          kunnr      TYPE bsid-kunnr,
          name1      TYPE kna1-name1,
          zuonr      TYPE bsid-zuonr,
          vbeln      TYPE bsid-vbeln,
          belnr      TYPE bsid-belnr,
          gjahr      TYPE bsid-gjahr,
          zfbdt      TYPE bsid-zfbdt,
          budat      TYPE bsid-budat,
          blart      TYPE bsid-blart,
          kdgrp      TYPE zfttfoutbd-kdgrp,
          topext     TYPE zfttfoutbd-topext,
          basic      TYPE zfttfoutbd-basic,
          leadtm1    TYPE zfttfoutbd-leadtm1,
          leadtm2    TYPE zfttfoutbd-leadtm2,
          dd01       TYPE zfttfoutbd-dd01,
          dd02       TYPE zfttfoutbd-dd02,
          dd03       TYPE zfttfoutbd-dd03,
          dd04       TYPE zfttfoutbd-dd04,
          dd01r      TYPE zfttfoutbd-dd01,
          dd02r      TYPE zfttfoutbd-dd02,
          dd03r      TYPE zfttfoutbd-dd03,
          dd04r      TYPE zfttfoutbd-dd04,
          zterm      TYPE bsid-zterm,
          zbd1t      TYPE bsid-zbd1t,
          shkzg      TYPE bsid-shkzg,
          waers      TYPE bsid-waers,
          dmbtr      TYPE bsid-dmbtr,
          tglttf     TYPE bsid-budat,
          suggest    TYPE bsid-budat,
          leadtime   TYPE p DECIMALS 0,
          estbayar   TYPE bsid-budat,
          real       TYPE bsid-budat,
          sel,
          check,
          icon(4),
          style      TYPE lvc_t_styl,
        END OF ty_out.

TYPES : BEGIN OF ty_report,
          bukrs       TYPE zftransttf-bukrs,
          vkbur       TYPE zftransttf-vkbur,
          nomorttf    TYPE zftransttf-nomorttf,
          kunnr       TYPE zftransttf-kunnr,
          name1       TYPE kna1-name1,
          zuonr       TYPE zftransttf-zuonr,
          vbeln       TYPE zftransttf-vbeln,
          belnr       TYPE zftransttf-belnr,
          gjahr       TYPE zftransttf-gjahr,
          zfbdt       TYPE zftransttf-zfbdt,
          budat       TYPE zftransttf-budat,
          blart       TYPE zftransttf-blart,
          topext      TYPE zftransttf-topext,
          zterm       TYPE zftransttf-zterm,
          leadtm      TYPE zftransttf-leadtm,
          shkzg       TYPE zftransttf-shkzg,
          dmbtr       TYPE zftransttf-dmbtr,
          waers       TYPE zftransttf-waers,
          zsugttf     TYPE zftransttf-zsugttf,
          zestdt      TYPE zftransttf-zestdt,
          zreadt      TYPE zftransttf-zreadt,
          username    TYPE zftransttf-username,
          tglinput    TYPE zftransttf-tglinput,
          jaminput    TYPE zftransttf-jaminput,
          bbeln       TYPE zfbih-bbeln,
          bidat       TYPE zfbih-bidat,
          usna1       TYPE zfbih-usna1,
          tglttf      TYPE zfbid-tglttf,
          payid       TYPE zfbid-usna1,
          paydt       TYPE zfbid-erdt1,
          payment     TYPE zfbid-pcash,
          bflag       TYPE zfbid-bflag,
          pstat       TYPE zfbid-pstat,
          ptype       TYPE zfbid-ptype,
          leadtf      TYPE p DECIMALS 0,
          losstf      TYPE p DECIMALS 0,
          estttf      TYPE sy-datum,
          realttf     TYPE sy-datum,
          selisih     TYPE zftransttf-dmbtr,
          sel,
        END OF ty_report.

TYPES : BEGIN OF ty_calendar,
          week   TYPE p DECIMALS 0,
          day    TYPE p DECIMALS 0,
          date   TYPE p DECIMALS 0,
          flag,
        END OF ty_calendar.

TYPES : BEGIN OF ty_payment,
          bukrs   TYPE zfbid-bukrs,
          vkbur   TYPE zfbid-vkbur,
          bbeln   TYPE zfbid-bbeln,
          zuonr   TYPE zfbid-zuonr,
          payid   TYPE zfbid-usna1,
          paydt   TYPE zfbid-erdt1,
          pcash   TYPE zfbid-pcash,
          ptrans  TYPE zfbid-ptrans,
          cchek   TYPE zfbicheck-cchek,
        END OF ty_payment.

TYPES : BEGIN OF ty_bino,
          bukrs   TYPE zfbid-bukrs,
          vkbur   TYPE zfbid-vkbur,
          zuonr   TYPE zfbid-zuonr,
          bbeln   TYPE zfbid-bbeln,
          erzet   TYPE zfbih-erzet,
          erdt1   TYPE zfbih-erdt1,
          bidat   TYPE zfbih-bidat,
          usna1   TYPE zfbih-usna1,
          tglttf  TYPE zfbid-tglttf,
          bflag   TYPE zfbid-bflag,
          pstat   TYPE zfbid-pstat,
          ptype   TYPE zfbid-ptype,
        END OF ty_bino.

DATA : d_repid              LIKE sy-repid,
       ok_code              TYPE sy-ucomm,
       gs_exclude           TYPE ui_functions,
       g_content            TYPE REF TO cl_salv_form_element,
       g_customcont         TYPE REF TO cl_gui_custom_container,
       g_splitter           TYPE REF TO cl_gui_splitter_container,
       g_container          TYPE REF TO cl_gui_container,
       g_maingrid           TYPE REF TO cl_gui_alv_grid,
       event_receiver       TYPE REF TO lcl_application,
       selected             VALUE 'X',
       gs_stable            TYPE lvc_s_stbl,
       gt_main_fieldcat     TYPE lvc_t_fcat,
       gs_layout_alv        TYPE lvc_s_layo,
       g_handle_alv         TYPE i,
       gt_main_sort         TYPE lvc_t_sort WITH HEADER LINE,
       gs_variant           LIKE disvariant,
       gs_toolbar           TYPE stb_button.

DATA : d_layout             TYPE lvc_s_layo,
       t_alv_isort          TYPE lvc_t_sort WITH HEADER LINE,
       d_print              TYPE lvc_s_prnt,
       t_alv_event          TYPE slis_t_event WITH HEADER LINE,
       t_alv_fieldcat       TYPE lvc_t_fcat WITH HEADER LINE,
       d_alv_variant        TYPE disvariant,
       t_event_exit         TYPE slis_t_event_exit WITH HEADER LINE,
       t_events             TYPE slis_t_event,
       t_alv_filter         TYPE slis_t_filter_alv WITH HEADER LINE,
       d_alv_isort          TYPE slis_sortinfo_alv,
       d_alv_list_scroll    TYPE slis_list_scroll,
       d_alv_sort_postn     TYPE i,
       d_alv_keyinfo        TYPE slis_keyinfo_alv,
       d_alv_fieldcat       TYPE slis_fieldcat_alv,
       d_alv_formname       TYPE slis_formname,
       d_alv_ucomm          TYPE slis_formname,
       d_alv_print          TYPE slis_print_alv,
       d_alv_repid          TYPE sy-repid,
       d_alv_tabix          TYPE sy-tabix,
       d_alv_subrc          TYPE sy-subrc,
       d_alv_layout         TYPE slis_layout_alv,
       d_alv_screen_start_column  TYPE i,
       d_alv_screen_start_line    TYPE i,
       d_alv_screen_end_column    TYPE i,
       d_alv_screen_end_line      TYPE i.

DATA : gt_knvv        TYPE STANDARD TABLE OF knvv INITIAL SIZE 0,
       gt_kna1        TYPE STANDARD TABLE OF kna1 INITIAL SIZE 0,
       gt_ttfoutpay   TYPE STANDARD TABLE OF zfttfoutpay INITIAL SIZE 0,
       gt_ttfoutbw    TYPE STANDARD TABLE OF zfttfoutbw INITIAL SIZE 0,
       gt_ttfoutbd    TYPE STANDARD TABLE OF zfttfoutbd INITIAL SIZE 0,
       gs_ttfoutbd    TYPE zfttfoutbd,
       gt_bsid        TYPE STANDARD TABLE OF bsid INITIAL SIZE 0,
       gt_out         TYPE STANDARD TABLE OF ty_out INITIAL SIZE 0,
       gt_report      TYPE STANDARD TABLE OF ty_report INITIAL SIZE 0,
       gs_zfttfno     TYPE zfttfno,
       gt_zfttfcg     TYPE STANDARD TABLE OF zfttfcg INITIAL SIZE 0,
       gt_zftransttf  TYPE STANDARD TABLE OF zftransttf INITIAL SIZE 0,
       gt_zfbih       TYPE STANDARD TABLE OF zfbih INITIAL SIZE 0,
       gt_zfbid       TYPE STANDARD TABLE OF zfbid INITIAL SIZE 0,
       gt_zfbicheck   TYPE STANDARD TABLE OF zfbicheck INITIAL SIZE 0,
       gt_calendar    TYPE ty_calendar,
       gt_payment     TYPE STANDARD TABLE OF ty_payment INITIAL SIZE 0,
       gt_bino        TYPE STANDARD TABLE OF ty_bino INITIAL SIZE 0.

DATA : BEGIN OF gt_error OCCURS 0,
         icon(4),
         vbeln   TYPE vbeln,
         mess    TYPE bdc_vtext1,
       END OF gt_error.

DATA : gv_butxt   TYPE t001-butxt,
       gv_bezei   TYPE tvkbt-bezei,
       gv_name1   TYPE kna1-name1,
       gv_bukrs   TYPE bsid-bukrs,
       gv_vkbur   TYPE tvbur-vkbur,
       gv_kunnr   TYPE bsid-kunnr.

DATA : gv_topex   TYPE zfttfoutbd-topext,
       gv_basic   TYPE zfttfoutbd-basic,
       gv_kdgrp   TYPE zfttfoutbd-kdgrp,
       gv_leadtm1 TYPE zfttfoutbd-leadtm1,
       gv_leadtm2 TYPE zfttfoutbd-leadtm2,
       gv_dd01    TYPE zfttfoutbd-dd01,
       gv_dd02    TYPE zfttfoutbd-dd02,
       gv_dd03    TYPE zfttfoutbd-dd03,
       gv_dd04    TYPE zfttfoutbd-dd04.

DATA : gv_week1   TYPE xfeld,
       gv_week2   TYPE xfeld,
       gv_week3   TYPE xfeld,
       gv_week4   TYPE xfeld,
       gv_week5   TYPE xfeld.

DATA : gv_sen1    TYPE xfeld,
       gv_sel1    TYPE xfeld,
       gv_rab1    TYPE xfeld,
       gv_kam1    TYPE xfeld,
       gv_jum1    TYPE xfeld,
       gv_sab1    TYPE xfeld.

DATA : gv_sen2    TYPE xfeld,
       gv_sel2    TYPE xfeld,
       gv_rab2    TYPE xfeld,
       gv_kam2    TYPE xfeld,
       gv_jum2    TYPE xfeld,
       gv_sab2    TYPE xfeld.

DATA : gv_sen3    TYPE xfeld,
       gv_sel3    TYPE xfeld,
       gv_rab3    TYPE xfeld,
       gv_kam3    TYPE xfeld,
       gv_jum3    TYPE xfeld,
       gv_sab3    TYPE xfeld.

DATA : gv_sen4    TYPE xfeld,
       gv_sel4    TYPE xfeld,
       gv_rab4    TYPE xfeld,
       gv_kam4    TYPE xfeld,
       gv_jum4    TYPE xfeld,
       gv_sab4    TYPE xfeld.

DATA : gv_sen5    TYPE xfeld,
       gv_sel5    TYPE xfeld,
       gv_rab5    TYPE xfeld,
       gv_kam5    TYPE xfeld,
       gv_jum5    TYPE xfeld,
       gv_sab5    TYPE xfeld.

DATA : gv_subrc  TYPE sy-subrc VALUE 4,
       gv_error  TYPE sy-subrc.

DATA : xfield          TYPE lvc_t_fcat,
       ref_grid        TYPE REF TO cl_gui_alv_grid.
