*----------------------------------------------------------------------*
*   INCLUDE ZFAP_AGING_TSP_TOP                                         *
*----------------------------------------------------------------------*

  TABLES: bsik, bsak, lfa1, tgsbt, t016t.

  TYPES: BEGIN OF ta_itab,
           gsber   LIKE bsik-gsber,
           lifnr   LIKE bsik-lifnr,
           augbl   LIKE bsik-augbl,
           brsch   LIKE lfa1-brsch,
           hkont   LIKE bsik-hkont,
           gjahr   LIKE bsik-gjahr,
           name1   LIKE lfa1-name1,
           blart   LIKE bsik-blart,
           zuonr   LIKE bsik-zuonr,
           belnr   LIKE bsik-belnr,
           monat   LIKE bsik-monat,
           budat   LIKE bsik-budat,
           bldat   LIKE bsik-bldat,
           augdt   LIKE bsik-augdt,
           zfbdt   LIKE bsik-zfbdt,
           zbd1t   LIKE bsik-zbd1t,
           shkzg   LIKE bsik-shkzg,
           zbd1tx(3),
           current LIKE bsik-dmbtr,
           wrbtr   LIKE bsik-wrbtr,
           dmbtr   LIKE bsik-dmbtr,
           dmbtr1  LIKE bsik-dmbtr,
           dmbtr2  LIKE bsik-dmbtr,
           dmbtr3  LIKE bsik-dmbtr,
           dmbtr4  LIKE bsik-dmbtr,
           dmbtr5  LIKE bsik-dmbtr,
         END OF ta_itab.

  TYPES: BEGIN OF ta_itab1,
           gsber   LIKE bsik-gsber,
           brsch   LIKE lfa1-brsch,
           lifnr   LIKE bsik-lifnr,
           augbl   LIKE bsik-augbl,
           gjahr   LIKE bsik-gjahr,
           name1   LIKE lfa1-name1,
           blart   LIKE bsik-blart,
           zuonr   LIKE bsik-zuonr,
           belnr   LIKE bsik-belnr,
           monat   LIKE bsik-monat,
           budat   LIKE bsik-budat,
           bldat   LIKE bsik-bldat,
           augdt   LIKE bsik-augdt,
           zfbdt   LIKE bsik-zfbdt,
           zbd1t   LIKE bsik-zbd1t,
           shkzg   LIKE bsik-shkzg,
           zbd1tx(3),
           current LIKE bsik-dmbtr,
           wrbtr   LIKE bsik-wrbtr,
           dmbtr   LIKE bsik-dmbtr,
           dmbtr1  LIKE bsik-dmbtr,
           dmbtr2  LIKE bsik-dmbtr,
           dmbtr3  LIKE bsik-dmbtr,
           dmbtr4  LIKE bsik-dmbtr,
           dmbtr5  LIKE bsik-dmbtr,
         END OF ta_itab1.

  TYPES: BEGIN OF ta_gsber,
           gsber     LIKE bsik-gsber,
           gtext     LIKE tgsbt-gtext,
           begbal    LIKE bsik-dmbtr,
           purchase  LIKE bsik-dmbtr,
           payment   LIKE bsik-dmbtr,
           endbal    LIKE bsik-dmbtr,
           current   LIKE bsik-dmbtr,
           dmbtr1    LIKE bsik-dmbtr,
           dmbtr2    LIKE bsik-dmbtr,
           dmbtr3    LIKE bsik-dmbtr,
           dmbtr4    LIKE bsik-dmbtr,
           dmbtr5    LIKE bsik-dmbtr,
         END OF ta_gsber.

  TYPES: BEGIN OF ta_lifnr,
           objkey(25),
           lifnr     LIKE bsik-lifnr,
           gsber     LIKE bsik-gsber,
           gtext     LIKE tgsbt-gtext,
           name1     LIKE lfa1-name1,
           shkzg     LIKE bsik-shkzg,
           monat     LIKE bsik-monat,
           budat     LIKE bsik-budat,
           bldat   LIKE bsik-bldat,
           augdt     LIKE bsik-augdt,
           blart     LIKE bsik-blart,
           begbal    LIKE bsik-dmbtr,
           dmbtr     LIKE bsik-dmbtr,
           endbal    LIKE bsik-dmbtr,
           current   LIKE bsik-dmbtr,
           dmbtr1    LIKE bsik-dmbtr,
           dmbtr2    LIKE bsik-dmbtr,
           dmbtr3    LIKE bsik-dmbtr,
           dmbtr4    LIKE bsik-dmbtr,
           dmbtr5    LIKE bsik-dmbtr,
           belnr     LIKE bsik-belnr,
           gjahr     LIKE bsik-gjahr,
         END OF ta_lifnr.

*--Add by sol_jonhar @01/10/2020
   TYPES: BEGIN OF ta_lifnr2,
           lifnr     LIKE bsik-lifnr,
           objkey(25),
           gsber     LIKE bsik-gsber,
           gtext     LIKE tgsbt-gtext,
           name1     LIKE lfa1-name1,
           shkzg     LIKE bsik-shkzg,
           monat     LIKE bsik-monat,
           budat     LIKE bsik-budat,
           bldat   LIKE bsik-bldat,
           augdt     LIKE bsik-augdt,
           blart     LIKE bsik-blart,
           begbal    LIKE bsik-dmbtr,
           dmbtr     LIKE bsik-dmbtr,
           endbal    LIKE bsik-dmbtr,
           current   LIKE bsik-dmbtr,
           dmbtr1    LIKE bsik-dmbtr,
           dmbtr2    LIKE bsik-dmbtr,
           dmbtr3    LIKE bsik-dmbtr,
           dmbtr4    LIKE bsik-dmbtr,
           dmbtr5    LIKE bsik-dmbtr,
           belnr     LIKE bsik-belnr,
           gjahr     LIKE bsik-gjahr,
         END OF ta_lifnr2.
"--End of add


  TYPES: BEGIN OF ta_brsch,
           brsch     LIKE lfa1-brsch,
           gsber     LIKE bsik-gsber,
           lifnr     LIKE bsik-lifnr,
           gtext     LIKE tgsbt-gtext,
           name1     LIKE lfa1-name1,
           shkzg     LIKE bsik-shkzg,
           monat     LIKE bsik-monat,
           budat     LIKE bsik-budat,
           bldat   LIKE bsik-bldat,
           augdt     LIKE bsik-augdt,
           blart     LIKE bsik-blart,
           begbal    LIKE bsik-dmbtr,
           dmbtr     LIKE bsik-dmbtr,
           endbal    LIKE bsik-dmbtr,
           current   LIKE bsik-dmbtr,
           dmbtr1    LIKE bsik-dmbtr,
           dmbtr2    LIKE bsik-dmbtr,
           dmbtr3    LIKE bsik-dmbtr,
           dmbtr4    LIKE bsik-dmbtr,
           dmbtr5    LIKE bsik-dmbtr,
         END OF ta_brsch.

  TYPES: BEGIN OF ta_hkont,
           hkont     LIKE bsik-hkont,
           gsber     LIKE bsik-gsber,
           brsch     LIKE lfa1-brsch,
           lifnr     LIKE bsik-lifnr,
           gtext     LIKE tgsbt-gtext,
           name1     LIKE lfa1-name1,
           shkzg     LIKE bsik-shkzg,
           monat     LIKE bsik-monat,
           budat     LIKE bsik-budat,
           bldat   LIKE bsik-bldat,
           augdt     LIKE bsik-augdt,
           blart     LIKE bsik-blart,
           begbal    LIKE bsik-dmbtr,
           dmbtr     LIKE bsik-dmbtr,
           endbal    LIKE bsik-dmbtr,
           current   LIKE bsik-dmbtr,
           dmbtr1    LIKE bsik-dmbtr,
           dmbtr2    LIKE bsik-dmbtr,
           dmbtr3    LIKE bsik-dmbtr,
           dmbtr4    LIKE bsik-dmbtr,
           dmbtr5    LIKE bsik-dmbtr,
         END OF ta_hkont.

  TYPES: BEGIN OF ta_zuonr,
           belnr     LIKE bsik-belnr,
           augbl     LIKE bsik-augbl,
           zuonr     LIKE bsik-zuonr,
           lifnr     LIKE bsik-lifnr,
           brsch     LIKE lfa1-brsch,
           gsber     LIKE bsik-gsber,
           gtext     LIKE tgsbt-gtext,
           name1     LIKE lfa1-name1,
           shkzg     LIKE bsik-shkzg,
           monat     LIKE bsik-monat,
           budat     LIKE bsik-budat,
           bldat   LIKE bsik-bldat,
           augdt     LIKE bsik-augdt,
           blart     LIKE bsik-blart,
           begbal    LIKE bsik-dmbtr,
           dmbtr     LIKE bsik-dmbtr,
           endbal    LIKE bsik-dmbtr,
           current   LIKE bsik-dmbtr,
           dmbtr1    LIKE bsik-dmbtr,
           dmbtr2    LIKE bsik-dmbtr,
           dmbtr3    LIKE bsik-dmbtr,
           dmbtr4    LIKE bsik-dmbtr,
           dmbtr5    LIKE bsik-dmbtr,
           gjahr     LIKE bsik-gjahr,
         END OF ta_zuonr.

  DATA: i_begbal    TYPE ta_itab OCCURS 0,
        wa_begbal   TYPE ta_itab,
        i_itab      TYPE ta_itab OCCURS 0,
        wa_itab     TYPE ta_itab,
        i_itab1     TYPE ta_itab1 OCCURS 0,
        wa_itab1    TYPE ta_itab1,
        wa_itab_kz  TYPE ta_itab,
        i_itab_ka   TYPE ta_itab OCCURS 0,
        i_itab_kg   TYPE ta_itab OCCURS 0,
        i_itab_kr   TYPE ta_itab OCCURS 0,
        i_itab_rc   TYPE ta_itab OCCURS 0,
        i_itab_re   TYPE ta_itab OCCURS 0,
        i_itab_sa   TYPE ta_itab OCCURS 0,
        i_itab_op   TYPE ta_itab OCCURS 0,
*** Modify By Budi 10/03/2006
        i_itab_k1   TYPE ta_itab OCCURS 0,
        i_itab_kz   TYPE ta_itab OCCURS 0,
*** End Modify
*** Modify By Budi 26/07/2006
        i_itab_ab   TYPE ta_itab OCCURS 0,
*** End Modify By Budi 26/07/2006
        i_itab_zx   TYPE ta_itab OCCURS 0,
        i_itab_zy   TYPE ta_itab OCCURS 0,
        i_itab_zz   TYPE ta_itab OCCURS 0,
        i_gsber     TYPE ta_gsber OCCURS 0,
        wa_gsber    TYPE ta_gsber,
        i_lifnr     TYPE ta_lifnr OCCURS 0,
        i_lifnr2     TYPE ta_lifnr2 OCCURS 0, "Add by sol_jonhar @01/10/2020
        wa_lifnr    TYPE ta_lifnr,
        wa_lifnr2    TYPE ta_lifnr2,  "Add by sol_jonhar @01/10/2020
        i_brsch     TYPE ta_brsch OCCURS 0,
        wa_brsch    TYPE ta_brsch,
        i_hkont     TYPE ta_hkont OCCURS 0,
        wa_hkont    TYPE ta_hkont,
        i_zuonr_clr TYPE ta_zuonr OCCURS 0 WITH HEADER LINE,
        i_zuonr     TYPE ta_zuonr OCCURS 0,
        i_augbl     TYPE ta_zuonr OCCURS 0 WITH HEADER LINE,
        wa_zuonr    TYPE ta_zuonr.

  DATA: va_monat1(2) TYPE n,
        va_monat2(2) TYPE n,
        va_gjahr(4)  TYPE n,
        va_gerdat1(8),
        va_gerdat2(8),
        va_currency(3).

  DATA:  va_begbal   LIKE bsik-dmbtr,
         va_purchase LIKE bsik-dmbtr,
         va_payment  LIKE bsik-dmbtr,
         va_current  LIKE bsik-dmbtr,
         va_endbal   LIKE bsik-dmbtr,
         va_dmbtr1   LIKE bsik-dmbtr,
         va_dmbtr2   LIKE bsik-dmbtr,
         va_dmbtr3   LIKE bsik-dmbtr,
         va_dmbtr4   LIKE bsik-dmbtr,
         va_dmbtr5   LIKE bsik-dmbtr.

  DATA: va_total     LIKE bsik-dmbtr.

  DATA:  total_begbal   LIKE bsik-dmbtr,
         total_purchase LIKE bsik-dmbtr,
         total_payment  LIKE bsik-dmbtr,
         total_endbal   LIKE bsik-dmbtr,
         total_current  LIKE bsik-dmbtr,
         total_dmbtr1   LIKE bsik-dmbtr,
         total_dmbtr2   LIKE bsik-dmbtr,
         total_dmbtr3   LIKE bsik-dmbtr,
         total_dmbtr4   LIKE bsik-dmbtr,
         total_dmbtr5   LIKE bsik-dmbtr.

  DATA:  va_gtext(25),
         va_bulan(2),
         va_tahun(4),
         va_bulan_text(9),
         va_period(13).

  DATA: text1(16),
        text2(16),
        text3(16),
        text4(16),
        text5(16).

  DATA: va_lifnr(10), " LIKE LFA1-LIFNR,
        va_lifnr1(10),
        va_name1(25),
        va_zuonr LIKE bsik-zuonr,
        va_augbl LIKE bsik-augbl,
        va_brsch LIKE lfa1-brsch,
        va_brsch1 LIKE lfa1-brsch,
        va_hkont LIKE bsik-hkont,
        va_hkont1 LIKE bsik-hkont,
        va_brtxt(31),
        va_txt20(25),
        va_begbal1(18),
        va_count TYPE i,
        counter TYPE i,
        va_belnr  LIKE bsik-belnr,
        va_gjahr1 LIKE bsik-gjahr.

*** Modify By Budi 10/03/2006
  DATA: va_clear(1),
        va_dmbtr LIKE bsik-dmbtr.
*** End Modify
ranges s_blart for bsid-blart.

 DEFINE m_range.
  clear : s_blart.
  s_blart-sign = 'I'.
  s_blart-low  = &1.
  s_blart-option = 'EQ'.
  APPEND s_blart.
END-OF-DEFINITION.
