*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFAPAR_BUKRSTOP.                  " Global Data
  INCLUDE LZFAPAR_BUKRSUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFAPAR_BUKRSF00                        . " subprograms
  INCLUDE LZFAPAR_BUKRSI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFAPAR_BUKRSF...                  " Subprograms
* INCLUDE LZFAPAR_BUKRSO...                  " PBO-Modules
* INCLUDE LZFAPAR_BUKRSI...                  " PAI-Modules
