PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFAPAR_TRN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFAPAR_TRN-BUKRS .
    FIELD ZFAPAR_TRN-GJAHR .
    FIELD ZFAPAR_TRN-BELNR .
    FIELD ZFAPAR_TRN-BUKRS_S .
    FIELD ZFAPAR_TRN-FAKTURNO .
    FIELD ZFAPAR_TRN-VBELN .
    FIELD ZFAPAR_TRN-GSBER .
    FIELD ZFAPAR_TRN-VKBUR .
    FIELD ZFAPAR_TRN-KUNNR .
    FIELD ZFAPAR_TRN-BUDAT .
    FIELD ZFAPAR_TRN-BLDAT .
    FIELD ZFAPAR_TRN-ZUPOS .
    FIELD ZFAPAR_TRN-ZDPOS .
    FIELD ZFAPAR_TRN-BELNRREV .
    FIELD ZFAPAR_TRN-USERIDREV .
    FIELD ZFAPAR_TRN-DATEREV .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFAPAR_TRN-BUKRS .
    FIELD ZFAPAR_TRN-GJAHR .
    FIELD ZFAPAR_TRN-BELNR .
    FIELD ZFAPAR_TRN-BUKRS_S .
    FIELD ZFAPAR_TRN-FAKTURNO .
    FIELD ZFAPAR_TRN-VBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
