*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFAPAR_TRNTOP.                    " Global Data
  INCLUDE LZFAPAR_TRNUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFAPAR_TRNF00                          . " subprograms
  INCLUDE LZFAPAR_TRNI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFAPAR_TRNF...                    " Subprograms
* INCLUDE LZFAPAR_TRNO...                    " PBO-Modules
* INCLUDE LZFAPAR_TRNI...                    " PAI-Modules
