*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFAPAR_ROUNDTOP.                  " Global Data
  INCLUDE LZFAPAR_ROUNDUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFAPAR_ROUNDF00                        . " subprograms
  INCLUDE LZFAPAR_ROUNDI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFAPAR_ROUNDF...                  " Subprograms
* INCLUDE LZFAPAR_ROUNDO...                  " PBO-Modules
* INCLUDE LZFAPAR_ROUNDI...                  " PAI-Modules
