PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFAPAR_ROUND CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFAPAR_ROUND-HKONT .
    FIELD ZFAPAR_ROUND-KOSTL .
    FIELD ZFAPAR_ROUND-VKORG .
    FIELD ZFAPAR_ROUND-WWPFN .
    FIELD ZFAPAR_ROUND-WWPOS .
    FIELD ZFAPAR_ROUND-KET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFAPAR_ROUND-HKONT .
    FIELD ZFAPAR_ROUND-KOSTL .
    FIELD ZFAPAR_ROUND-VKORG .
    FIELD ZFAPAR_ROUND-WWPFN .
    FIELD ZFAPAR_ROUND-WWPOS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
