PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFARPOTH CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFARPOTH-BUKRS .
    FIELD ZFARPOTH-GSBER .
    FIELD ZFARPOTH-VKBUR .
    FIELD ZFARPOTH-NOARP .
    FIELD ZFARPOTH-MJAHR .
    FIELD ZFARPOTH-ERDAT .
    FIELD ZFARPOTH-ERZET .
    FIELD ZFARPOTH-TXARP .
    FIELD ZFARPOTH-VOUCR .
    FIELD ZFARPOTH-HKONT .
    FIELD ZFARPOTH-AMOUNT .
    FIELD ZFARPOTH-BELNR .
    FIELD ZFARPOTH-GJAHR .
    FIELD ZFARPOTH-BUDAT .
    FIELD ZFARPOTH-BUZET .
    FIELD ZFARPOTH-BUNAM .
    FIELD ZFARPOTH-BELNRREV .
    FIELD ZFARPOTH-DATEREV .
    FIELD ZFARPOTH-USERREV .
    FIELD ZFARPOTH-BLDAT .
    FIELD ZFARPOTH-NODPY .
    FIELD ZFARPOTH-BBELN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFARPOTH-BUKRS .
    FIELD ZFARPOTH-GSBER .
    FIELD ZFARPOTH-VKBUR .
    FIELD ZFARPOTH-NOARP .
    FIELD ZFARPOTH-MJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
