*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFARSOFFTOP.                      " Global Data
  INCLUDE LZFARSOFFUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFARSOFFF00                            . " subprograms
  INCLUDE LZFARSOFFI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFARSOFFF...                      " Subprograms
* INCLUDE LZFARSOFFO...                      " PBO-Modules
* INCLUDE LZFARSOFFI...                      " PAI-Modules
