PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFARPOTD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFARPOTD-BUKRS .
    FIELD ZFARPOTD-GSBER .
    FIELD ZFARPOTD-VKBUR .
    FIELD ZFARPOTD-NOARP .
    FIELD ZFARPOTD-MJAHR .
    FIELD ZFARPOTD-POSNR .
    FIELD ZFARPOTD-KUNNR .
    FIELD ZFARPOTD-RTVTYP .
    FIELD ZFARPOTD-RTVNR .
    FIELD ZFARPOTD-RTVDT .
    FIELD ZFARPOTD-RTVAMT .
    FIELD ZFARPOTD-RTVKET .
    FIELD ZFARPOTD-XBLNR .
    FIELD ZFARPOTD-HKONT .
    FIELD ZFARPOTD-BELNR .
    FIELD ZFARPOTD-GJAHR .
    FIELD ZFARPOTD-BUDAT .
    FIELD ZFARPOTD-BUZET .
    FIELD ZFARPOTD-BUNAM .
    FIELD ZFARPOTD-BELNRREV .
    FIELD ZFARPOTD-DATEREV .
    FIELD ZFARPOTD-USERREV .
    FIELD ZFARPOTD-FLAG .
    FIELD ZFARPOTD-TXARP .
    FIELD ZFARPOTD-VOUCR .
    FIELD ZFARPOTD-POSAMT .
    FIELD ZFARPOTD-INPAMT .
    FIELD ZFARPOTD-ZTERM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFARPOTD-BUKRS .
    FIELD ZFARPOTD-GSBER .
    FIELD ZFARPOTD-VKBUR .
    FIELD ZFARPOTD-NOARP .
    FIELD ZFARPOTD-MJAHR .
    FIELD ZFARPOTD-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
