*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFARPOTDTOP.                      " Global Data
  INCLUDE LZFARPOTDUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFARPOTDF00                            . " subprograms
  INCLUDE LZFARPOTDI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFARPOTDF...                      " Subprograms
* INCLUDE LZFARPOTDO...                      " PBO-Modules
* INCLUDE LZFARPOTDI...                      " PAI-Modules
