*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFARPOTDCNTOP.                    " Global Data
  INCLUDE LZFARPOTDCNUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFARPOTDCNF00                          . " subprograms
  INCLUDE LZFARPOTDCNI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFARPOTDCNF...                    " Subprograms
* INCLUDE LZFARPOTDCNO...                    " PBO-Modules
* INCLUDE LZFARPOTDCNI...                    " PAI-Modules
