PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFARPOTDCN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFARPOTDCN-BUKRS .
    FIELD ZFARPOTDCN-GSBER .
    FIELD ZFARPOTDCN-VKBUR .
    FIELD ZFARPOTDCN-NOARP .
    FIELD ZFARPOTDCN-MJAHR .
    FIELD ZFARPOTDCN-BELNR .
    FIELD ZFARPOTDCN-RTVNR .
    FIELD ZFARPOTDCN-ZUONR .
    FIELD ZFARPOTDCN-WRBTR .
    FIELD ZFARPOTDCN-INPAMT .
    FIELD ZFARPOTDCN-SELAMT .
    FIELD ZFARPOTDCN-STBLG .
    FIELD ZFARPOTDCN-STJAH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFARPOTDCN-BUKRS .
    FIELD ZFARPOTDCN-GSBER .
    FIELD ZFARPOTDCN-VKBUR .
    FIELD ZFARPOTDCN-NOARP .
    FIELD ZFARPOTDCN-MJAHR .
    FIELD ZFARPOTDCN-BELNR .
    FIELD ZFARPOTDCN-RTVNR .
    FIELD ZFARPOTDCN-ZUONR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
