PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFARPOTD2 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFARPOTD2-BUKRS .
    FIELD ZFARPOTD2-GSBER .
    FIELD ZFARPOTD2-VKBUR .
    FIELD ZFARPOTD2-NOARP .
    FIELD ZFARPOTD2-MJAHR .
    FIELD ZFARPOTD2-POSNR .
    FIELD ZFARPOTD2-BELNR .
    FIELD ZFARPOTD2-GJAHR .
    FIELD ZFARPOTD2-BUDAT .
    FIELD ZFARPOTD2-BUZET .
    FIELD ZFARPOTD2-BUNAM .
    FIELD ZFARPOTD2-KUNNR .
    FIELD ZFARPOTD2-RTVTYP .
    FIELD ZFARPOTD2-RTVNR .
    FIELD ZFARPOTD2-RTVDT .
    FIELD ZFARPOTD2-RTVAMT .
    FIELD ZFARPOTD2-RTVKET .
    FIELD ZFARPOTD2-XBLNR .
    FIELD ZFARPOTD2-HKONT .
    FIELD ZFARPOTD2-BELNRREV .
    FIELD ZFARPOTD2-DATEREV .
    FIELD ZFARPOTD2-USERREV .
    FIELD ZFARPOTD2-FLAG .
    FIELD ZFARPOTD2-TXARP .
    FIELD ZFARPOTD2-VOUCR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFARPOTD2-BUKRS .
    FIELD ZFARPOTD2-GSBER .
    FIELD ZFARPOTD2-VKBUR .
    FIELD ZFARPOTD2-NOARP .
    FIELD ZFARPOTD2-MJAHR .
    FIELD ZFARPOTD2-POSNR .
    FIELD ZFARPOTD2-BELNR .
    FIELD ZFARPOTD2-GJAHR .
    FIELD ZFARPOTD2-BUDAT .
    FIELD ZFARPOTD2-BUZET .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
