PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFBICHECK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFBICHECK-BUKRS .
    FIELD ZFBICHECK-VKBUR .
    FIELD ZFBICHECK-GJAHR .
    FIELD ZFBICHECK-BUZEI .
    FIELD ZFBICHECK-GSBER .
    FIELD ZFBICHECK-BUDAT .
    FIELD ZFBICHECK-KUNNR .
    FIELD ZFBICHECK-ZFBDT .
    FIELD ZFBICHECK-SEQNO .
    FIELD ZFBICHECK-CEKNO .
    FIELD ZFBICHECK-BNAME .
    FIELD ZFBICHECK-BELNR .
    FIELD ZFBICHECK-BBELN .
    FIELD ZFBICHECK-ZUONR .
    FIELD ZFBICHECK-SLCOD .
    FIELD ZFBICHECK-DUEDT .
    FIELD ZFBICHECK-BLNCK .
    FIELD ZFBICHECK-NCAIR .
    FIELD ZFBICHECK-CCHEK .
    FIELD ZFBICHECK-WRBTR .
    FIELD ZFBICHECK-BLBIL .
    FIELD ZFBICHECK-BLCHK .
    FIELD ZFBICHECK-XBLNR .
    FIELD ZFBICHECK-HKONT .
    FIELD ZFBICHECK-PCAIR .
    FIELD ZFBICHECK-USNA1 .
    FIELD ZFBICHECK-ERDT1 .
    FIELD ZFBICHECK-USNA2 .
    FIELD ZFBICHECK-ERDT2 .
    FIELD ZFBICHECK-PSTAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFBICHECK-BUKRS .
    FIELD ZFBICHECK-VKBUR .
    FIELD ZFBICHECK-GJAHR .
    FIELD ZFBICHECK-BUZEI .
    FIELD ZFBICHECK-GSBER .
    FIELD ZFBICHECK-BUDAT .
    FIELD ZFBICHECK-KUNNR .
    FIELD ZFBICHECK-ZFBDT .
    FIELD ZFBICHECK-SEQNO .
    FIELD ZFBICHECK-CEKNO .
    FIELD ZFBICHECK-BNAME .
    FIELD ZFBICHECK-BELNR .
    FIELD ZFBICHECK-BBELN .
    FIELD ZFBICHECK-ZUONR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
