PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFBIH_SFA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFBIH_SFA-BUKRS .
    FIELD ZFBIH_SFA-VKBUR .
    FIELD ZFBIH_SFA-BBELN .
    FIELD ZFBIH_SFA-BIDAT .
    FIELD ZFBIH_SFA-PARNR .
    FIELD ZFBIH_SFA-WAERS .
    FIELD ZFBIH_SFA-ZFLAG .
    FIELD ZFBIH_SFA-USNA1 .
    FIELD ZFBIH_SFA-ERZET .
    FIELD ZFBIH_SFA-ERDT1 .
    FIELD ZFBIH_SFA-USNA2 .
    FIELD ZFBIH_SFA-ERDT2 .
    FIELD ZFBIH_SFA-TAHUN .
    FIELD ZFBIH_SFA-SPMTH .
    FIELD ZFBIH_SFA-BACKUP .
    FIELD ZFBIH_SFA-REFNO .
    FIELD ZFBIH_SFA-DAILY_CALL_NUM .
    FIELD ZFBIH_SFA-SDATE .
    FIELD ZFBIH_SFA-ERZET2 .
    FIELD ZFBIH_SFA-HKONT1 .
    FIELD ZFBIH_SFA-HKONT1EXP .
    FIELD ZFBIH_SFA-BUDAT1 .
    FIELD ZFBIH_SFA-HKONT2 .
    FIELD ZFBIH_SFA-HKONT2EXP .
    FIELD ZFBIH_SFA-BUDAT2 .
    FIELD ZFBIH_SFA-VCHR_CR .
    FIELD ZFBIH_SFA-VCHR_CP .
    FIELD ZFBIH_SFA-VCHR_BR .
    FIELD ZFBIH_SFA-VCHR_BP .
    FIELD ZFBIH_SFA-VCHR_DATE .
    FIELD ZFBIH_SFA-USNAM_POST .
    FIELD ZFBIH_SFA-ERDAT_POST .
    FIELD ZFBIH_SFA-ERZET_POST .
    FIELD ZFBIH_SFA-POSTDOC1 .
    FIELD ZFBIH_SFA-POSTDOC2 .
    FIELD ZFBIH_SFA-USNAM_REL .
    FIELD ZFBIH_SFA-ERDAT_REL .
    FIELD ZFBIH_SFA-ERZET_REL .
    FIELD ZFBIH_SFA-FILENM_DWN .
    FIELD ZFBIH_SFA-ERDAT_DWN .
    FIELD ZFBIH_SFA-RECEIVE_KE .
    FIELD ZFBIH_SFA-USNAM_UNREL .
    FIELD ZFBIH_SFA-ERDAT_UNREL .
    FIELD ZFBIH_SFA-ERZET_UNREL .
    FIELD ZFBIH_SFA-FILENM_UNREL .
    FIELD ZFBIH_SFA-PAYUPLNM .
    FIELD ZFBIH_SFA-PAYUPLDT .
    FIELD ZFBIH_SFA-PAYUPLTM .
    FIELD ZFBIH_SFA-PAYUPL_FILENM .
    FIELD ZFBIH_SFA-FPARTIAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFBIH_SFA-BUKRS .
    FIELD ZFBIH_SFA-VKBUR .
    FIELD ZFBIH_SFA-BBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
