*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFBICHECKTOP.                     " Global Data
  INCLUDE LZFBICHECKUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFBICHECKF00                           . " subprograms
  INCLUDE LZFBICHECKI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFBICHECKF...                     " Subprograms
* INCLUDE LZFBICHECKO...                     " PBO-Modules
* INCLUDE LZFBICHECKI...                     " PAI-Modules
