PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFBID_ARPOT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFBID_ARPOT-BUKRS .
    FIELD ZFBID_ARPOT-VKBUR .
    FIELD ZFBID_ARPOT-BBELN .
    FIELD ZFBID_ARPOT-EBELP .
    FIELD ZFBID_ARPOT-VBELN .
    FIELD ZFBID_ARPOT-BELNR1 .
    FIELD ZFBID_ARPOT-GJAHR1 .
    FIELD ZFBID_ARPOT-AMTCAR .
    FIELD ZFBID_ARPOT-BELNR2 .
    FIELD ZFBID_ARPOT-GJAHR2 .
    FIELD ZFBID_ARPOT-AMTTAR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFBID_ARPOT-BUKRS .
    FIELD ZFBID_ARPOT-VKBUR .
    FIELD ZFBID_ARPOT-BBELN .
    FIELD ZFBID_ARPOT-EBELP .
    FIELD ZFBID_ARPOT-VBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
