PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFBID_PAYCUST CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFBID_PAYCUST-BUKRS .
    FIELD ZFBID_PAYCUST-VKBUR .
    FIELD ZFBID_PAYCUST-BBELN .
    FIELD ZFBID_PAYCUST-EBELP .
    FIELD ZFBID_PAYCUST-ZPARTIAL .
    FIELD ZFBID_PAYCUST-VBELN .
    FIELD ZFBID_PAYCUST-GJAHR .
    FIELD ZFBID_PAYCUST-ZUONR .
    FIELD ZFBID_PAYCUST-BUZEI .
    FIELD ZFBID_PAYCUST-GSBER .
    FIELD ZFBID_PAYCUST-FKDAT .
    FIELD ZFBID_PAYCUST-KUNNR .
    FIELD ZFBID_PAYCUST-PARVW .
    FIELD ZFBID_PAYCUST-SLCOD .
    FIELD ZFBID_PAYCUST-ZFBDT .
    FIELD ZFBID_PAYCUST-WRBTR .
    FIELD ZFBID_PAYCUST-PCASH .
    FIELD ZFBID_PAYCUST-PCHEK .
    FIELD ZFBID_PAYCUST-PYTOT .
    FIELD ZFBID_PAYCUST-RESID .
    FIELD ZFBID_PAYCUST-PCNOT .
    FIELD ZFBID_PAYCUST-JMLCK .
    FIELD ZFBID_PAYCUST-XBLNR .
    FIELD ZFBID_PAYCUST-HKONT .
    FIELD ZFBID_PAYCUST-USNA1 .
    FIELD ZFBID_PAYCUST-ERDT1 .
    FIELD ZFBID_PAYCUST-USNA2 .
    FIELD ZFBID_PAYCUST-ERDT2 .
    FIELD ZFBID_PAYCUST-CHDET .
    FIELD ZFBID_PAYCUST-BFLAG .
    FIELD ZFBID_PAYCUST-PSTAT .
    FIELD ZFBID_PAYCUST-PTYPE .
    FIELD ZFBID_PAYCUST-TAHUN .
    FIELD ZFBID_PAYCUST-SPMTH .
    FIELD ZFBID_PAYCUST-BACKUP .
    FIELD ZFBID_PAYCUST-REFNO .
    FIELD ZFBID_PAYCUST-NOTTF .
    FIELD ZFBID_PAYCUST-TGLTTF .
    FIELD ZFBID_PAYCUST-AMTTTF .
    FIELD ZFBID_PAYCUST-PTRANS .
    FIELD ZFBID_PAYCUST-PTRANSEXP .
    FIELD ZFBID_PAYCUST-REWARD .
    FIELD ZFBID_PAYCUST-KDTRF .
    FIELD ZFBID_PAYCUST-XBLNRT .
    FIELD ZFBID_PAYCUST-RESIDT .
    FIELD ZFBID_PAYCUST-PTNOT .
    FIELD ZFBID_PAYCUST-PCASHEXP .
    FIELD ZFBID_PAYCUST-BLART .
    FIELD ZFBID_PAYCUST-BLDAT .
    FIELD ZFBID_PAYCUST-BELNR .
    FIELD ZFBID_PAYCUST-ZTEXT .
    FIELD ZFBID_PAYCUST-ZDELE .
    FIELD ZFBID_PAYCUST-DUDAT .
    FIELD ZFBID_PAYCUST-INP_CASH .
    FIELD ZFBID_PAYCUST-INP_TRNSFR .
    FIELD ZFBID_PAYCUST-INP_GIRO .
    FIELD ZFBID_PAYCUST-INP_CASH_CN .
    FIELD ZFBID_PAYCUST-INP_TRNSFR_CN .
    FIELD ZFBID_PAYCUST-INP_CASH_EXP .
    FIELD ZFBID_PAYCUST-INP_TRNSFR_EXP .
    FIELD ZFBID_PAYCUST-INP_FKB_AMT .
    FIELD ZFBID_PAYCUST-INP_FKB_KET .
    FIELD ZFBID_PAYCUST-KET_DTL .
    FIELD ZFBID_PAYCUST-KODE_TRNSFR .
    FIELD ZFBID_PAYCUST-XREF3 .
    FIELD ZFBID_PAYCUST-POSTDOC2 .
    FIELD ZFBID_PAYCUST-BANK_CHECK .
    FIELD ZFBID_PAYCUST-BANK_NAME .
    FIELD ZFBID_PAYCUST-BANK_DUDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFBID_PAYCUST-BUKRS .
    FIELD ZFBID_PAYCUST-VKBUR .
    FIELD ZFBID_PAYCUST-BBELN .
    FIELD ZFBID_PAYCUST-EBELP .
    FIELD ZFBID_PAYCUST-ZPARTIAL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
