PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFBID_SFA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFBID_SFA-BUKRS .
    FIELD ZFBID_SFA-VKBUR .
    FIELD ZFBID_SFA-BBELN .
    FIELD ZFBID_SFA-EBELP .
    FIELD ZFBID_SFA-VBELN .
    FIELD ZFBID_SFA-GJAHR .
    FIELD ZFBID_SFA-ZUONR .
    FIELD ZFBID_SFA-BUZEI .
    FIELD ZFBID_SFA-GSBER .
    FIELD ZFBID_SFA-FKDAT .
    FIELD ZFBID_SFA-KUNNR .
    FIELD ZFBID_SFA-PARVW .
    FIELD ZFBID_SFA-SLCOD .
    FIELD ZFBID_SFA-ZFBDT .
    FIELD ZFBID_SFA-WRBTR .
    FIELD ZFBID_SFA-PCASH .
    FIELD ZFBID_SFA-PCHEK .
    FIELD ZFBID_SFA-PYTOT .
    FIELD ZFBID_SFA-RESID .
    FIELD ZFBID_SFA-PCNOT .
    FIELD ZFBID_SFA-JMLCK .
    FIELD ZFBID_SFA-XBLNR .
    FIELD ZFBID_SFA-HKONT .
    FIELD ZFBID_SFA-USNA1 .
    FIELD ZFBID_SFA-ERDT1 .
    FIELD ZFBID_SFA-USNA2 .
    FIELD ZFBID_SFA-ERDT2 .
    FIELD ZFBID_SFA-CHDET .
    FIELD ZFBID_SFA-BFLAG .
    FIELD ZFBID_SFA-PSTAT .
    FIELD ZFBID_SFA-PTYPE .
    FIELD ZFBID_SFA-TAHUN .
    FIELD ZFBID_SFA-SPMTH .
    FIELD ZFBID_SFA-BACKUP .
    FIELD ZFBID_SFA-REFNO .
    FIELD ZFBID_SFA-NOTTF .
    FIELD ZFBID_SFA-TGLTTF .
    FIELD ZFBID_SFA-AMTTTF .
    FIELD ZFBID_SFA-PTRANS .
    FIELD ZFBID_SFA-PTRANSEXP .
    FIELD ZFBID_SFA-REWARD .
    FIELD ZFBID_SFA-KDTRF .
    FIELD ZFBID_SFA-XBLNRT .
    FIELD ZFBID_SFA-RESIDT .
    FIELD ZFBID_SFA-PTNOT .
    FIELD ZFBID_SFA-PCASHEXP .
    FIELD ZFBID_SFA-BLART .
    FIELD ZFBID_SFA-BLDAT .
    FIELD ZFBID_SFA-BELNR .
    FIELD ZFBID_SFA-ZTEXT .
    FIELD ZFBID_SFA-ZDELE .
    FIELD ZFBID_SFA-DUDAT .
    FIELD ZFBID_SFA-INP_CASH .
    FIELD ZFBID_SFA-INP_TRNSFR .
    FIELD ZFBID_SFA-INP_GIRO .
    FIELD ZFBID_SFA-INP_CASH_CN .
    FIELD ZFBID_SFA-INP_TRNSFR_CN .
    FIELD ZFBID_SFA-INP_CASH_EXP .
    FIELD ZFBID_SFA-INP_TRNSFR_EXP .
    FIELD ZFBID_SFA-INP_FKB_AMT .
    FIELD ZFBID_SFA-INP_FKB_KET .
    FIELD ZFBID_SFA-KET_DTL .
    FIELD ZFBID_SFA-KODE_TRNSFR .
    FIELD ZFBID_SFA-XREF3 .
    FIELD ZFBID_SFA-POSTDOC2 .
    FIELD ZFBID_SFA-ZPARTIAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFBID_SFA-BUKRS .
    FIELD ZFBID_SFA-VKBUR .
    FIELD ZFBID_SFA-BBELN .
    FIELD ZFBID_SFA-EBELP .
    FIELD ZFBID_SFA-VBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
