*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFBIH_PAYCUSTTOP.                 " Global Data
  INCLUDE LZFBIH_PAYCUSTUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFBIH_PAYCUSTF00                       . " subprograms
  INCLUDE LZFBIH_PAYCUSTI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFBIH_PAYCUSTF...                 " Subprograms
* INCLUDE LZFBIH_PAYCUSTO...                 " PBO-Modules
* INCLUDE LZFBIH_PAYCUSTI...                 " PAI-Modules
