*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFBID_SFATOP.                     " Global Data
  INCLUDE LZFBID_SFAUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFBID_SFAF00                           . " subprograms
  INCLUDE LZFBID_SFAI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFBID_SFAF...                     " Subprograms
* INCLUDE LZFBID_SFAO...                     " PBO-Modules
* INCLUDE LZFBID_SFAI...                     " PAI-Modules
