PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFBIH_PAYCUST CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFBIH_PAYCUST-BUKRS .
    FIELD ZFBIH_PAYCUST-VKBUR .
    FIELD ZFBIH_PAYCUST-BBELN .
    FIELD ZFBIH_PAYCUST-ZPARTIAL .
    FIELD ZFBIH_PAYCUST-BIDAT .
    FIELD ZFBIH_PAYCUST-PARNR .
    FIELD ZFBIH_PAYCUST-WAERS .
    FIELD ZFBIH_PAYCUST-ZFLAG .
    FIELD ZFBIH_PAYCUST-USNA1 .
    FIELD ZFBIH_PAYCUST-ERZET .
    FIELD ZFBIH_PAYCUST-ERDT1 .
    FIELD ZFBIH_PAYCUST-USNA2 .
    FIELD ZFBIH_PAYCUST-ERDT2 .
    FIELD ZFBIH_PAYCUST-TAHUN .
    FIELD ZFBIH_PAYCUST-SPMTH .
    FIELD ZFBIH_PAYCUST-BACKUP .
    FIELD ZFBIH_PAYCUST-REFNO .
    FIELD ZFBIH_PAYCUST-DAILY_CALL_NUM .
    FIELD ZFBIH_PAYCUST-SDATE .
    FIELD ZFBIH_PAYCUST-ERZET2 .
    FIELD ZFBIH_PAYCUST-HKONT1 .
    FIELD ZFBIH_PAYCUST-HKONT1EXP .
    FIELD ZFBIH_PAYCUST-BUDAT1 .
    FIELD ZFBIH_PAYCUST-HKONT2 .
    FIELD ZFBIH_PAYCUST-HKONT2EXP .
    FIELD ZFBIH_PAYCUST-BUDAT2 .
    FIELD ZFBIH_PAYCUST-VCHR_CR .
    FIELD ZFBIH_PAYCUST-VCHR_CP .
    FIELD ZFBIH_PAYCUST-VCHR_BR .
    FIELD ZFBIH_PAYCUST-VCHR_BP .
    FIELD ZFBIH_PAYCUST-VCHR_DATE .
    FIELD ZFBIH_PAYCUST-USNAM_POST .
    FIELD ZFBIH_PAYCUST-ERDAT_POST .
    FIELD ZFBIH_PAYCUST-ERZET_POST .
    FIELD ZFBIH_PAYCUST-POSTDOC1 .
    FIELD ZFBIH_PAYCUST-POSTDOC2 .
    FIELD ZFBIH_PAYCUST-PAYUPLNM .
    FIELD ZFBIH_PAYCUST-PAYUPLDT .
    FIELD ZFBIH_PAYCUST-PAYUPLTM .
    FIELD ZFBIH_PAYCUST-PAYUPL_FILENM .
    FIELD ZFBIH_PAYCUST-LOYALTY .
    FIELD ZFBIH_PAYCUST-ADVFEE .
    FIELD ZFBIH_PAYCUST-HKONT_ADV .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFBIH_PAYCUST-BUKRS .
    FIELD ZFBIH_PAYCUST-VKBUR .
    FIELD ZFBIH_PAYCUST-BBELN .
    FIELD ZFBIH_PAYCUST-ZPARTIAL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
