PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFCHANEL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFCHANEL-BUKRS .
    FIELD ZFCHANEL-VKBUR .
    FIELD ZFCHANEL-CHANNEL .
    FIELD ZFCHANEL-KDGRP .
    FIELD ZFCHANEL-BRSCH .
    FIELD ZFCHANEL-FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFCHANEL-BUKRS .
    FIELD ZFCHANEL-VKBUR .
    FIELD ZFCHANEL-CHANNEL .
    FIELD ZFCHANEL-KDGRP .
    FIELD ZFCHANEL-BRSCH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
