*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFDEPTTOP.                        " Global Data
  INCLUDE LZFDEPTUXX.                        " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFDEPTF00                              . " subprograms
  INCLUDE LZFDEPTI00                              . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFDEPTF...                        " Subprograms
* INCLUDE LZFDEPTO...                        " PBO-Modules
* INCLUDE LZFDEPTI...                        " PAI-Modules
