*----------------------------------------------------------------------*
*   INCLUDE ZFF_VATOUT_FIN_T                                           *
*----------------------------------------------------------------------*
TYPES  :  BEGIN OF T_VAT01,
            BUKRS LIKE BSID-BUKRS,
            GSBER LIKE BSID-GSBER,
            BLART LIKE BSID-BLART,
            XBLNR LIKE BSID-XBLNR,
            BELNR LIKE BSID-BELNR,
            ZUONR LIKE BSID-ZUONR,
            BLDAT LIKE BSID-BLDAT,
            BUDAT LIKE BSID-BUDAT,
            GJAHR LIKE BSID-GJAHR,
            WRBTR LIKE BSID-WRBTR,
            SGTXT LIKE BSID-SGTXT,
            KUNNR LIKE BSID-KUNNR,
            ZFBDT LIKE BSID-ZFBDT,
            NAME_CO LIKE ADRC-NAME_CO,
            STR_SUPPL1 LIKE ADRC-STR_SUPPL1,
            STR_SUPPL2 LIKE ADRC-STR_SUPPL2,
            STRAS LIKE KNA1-STRAS,
            ORT01 LIKE KNA1-ORT01,
            CITYC LIKE KNA1-CITYC,
            PSTLZ LIKE KNA1-PSTLZ,
            STCEG LIKE KNA1-STCEG,
            WRBT1 LIKE BSIS-WRBTR,
            WRBTX TYPE P,
            MWSBK TYPE ZFVATO-MWSBK,
            DUDAT LIKE ZFVATO-DUDAT,
            ADRNR LIKE ZFVATO-ADRNR,
            FNAME1 LIKE ZFVATO-FNAME1,
            FSTREET LIKE ZFVATO-FSTREET,
            FHOUSE_NUM1 LIKE ZFVATO-FHOUSE_NUM1,
            FCITY1 LIKE ZFVATO-FCITY1,
            FCITY2 LIKE ZFVATO-FCITY1,
            FPOST_CODE1 LIKE ZFVATO-FPOST_CODE1,
            VATNO LIKE ZFVATO-VATNO,
            VATOLD LIKE ZFVATNR-VATOLD,
            VATPR LIKE ZFVATO-VATPR,
            VATDT LIKE ZFVATO-VATDT,
            VATNM LIKE ZFVATNM-VATNM,
            VATTL LIKE ZFVATNM-VATTL,
            object like zfvatnm-object1,
            GFORM LIKE KNA1-GFORM,
            STKZA LIKE KNA1-STKZA,
          END OF T_VAT01.

TYPES  :  BEGIN OF T_VAT02,
            NO(2),
            PROD(50),
            QTY(13),
            PRICE(15),
            VALUE(16),
            UOM(4),
          END OF T_VAT02.

TYPES  :  BEGIN OF T_SELS.
            INCLUDE STRUCTURE TLINE.
TYPES  :  END OF T_SELS.

TYPES  :  TSUBTOTAL(14) TYPE P DECIMALS 2,
          TSUBTOTAL_L(14) TYPE P DECIMALS 2,
          TPRICE LIKE VBRP-NETWR,
          TDISC(14) TYPE P DECIMALS 2,
          TPDISCV(14) TYPE P DECIMALS 0,
          TPDISC(5) TYPE P DECIMALS 2,
          TTOTAL(14) TYPE P DECIMALS 2,
          TTOT_VALUE(14) TYPE P DECIMALS 2,
          TTOT_DISC(14) TYPE P DECIMALS 2,
          TTAX_BASE(14) TYPE P DECIMALS 2,
          TTAX_AMT(14) TYPE P DECIMALS 2,
          TMONTH(2) TYPE C.

DATA  :  I_VAT01 TYPE T_VAT01 OCCURS 0,
         I_VAT02 TYPE BSIS OCCURS 0,
         I_VAT05 TYPE T_VAT02 OCCURS 0,
         I_SELS1 TYPE T_SELS OCCURS 0,
         T_ITAB1 LIKE TLINE OCCURS 2 WITH HEADER LINE,
         WA_VAT1 TYPE T_VAT01,
         wa_zfvatnr_dtl LIKE zfvatnr_dtl,
         WA_VAT2 TYPE BSIS,
         WA_VAT3 TYPE ZFVATNR,
         WA_VAT4 TYPE ZFVATNM,
         WA_VAT5 TYPE T_VAT02,
         WA_LOCK TYPE T_VAT01,
         WA_SELS TYPE T_SELS.

DATA  :  V_DATUM TYPE DATS,
         V_VATTO LIKE ZFVATNR-VATTO,
         V_VATNO LIKE ZFVATO-VATNO,
         V_VATOLD LIKE ZFVATNR-VATOLD,
         V_VATCD LIKE ZFVATNR-VATCD,
         V_posnr LIKE ZFVATNR-posnr,
         V_VATPR LIKE ZFVATO-VATPR,
         V_VATPR1 LIKE ZFVATNR-VATPR,
         V_VATDT LIKE ZFVATO-VATDT,
         V_VATNM LIKE ZFVATNM-VATNM,
         V_VATTL LIKE ZFVATNM-VATTL,
         V_RECNO TYPE I VALUE 0.

DATA  :  I_VATALV TYPE ZFVAT_ALVGRID OCCURS 0,
         WA_VATALV TYPE ZFVAT_ALVGRID.


DATA  :  OK_CODE LIKE SY-UCOMM,
         SAVE_OK LIKE OK_CODE.

DATA  :  CONTAINER_R TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
         GRID_R TYPE REF TO CL_GUI_ALV_GRID.

DATA  :  VALUE1(16) TYPE P DECIMALS 0,
         VALUE2(16) TYPE P DECIMALS 0,
         VALUE3(16) TYPE P DECIMALS 0,
         VALUE4(16) TYPE P DECIMALS 0,
         VALUE5(16) TYPE P DECIMALS 0,
         VALUE6(16) TYPE P DECIMALS 0,
         VALUE7(16) TYPE P DECIMALS 0,
         VALUE8(16) TYPE P DECIMALS 0,
         VALUE9(16) TYPE P DECIMALS 0,
         VALUE10(16) TYPE P DECIMALS 0,
         VALUE11(16) TYPE P DECIMALS 0,
         VALUE12(16) TYPE P DECIMALS 0,
         VALUE13(16) TYPE P DECIMALS 0,
         VALUE14(16) TYPE P DECIMALS 0,
         VALUE15(16) TYPE P DECIMALS 0,
         VALUE_TOT LIKE zfvato-netwr,
         V_TAX LIKE ZFVATO-WRBT1,
         V_VAR TYPE P,
         MSG1(2), MSG2(2), MSG3(2), MSG4(2), MSG5(2),
         MSG6(2), MSG7(2), MSG8(2), MSG9(2), MSG10(2),
         MSG11(2), MSG12(2), MSG13(2), MSG14(2), MSG15(2),
         MSGLIN(65).

DATA  :  VCOUNT TYPE I,
         VCOUNT_DTL TYPE I,
         VRESULT LIKE ITCPP,
         XRESULT LIKE ITCPP,
         SW(1),
         VA_MARK(1),
         VA_BELNR LIKE BSID-BELNR,
         VA_WRBTX(19),
         VA_TOTAL(21),
         VA_HEAD LIKE THEAD,
         VA_HNAME LIKE VA_HEAD-TDNAME,
         OBLN(2),
         OVATPR LIKE ZFVATNR-VATPR,
         OVATNO LIKE ZFVATNR-VATNO,
         OBUTXT LIKE T001-BUTXT,
         OSTRET LIKE ADRC-STREET,
         OCITY1 LIKE ADRC-CITY1,
         OHOUSENUM1 LIKE ADRC-HOUSE_NUM1,
         OCNPWP LIKE ZFTAX-NPWP,
         OPKPDT LIKE ZFTAX-PKDAT,
         OFNAME1 LIKE ZFVATO-FNAME1,
         OFSTREET LIKE ZFVATO-FSTREET,
         OFHOUSE_NUM1 LIKE ZFVATO-FHOUSE_NUM1,
         OFCITY1 LIKE ZFVATO-FCITY1,
         OFCITY2 LIKE ZFVATO-FCITY1,
         OPOST_CODE1 LIKE ZFVATO-FPOST_CODE1,
         ONAME1 LIKE ADRC-NAME_CO,
         ONAME2 LIKE ADRC-STR_SUPPL1,
         ONAME3 LIKE ADRC-STR_SUPPL2,
         OSTCEG LIKE KNA1-STCEG,
         ONPPKP(35),
         OSTRAS LIKE KNA1-STRAS,
         OORT01 LIKE KNA1-ORT01,
         OSEQ TYPE I,
         o_rec TYPE i,
         o_count TYPE i,
         OPROD(50),
         OQTY LIKE ZFVATO-WRBTR,
         OUOM(4),
         OPRICE(15) TYPE P DECIMALS 0,
         OVALUE(16) TYPE P DECIMALS 0,
         OSGTXT LIKE BSID-SGTXT,
         OWRBTR LIKE BSID-WRBTR,
         OSUBTOTAL TYPE TSUBTOTAL,
         OSUBTOTAL_L TYPE TSUBTOTAL_L,
         OSDISC TYPE TDISC,
         OVDISC TYPE TDISC,
         VPDISC TYPE TPDISCV,
         OPDISC TYPE TPDISC,
         OTOTAL TYPE TTOTAL,
         OTOT_VALUE TYPE TTOT_VALUE,
         OTOT_DISC TYPE TTOT_DISC,
         OTAX_BASE TYPE TTAX_BASE,
         OTAX_AMT TYPE TTAX_AMT,
         ODUDAT LIKE ZFVATO-DUDAT,
         ONPWPBARU(51),
         ONPWPBARU1(51),
         OOBJECT LIKE ZFVATNM-OBJECT1,
         OSIGN_NAME LIKE ZFVATNM-VATNM,
         OSIGN_TITLE LIKE ZFVATNM-VATTL.

DATA  :  S2VKORG LIKE ZFVATNR-VKORG,
         S2VKORGT LIKE TVKOT-VTEXT,
         S2VKBUR LIKE ZFVATNR-VKBUR,
         S2VKBURT LIKE TVKBT-BEZEI,
         S2VATNO LIKE ZFVATNR-VATNO,
         S2VATFR LIKE ZFVATNR-VATFR,
         S2VATTO LIKE ZFVATNR-VATTO,
         S2VATPR LIKE ZFVATNR-VATPR,
         S2VATDT LIKE ZFVATNR-VATDT,
         S2GJAHR LIKE ZFVATNR-GJAHR,
         VFLAG1 TYPE I VALUE 0.

DATA  :  S3VKORG LIKE ZFVATNM-VKORG,
         S3VKORGT LIKE TVKOT-VTEXT,
         S3VKBUR LIKE ZFVATNM-VKBUR,
         S3VKBURT LIKE TVKBT-BEZEI,
         s3object like zfvatnm-object1,
         S3VATNM LIKE ZFVATNM-VATNM,
         S3VATTL LIKE ZFVATNM-VATTL.

DATA  :  c1    type i,
       c2    type i,
       c3    type i,
       c4    type i,
       w1    type i,  w2    type i,  w3    type i,  w4    type i,
       w5    type i,  w6    type i,  w7    type i,  w8    type i,
       w9    type i,  w10   type i,  w11   type i,  w12   type i,
       w13   type i,  w14   type i,  w15   type i,  w16   type i,
       w17   type i,  w18   type i,  w19   type i,  w19a  type i,
       w20   type i,  w17a  type i,
       w21   type i,  w22   type i,  w23   type i,  w24   type i,
       w25   type i,  w26   type i,  w27   type i,  w28   type i,
       w29   type i,  w30   type i,  w31   type i,  w32   type i,
       w33   type i,  w34   type i,  w35   type i.

data: v_dat_pajak2013 LIKE zproject-datab,
      v_flg_pajak2013 LIKE zproject-flag.
