PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGAJI_PROSES CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGAJI_PROSES-BUKRS .
    FIELD ZFGAJI_PROSES-VKBUR .
    FIELD ZFGAJI_PROSES-ZLOCT .
    FIELD ZFGAJI_PROSES-MONAT .
    FIELD ZFGAJI_PROSES-GJAHR .
    FIELD ZFGAJI_PROSES-ZTYPE .
    FIELD ZFGAJI_PROSES-ZNOMOR .
    FIELD ZFGAJI_PROSES-APV_USER .
    FIELD ZFGAJI_PROSES-APV_DATE .
    FIELD ZFGAJI_PROSES-POST_USER .
    FIELD ZFGAJI_PROSES-POST_DATE .
    FIELD ZFGAJI_PROSES-POST_BELNR .
    FIELD ZFGAJI_PROSES-POST_GJAHR .
    FIELD ZFGAJI_PROSES-POST_FILES .
    FIELD ZFGAJI_PROSES-POST_BUDAT .
    FIELD ZFGAJI_PROSES-REV_BELNR .
    FIELD ZFGAJI_PROSES-REV_USER .
    FIELD ZFGAJI_PROSES-REV_BUDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGAJI_PROSES-BUKRS .
    FIELD ZFGAJI_PROSES-VKBUR .
    FIELD ZFGAJI_PROSES-ZLOCT .
    FIELD ZFGAJI_PROSES-MONAT .
    FIELD ZFGAJI_PROSES-GJAHR .
    FIELD ZFGAJI_PROSES-ZTYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
