*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGAJI_CONTROLTOP.                " Global Data
  INCLUDE LZFGAJI_CONTROLUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGAJI_CONTROLF00                      . " subprograms
  INCLUDE LZFGAJI_CONTROLI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGAJI_CONTROLF...                " Subprograms
* INCLUDE LZFGAJI_CONTROLO...                " PBO-Modules
* INCLUDE LZFGAJI_CONTROLI...                " PAI-Modules
