PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGAJI_HKONT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGAJI_HKONT-ITEMGAJI .
    FIELD ZFGAJI_HKONT-TYPE .
    FIELD ZFGAJI_HKONT-JOB .
    FIELD ZFGAJI_HKONT-LIVE .
    FIELD ZFGAJI_HKONT-HKONT .
    FIELD ZFGAJI_HKONT-BSCHL .
    FIELD ZFGAJI_HKONT-HKONT1 .
    FIELD ZFGAJI_HKONT-BSCHL1 .
    FIELD ZFGAJI_HKONT-TEXT1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGAJI_HKONT-ITEMGAJI .
    FIELD ZFGAJI_HKONT-TYPE .
    FIELD ZFGAJI_HKONT-JOB .
    FIELD ZFGAJI_HKONT-LIVE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
