*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGAJI_PERIODTOP.                 " Global Data
  INCLUDE LZFGAJI_PERIODUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGAJI_PERIODF00                       . " subprograms
  INCLUDE LZFGAJI_PERIODI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGAJI_PERIODF...                 " Subprograms
* INCLUDE LZFGAJI_PERIODO...                 " PBO-Modules
* INCLUDE LZFGAJI_PERIODI...                 " PAI-Modules
