*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGAJI_KOSTLTOP.                  " Global Data
  INCLUDE LZFGAJI_KOSTLUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGAJI_KOSTLF00                        . " subprograms
  INCLUDE LZFGAJI_KOSTLI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGAJI_KOSTLF...                  " Subprograms
* INCLUDE LZFGAJI_KOSTLO...                  " PBO-Modules
* INCLUDE LZFGAJI_KOSTLI...                  " PAI-Modules
