PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGAJI_LOKASI CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGAJI_LOKASI-ZLOCT .
    FIELD ZFGAJI_LOKASI-ZTYPE .
    FIELD ZFGAJI_LOKASI-BUKRS .
    FIELD ZFGAJI_LOKASI-GSBER .
    FIELD ZFGAJI_LOKASI-VKBUR .
    FIELD ZFGAJI_LOKASI-KOSTL .
    FIELD ZFGAJI_LOKASI-BLART .
    FIELD ZFGAJI_LOKASI-NEWBS .
    FIELD ZFGAJI_LOKASI-HKONT .
    FIELD ZFGAJI_LOKASI-DESCRIPTION .
    FIELD ZFGAJI_LOKASI-GSBER1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGAJI_LOKASI-ZLOCT .
    FIELD ZFGAJI_LOKASI-ZTYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
