PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGAJI_KOSTL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGAJI_KOSTL-BUKRS .
    FIELD ZFGAJI_KOSTL-DEPARTEMENT .
    FIELD ZFGAJI_KOSTL-KOSTL .
    FIELD ZFGAJI_KOSTL-VTWEG .
    FIELD ZFGAJI_KOSTL-WWSFR .
    FIELD ZFGAJI_KOSTL-WWPFN .
    FIELD ZFGAJI_KOSTL-WWPOS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGAJI_KOSTL-BUKRS .
    FIELD ZFGAJI_KOSTL-DEPARTEMENT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
