*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGAJI_PROSESTOP.                 " Global Data
  INCLUDE LZFGAJI_PROSESUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGAJI_PROSESF00                       . " subprograms
  INCLUDE LZFGAJI_PROSESI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGAJI_PROSESF...                 " Subprograms
* INCLUDE LZFGAJI_PROSESO...                 " PBO-Modules
* INCLUDE LZFGAJI_PROSESI...                 " PAI-Modules
