*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGAJI_LOKASITOP.                 " Global Data
  INCLUDE LZFGAJI_LOKASIUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGAJI_LOKASIF00                       . " subprograms
  INCLUDE LZFGAJI_LOKASII00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGAJI_LOKASIF...                 " Subprograms
* INCLUDE LZFGAJI_LOKASIO...                 " PBO-Modules
* INCLUDE LZFGAJI_LOKASII...                 " PAI-Modules
