*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGAJI_HKONTTOP.                  " Global Data
  INCLUDE LZFGAJI_HKONTUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGAJI_HKONTF00                        . " subprograms
  INCLUDE LZFGAJI_HKONTI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGAJI_HKONTF...                  " Subprograms
* INCLUDE LZFGAJI_HKONTO...                  " PBO-Modules
* INCLUDE LZFGAJI_HKONTI...                  " PAI-Modules
