*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGAJI_COMPANYTOP.                " Global Data
  INCLUDE LZFGAJI_COMPANYUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGAJI_COMPANYF00                      . " subprograms
  INCLUDE LZFGAJI_COMPANYI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGAJI_COMPANYF...                " Subprograms
* INCLUDE LZFGAJI_COMPANYO...                " PBO-Modules
* INCLUDE LZFGAJI_COMPANYI...                " PAI-Modules
