PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSCAB CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSCAB-BUKRS .
    FIELD ZFGSCAB-GSBER .
    FIELD ZFGSCAB-BELNR .
    FIELD ZFGSCAB-GJAHR .
    FIELD ZFGSCAB-BUZEI .
    FIELD ZFGSCAB-BUDAT .
    FIELD ZFGSCAB-BLDAT .
    FIELD ZFGSCAB-XBLNR .
    FIELD ZFGSCAB-XREF2 .
    FIELD ZFGSCAB-XREF3 .
    FIELD ZFGSCAB-ZUONR .
    FIELD ZFGSCAB-SGTXT .
    FIELD ZFGSCAB-ZGSNO .
    FIELD ZFGSCAB-ZTYPE .
    FIELD ZFGSCAB-ZSUBTYPE .
    FIELD ZFGSCAB-VBUND .
    FIELD ZFGSCAB-KUNNR .
    FIELD ZFGSCAB-WAERS .
    FIELD ZFGSCAB-SHKZG .
    FIELD ZFGSCAB-WRBTR .
    FIELD ZFGSCAB-HKONT .
    FIELD ZFGSCAB-TXT1 .
    FIELD ZFGSCAB-TXT2 .
    FIELD ZFGSCAB-TXT3 .
    FIELD ZFGSCAB-TXT4 .
    FIELD ZFGSCAB-BELNRGS .
    FIELD ZFGSCAB-USERGS .
    FIELD ZFGSCAB-TGLGS .
    FIELD ZFGSCAB-JAMGS .
    FIELD ZFGSCAB-BELNRREVGS .
    FIELD ZFGSCAB-USERREVGS .
    FIELD ZFGSCAB-TGLREVGS .
    FIELD ZFGSCAB-JAMREVGS .
    FIELD ZFGSCAB-BELNRPOST .
    FIELD ZFGSCAB-BELNRDN .
    FIELD ZFGSCAB-GJAHRPOST .
    FIELD ZFGSCAB-USERPOST .
    FIELD ZFGSCAB-POSTDT .
    FIELD ZFGSCAB-TGLPOST .
    FIELD ZFGSCAB-JAMPOST .
    FIELD ZFGSCAB-BELNRREV .
    FIELD ZFGSCAB-BELNRREVDN .
    FIELD ZFGSCAB-USERREV .
    FIELD ZFGSCAB-TGLREV .
    FIELD ZFGSCAB-ZPPN1 .
    FIELD ZFGSCAB-ZPPN2 .
    FIELD ZFGSCAB-GSBERK .
    FIELD ZFGSCAB-GSBERT .
    FIELD ZFGSCAB-KUNTM .
    FIELD ZFGSCAB-PERFR .
    FIELD ZFGSCAB-PERTO .
    FIELD ZFGSCAB-ZFLAG .
    FIELD ZFGSCAB-VBUNDX .
    FIELD ZFGSCAB-KUNNRX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSCAB-BUKRS .
    FIELD ZFGSCAB-GSBER .
    FIELD ZFGSCAB-BELNR .
    FIELD ZFGSCAB-GJAHR .
    FIELD ZFGSCAB-BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
