PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSCAB_HDR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSCAB_HDR-XREF2 .
    FIELD ZFGSCAB_HDR-VATNO .
    FIELD ZFGSCAB_HDR-PPN .
    FIELD ZFGSCAB_HDR-PPH .
    FIELD ZFGSCAB_HDR-WAERS .
    FIELD ZFGSCAB_HDR-BELNR .
    FIELD ZFGSCAB_HDR-BUDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSCAB_HDR-XREF2 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
