*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSCAB_MAP2TOP.                  " Global Data
  INCLUDE LZFGSCAB_MAP2UXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSCAB_MAP2F00                        . " subprograms
  INCLUDE LZFGSCAB_MAP2I00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSCAB_MAP2F...                  " Subprograms
* INCLUDE LZFGSCAB_MAP2O...                  " PBO-Modules
* INCLUDE LZFGSCAB_MAP2I...                  " PAI-Modules
