*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSNOMOR2TOP.                    " Global Data
  INCLUDE LZFGSNOMOR2UXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSNOMOR2F00                          . " subprograms
  INCLUDE LZFGSNOMOR2I00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSNOMOR2F...                    " Subprograms
* INCLUDE LZFGSNOMOR2O...                    " PBO-Modules
* INCLUDE LZFGSNOMOR2I...                    " PAI-Modules
