PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSTT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSTT-GSBER .
    FIELD ZFGSTT-ZTYPE .
    FIELD ZFGSTT-ZFORM .
    FIELD ZFGSTT-FNAME .
    FIELD ZFGSTT-PETUGAS1 .
    FIELD ZFGSTT-JABAT1 .
    FIELD ZFGSTT-PETUGAS2 .
    FIELD ZFGSTT-JABAT2 .
    FIELD ZFGSTT-GRAPH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSTT-GSBER .
    FIELD ZFGSTT-ZTYPE .
    FIELD ZFGSTT-ZFORM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
