*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSTMMT_CUSTTOP.                 " Global Data
  INCLUDE LZFGSTMMT_CUSTUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSTMMT_CUSTF00                       . " subprograms
  INCLUDE LZFGSTMMT_CUSTI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSTMMT_CUSTF...                 " Subprograms
* INCLUDE LZFGSTMMT_CUSTO...                 " PBO-Modules
* INCLUDE LZFGSTMMT_CUSTI...                 " PAI-Modules
