PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSTMMT3 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSTMMT3-SUBCHNL .
    FIELD ZFGSTMMT3-CUSTTY .
    FIELD ZFGSTMMT3-KVGR4 .
    FIELD ZFGSTMMT3-NTOKO .
    FIELD ZFGSTMMT3-KACGRP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSTMMT3-SUBCHNL .
    FIELD ZFGSTMMT3-CUSTTY .
    FIELD ZFGSTMMT3-KVGR4 .
    FIELD ZFGSTMMT3-NTOKO .
    FIELD ZFGSTMMT3-KACGRP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
