*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSCAB_MAPTOP.                   " Global Data
  INCLUDE LZFGSCAB_MAPUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSCAB_MAPF00                         . " subprograms
  INCLUDE LZFGSCAB_MAPI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSCAB_MAPF...                   " Subprograms
* INCLUDE LZFGSCAB_MAPO...                   " PBO-Modules
* INCLUDE LZFGSCAB_MAPI...                   " PAI-Modules
