PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSCAB_MAP1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSCAB_MAP1-VBUND .
    FIELD ZFGSCAB_MAP1-GJAHR .
    FIELD ZFGSCAB_MAP1-EXP_SUB_GRP .
    FIELD ZFGSCAB_MAP1-HKONT .
    FIELD ZFGSCAB_MAP1-WWSEC .
    FIELD ZFGSCAB_MAP1-WWTRZ .
    FIELD ZFGSCAB_MAP1-AUFNR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSCAB_MAP1-VBUND .
    FIELD ZFGSCAB_MAP1-GJAHR .
    FIELD ZFGSCAB_MAP1-EXP_SUB_GRP .
    FIELD ZFGSCAB_MAP1-HKONT .
    FIELD ZFGSCAB_MAP1-WWSEC .
    FIELD ZFGSCAB_MAP1-WWTRZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
