*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSKUNNRTOP.                     " Global Data
  INCLUDE LZFGSKUNNRUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSKUNNRF00                           . " subprograms
  INCLUDE LZFGSKUNNRI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSKUNNRF...                     " Subprograms
* INCLUDE LZFGSKUNNRO...                     " PBO-Modules
* INCLUDE LZFGSKUNNRI...                     " PAI-Modules
