*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSACCGSTOP.                     " Global Data
  INCLUDE LZFGSACCGSUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSACCGSF00                           . " subprograms
  INCLUDE LZFGSACCGSI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSACCGSF...                     " Subprograms
* INCLUDE LZFGSACCGSO...                     " PBO-Modules
* INCLUDE LZFGSACCGSI...                     " PAI-Modules
