*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSSUBTYTTOP.                    " Global Data
  INCLUDE LZFGSSUBTYTUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSSUBTYTF00                          . " subprograms
  INCLUDE LZFGSSUBTYTI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSSUBTYTF...                    " Subprograms
* INCLUDE LZFGSSUBTYTO...                    " PBO-Modules
* INCLUDE LZFGSSUBTYTI...                    " PAI-Modules
