PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSNOMOR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSNOMOR-GSBER .
    FIELD ZFGSNOMOR-SPMON .
    FIELD ZFGSNOMOR-ZTYPE .
    FIELD ZFGSNOMOR-ZFORM .
    FIELD ZFGSNOMOR-PREFIX1 .
    FIELD ZFGSNOMOR-PREFIX2 .
    FIELD ZFGSNOMOR-NOMOR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSNOMOR-GSBER .
    FIELD ZFGSNOMOR-SPMON .
    FIELD ZFGSNOMOR-ZTYPE .
    FIELD ZFGSNOMOR-ZFORM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
