*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSDNTMMT_ADDTOP.                " Global Data
  INCLUDE LZFGSDNTMMT_ADDUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSDNTMMT_ADDF00                      . " subprograms
  INCLUDE LZFGSDNTMMT_ADDI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSDNTMMT_ADDF...                " Subprograms
* INCLUDE LZFGSDNTMMT_ADDO...                " PBO-Modules
* INCLUDE LZFGSDNTMMT_ADDI...                " PAI-Modules
