PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSCAB_DTL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSCAB_DTL-BUKRS .
    FIELD ZFGSCAB_DTL-GJAHR .
    FIELD ZFGSCAB_DTL-XREF2 .
    FIELD ZFGSCAB_DTL-MATNR .
    FIELD ZFGSCAB_DTL-EXP_TYPE .
    FIELD ZFGSCAB_DTL-EXP_SUB_GRP .
    FIELD ZFGSCAB_DTL-CUST_GRP .
    FIELD ZFGSCAB_DTL-CUST_SUB_GRP .
    FIELD ZFGSCAB_DTL-NM_BREAK .
    FIELD ZFGSCAB_DTL-AMOUNT .
    FIELD ZFGSCAB_DTL-CURRENCY .
    FIELD ZFGSCAB_DTL-ZFLAG .
    FIELD ZFGSCAB_DTL-FI_POSTING .
    FIELD ZFGSCAB_DTL-POSTING_DATE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSCAB_DTL-BUKRS .
    FIELD ZFGSCAB_DTL-GJAHR .
    FIELD ZFGSCAB_DTL-XREF2 .
    FIELD ZFGSCAB_DTL-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
