*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSCAB_NISTOP.                   " Global Data
  INCLUDE LZFGSCAB_NISUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSCAB_NISF00                         . " subprograms
  INCLUDE LZFGSCAB_NISI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSCAB_NISF...                   " Subprograms
* INCLUDE LZFGSCAB_NISO...                   " PBO-Modules
* INCLUDE LZFGSCAB_NISI...                   " PAI-Modules
