PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSCAB_CL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSCAB_CL-BELNR .
    FIELD ZFGSCAB_CL-GJAHR .
    FIELD ZFGSCAB_CL-ZGSNO .
    FIELD ZFGSCAB_CL-ITMNO .
    FIELD ZFGSCAB_CL-KDGRP .
    FIELD ZFGSCAB_CL-MATKL .
    FIELD ZFGSCAB_CL-CLNR .
    FIELD ZFGSCAB_CL-XREF2 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSCAB_CL-BELNR .
    FIELD ZFGSCAB_CL-GJAHR .
    FIELD ZFGSCAB_CL-ZGSNO .
    FIELD ZFGSCAB_CL-ITMNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
