*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSCAB_DTLTOP.                   " Global Data
  INCLUDE LZFGSCAB_DTLUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSCAB_DTLF00                         . " subprograms
  INCLUDE LZFGSCAB_DTLI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSCAB_DTLF...                   " Subprograms
* INCLUDE LZFGSCAB_DTLO...                   " PBO-Modules
* INCLUDE LZFGSCAB_DTLI...                   " PAI-Modules
