*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSFLAGTYPETOP.                  " Global Data
  INCLUDE LZFGSFLAGTYPEUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSFLAGTYPEF00                        . " subprograms
  INCLUDE LZFGSFLAGTYPEI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSFLAGTYPEF...                  " Subprograms
* INCLUDE LZFGSFLAGTYPEO...                  " PBO-Modules
* INCLUDE LZFGSFLAGTYPEI...                  " PAI-Modules
