PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSDNTMMT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSDNTMMT-BUKRS .
    FIELD ZFGSDNTMMT-GSBER .
    FIELD ZFGSDNTMMT-BELNR .
    FIELD ZFGSDNTMMT-GJAHR .
    FIELD ZFGSDNTMMT-NOMORDN .
    FIELD ZFGSDNTMMT-BELNRDN .
    FIELD ZFGSDNTMMT-BELNRDNREV .
    FIELD ZFGSDNTMMT-BKTXT .
    FIELD ZFGSDNTMMT-XBLNR .
    FIELD ZFGSDNTMMT-NOPAAF .
    FIELD ZFGSDNTMMT-MAKTX .
    FIELD ZFGSDNTMMT-XREF2 .
    FIELD ZFGSDNTMMT-XREF3 .
    FIELD ZFGSDNTMMT-WAERS .
    FIELD ZFGSDNTMMT-WRBTR .
    FIELD ZFGSDNTMMT-KUNNR .
    FIELD ZFGSDNTMMT-BUDAT .
    FIELD ZFGSDNTMMT-FLAG .
    FIELD ZFGSDNTMMT-ZUSER .
    FIELD ZFGSDNTMMT-ZDATUM .
    FIELD ZFGSDNTMMT-ZUZEIT .
    FIELD ZFGSDNTMMT-ZUSERREV .
    FIELD ZFGSDNTMMT-ZDATUMREV .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSDNTMMT-BUKRS .
    FIELD ZFGSDNTMMT-GSBER .
    FIELD ZFGSDNTMMT-BELNR .
    FIELD ZFGSDNTMMT-GJAHR .
    FIELD ZFGSDNTMMT-NOMORDN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
