PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSACCGS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSACCGS-ZTYPE .
    FIELD ZFGSACCGS-ZSUBTYPE .
    FIELD ZFGSACCGS-GSBER .
    FIELD ZFGSACCGS-BLART .
    FIELD ZFGSACCGS-BSCHL1 .
    FIELD ZFGSACCGS-HKONT1 .
    FIELD ZFGSACCGS-MWSKZ1 .
    FIELD ZFGSACCGS-ZTAX1 .
    FIELD ZFGSACCGS-BSCHL2 .
    FIELD ZFGSACCGS-HKONT2 .
    FIELD ZFGSACCGS-MWSKZ2 .
    FIELD ZFGSACCGS-ZTAX2 .
    FIELD ZFGSACCGS-BSCHL3 .
    FIELD ZFGSACCGS-HKONT3 .
    FIELD ZFGSACCGS-MWSKZ3 .
    FIELD ZFGSACCGS-ZTAX3 .
    FIELD ZFGSACCGS-BSCHL4 .
    FIELD ZFGSACCGS-HKONT4 .
    FIELD ZFGSACCGS-MWSKZ4 .
    FIELD ZFGSACCGS-ZTAX4 .
    FIELD ZFGSACCGS-BSCHL5 .
    FIELD ZFGSACCGS-HKONT5 .
    FIELD ZFGSACCGS-MWSKZ5 .
    FIELD ZFGSACCGS-ZTAX5 .
    FIELD ZFGSACCGS-BSCHL6 .
    FIELD ZFGSACCGS-HKONT6 .
    FIELD ZFGSACCGS-MWSKZ6 .
    FIELD ZFGSACCGS-ZTAX6 .
    FIELD ZFGSACCGS-BSCHL7 .
    FIELD ZFGSACCGS-HKONT7 .
    FIELD ZFGSACCGS-MWSKZ7 .
    FIELD ZFGSACCGS-ZTAX7 .
    FIELD ZFGSACCGS-BSCHL8 .
    FIELD ZFGSACCGS-HKONT8 .
    FIELD ZFGSACCGS-MWSKZ8 .
    FIELD ZFGSACCGS-ZTAX8 .
    FIELD ZFGSACCGS-ZPOSTDN .
    FIELD ZFGSACCGS-ZPRNTDN .
    FIELD ZFGSACCGS-ZINPUTPPN .
    FIELD ZFGSACCGS-ZINPUTGSBER .
    FIELD ZFGSACCGS-ZINPUTHKONT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSACCGS-ZTYPE .
    FIELD ZFGSACCGS-ZSUBTYPE .
    FIELD ZFGSACCGS-GSBER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
