*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSTMMT2TOP.                     " Global Data
  INCLUDE LZFGSTMMT2UXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSTMMT2F00                           . " subprograms
  INCLUDE LZFGSTMMT2I00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSTMMT2F...                     " Subprograms
* INCLUDE LZFGSTMMT2O...                     " PBO-Modules
* INCLUDE LZFGSTMMT2I...                     " PAI-Modules
