PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSDNTMMT_ADD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSDNTMMT_ADD-BUKRS .
    FIELD ZFGSDNTMMT_ADD-GSBER .
    FIELD ZFGSDNTMMT_ADD-BELNR .
    FIELD ZFGSDNTMMT_ADD-GJAHR .
    FIELD ZFGSDNTMMT_ADD-ZGSNO .
    FIELD ZFGSDNTMMT_ADD-JBIAYA .
    FIELD ZFGSDNTMMT_ADD-SCHNL .
    FIELD ZFGSDNTMMT_ADD-KVGR4 .
    FIELD ZFGSDNTMMT_ADD-KUNNR .
    FIELD ZFGSDNTMMT_ADD-NAME1 .
    FIELD ZFGSDNTMMT_ADD-JBREAK1 .
    FIELD ZFGSDNTMMT_ADD-JBREAK2 .
    FIELD ZFGSDNTMMT_ADD-JBREAK3 .
    FIELD ZFGSDNTMMT_ADD-JBREAK4 .
    FIELD ZFGSDNTMMT_ADD-JBREAK5 .
    FIELD ZFGSDNTMMT_ADD-WRBTR1 .
    FIELD ZFGSDNTMMT_ADD-WRBTR2 .
    FIELD ZFGSDNTMMT_ADD-WRBTR3 .
    FIELD ZFGSDNTMMT_ADD-WRBTR4 .
    FIELD ZFGSDNTMMT_ADD-WRBTR5 .
    FIELD ZFGSDNTMMT_ADD-PPN .
    FIELD ZFGSDNTMMT_ADD-PPH .
    FIELD ZFGSDNTMMT_ADD-TYTAGIH .
    FIELD ZFGSDNTMMT_ADD-DNDEPO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSDNTMMT_ADD-BUKRS .
    FIELD ZFGSDNTMMT_ADD-GSBER .
    FIELD ZFGSDNTMMT_ADD-BELNR .
    FIELD ZFGSDNTMMT_ADD-GJAHR .
    FIELD ZFGSDNTMMT_ADD-ZGSNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
