PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFGSCAB_ADD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFGSCAB_ADD-BUKRS .
    FIELD ZFGSCAB_ADD-GSBER .
    FIELD ZFGSCAB_ADD-BELNR .
    FIELD ZFGSCAB_ADD-GJAHR .
    FIELD ZFGSCAB_ADD-ZGSNO .
    FIELD ZFGSCAB_ADD-ZTYPE .
    FIELD ZFGSCAB_ADD-ZSUBTYPE .
    FIELD ZFGSCAB_ADD-PERIOD .
    FIELD ZFGSCAB_ADD-SUBACCT .
    FIELD ZFGSCAB_ADD-ACTDESC .
    FIELD ZFGSCAB_ADD-PROMONR .
    FIELD ZFGSCAB_ADD-CLAIMAMT .
    FIELD ZFGSCAB_ADD-FEEDESC .
    FIELD ZFGSCAB_ADD-FEEAMT .
    FIELD ZFGSCAB_ADD-VAT .
    FIELD ZFGSCAB_ADD-PPH .
    FIELD ZFGSCAB_ADD-FPNR .
    FIELD ZFGSCAB_ADD-FPDAT .
    FIELD ZFGSCAB_ADD-TAXLVL .
    FIELD ZFGSCAB_ADD-KUNNR .
    FIELD ZFGSCAB_ADD-FILECABANG .
    FIELD ZFGSCAB_ADD-FILEPUSAT .
    FIELD ZFGSCAB_ADD-FILEDOWN .
    FIELD ZFGSCAB_ADD-FILEDOWN2 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFGSCAB_ADD-BUKRS .
    FIELD ZFGSCAB_ADD-GSBER .
    FIELD ZFGSCAB_ADD-BELNR .
    FIELD ZFGSCAB_ADD-GJAHR .
    FIELD ZFGSCAB_ADD-ZGSNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
