*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSNOMORTOP.                     " Global Data
  INCLUDE LZFGSNOMORUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSNOMORF00                           . " subprograms
  INCLUDE LZFGSNOMORI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSNOMORF...                     " Subprograms
* INCLUDE LZFGSNOMORO...                     " PBO-Modules
* INCLUDE LZFGSNOMORI...                     " PAI-Modules
