*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFGSGSBERTOP.                     " Global Data
  INCLUDE LZFGSGSBERUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFGSGSBERF00                           . " subprograms
  INCLUDE LZFGSGSBERI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFGSGSBERF...                     " Subprograms
* INCLUDE LZFGSGSBERO...                     " PBO-Modules
* INCLUDE LZFGSGSBERI...                     " PAI-Modules
