PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFH_KR1AT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFH_KR1AT-BUKRS .
    FIELD ZFH_KR1AT-GSBER .
    FIELD ZFH_KR1AT-VKBUR .
    FIELD ZFH_KR1AT-NOFORM .
    FIELD ZFH_KR1AT-ZUONR .
    FIELD ZFH_KR1AT-DTFORM .
    FIELD ZFH_KR1AT-UMSKZ .
    FIELD ZFH_KR1AT-KUNNR .
    FIELD ZFH_KR1AT-BELNR .
    FIELD ZFH_KR1AT-GJAHR .
    FIELD ZFH_KR1AT-BUDAT .
    FIELD ZFH_KR1AT-BLDAT .
    FIELD ZFH_KR1AT-ZFBDT .
    FIELD ZFH_KR1AT-ZTERM .
    FIELD ZFH_KR1AT-WAERS .
    FIELD ZFH_KR1AT-WRBTR .
    FIELD ZFH_KR1AT-KLIMK .
    FIELD ZFH_KR1AT-OVERDSO .
    FIELD ZFH_KR1AT-STATUS .
    FIELD ZFH_KR1AT-ZDESC1 .
    FIELD ZFH_KR1AT-USNAM .
    FIELD ZFH_KR1AT-UTIME .
    FIELD ZFH_KR1AT-USRGROUP1 .
    FIELD ZFH_KR1AT-ZDEPT1 .
    FIELD ZFH_KR1AT-STSREL1 .
    FIELD ZFH_KR1AT-NAMEREL1 .
    FIELD ZFH_KR1AT-DATEREL1 .
    FIELD ZFH_KR1AT-TIMEREL1 .
    FIELD ZFH_KR1AT-USRGROUP2 .
    FIELD ZFH_KR1AT-ZDEPT2 .
    FIELD ZFH_KR1AT-STSREL2 .
    FIELD ZFH_KR1AT-NAMEREL2 .
    FIELD ZFH_KR1AT-DATEREL2 .
    FIELD ZFH_KR1AT-TIMEREL2 .
    FIELD ZFH_KR1AT-USRGROUP3 .
    FIELD ZFH_KR1AT-STSREL3 .
    FIELD ZFH_KR1AT-NAMEREL3 .
    FIELD ZFH_KR1AT-DATEREL3 .
    FIELD ZFH_KR1AT-TIMEREL3 .
    FIELD ZFH_KR1AT-USRGROUP4 .
    FIELD ZFH_KR1AT-STSREL4 .
    FIELD ZFH_KR1AT-NAMEREL4 .
    FIELD ZFH_KR1AT-DATEREL4 .
    FIELD ZFH_KR1AT-TIMEREL4 .
    FIELD ZFH_KR1AT-USRGROUP5 .
    FIELD ZFH_KR1AT-STSREL5 .
    FIELD ZFH_KR1AT-NAMEREL5 .
    FIELD ZFH_KR1AT-DATEREL5 .
    FIELD ZFH_KR1AT-TIMEREL5 .
    FIELD ZFH_KR1AT-NAMEPOS1 .
    FIELD ZFH_KR1AT-UMSKZ1 .
    FIELD ZFH_KR1AT-BELNRPOS1 .
    FIELD ZFH_KR1AT-GJAHRPOS1 .
    FIELD ZFH_KR1AT-DATEPOS1 .
    FIELD ZFH_KR1AT-TIMEPOS1 .
    FIELD ZFH_KR1AT-SGTXT1 .
    FIELD ZFH_KR1AT-NAMEPOS2 .
    FIELD ZFH_KR1AT-UMSKZ2 .
    FIELD ZFH_KR1AT-BELNRPOS2 .
    FIELD ZFH_KR1AT-GJAHRPOS2 .
    FIELD ZFH_KR1AT-DATEPOS2 .
    FIELD ZFH_KR1AT-TIMEPOS2 .
    FIELD ZFH_KR1AT-SGTXT2 .
    FIELD ZFH_KR1AT-SGTXT3 .
    FIELD ZFH_KR1AT-DOWNNO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFH_KR1AT-BUKRS .
    FIELD ZFH_KR1AT-GSBER .
    FIELD ZFH_KR1AT-VKBUR .
    FIELD ZFH_KR1AT-NOFORM .
    FIELD ZFH_KR1AT-ZUONR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
