*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFH_KR1ATTOP.                     " Global Data
  INCLUDE LZFH_KR1ATUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFH_KR1ATF00                           . " subprograms
  INCLUDE LZFH_KR1ATI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFH_KR1ATF...                     " Subprograms
* INCLUDE LZFH_KR1ATO...                     " PBO-Modules
* INCLUDE LZFH_KR1ATI...                     " PAI-Modules
