*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFHSTATUSTOP.                     " Global Data
  INCLUDE LZFHSTATUSUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFHSTATUSF00                           . " subprograms
  INCLUDE LZFHSTATUSI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFHSTATUSF...                     " Subprograms
* INCLUDE LZFHSTATUSO...                     " PBO-Modules
* INCLUDE LZFHSTATUSI...                     " PAI-Modules
