FUNCTION ZF_NPWP_MODIFICATION.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(NPWP_IN) LIKE  ZFVATA1-STCEG DEFAULT SPACE
*"  EXPORTING
*"     REFERENCE(NPWP_OUT) LIKE  ZFVATA1-STCEG
*"----------------------------------------------------------------------
  DATA: V_LEN        TYPE I,
        V_LEN1       TYPE I,
        COUNTER      TYPE I,
        VA_CASE      TYPE I,
        NPWP_IN1(1),
        NPWP_IN2(1),
        NPWP_IN3(1),
        NPWP_IN4(1),
        NPWP_IN5(1),
        NPWP_IN6(1),
        NPWP_IN7(1),
        NPWP_IN8(1),
        NPWP_IN9(1),
        NPWP_IN10(1),
        NPWP_IN11(1),
        NPWP_IN12(1),
        NPWP_IN13(1),
        NPWP_IN14(1),
        NPWP_IN15(1),
        NPWP_IN16(1),
        NPWP_IN17(1),
        NPWP_IN18(1),
        NPWP_IN19(1),
        NPWP_IN20(1).

  V_LEN = STRLEN( NPWP_IN ).

  DO V_LEN TIMES.
    ADD 1 TO VA_CASE.
    ADD 1 TO COUNTER.
    CASE VA_CASE.
    WHEN 1.
    COUNTER = COUNTER - 1.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN1.
    ENDIF.
    WHEN 2.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN2.
    ENDIF.
    WHEN 3.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN3.
    ENDIF.
    WHEN 4.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN4.
    ENDIF.
    WHEN 5.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN5.
    ENDIF.
    WHEN 6.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN6.
    ENDIF.
    WHEN 7.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN7.
    ENDIF.
    WHEN 8.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN8.
    ENDIF.
    WHEN 9.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN9.
    ENDIF.
    WHEN 10.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN10.
    ENDIF.
    WHEN 11.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN11.
    ENDIF.
    WHEN 12.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN12.
    ENDIF.
    WHEN 13.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN13.
    ENDIF.
    WHEN 14.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN14.
    ENDIF.
    WHEN 15.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN15.
    ENDIF.
    WHEN 16.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN16.
    ENDIF.
    WHEN 17.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN17.
    ENDIF.
    WHEN 18.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN18.
    ENDIF.
    WHEN 19.
    IF NPWP_IN+COUNTER(1) NE '.' AND
         NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN19.
    ENDIF.
    WHEN 20.
    IF NPWP_IN+COUNTER(1) NE '.' AND
       NPWP_IN+COUNTER(1) NE '-'.
      MOVE NPWP_IN+COUNTER(1) TO NPWP_IN20.
    ENDIF.
    ENDCASE.
  ENDDO.

  CONCATENATE NPWP_IN1 NPWP_IN2 NPWP_IN3 NPWP_IN4 NPWP_IN5 NPWP_IN6
              NPWP_IN7 NPWP_IN8 NPWP_IN9 NPWP_IN10 NPWP_IN11 NPWP_IN12
              NPWP_IN13 NPWP_IN14 NPWP_IN15 NPWP_IN16 NPWP_IN17
              NPWP_IN18 NPWP_IN19 NPWP_IN20
  INTO NPWP_OUT.

  V_LEN1 = STRLEN( NPWP_OUT ).
  IF V_LEN1 EQ 14.
    CONCATENATE '0' NPWP_OUT INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 12.
    CONCATENATE '0' NPWP_OUT '00' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 11.
    CONCATENATE '0' NPWP_OUT '000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 10.
    CONCATENATE '0' NPWP_OUT '0000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 9.
    CONCATENATE '0' NPWP_OUT '00000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 8.
    CONCATENATE '0' NPWP_OUT '000000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 7.
    CONCATENATE '0' NPWP_OUT '0000000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 6.
    CONCATENATE '0' NPWP_OUT '00000000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 5.
    CONCATENATE '0' NPWP_OUT '000000000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 4.
    CONCATENATE '0' NPWP_OUT '0000000000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 3.
    CONCATENATE '0' NPWP_OUT '00000000000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 2.
    CONCATENATE '0' NPWP_OUT '000000000000' INTO NPWP_OUT.
  ENDIF.

  IF V_LEN1 EQ 1.
    CONCATENATE '0' NPWP_OUT '0000000000000' INTO NPWP_OUT.
  ENDIF.
ENDFUNCTION.
