*&---------------------------------------------------------------------*
*&  Include           ZCO_E001TOP
*&---------------------------------------------------------------------*
TABLES : bkpf, bseg, vttk, zwmdt004, sscrfields.

CLASS : lcl_application DEFINITION DEFERRED.

TYPES : BEGIN OF ty_out,
          mark,
          icon(4),
          bukrs     TYPE bseg-bukrs,
          belnr     TYPE bseg-belnr,
          gjahr     TYPE bseg-gjahr,
          buzei     TYPE bseg-buzei,
          gsber     TYPE bseg-gsber,
          bschl     TYPE bseg-bschl,
          hkont     TYPE bseg-hkont,
          kostl     TYPE bseg-kostl,
          matnr     TYPE bseg-matnr,
          maktx     TYPE makt-maktx,
          dmbtr     TYPE bseg-dmbtr,
          budat     TYPE bkpf-budat,
          waers     TYPE bkpf-waers,
          zuonr     TYPE bseg-zuonr,
          prctr     TYPE bseg-prctr,
          budat_r   TYPE budat,
          belnr_r   TYPE belnr_d,
          gjahr_r   TYPE gjahr,
          hkont_clr TYPE zhkont_clr,
          acctyp    TYPE zacctyp,
          style     TYPE lvc_t_styl,
          color     TYPE lvc_t_scol,
        END OF ty_out.

TYPES: BEGIN OF ty_bseg,
         bukrs TYPE bkpf-bukrs,
         belnr TYPE bkpf-belnr,
         gjahr TYPE bkpf-gjahr,
         waers TYPE bkpf-waers,
         budat TYPE bkpf-budat,
         buzei TYPE bseg-buzei,
         gsber TYPE bseg-gsber,
         bschl TYPE bseg-bschl,
         hkont TYPE bseg-hkont,
         kostl TYPE bseg-kostl,
         matnr TYPE bseg-matnr,
         dmbtr TYPE bseg-dmbtr,
         kunnr TYPE bseg-kunnr,
         zuonr TYPE bseg-zuonr,
         prctr TYPE bseg-prctr,
       END OF ty_bseg.

DATA : ok_code          TYPE sy-ucomm,
       dynerrlog        TYPE smp_dyntxt,
       dynpost          TYPE smp_dyntxt,
       gs_exclude       TYPE ui_functions,
       g_customcont     TYPE REF TO cl_gui_custom_container,
       g_splitter       TYPE REF TO cl_gui_splitter_container,
       g_splitter1      TYPE REF TO cl_gui_splitter_container,
       g_contain01      TYPE REF TO cl_gui_container,
       g_contain02      TYPE REF TO cl_gui_container,
       g_contain03      TYPE REF TO cl_gui_container,
       g_contain04      TYPE REF TO cl_gui_container,
       g_tabgrid        TYPE REF TO cl_gui_alv_grid,
       event_receiver   TYPE REF TO lcl_application,
       selected         VALUE 'X',
       gv_repid         LIKE sy-repid,
       gs_variant       LIKE disvariant,
       gs_layout_alv    TYPE lvc_s_layo,
       gt_main_sort     TYPE lvc_t_sort WITH HEADER LINE,
       gt_main_fieldcat TYPE lvc_t_fcat,
       gs_stable        TYPE lvc_s_stbl,
       gs_toolbar       TYPE stb_button,
       gr_hierseq       TYPE REF TO cl_salv_hierseq_table,
       gr_table         TYPE REF TO cl_salv_table,
       g_handle_alv     TYPE i,
       gt_bapiret2      TYPE STANDARD TABLE OF bapiret2.

DATA : gt_out      TYPE STANDARD TABLE OF ty_out,
       gt_bseg     TYPE STANDARD TABLE OF ty_bseg,
       gt_makt     TYPE STANDARD TABLE OF makt,
       gt_zfidt007 TYPE STANDARD TABLE OF zfidt007,
       gt_zfidt008 TYPE STANDARD TABLE OF zfidt008,
       gt_zfidt009 TYPE STANDARD TABLE OF zfidt009,
       gr_hkont    TYPE RANGE OF hkont.

DATA : gv_post,
       gv_simulate,
       gv_belnr    TYPE bseg-belnr,
       gv_gjahr    TYPE bseg-gjahr.
