PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFI_CONTROL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFI_CONTROL-ZTYPE .
    FIELD ZFI_CONTROL-FIELD_NAME .
    FIELD ZFI_CONTROL-FIELD_VALUE .
    FIELD ZFI_CONTROL-FIELD_VALUE2 .
    FIELD ZFI_CONTROL-DATAB .
    FIELD ZFI_CONTROL-DATBI .
    FIELD ZFI_CONTROL-ERNAM .
    FIELD ZFI_CONTROL-ERDAT .
    FIELD ZFI_CONTROL-ERZET .
    FIELD ZFI_CONTROL-TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFI_CONTROL-ZTYPE .
    FIELD ZFI_CONTROL-FIELD_NAME .
    FIELD ZFI_CONTROL-FIELD_VALUE .
    FIELD ZFI_CONTROL-FIELD_VALUE2 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
