*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFI_CONTROLTOP.                   " Global Data
  INCLUDE LZFI_CONTROLUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFI_CONTROLF00                         . " subprograms
  INCLUDE LZFI_CONTROLI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFI_CONTROLF...                   " Subprograms
* INCLUDE LZFI_CONTROLO...                   " PBO-Modules
* INCLUDE LZFI_CONTROLI...                   " PAI-Modules

INCLUDE LZFI_CONTROLF01.
