*&---------------------------------------------------------------------**
*&  Include           ZFI_E005TOP
*&---------------------------------------------------------------------*
TABLES : sscrfields, bkpf, zfidt004, bseg.

CONTROLS : tc_bank        TYPE TABLEVIEW USING SCREEN 100.

TYPES : BEGIN OF ty_data,
          c01 TYPE string,
          c02 TYPE string,
          c03 TYPE string,
          c04 TYPE string,
          c05 TYPE string,
          c06 TYPE string,
          c07 TYPE string,
          c08 TYPE string,
          c09 TYPE string,
          c10 TYPE string,
          c11 TYPE string,
          c12 TYPE string,
          c13 TYPE string,
          c14 TYPE string,
          c15 TYPE string,
          c16 TYPE string,
          c17 TYPE string,
          c18 TYPE string,
          c19 TYPE string,
          c20 TYPE string,
          c21 TYPE string,
          c22 TYPE string,
          c23 TYPE string,
          c24 TYPE string,
          c25 TYPE string,
          c26 TYPE string,
          c27 TYPE string,
          c28 TYPE string,
          c29 TYPE string,
          c30 TYPE string,
        END OF ty_data.

TYPES : BEGIN OF ty_out,
          mark,
          icon(4),
          buzei      TYPE zfidt005-buzei,
          budat      TYPE zfidt005-budat,
          bukrs      TYPE zfidt005-bukrs,
          zbank      TYPE zfidt005-zbank,
          znorek     TYPE zfidt005-znorek,
          kunnr      TYPE zfidt005-kunnr,
          name1      TYPE zfidt004-keterangan,
          keterangan TYPE c LENGTH 100,
          kursf      TYPE zfidt005-kursf,
          wrbtr      TYPE zfidt005-wrbtr,
          dmbtr      TYPE zfidt005-dmbtr,
          waers      TYPE zfidt005-waers,
          trans      TYPE zfidt005-trans,
          descr      TYPE zfidt005-descr,
          style      TYPE lvc_t_styl,
          color      TYPE lvc_t_scol,
        END OF ty_out.

TYPES : BEGIN OF ty_r005,
          bukrs      TYPE zfidt005-bukrs,
          zbrvn      TYPE zfidt005-zbrvn,
          budat      TYPE zfidt005-budat,
          zbank      TYPE zfidt005-zbank,
          znorek     TYPE zfidt005-znorek,
          buzei      TYPE zfidt005-buzei,
          kunnr      TYPE zfidt005-kunnr,
          name1      TYPE zfidt005-name1,
          shkzg      TYPE zfidt005-shkzg,
          kursf      TYPE zfidt005-kursf,
          wrbtr      TYPE zfidt005-wrbtr,
          dmbtr      TYPE zfidt005-dmbtr,
          waers      TYPE zfidt005-waers,
          trans      TYPE zfidt005-trans,
          descr      TYPE zfidt005-descr,
          keterangan TYPE zfidt005-keterangan,
        END OF ty_r005.

TYPES : BEGIN OF ty_r006,
          bukrs   TYPE zfidt006-bukrs,
          zbpvn   TYPE zfidt006-zbpvn,
          budat   TYPE zfidt006-budat,
          zbank1  TYPE zfidt006-zbank1,
          znorek1 TYPE zfidt006-znorek1,
          zbank2  TYPE zfidt006-zbank2,
          znorek2 TYPE zfidt006-znorek2,
          buzei   TYPE zfidt006-buzei,
          shkzg   TYPE zfidt006-shkzg,
          kursf   TYPE zfidt006-kursf,
          wrbtr   TYPE zfidt006-wrbtr,
          dmbtr   TYPE zfidt006-dmbtr,
          waers   TYPE zfidt006-waers,
          cheque  TYPE zfidt006-cheque,
          descr   TYPE zfidt006-descr,
        END OF ty_r006.

TYPES : BEGIN OF ty_bpvd,
          zbank2  TYPE zfidt006-zbank2,
          znorek2 TYPE zfidt006-znorek2,
          wrbtr2  TYPE zfidt006-wrbtr,
          zdesc2  TYPE zfidt006-descr,
          kursf   TYPE zfidt006-kursf,
        END OF ty_bpvd.

TYPES : BEGIN OF ty_filter,
          index TYPE sy-tabix,
        END OF ty_filter.

CLASS : lcl_application DEFINITION DEFERRED.

CONSTANTS : c_comma     TYPE c LENGTH 1 VALUE ',',
            c_tabulator TYPE c VALUE ' '. "cl_abap_char_utilities=>cr_lf.

DATA : ok_code          TYPE sy-ucomm,
       dynlog           TYPE smp_dyntxt,
       gs_exclude       TYPE ui_functions,
       g_customcont     TYPE REF TO cl_gui_custom_container,
       g_splitter       TYPE REF TO cl_gui_splitter_container,
       g_splitter1      TYPE REF TO cl_gui_splitter_container,
       g_contain01      TYPE REF TO cl_gui_container,
       g_contain02      TYPE REF TO cl_gui_container,
       g_contain03      TYPE REF TO cl_gui_container,
       g_contain04      TYPE REF TO cl_gui_container,
       g_tabgrid        TYPE REF TO cl_gui_alv_grid,
       event_receiver   TYPE REF TO lcl_application,
       selected         VALUE 'X',
       gv_repid         LIKE sy-repid,
       gs_variant       LIKE disvariant,
       gs_layout_alv    TYPE lvc_s_layo,
       gt_main_sort     TYPE lvc_t_sort WITH HEADER LINE,
       gt_main_fieldcat TYPE lvc_t_fcat,
       gs_stable        TYPE lvc_s_stbl,
       gs_toolbar       TYPE stb_button,
       gr_hierseq       TYPE REF TO cl_salv_hierseq_table,
       gr_table         TYPE REF TO cl_salv_table,
       g_handle_alv     TYPE i,
       gt_bapiret2      TYPE STANDARD TABLE OF bapiret2,
       gt_filter        TYPE STANDARD TABLE OF ty_filter,
       lines            TYPE i,
       fill             TYPE i.

DATA : gt_out       TYPE STANDARD TABLE OF ty_out,
       gt_xout      TYPE STANDARD TABLE OF ty_out,
       gt_data      TYPE STANDARD TABLE OF ty_data,
       gt_tbsl      TYPE STANDARD TABLE OF tbsl,
       gt_004       TYPE STANDARD TABLE OF zfidt004,
       gt_004c      TYPE STANDARD TABLE OF zfidt004c,
       gt_005       TYPE STANDARD TABLE OF zfidt005,
       gt_x005      TYPE STANDARD TABLE OF zfidt005,
       gs_004       LIKE LINE OF gt_004,
       gs_out       LIKE LINE OF gt_out,
       gt_t001      TYPE STANDARD TABLE OF t001,
       gt_r005      TYPE STANDARD TABLE OF ty_r005,
       gt_r006      TYPE STANDARD TABLE OF ty_r006,
       gt_bpv       TYPE STANDARD TABLE OF zfidt006,
       gs_bpv       TYPE zfidt006,
       gt_bpvd      TYPE STANDARD TABLE OF ty_bpvd,
       gs_bpvd      LIKE LINE OF gt_bpvd,
       gt_biw_knb1t TYPE STANDARD TABLE OF biw_knb1t.

DATA : gs_header  TYPE zfexpstprnt,
       gt_detail  TYPE STANDARD TABLE OF zfexpstprnt,
       gt_window3 TYPE STANDARD TABLE OF zfexpstprnt.

DATA : gv_subrc      TYPE sy-subrc,
       gv_keterangan TYPE c LENGTH 100,
       gv_wrbtr      TYPE bseg-dmbtr,
       gv_waers      TYPE bkpf-waers,
       gv_row        TYPE lvc_s_row,
       gv_customer   TYPE c LENGTH 40,
       gv_kursf      TYPE tcurr-ukurs,
       gv_descr      TYPE zfidt005-descr.

DATA : p_trade,
       p_other,
       p_pindah.

DATA : dynpfields     TYPE STANDARD TABLE OF dynpread INITIAL SIZE 0.

FIELD-SYMBOLS : <fs_table> TYPE STANDARD TABLE,
                <fs_tab>   TYPE STANDARD TABLE,
                <fs_out>   TYPE STANDARD TABLE,
                <fs_wa>    TYPE any.
