*&---------------------------------------------------------------------*
*&  Include           ZFI_E001TOP
*&---------------------------------------------------------------------*
TABLES : s626, bkpf, sscrfields.

TYPES : BEGIN OF ty_filter,
          index   TYPE sy-tabix,
        END OF ty_filter.

TYPES : BEGIN OF ty_s626,
          ssour     TYPE s626-ssour,
          vrsio     TYPE s626-vrsio,
          spmon     TYPE s626-spmon,
          sptag     TYPE s626-sptag,
          spwoc     TYPE s626-spwoc,
          spbup     TYPE s626-spbup,
          vkbur     TYPE s626-vkbur,
          fkart     TYPE s626-fkart,
          vbeln     TYPE s626-vbeln,
          pkunwe    TYPE s626-pkunwe,
          kdgrp     TYPE s626-kdgrp,
          kvgr3     TYPE s626-kvgr3,
          prodh1    TYPE s626-prodh1,
          matkl     TYPE s626-matkl,
          matnr     TYPE s626-matnr,
          stwae     TYPE s626-stwae,
          basme     TYPE s626-basme,
          umkzwi1   TYPE s626-umkzwi1,
          gukzwi1   TYPE s626-gukzwi1,
          umkzwi4   TYPE s626-umkzwi4,
          gukzwi4   TYPE s626-gukzwi4,
          ummenge   TYPE s626-ummenge,
          gumenge   TYPE s626-gumenge,
          zdisa     TYPE s626-zdisa,
          zdisb     TYPE s626-zdisb,
          zdisc     TYPE s626-zdisc,
          zdise     TYPE s626-zdise,
          zdisf     TYPE s626-zdisf,
          zdisa1    TYPE s626-zdisa1,
          zdisb1    TYPE s626-zdisb1,
          zdisc1    TYPE s626-zdisc1,
          zdise1    TYPE s626-zdise1,
          zdisf1    TYPE s626-zdisf1,
          zdisf3    TYPE s626-zdisf3,
          zdisf3t   TYPE s626-zdisf3t,
          zpmp      TYPE s626-zpmp,
          vbtyp     TYPE s626-vbtyp,
          zdncn(10),
        END OF ty_s626.

TYPES : BEGIN OF ty_out,
          mark,
          icon(4),
          vkbur   TYPE s626-vkbur,
          prodh1  TYPE s626-prodh1,
          vbtyp   TYPE s626-vbtyp,
          zdncn(10),
          vbeln   TYPE s626-vbeln,
          xblnr   TYPE bkpf-xblnr,
          zdistp  TYPE zfidt001-zdistp,
          sptag   TYPE s626-sptag,
          pkunwe  TYPE s626-pkunwe,
          name1   TYPE adrc-name1,
          stwae   TYPE s626-stwae,
          umkzwi1 TYPE s626-umkzwi1,
          gukzwi1 TYPE s626-gukzwi1,
          disc    TYPE s626-zdisb,
          discf   TYPE s626-zdisb1,
          belnr   TYPE bkpf-belnr,
          gjahr   TYPE bkpf-gjahr,
          style   TYPE lvc_t_styl,
          color   TYPE lvc_t_scol,
        END OF ty_out.

TYPES : BEGIN OF ty_claimdisc,
          vkbur   TYPE s626-vkbur,
          prodh1  TYPE s626-prodh1,
          vbtyp   TYPE s626-vbtyp,
          zdncn(10),
          vbeln   TYPE s626-vbeln,
          xblnr   TYPE bkpf-xblnr,
          sptag   TYPE s626-sptag,
          pkunwe  TYPE s626-pkunwe,
          name1   TYPE adrc-name1,
          stwae   TYPE s626-stwae,
          umkzwi1 TYPE s626-umkzwi1,
          gukzwi1 TYPE s626-gukzwi1,
          xbln1   TYPE bkpf-xblnr,
          disc1   TYPE s626-zdisb,
          discf1  TYPE s626-zdisb1,
          mwsbk1  TYPE vbrk-mwsbk,
          beln1   TYPE bkpf-belnr,
          xbln2   TYPE bkpf-xblnr,
          disc2   TYPE s626-zdisb,
          discf2  TYPE s626-zdisb1,
          mwsbk2  TYPE vbrk-mwsbk,
          beln2   TYPE bkpf-belnr,
          xbln3   TYPE bkpf-xblnr,
          disc3   TYPE s626-zdisb,
          discf3  TYPE s626-zdisb1,
          mwsbk3  TYPE vbrk-mwsbk,
          beln3   TYPE bkpf-belnr,
        END OF ty_claimdisc.

TYPES : BEGIN OF ty_error.
        INCLUDE STRUCTURE bapiret2.
TYPES : vbeln   TYPE s626-vbeln,
        END OF ty_error.

CLASS : lcl_application DEFINITION DEFERRED.

DATA : ok_code            TYPE sy-ucomm,
       dynlog             TYPE smp_dyntxt,
       gs_exclude         TYPE ui_functions,
       g_customcont       TYPE REF TO cl_gui_custom_container,
       g_splitter         TYPE REF TO cl_gui_splitter_container,
       g_splitter1        TYPE REF TO cl_gui_splitter_container,
       g_contain01        TYPE REF TO cl_gui_container,
       g_contain02        TYPE REF TO cl_gui_container,
       g_contain03        TYPE REF TO cl_gui_container,
       g_contain04        TYPE REF TO cl_gui_container,
       g_tabgrid          TYPE REF TO cl_gui_alv_grid,
       event_receiver     TYPE REF TO lcl_application,
       selected           VALUE 'X',
       gv_repid           LIKE sy-repid,
       gs_variant         LIKE disvariant,
       gs_layout_alv      TYPE lvc_s_layo,
       gt_main_sort       TYPE lvc_t_sort WITH HEADER LINE,
       gt_main_fieldcat   TYPE lvc_t_fcat,
       gs_stable          TYPE lvc_s_stbl,
       gs_toolbar         TYPE stb_button,
       gr_hierseq         TYPE REF TO cl_salv_hierseq_table,
       gr_table           TYPE REF TO cl_salv_table,
       g_handle_alv       TYPE i,
       gt_bapiret2        TYPE STANDARD TABLE OF bapiret2,
       gt_filter          TYPE STANDARD TABLE OF ty_filter.

DATA : gt_out             TYPE STANDARD TABLE OF ty_out,
       gt_xout            TYPE STANDARD TABLE OF ty_out,
       gt_s626            TYPE STANDARD TABLE OF ty_s626,
       gt_kna1            TYPE STANDARD TABLE OF kna1,
       gt_adrc            TYPE STANDARD TABLE OF adrc,
       gt_tvfk            TYPE STANDARD TABLE OF tvfk,
       gt_tbsl            TYPE STANDARD TABLE OF tbsl.

DATA : gt_001             TYPE STANDARD TABLE OF zfidt001,
       gt_x001            TYPE STANDARD TABLE OF zfidt001,
       gt_save            TYPE STANDARD TABLE OF zfidt001,
       gt_error           TYPE STANDARD TABLE OF ty_error,
       gt_claimdisc       TYPE STANDARD TABLE OF ty_claimdisc.

DATA : gv_budat           TYPE bkpf-budat,
       gv_bktxt           TYPE bkpf-bktxt,
       gv_zuonr           TYPE bseg-zuonr,
       gv_sgtxt           TYPE bseg-sgtxt,
       gv_zdistp          TYPE zfidt001-zdistp,
       gv_subrc           TYPE sy-subrc.

DATA : gt_head            TYPE STANDARD TABLE OF zdgfish_f001,
       gt_detl            TYPE STANDARD TABLE OF zdgfisd_f001.

DATA : gv_belnr           TYPE bkpf-belnr,
       gv_gjahr           TYPE bkpf-gjahr.
