PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIBPHD001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIBPHD001-NOREF .
    FIELD ZFIBPHD001-BUKRS .
    FIELD ZFIBPHD001-GSBER .
    FIELD ZFIBPHD001-DOCDT .
    FIELD ZFIBPHD001-DUEDT .
    FIELD ZFIBPHD001-WAERS .
    FIELD ZFIBPHD001-PAYTO .
    FIELD ZFIBPHD001-TOTAMT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIBPHD001-NOREF .
    FIELD ZFIBPHD001-BUKRS .
    FIELD ZFIBPHD001-GSBER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
