PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIBPDT001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIBPDT001-NOREF .
    FIELD ZFIBPDT001-ITMNO .
    FIELD ZFIBPDT001-HKONT .
    FIELD ZFIBPDT001-TXT50 .
    FIELD ZFIBPDT001-ITMDSC .
    FIELD ZFIBPDT001-INVNO .
    FIELD ZFIBPDT001-ITMAMT .
    FIELD ZFIBPDT001-WAERS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIBPDT001-NOREF .
    FIELD ZFIBPDT001-ITMNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
