*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFIBPHD001TOP.                    " Global Data
  INCLUDE LZFIBPHD001UXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFIBPHD001F00                          . " subprograms
  INCLUDE LZFIBPHD001I00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFIBPHD001F...                    " Subprograms
* INCLUDE LZFIBPHD001O...                    " PBO-Modules
* INCLUDE LZFIBPHD001I...                    " PAI-Modules
