PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIDT005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIDT005-BUKRS .
    FIELD ZFIDT005-ZBRVN .
    FIELD ZFIDT005-BUDAT .
    FIELD ZFIDT005-ZBANK .
    FIELD ZFIDT005-ZNOREK .
    FIELD ZFIDT005-BUZEI .
    FIELD ZFIDT005-KUNNR .
    FIELD ZFIDT005-NAME1 .
    FIELD ZFIDT005-SHKZG .
    FIELD ZFIDT005-KURSF .
    FIELD ZFIDT005-WRBTR .
    FIELD ZFIDT005-DMBTR .
    FIELD ZFIDT005-WAERS .
    FIELD ZFIDT005-TRANS .
    FIELD ZFIDT005-DESCR .
    FIELD ZFIDT005-KETERANGAN .
    FIELD ZFIDT005-BELNR .
    FIELD ZFIDT005-GJAHR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIDT005-BUKRS .
    FIELD ZFIDT005-ZBRVN .
    FIELD ZFIDT005-BUDAT .
    FIELD ZFIDT005-ZBANK .
    FIELD ZFIDT005-ZNOREK .
    FIELD ZFIDT005-BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
