PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIDT004 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIDT004-BUKRS .
    FIELD ZFIDT004-KUNNR .
    FIELD ZFIDT004-ZBANK .
    FIELD ZFIDT004-ZNOREK .
    FIELD ZFIDT004-COMPANY .
    FIELD ZFIDT004-WAERS .
    FIELD ZFIDT004-KETERANGAN .
    FIELD ZFIDT004-FILENAME .
    FIELD ZFIDT004-ZROW .
    FIELD ZFIDT004-ZDCOL .
    FIELD ZFIDT004-ZKCOL .
    FIELD ZFIDT004-ZACOL .
    FIELD ZFIDT004-DELIM .
    FIELD ZFIDT004-ZDECI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIDT004-BUKRS .
    FIELD ZFIDT004-KUNNR .
    FIELD ZFIDT004-ZBANK .
    FIELD ZFIDT004-ZNOREK .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
