PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIDT002 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIDT002-BUKRS .
    FIELD ZFIDT002-CABANG .
    FIELD ZFIDT002-ZBANK .
    FIELD ZFIDT002-ZNOREK .
    FIELD ZFIDT002-ZCABNM .
    FIELD ZFIDT002-HKONT .
    FIELD ZFIDT002-ZROW .
    FIELD ZFIDT002-ZKCOL .
    FIELD ZFIDT002-ZACOL .
    FIELD ZFIDT002-DELIM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIDT002-BUKRS .
    FIELD ZFIDT002-CABANG .
    FIELD ZFIDT002-ZBANK .
    FIELD ZFIDT002-ZNOREK .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
