PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIDT006 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIDT006-BUKRS .
    FIELD ZFIDT006-ZBPVN .
    FIELD ZFIDT006-BUDAT .
    FIELD ZFIDT006-ZBANK1 .
    FIELD ZFIDT006-ZNOREK1 .
    FIELD ZFIDT006-ZBANK2 .
    FIELD ZFIDT006-ZNOREK2 .
    FIELD ZFIDT006-BUZEI .
    FIELD ZFIDT006-SHKZG .
    FIELD ZFIDT006-KURSF .
    FIELD ZFIDT006-WRBTR .
    FIELD ZFIDT006-DMBTR .
    FIELD ZFIDT006-WAERS .
    FIELD ZFIDT006-CHEQUE .
    FIELD ZFIDT006-DESCR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIDT006-BUKRS .
    FIELD ZFIDT006-ZBPVN .
    FIELD ZFIDT006-BUDAT .
    FIELD ZFIDT006-ZBANK1 .
    FIELD ZFIDT006-ZNOREK1 .
    FIELD ZFIDT006-ZBANK2 .
    FIELD ZFIDT006-ZNOREK2 .
    FIELD ZFIDT006-BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
