PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIDT016 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIDT016-BUKRS .
    FIELD ZFIDT016-ANLN1 .
    FIELD ZFIDT016-ANLN2 .
    FIELD ZFIDT016-GJAHR .
    FIELD ZFIDT016-GSBER .
    FIELD ZFIDT016-ANLKL .
    FIELD ZFIDT016-DMBTR .
    FIELD ZFIDT016-WAERS .
    FIELD ZFIDT016-AMTUPL .
    FIELD ZFIDT016-AMTNBV .
    FIELD ZFIDT016-BELNR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIDT016-BUKRS .
    FIELD ZFIDT016-ANLN1 .
    FIELD ZFIDT016-ANLN2 .
    FIELD ZFIDT016-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
