PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIDT014 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIDT014-BUKRS .
    FIELD ZFIDT014-FIELD .
    FIELD ZFIDT014-VALUE .
    FIELD ZFIDT014-WRBTR_LOW .
    FIELD ZFIDT014-WRBTR_HIGH .
    FIELD ZFIDT014-SIGN01 .
    FIELD ZFIDT014-SIGN02 .
    FIELD ZFIDT014-SIGN03 .
    FIELD ZFIDT014-SIGN04 .
    FIELD ZFIDT014-SIGN05 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIDT014-BUKRS .
    FIELD ZFIDT014-FIELD .
    FIELD ZFIDT014-VALUE .
    FIELD ZFIDT014-WRBTR_LOW .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
