*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFKWIOUTTOP.                      " Global Data
  INCLUDE LZFKWIOUTUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFKWIOUTF00                            . " subprograms
  INCLUDE LZFKWIOUTI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFKWIOUTF...                      " Subprograms
* INCLUDE LZFKWIOUTO...                      " PBO-Modules
* INCLUDE LZFKWIOUTI...                      " PAI-Modules

INCLUDE LZFKWIOUTO01.

*INCLUDE LZFKWIOUTF01.
