PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFKWI CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFKWI-ZTRAN .
    FIELD ZFKWI-BUKRS .
    FIELD ZFKWI-KUNNR .
    FIELD ZFKWI-ZUONR .
    FIELD ZFKWI-NOKWI .
    FIELD ZFKWI-NOTTF .
    FIELD ZFKWI-GJAHR .
    FIELD ZFKWI-BELNR .
    FIELD ZFKWI-BUZEI .
    FIELD ZFKWI-BLDAT .
    FIELD ZFKWI-BUDAT .
    FIELD ZFKWI-XBLNR .
    FIELD ZFKWI-BLART .
    FIELD ZFKWI-GSBER .
    FIELD ZFKWI-VKBUR .
    FIELD ZFKWI-SHKZG .
    FIELD ZFKWI-WAERS .
    FIELD ZFKWI-DMBTR .
    FIELD ZFKWI-ZFLAG1 .
    FIELD ZFKWI-ZFLAG2 .
    FIELD ZFKWI-ZFLAG3 .
    FIELD ZFKWI-ZUPLD .
    FIELD ZFKWI-ZUPLT .
    FIELD ZFKWI-ZUPLU .
    FIELD ZFKWI-ZTTFDT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFKWI-ZTRAN .
    FIELD ZFKWI-BUKRS .
    FIELD ZFKWI-KUNNR .
    FIELD ZFKWI-ZUONR .
    FIELD ZFKWI-NOKWI .
    FIELD ZFKWI-NOTTF .
    FIELD ZFKWI-GJAHR .
    FIELD ZFKWI-BELNR .
    FIELD ZFKWI-BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
