*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFKWINOTOP.                       " Global Data
  INCLUDE LZFKWINOUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFKWINOF00                             . " subprograms
  INCLUDE LZFKWINOI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFKWINOF...                       " Subprograms
* INCLUDE LZFKWINOO...                       " PBO-Modules
* INCLUDE LZFKWINOI...                       " PAI-Modules
