*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFLOGTRTOP.                       " Global Data
  INCLUDE LZFLOGTRUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFLOGTRF00                             . " subprograms
  INCLUDE LZFLOGTRI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFLOGTRF...                       " Subprograms
* INCLUDE LZFLOGTRO...                       " PBO-Modules
* INCLUDE LZFLOGTRI...                       " PAI-Modules
