*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNOEFAKTURTOP.                   " Global Data
  INCLUDE LZFNOEFAKTURUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNOEFAKTURF00                         . " subprograms
  INCLUDE LZFNOEFAKTURI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNOEFAKTURF...                   " Subprograms
* INCLUDE LZFNOEFAKTURO...                   " PBO-Modules
* INCLUDE LZFNOEFAKTURI...                   " PAI-Modules
