*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNRCNCUSTTOP.                    " Global Data
  INCLUDE LZFNRCNCUSTUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNRCNCUSTF00                          . " subprograms
  INCLUDE LZFNRCNCUSTI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNRCNCUSTF...                    " Subprograms
* INCLUDE LZFNRCNCUSTO...                    " PBO-Modules
* INCLUDE LZFNRCNCUSTI...                    " PAI-Modules
