PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFNR_RANGE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFNR_RANGE-VKBUR .
    FIELD ZFNR_RANGE-ZITEM .
    FIELD ZFNR_RANGE-NUMKI_QTN .
    FIELD ZFNR_RANGE-NUMKI_SO .
    FIELD ZFNR_RANGE-NUMKI_DO .
    FIELD ZFNR_RANGE-NUMKI_BILL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFNR_RANGE-VKBUR .
    FIELD ZFNR_RANGE-ZITEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
