*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 05.03.2007 at 11:43:52 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNREXCLUDETOP.                   " Global Data
  INCLUDE LZFNREXCLUDEUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNREXCLUDEF00                         . " subprograms
  INCLUDE LZFNREXCLUDEI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNREXCLUDEF...                   " Subprograms
* INCLUDE LZFNREXCLUDEO...                   " PBO-Modules
* INCLUDE LZFNREXCLUDEI...                   " PAI-Modules
