*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNRCUSTMTOP.                     " Global Data
  INCLUDE LZFNRCUSTMUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNRCUSTMF00                           . " subprograms
  INCLUDE LZFNRCUSTMI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNRCUSTMF...                     " Subprograms
* INCLUDE LZFNRCUSTMO...                     " PBO-Modules
* INCLUDE LZFNRCUSTMI...                     " PAI-Modules
