*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNRSTATUSTOP.                    " Global Data
  INCLUDE LZFNRSTATUSUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNRSTATUSF00                          . " subprograms
  INCLUDE LZFNRSTATUSI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNRSTATUSF...                    " Subprograms
* INCLUDE LZFNRSTATUSO...                    " PBO-Modules
* INCLUDE LZFNRSTATUSI...                    " PAI-Modules
