PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFNRCLOSE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFNRCLOSE-VKORG .
    FIELD ZFNRCLOSE-VKBUR .
    FIELD ZFNRCLOSE-MONAT .
    FIELD ZFNRCLOSE-GJAHR .
    FIELD ZFNRCLOSE-MONATTO .
    FIELD ZFNRCLOSE-GJAHRTO .
    FIELD ZFNRCLOSE-USNA1 .
    FIELD ZFNRCLOSE-ERDT1 .
    FIELD ZFNRCLOSE-ERZET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFNRCLOSE-VKORG .
    FIELD ZFNRCLOSE-VKBUR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
