*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNR_RANGETOP.                    " Global Data
  INCLUDE LZFNR_RANGEUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNR_RANGEF00                          . " subprograms
  INCLUDE LZFNR_RANGEI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNR_RANGEF...                    " Subprograms
* INCLUDE LZFNR_RANGEO...                    " PBO-Modules
* INCLUDE LZFNR_RANGEI...                    " PAI-Modules
