PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFNRRANGE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFNRRANGE-VKORG .
    FIELD ZFNRRANGE-VKBUR .
    FIELD ZFNRRANGE-KUNNR .
    FIELD ZFNRRANGE-WAERK .
    FIELD ZFNRRANGE-RANGE_MIN .
    FIELD ZFNRRANGE-RANGE_MAX .
    FIELD ZFNRRANGE-USNA1 .
    FIELD ZFNRRANGE-ERDT1 .
    FIELD ZFNRRANGE-ERZET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFNRRANGE-VKORG .
    FIELD ZFNRRANGE-VKBUR .
    FIELD ZFNRRANGE-KUNNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
