*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNRRANGETOP.                     " Global Data
  INCLUDE LZFNRRANGEUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNRRANGEF00                           . " subprograms
  INCLUDE LZFNRRANGEI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNRRANGEF...                     " Subprograms
* INCLUDE LZFNRRANGEO...                     " PBO-Modules
* INCLUDE LZFNRRANGEI...                     " PAI-Modules
