*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 19.02.2007 at 10:39:09 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNRCLOSETOP.                     " Global Data
  INCLUDE LZFNRCLOSEUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNRCLOSEF00                           . " subprograms
  INCLUDE LZFNRCLOSEI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNRCLOSEF...                     " Subprograms
* INCLUDE LZFNRCLOSEO...                     " PBO-Modules
* INCLUDE LZFNRCLOSEI...                     " PAI-Modules
