*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFNRVALIDTOP.                     " Global Data
  INCLUDE LZFNRVALIDUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFNRVALIDF00                           . " subprograms
  INCLUDE LZFNRVALIDI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFNRVALIDF...                     " Subprograms
* INCLUDE LZFNRVALIDO...                     " PBO-Modules
* INCLUDE LZFNRVALIDI...                     " PAI-Modules
