PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFPPNNRDTL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFPPNNRDTL-BUKRS .
    FIELD ZFPPNNRDTL-VKBUR .
    FIELD ZFPPNNRDTL-KUNNR .
    FIELD ZFPPNNRDTL-GJAHR .
    FIELD ZFPPNNRDTL-NONR .
    FIELD ZFPPNNRDTL-MATNR .
    FIELD ZFPPNNRDTL-NRDT .
    FIELD ZFPPNNRDTL-ARKTX .
    FIELD ZFPPNNRDTL-FKIMG .
    FIELD ZFPPNNRDTL-VRKME .
    FIELD ZFPPNNRDTL-KZWI1 .
    FIELD ZFPPNNRDTL-WAERK .
    FIELD ZFPPNNRDTL-KZWI5 .
    FIELD ZFPPNNRDTL-DPPNR .
    FIELD ZFPPNNRDTL-PPNNR .
    FIELD ZFPPNNRDTL-SKFBP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFPPNNRDTL-BUKRS .
    FIELD ZFPPNNRDTL-VKBUR .
    FIELD ZFPPNNRDTL-KUNNR .
    FIELD ZFPPNNRDTL-GJAHR .
    FIELD ZFPPNNRDTL-NONR .
    FIELD ZFPPNNRDTL-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
