*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFPPNNRDTLTOP.                    " Global Data
  INCLUDE LZFPPNNRDTLUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFPPNNRDTLF00                          . " subprograms
  INCLUDE LZFPPNNRDTLI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFPPNNRDTLF...                    " Subprograms
* INCLUDE LZFPPNNRDTLO...                    " PBO-Modules
* INCLUDE LZFPPNNRDTLI...                    " PAI-Modules
