
PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFPPNNRH CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFPPNNRH-VRSIO .
    FIELD ZFPPNNRH-BUKRS .
    FIELD ZFPPNNRH-KUNNR .
    FIELD ZFPPNNRH-MONAT .
    FIELD ZFPPNNRH-GJAHR .
    FIELD ZFPPNNRH-NONR .
    FIELD ZFPPNNRH-NRDT .
    FIELD ZFPPNNRH-NAME1 .
    FIELD ZFPPNNRH-NAME_CO .
    FIELD ZFPPNNRH-STCEG .
    FIELD ZFPPNNRH-VATPR1 .
    FIELD ZFPPNNRH-VATDT1 .
    FIELD ZFPPNNRH-VATPR2 .
    FIELD ZFPPNNRH-VATDT2 .
    FIELD ZFPPNNRH-VATPR3 .
    FIELD ZFPPNNRH-VATDT3 .
    FIELD ZFPPNNRH-VATPR4 .
    FIELD ZFPPNNRH-VATDT4 .
    FIELD ZFPPNNRH-VATPR5 .
    FIELD ZFPPNNRH-VATDT5 .
    FIELD ZFPPNNRH-WAERS .
    FIELD ZFPPNNRH-TTLNR .
    FIELD ZFPPNNRH-DPPNR .
    FIELD ZFPPNNRH-PPNNR .
    FIELD ZFPPNNRH-TTLCN .
    FIELD ZFPPNNRH-DPPCN .
    FIELD ZFPPNNRH-PPNCN .
    FIELD ZFPPNNRH-BELNRRC .
    FIELD ZFPPNNRH-GJAHRRC .
    FIELD ZFPPNNRH-BUDATRC .
    FIELD ZFPPNNRH-HKONTRC .
    FIELD ZFPPNNRH-SHKZGRC .
    FIELD ZFPPNNRH-WRBTRRC .
    FIELD ZFPPNNRH-USNA1 .
    FIELD ZFPPNNRH-ERDT1 .
    FIELD ZFPPNNRH-ERZET .
    FIELD ZFPPNNRH-USNA2 .
    FIELD ZFPPNNRH-ERDT2 .
    FIELD ZFPPNNRH-BDCFLAG .
    FIELD ZFPPNNRH-NMPEM .
    FIELD ZFPPNNRH-JAPEM .
    FIELD ZFPPNNRH-CITY .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFPPNNRH-VRSIO .
    FIELD ZFPPNNRH-BUKRS .
    FIELD ZFPPNNRH-KUNNR .
    FIELD ZFPPNNRH-MONAT .
    FIELD ZFPPNNRH-GJAHR .
    FIELD ZFPPNNRH-NONR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
