*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 19.12.2002 at 10:24:49 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFRECONTOP.                       " Global Data
  INCLUDE LZFRECONUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFRECONF00                             . " subprograms
  INCLUDE LZFRECONI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFRECONF...                       " Subprograms
* INCLUDE LZFRECONO...                       " PBO-Modules
* INCLUDE LZFRECONI...                       " PAI-Modules
