*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFROUTE_APARTOP.                  " Global Data
  INCLUDE LZFROUTE_APARUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFROUTE_APARF00                        . " subprograms
  INCLUDE LZFROUTE_APARI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFROUTE_APARF...                  " Subprograms
* INCLUDE LZFROUTE_APARO...                  " PBO-Modules
* INCLUDE LZFROUTE_APARI...                  " PAI-Modules
