PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFROUTE_APAR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFROUTE_APAR-ROUTE .
    FIELD ZFROUTE_APAR-ADD04 .
    FIELD ZFROUTE_APAR-BUKRS .
    FIELD ZFROUTE_APAR-KUNWE .
    FIELD ZFROUTE_APAR-BEZEI .
    FIELD ZFROUTE_APAR-WERKS .
    FIELD ZFROUTE_APAR-VKBUR .
    FIELD ZFROUTE_APAR-VBUND .
    FIELD ZFROUTE_APAR-BLART .
    FIELD ZFROUTE_APAR-NEWBS1 .
    FIELD ZFROUTE_APAR-NEWKO1 .
    FIELD ZFROUTE_APAR-NEWUM1 .
    FIELD ZFROUTE_APAR-GSBER1 .
    FIELD ZFROUTE_APAR-KOSTL1 .
    FIELD ZFROUTE_APAR-WWPFN1 .
    FIELD ZFROUTE_APAR-WWPOS1 .
    FIELD ZFROUTE_APAR-KET1 .
    FIELD ZFROUTE_APAR-NEWBS_L1 .
    FIELD ZFROUTE_APAR-NEWKO_L1 .
    FIELD ZFROUTE_APAR-NEWBS2 .
    FIELD ZFROUTE_APAR-NEWKO2 .
    FIELD ZFROUTE_APAR-NEWUM2 .
    FIELD ZFROUTE_APAR-GSBER2 .
    FIELD ZFROUTE_APAR-KOSTL2 .
    FIELD ZFROUTE_APAR-WWPFN2 .
    FIELD ZFROUTE_APAR-WWPOS2 .
    FIELD ZFROUTE_APAR-KET2 .
    FIELD ZFROUTE_APAR-NEWBS_L2 .
    FIELD ZFROUTE_APAR-NEWKO_L2 .
    FIELD ZFROUTE_APAR-NEWBS3 .
    FIELD ZFROUTE_APAR-NEWKO3 .
    FIELD ZFROUTE_APAR-NEWUM3 .
    FIELD ZFROUTE_APAR-GSBER3 .
    FIELD ZFROUTE_APAR-KOSTL3 .
    FIELD ZFROUTE_APAR-WWPFN3 .
    FIELD ZFROUTE_APAR-WWPOS3 .
    FIELD ZFROUTE_APAR-KET3 .
    FIELD ZFROUTE_APAR-NEWBS_L3 .
    FIELD ZFROUTE_APAR-NEWKO_L3 .
    FIELD ZFROUTE_APAR-NEWBS4 .
    FIELD ZFROUTE_APAR-NEWKO4 .
    FIELD ZFROUTE_APAR-NEWUM4 .
    FIELD ZFROUTE_APAR-GSBER4 .
    FIELD ZFROUTE_APAR-KOSTL4 .
    FIELD ZFROUTE_APAR-WWPFN4 .
    FIELD ZFROUTE_APAR-WWPOS4 .
    FIELD ZFROUTE_APAR-KET4 .
    FIELD ZFROUTE_APAR-NEWBS_L4 .
    FIELD ZFROUTE_APAR-NEWKO_L4 .
    FIELD ZFROUTE_APAR-NEWBS5 .
    FIELD ZFROUTE_APAR-NEWKO5 .
    FIELD ZFROUTE_APAR-NEWUM5 .
    FIELD ZFROUTE_APAR-GSBER5 .
    FIELD ZFROUTE_APAR-KOSTL5 .
    FIELD ZFROUTE_APAR-WWPFN5 .
    FIELD ZFROUTE_APAR-WWPOS5 .
    FIELD ZFROUTE_APAR-KET5 .
    FIELD ZFROUTE_APAR-NEWBS_L5 .
    FIELD ZFROUTE_APAR-NEWKO_L5 .
    FIELD ZFROUTE_APAR-NEWBS6 .
    FIELD ZFROUTE_APAR-NEWKO6 .
    FIELD ZFROUTE_APAR-NEWUM6 .
    FIELD ZFROUTE_APAR-GSBER6 .
    FIELD ZFROUTE_APAR-KOSTL6 .
    FIELD ZFROUTE_APAR-WWPFN6 .
    FIELD ZFROUTE_APAR-WWPOS6 .
    FIELD ZFROUTE_APAR-KET6 .
    FIELD ZFROUTE_APAR-NEWBS_L6 .
    FIELD ZFROUTE_APAR-NEWKO_L6 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFROUTE_APAR-ROUTE .
    FIELD ZFROUTE_APAR-ADD04 .
    FIELD ZFROUTE_APAR-BUKRS .
    FIELD ZFROUTE_APAR-KUNWE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
