*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFSFA_CHANNELTOP.                 " Global Data
  INCLUDE LZFSFA_CHANNELUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFSFA_CHANNELF00                       . " subprograms
  INCLUDE LZFSFA_CHANNELI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFSFA_CHANNELF...                 " Subprograms
* INCLUDE LZFSFA_CHANNELO...                 " PBO-Modules
* INCLUDE LZFSFA_CHANNELI...                 " PAI-Modules
