*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFSFA_JHTOP.                      " Global Data
  INCLUDE LZFSFA_JHUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFSFA_JHF00                            . " subprograms
  INCLUDE LZFSFA_JHI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFSFA_JHF...                      " Subprograms
* INCLUDE LZFSFA_JHO...                      " PBO-Modules
* INCLUDE LZFSFA_JHI...                      " PAI-Modules
