PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFTOP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFTOP-BUKRS .
    FIELD ZFTOP-KVGR3 .
    FIELD ZFTOP-TOPIN .
    FIELD ZFTOP-TOPIN1 .
    FIELD ZFTOP-TOPIN2 .
    FIELD ZFTOP-TOPIN3 .
    FIELD ZFTOP-TOPIN4 .
    FIELD ZFTOP-TOPIN5 .
    FIELD ZFTOP-TOPMAX .
    FIELD ZFTOP-TOPSTD .
    FIELD ZFTOP-WAERS .
    FIELD ZFTOP-VALUE .
    FIELD ZFTOP-ACTUAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFTOP-BUKRS .
    FIELD ZFTOP-KVGR3 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
