PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFTOP2 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFTOP2-BUKRS .
    FIELD ZFTOP2-AUART .
    FIELD ZFTOP2-KVGR3 .
    FIELD ZFTOP2-TOPIN .
    FIELD ZFTOP2-TOPIN1 .
    FIELD ZFTOP2-TOPIN2 .
    FIELD ZFTOP2-TOPIN3 .
    FIELD ZFTOP2-TOPIN4 .
    FIELD ZFTOP2-TOPIN5 .
    FIELD ZFTOP2-TOPMAX .
    FIELD ZFTOP2-TOPSTD .
    FIELD ZFTOP2-WAERS .
    FIELD ZFTOP2-VALUE .
    FIELD ZFTOP2-ACTUAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFTOP2-BUKRS .
    FIELD ZFTOP2-AUART .
    FIELD ZFTOP2-KVGR3 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
