*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFTRANSTTFTOP.                    " Global Data
  INCLUDE LZFTRANSTTFUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFTRANSTTFF00                          . " subprograms
  INCLUDE LZFTRANSTTFI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFTRANSTTFF...                    " Subprograms
* INCLUDE LZFTRANSTTFO...                    " PBO-Modules
* INCLUDE LZFTRANSTTFI...                    " PAI-Modules
