PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFTRANSTTF CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFTRANSTTF-BUKRS .
    FIELD ZFTRANSTTF-VKBUR .
    FIELD ZFTRANSTTF-NOMORTTF .
    FIELD ZFTRANSTTF-KUNNR .
    FIELD ZFTRANSTTF-ZUONR .
    FIELD ZFTRANSTTF-VBELN .
    FIELD ZFTRANSTTF-BELNR .
    FIELD ZFTRANSTTF-GJAHR .
    FIELD ZFTRANSTTF-ZFBDT .
    FIELD ZFTRANSTTF-BUDAT .
    FIELD ZFTRANSTTF-BLART .
    FIELD ZFTRANSTTF-TOPEXT .
    FIELD ZFTRANSTTF-ZTERM .
    FIELD ZFTRANSTTF-LEADTM .
    FIELD ZFTRANSTTF-SHKZG .
    FIELD ZFTRANSTTF-DMBTR .
    FIELD ZFTRANSTTF-WAERS .
    FIELD ZFTRANSTTF-ZSUGTTF .
    FIELD ZFTRANSTTF-ZESTDT .
    FIELD ZFTRANSTTF-ZREADT .
    FIELD ZFTRANSTTF-USERNAME .
    FIELD ZFTRANSTTF-TGLINPUT .
    FIELD ZFTRANSTTF-JAMINPUT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFTRANSTTF-BUKRS .
    FIELD ZFTRANSTTF-VKBUR .
    FIELD ZFTRANSTTF-NOMORTTF .
    FIELD ZFTRANSTTF-KUNNR .
    FIELD ZFTRANSTTF-ZUONR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
