*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFTTFNOTOP.                       " Global Data
  INCLUDE LZFTTFNOUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFTTFNOF00                             . " subprograms
  INCLUDE LZFTTFNOI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFTTFNOF...                       " Subprograms
* INCLUDE LZFTTFNOO...                       " PBO-Modules
* INCLUDE LZFTTFNOI...                       " PAI-Modules
