PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFTTFOUTPAY CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFTTFOUTPAY-BUKRS .
    FIELD ZFTTFOUTPAY-VKBUR .
    FIELD ZFTTFOUTPAY-KUNNR .
    FIELD ZFTTFOUTPAY-WEEK .
    FIELD ZFTTFOUTPAY-DAY1 .
    FIELD ZFTTFOUTPAY-DAY2 .
    FIELD ZFTTFOUTPAY-DAY3 .
    FIELD ZFTTFOUTPAY-DAY4 .
    FIELD ZFTTFOUTPAY-DAY5 .
    FIELD ZFTTFOUTPAY-DAY6 .
    FIELD ZFTTFOUTPAY-DAY7 .
    FIELD ZFTTFOUTPAY-USERNAME .
    FIELD ZFTTFOUTPAY-TGLINPUT .
    FIELD ZFTTFOUTPAY-JAMINPUT .
    FIELD ZFTTFOUTPAY-MODBE .
    FIELD ZFTTFOUTPAY-MODDA .
    FIELD ZFTTFOUTPAY-MODTI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFTTFOUTPAY-BUKRS .
    FIELD ZFTTFOUTPAY-VKBUR .
    FIELD ZFTTFOUTPAY-KUNNR .
    FIELD ZFTTFOUTPAY-WEEK .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
