*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFTTFCGTOP.                       " Global Data
  INCLUDE LZFTTFCGUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFTTFCGF00                             . " subprograms
  INCLUDE LZFTTFCGI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFTTFCGF...                       " Subprograms
* INCLUDE LZFTTFCGO...                       " PBO-Modules
* INCLUDE LZFTTFCGI...                       " PAI-Modules
