*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFTTFOUTBDTOP.                    " Global Data
  INCLUDE LZFTTFOUTBDUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFTTFOUTBDF00                          . " subprograms
  INCLUDE LZFTTFOUTBDI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFTTFOUTBDF...                    " Subprograms
* INCLUDE LZFTTFOUTBDO...                    " PBO-Modules
* INCLUDE LZFTTFOUTBDI...                    " PAI-Modules
