*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFTTFOUTPAYTOP.                   " Global Data
  INCLUDE LZFTTFOUTPAYUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFTTFOUTPAYF00                         . " subprograms
  INCLUDE LZFTTFOUTPAYI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFTTFOUTPAYF...                   " Subprograms
* INCLUDE LZFTTFOUTPAYO...                   " PBO-Modules
* INCLUDE LZFTTFOUTPAYI...                   " PAI-Modules
