*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFTTFOUTBWTOP.                    " Global Data
  INCLUDE LZFTTFOUTBWUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFTTFOUTBWF00                          . " subprograms
  INCLUDE LZFTTFOUTBWI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFTTFOUTBWF...                    " Subprograms
* INCLUDE LZFTTFOUTBWO...                    " PBO-Modules
* INCLUDE LZFTTFOUTBWI...                    " PAI-Modules
