PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFTTFOUTBD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFTTFOUTBD-BUKRS .
    FIELD ZFTTFOUTBD-VKBUR .
    FIELD ZFTTFOUTBD-KUNNR .
    FIELD ZFTTFOUTBD-KDGRP .
    FIELD ZFTTFOUTBD-TOPEXT .
    FIELD ZFTTFOUTBD-LEADTM1 .
    FIELD ZFTTFOUTBD-LEADTM2 .
    FIELD ZFTTFOUTBD-BASIC .
    FIELD ZFTTFOUTBD-DD01 .
    FIELD ZFTTFOUTBD-DD02 .
    FIELD ZFTTFOUTBD-DD03 .
    FIELD ZFTTFOUTBD-DD04 .
    FIELD ZFTTFOUTBD-USERNAME .
    FIELD ZFTTFOUTBD-TGLINPUT .
    FIELD ZFTTFOUTBD-JAMINPUT .
    FIELD ZFTTFOUTBD-MODBE .
    FIELD ZFTTFOUTBD-MODDA .
    FIELD ZFTTFOUTBD-MODTI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFTTFOUTBD-BUKRS .
    FIELD ZFTTFOUTBD-VKBUR .
    FIELD ZFTTFOUTBD-KUNNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
