PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFTTFOUTBW CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFTTFOUTBW-BUKRS .
    FIELD ZFTTFOUTBW-VKBUR .
    FIELD ZFTTFOUTBW-KUNNR .
    FIELD ZFTTFOUTBW-WEEK .
    FIELD ZFTTFOUTBW-KDGRP .
    FIELD ZFTTFOUTBW-DAY1 .
    FIELD ZFTTFOUTBW-DAY2 .
    FIELD ZFTTFOUTBW-DAY3 .
    FIELD ZFTTFOUTBW-DAY4 .
    FIELD ZFTTFOUTBW-DAY5 .
    FIELD ZFTTFOUTBW-DAY6 .
    FIELD ZFTTFOUTBW-DAY7 .
    FIELD ZFTTFOUTBW-USERNAME .
    FIELD ZFTTFOUTBW-TGLINPUT .
    FIELD ZFTTFOUTBW-JAMINPUT .
    FIELD ZFTTFOUTBW-MODBE .
    FIELD ZFTTFOUTBW-MODDA .
    FIELD ZFTTFOUTBW-MODTI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFTTFOUTBW-BUKRS .
    FIELD ZFTTFOUTBW-VKBUR .
    FIELD ZFTTFOUTBW-KUNNR .
    FIELD ZFTTFOUTBW-WEEK .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
