PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFVATIN_NR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFVATIN_NR-BUKRS .
    FIELD ZFVATIN_NR-GSBER .
    FIELD ZFVATIN_NR-BELNR .
    FIELD ZFVATIN_NR-GJAHR .
    FIELD ZFVATIN_NR-LIFNR .
    FIELD ZFVATIN_NR-STREET .
    FIELD ZFVATIN_NR-CITY1 .
    FIELD ZFVATIN_NR-STCEG .
    FIELD ZFVATIN_NR-NONR .
    FIELD ZFVATIN_NR-VATPR1 .
    FIELD ZFVATIN_NR-VATDT1 .
    FIELD ZFVATIN_NR-USNA1 .
    FIELD ZFVATIN_NR-ERDT1 .
    FIELD ZFVATIN_NR-ERZET .
    FIELD ZFVATIN_NR-FILES .
    FIELD ZFVATIN_NR-ZUPOS .
    FIELD ZFVATIN_NR-ZDPOS .
    FIELD ZFVATIN_NR-ZZPOS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFVATIN_NR-BUKRS .
    FIELD ZFVATIN_NR-GSBER .
    FIELD ZFVATIN_NR-BELNR .
    FIELD ZFVATIN_NR-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
