PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFVATA2 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFVATA2-BUKRS .
    FIELD ZFVATA2-GSBER .
    FIELD ZFVATA2-GJAHR .
    FIELD ZFVATA2-MONAT .
    FIELD ZFVATA2-TXDAT .
    FIELD ZFVATA2-TBELN .
    FIELD ZFVATA2-NAME1 .
    FIELD ZFVATA2-STCEG .
    FIELD ZFVATA2-SHKZG .
    FIELD ZFVATA2-WAERS .
    FIELD ZFVATA2-DMBTR .
    FIELD ZFVATA2-REMARK .
    FIELD ZFVATA2-ZSTATUS .
    FIELD ZFVATA2-ZDPP .
    FIELD ZFVATA2-STCEG1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFVATA2-BUKRS .
    FIELD ZFVATA2-GSBER .
    FIELD ZFVATA2-GJAHR .
    FIELD ZFVATA2-MONAT .
    FIELD ZFVATA2-TXDAT .
    FIELD ZFVATA2-TBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
