PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFVATA1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFVATA1-BUKRS .
    FIELD ZFVATA1-GSBER .
    FIELD ZFVATA1-GJAHR .
    FIELD ZFVATA1-MONAT .
    FIELD ZFVATA1-TXDAT .
    FIELD ZFVATA1-TBELN .
    FIELD ZFVATA1-NAME1 .
    FIELD ZFVATA1-STCEG .
    FIELD ZFVATA1-SHKZG .
    FIELD ZFVATA1-WAERS .
    FIELD ZFVATA1-DMBTR .
    FIELD ZFVATA1-REMARK .
    FIELD ZFVATA1-ZSTATUS .
    FIELD ZFVATA1-ZDPP .
    FIELD ZFVATA1-STCEG1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFVATA1-BUKRS .
    FIELD ZFVATA1-GSBER .
    FIELD ZFVATA1-GJAHR .
    FIELD ZFVATA1-MONAT .
    FIELD ZFVATA1-TXDAT .
    FIELD ZFVATA1-TBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
