*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 20.02.2004 at 17:44:01 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFVATA2TOP.                       " Global Data
  INCLUDE LZFVATA2UXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFVATA2F00                             . " subprograms
  INCLUDE LZFVATA2I00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFVATA2F...                       " Subprograms
* INCLUDE LZFVATA2O...                       " PBO-Modules
* INCLUDE LZFVATA2I...                       " PAI-Modules
