*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 29.08.2002 at 15:44:41 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFVATA3TOP.                       " Global Data
  INCLUDE LZFVATA3UXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFVATA3F00                             . " subprograms
  INCLUDE LZFVATA3I00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFVATA3F...                       " Subprograms
* INCLUDE LZFVATA3O...                       " PBO-Modules
* INCLUDE LZFVATA3I...                       " PAI-Modules
