*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFVATIN_NRTOP.                    " Global Data
  INCLUDE LZFVATIN_NRUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFVATIN_NRF00                          . " subprograms
  INCLUDE LZFVATIN_NRI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFVATIN_NRF...                    " Subprograms
* INCLUDE LZFVATIN_NRO...                    " PBO-Modules
* INCLUDE LZFVATIN_NRI...                    " PAI-Modules
