PROCESS BEFORE OUTPUT.
* PBO FLOW LOGIC FOR TABLECONTROL 'TA_TABLE1'
  MODULE TA_TABLE1_INIT.
* MODULE TA_TABLE1_CHANGE_TC_ATTR.
* MODULE TA_TABLE1_CHANGE_COL_ATTR.
  LOOP AT   G_TA_TABLE1_ITAB
       INTO G_TA_TABLE1_WA
       WITH CONTROL TA_TABLE1
       CURSOR TA_TABLE1-CURRENT_LINE.
*   MODULE TA_TABLE1_CHANGE_FIELD_ATTR
    MODULE MODIFY_SCREEN1.
    MODULE TA_TABLE1_MOVE.
    MODULE TA_TABLE1_GET_LINES.
  ENDLOOP.

 MODULE STATUS_0910.
*
PROCESS AFTER INPUT.
* PAI FLOW LOGIC FOR TABLECONTROL 'TA_TABLE1'
  LOOP AT G_TA_TABLE1_ITAB.
    CHAIN.
      FIELD G_TA_TABLE1_WA-CHECK.
      FIELD ZFVATA3-BUKRS.
      FIELD ZFVATA3-GSBER.
      FIELD ZFVATA3-GJAHR.
      FIELD ZFVATA3-MONAT.
      FIELD ZFVATA3-TXDAT.
      FIELD ZFVATA3-TBELN.
      FIELD ZFVATA3-NAME1.
      FIELD ZFVATA3-STCEG.
      FIELD ZFVATA3-SHKZG.
      FIELD ZFVATA3-WAERS.
      FIELD ZFVATA3-DMBTR.
      FIELD ZFVATA3-REMARK.
      FIELD ZFVATA3-ZSTATUS.
      MODULE TA_TABLE1_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.
  MODULE TA_TABLE1_USER_COMMAND.
* MODULE TA_TABLE1_CHANGE_TC_ATTR.
* MODULE TA_TABLE1_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0910.
