PROCESS BEFORE OUTPUT.
* PBO FLOW LOGIC FOR TABLECONTROL 'TA_TABLE'
  MODULE TA_TABLE_INIT.
* MODULE TA_TABLE_CHANGE_TC_ATTR.
* MODULE TA_TABLE_CHANGE_COL_ATTR.
  LOOP AT   G_TA_TABLE_ITAB
       INTO G_TA_TABLE_WA
       WITH CONTROL TA_TABLE
       CURSOR TA_TABLE-CURRENT_LINE.
*   MODULE TA_TABLE_CHANGE_FIELD_ATTR
    MODULE MODIFY_SCREEN.
    MODULE TA_TABLE_MOVE.
    MODULE TA_TABLE_GET_LINES.
  ENDLOOP.

 MODULE STATUS_0900.
*
PROCESS AFTER INPUT.
* PAI FLOW LOGIC FOR TABLECONTROL 'TA_TABLE'
  LOOP AT G_TA_TABLE_ITAB.
    CHAIN.
      FIELD G_TA_TABLE_WA-CHECK.
      FIELD ZFVATA1-BUKRS.
      FIELD ZFVATA1-GSBER.
      FIELD ZFVATA1-GJAHR.
      FIELD ZFVATA1-MONAT.
      FIELD ZFVATA1-TXDAT.
      FIELD ZFVATA1-TBELN.
      FIELD ZFVATA1-NAME1.
      FIELD ZFVATA1-STCEG.
      FIELD ZFVATA1-SHKZG.
      FIELD ZFVATA1-WAERS.
      FIELD ZFVATA1-DMBTR.
      FIELD ZFVATA1-REMARK.
      FIELD ZFVATA1-ZSTATUS.
      MODULE TA_TABLE_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.
  MODULE TA_TABLE_USER_COMMAND.
* MODULE TA_TABLE_CHANGE_TC_ATTR.
* MODULE TA_TABLE_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0900.
