PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFVATA3 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFVATA3-BUKRS .
    FIELD ZFVATA3-GSBER .
    FIELD ZFVATA3-GJAHR .
    FIELD ZFVATA3-MONAT .
    FIELD ZFVATA3-TXDAT .
    FIELD ZFVATA3-TBELN .
    FIELD ZFVATA3-NAME1 .
    FIELD ZFVATA3-STCEG .
    FIELD ZFVATA3-SHKZG .
    FIELD ZFVATA3-WAERS .
    FIELD ZFVATA3-DMBTR .
    FIELD ZFVATA3-REMARK .
    FIELD ZFVATA3-ZSTATUS .
    FIELD ZFVATA3-ZDPP .
    FIELD ZFVATA3-STCEG1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFVATA3-BUKRS .
    FIELD ZFVATA3-GSBER .
    FIELD ZFVATA3-GJAHR .
    FIELD ZFVATA3-MONAT .
    FIELD ZFVATA3-TXDAT .
    FIELD ZFVATA3-TBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
