PROCESS BEFORE OUTPUT.
* PBO FLOW LOGIC FOR TABLECONTROL 'TA_TABLE'
  MODULE TA_TABLE2_INIT.
* MODULE TA_TABLE_CHANGE_TC_ATTR.
* MODULE TA_TABLE_CHANGE_COL_ATTR.
  LOOP AT   G_TA_TABLE2_ITAB
       INTO G_TA_TABLE2_WA
       WITH CONTROL TA_TABLE2
       CURSOR TA_TABLE2-CURRENT_LINE.
*   MODULE TA_TABLE_CHANGE_FIELD_ATTR
    MODULE MODIFY_SCREEN2.
    MODULE TA_TABLE2_MOVE.
    MODULE TA_TABLE2_GET_LINES.
  ENDLOOP.

 MODULE STATUS_0920.
*
PROCESS AFTER INPUT.
* PAI FLOW LOGIC FOR TABLECONTROL 'TA_TABLE'
  LOOP AT G_TA_TABLE2_ITAB.
    CHAIN.
      FIELD G_TA_TABLE2_WA-CHECK.
      FIELD ZFVATA2-BUKRS.
      FIELD ZFVATA2-GSBER.
      FIELD ZFVATA2-GJAHR.
      FIELD ZFVATA2-MONAT.
      FIELD ZFVATA2-TXDAT.
      FIELD ZFVATA2-TBELN.
      FIELD ZFVATA2-NAME1.
      FIELD ZFVATA2-STCEG.
      FIELD ZFVATA2-SHKZG.
      FIELD ZFVATA2-WAERS.
      FIELD ZFVATA2-DMBTR.
      FIELD ZFVATA2-REMARK.
      FIELD ZFVATA2-ZSTATUS.
      MODULE TA_TABLE2_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.
  MODULE TA_TABLE2_USER_COMMAND.
* MODULE TA_TABLE_CHANGE_TC_ATTR.
* MODULE TA_TABLE_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0920.
