PROCESS BEFORE OUTPUT.
* PBO FLOW LOGIC FOR TABLECONTROL 'TA_TABLE1'
  MODULE TA_TABLE1_INIT.
* MODULE TA_TABLE1_CHANGE_TC_ATTR.
* MODULE TA_TABLE1_CHANGE_COL_ATTR.
  LOOP AT   G_TA_TABLE1_ITAB
       INTO G_TA_TABLE1_WA
       WITH CONTROL TA_TABLE1
       CURSOR TA_TABLE1-CURRENT_LINE.
*   MODULE TA_TABLE1_CHANGE_FIELD_ATTR
    MODULE MODIFY_SCREEN1.
    MODULE TA_TABLE1_MOVE.
    MODULE TA_TABLE1_GET_LINES.
  ENDLOOP.

 MODULE STATUS_0910.
*
PROCESS AFTER INPUT.
* PAI FLOW LOGIC FOR TABLECONTROL 'TA_TABLE1'
  LOOP AT G_TA_TABLE1_ITAB.
    CHAIN.
      FIELD G_TA_TABLE1_WA-CHECK.
      FIELD ZFVATB4-BUKRS.
      FIELD ZFVATB4-GSBER.
      FIELD ZFVATB4-GJAHR.
      FIELD ZFVATB4-MONAT.
      FIELD ZFVATB4-TXDAT.
      FIELD ZFVATB4-TBELN.
      FIELD ZFVATB4-NAME1.
      FIELD ZFVATB4-SHKZG.
      FIELD ZFVATB4-STCEG.
      FIELD ZFVATB4-WAERS.
      FIELD ZFVATB4-MWSBK.
      FIELD ZFVATB4-REMARK.
      FIELD ZFVATB4-ZSTATUS.
      MODULE TA_TABLE1_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.
  MODULE TA_TABLE1_USER_COMMAND.
* MODULE TA_TABLE1_CHANGE_TC_ATTR.
* MODULE TA_TABLE1_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0910.
