*----------------------------------------------------------------------*
*   INCLUDE ZGDMMF0005TOP                                              *
*----------------------------------------------------------------------*
  TABLES: csks,coep,setleaf,zcodt007.

  TYPES: BEGIN OF ty_out1,
          bukrs   TYPE coep-bukrs,
          gsber   TYPE coep-gsber,
          perio   TYPE coep-perio,
          gjahr   TYPE coep-gjahr,
          kostls  TYPE csks-kostl,
          ltexts  TYPE cskt-ltext,
          kostlr  TYPE csks-kostl,
          ltextr  TYPE cskt-ltext,
          kstar   TYPE coep-kstar,
          ltextk  TYPE csku-ltext,
          setname TYPE setleaf-setname,
          wogbtr  TYPE coep-wogbtr,
          owaer   TYPE coep-owaer,
          megbtr  TYPE coep-megbtr,
          meinh   TYPE coep-meinh,
          amount  TYPE coep-wogbtr,
          zgroup  TYPE char1,
          zlabor  TYPE char5,
          types   TYPE ztypes,
         END OF ty_out1.

  TYPES: BEGIN OF ty_out2,
          bukrs   TYPE coep-bukrs,
          gsber   TYPE coep-gsber,
          perio   TYPE coep-perio,
          gjahr   TYPE coep-gjahr,
          kostl   TYPE csks-kostl,
          ltext   TYPE cskt-ltext,
          wogbtr1 TYPE coep-wogbtr,
          wogbtr2 TYPE coep-wogbtr,
          wogbtr12 TYPE coep-wogbtr,
          wogbtr3 TYPE coep-wogbtr,
          wogbtr4 TYPE coep-wogbtr,
          wogbtr34 TYPE coep-wogbtr,
          owaer   TYPE coep-owaer,
          megbtr1 TYPE coep-megbtr,
          megbtr2 TYPE coep-megbtr,
          megbtr12 TYPE coep-megbtr,
          meinh   TYPE coep-meinh,
          amount1 TYPE coep-wogbtr,
          amount2 TYPE coep-wogbtr,
          amount3 TYPE coep-wogbtr,
          amount4 TYPE coep-wogbtr,
          zgroup  TYPE char1,
         END OF ty_out2.

  TYPES: BEGIN OF ty_out3,
          bukrs   TYPE coep-bukrs,
          gsber   TYPE coep-gsber,
          perio   TYPE coep-perio,
          gjahr   TYPE coep-gjahr,
          plnbez  TYPE afko-plnbez,
          maktx   TYPE makt-maktx,
          objnr   TYPE coep-objnr,
          kostl   TYPE csks-kostl,
          ltexts  TYPE cskt-ltext,
          kstar   TYPE coep-kstar,
          ltextu  TYPE csku-ltext,
          megbtr1 TYPE coep-megbtr,
          megbtr2 TYPE coep-megbtr,
          meinh   TYPE coep-meinh,
          wogbtr1 TYPE coep-wogbtr,
          wogbtr2 TYPE coep-wogbtr,
          wogbtr3 TYPE coep-wogbtr,
          wogbtr4 TYPE coep-wogbtr,
          owaer   TYPE coep-owaer,
          amount1 TYPE coep-wogbtr,
          amount2 TYPE coep-wogbtr,
          amount3 TYPE coep-wogbtr,
          amount4 TYPE coep-wogbtr,
          zgroup  TYPE char1,
         END OF ty_out3.

* Refrence Objects To Alv Grid & Custom Container Classes
  DATA: g_container TYPE scrfname VALUE 'CONTAINER',
        g_grid      TYPE REF TO cl_gui_alv_grid,
*      g_handler   TYPE REF TO lcl_event_responder,
*      g_event_handler TYPE REF TO lcl_event_handler,
        g_custom_container TYPE REF TO cl_gui_custom_container,
        gt_fieldcat TYPE lvc_t_fcat WITH HEADER LINE,
        gt_sort     TYPE lvc_t_sort WITH HEADER LINE,
        gs_layout   TYPE lvc_s_layo,
        gv_repid    LIKE sy-repid,
        gs_variant  TYPE disvariant,
        gt_exclude  TYPE ui_functions,
        e_object    TYPE REF TO cl_alv_event_toolbar_set.

  DATA: gt_out1         TYPE TABLE OF ty_out1 WITH HEADER LINE,
        gt_out2         TYPE TABLE OF ty_out2 WITH HEADER LINE,
        gt_out3         TYPE TABLE OF ty_out3 WITH HEADER LINE,
        gt_out1s1       TYPE TABLE OF ty_out1 WITH HEADER LINE,
        gt_out1s2       TYPE TABLE OF ty_out1 WITH HEADER LINE,
        gt_out1s3       TYPE TABLE OF ty_out1 WITH HEADER LINE,
        gt_makt         TYPE TABLE OF makt    WITH HEADER LINE,
        gt_afko         TYPE TABLE OF afko    WITH HEADER LINE,
        gt_csksmoh      TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprd      TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprd2     TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprde     TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprd_lbr  TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprd_nlbr TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprd2_lbr  TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprd2_nlbr TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprde_lbr  TYPE TABLE OF csks    WITH HEADER LINE,
        gt_csksprde_nlbr TYPE TABLE OF csks    WITH HEADER LINE,
        gt_setleaf      TYPE TABLE OF setleaf WITH HEADER LINE,
        gt_setleafgrp   TYPE TABLE OF setleaf WITH HEADER LINE,
        gt_coepmoh      TYPE TABLE OF coep    WITH HEADER LINE,
        gt_coepprd      TYPE TABLE OF coep    WITH HEADER LINE,
        gt_coepprde     TYPE TABLE OF coep    WITH HEADER LINE,
        gt_coepprd_3    TYPE TABLE OF coep    WITH HEADER LINE,
        gt_coepprd_lbr  TYPE TABLE OF coep    WITH HEADER LINE,
        gt_coepprd_nlbr TYPE TABLE OF coep    WITH HEADER LINE,
        gt_coepprde_lbr  TYPE TABLE OF coep    WITH HEADER LINE,
        gt_coepprde_nlbr TYPE TABLE OF coep    WITH HEADER LINE,
        gt_zcodt007     TYPE TABLE OF zcodt007 WITH HEADER LINE,
        gt_zcodt008     TYPE TABLE OF zcodt008 WITH HEADER LINE.

  DATA: gv_megbtr_lbr   TYPE coep-megbtr,
        gv_megbtr_nlbr  TYPE coep-megbtr,
        gv_kokrs        TYPE csks-kokrs  VALUE '8010',
        gv_kstar        TYPE kstar,
        gv_labor        TYPE char10,
        gv_nonlbr       TYPE char10,
        gr_fixlbr       TYPE RANGE OF coep-kstar WITH HEADER LINE,
        gr_varlbr       TYPE RANGE OF coep-kstar WITH HEADER LINE,
        gr_fixnlbr      TYPE RANGE OF coep-kstar WITH HEADER LINE,
        gr_varnlbr      TYPE RANGE OF coep-kstar WITH HEADER LINE.

  FIELD-SYMBOLS: <fs_out1> LIKE gt_out1,
                 <fs_out2> LIKE gt_out2,
                 <fs_out3> LIKE gt_out3.
