*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDFAKTURKOMTOP.                  " Global Data
  INCLUDE LZGDFAKTURKOMUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDFAKTURKOMF00                        . " subprograms
  INCLUDE LZGDFAKTURKOMI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDFAKTURKOMF...                  " Subprograms
* INCLUDE LZGDFAKTURKOMO...                  " PBO-Modules
* INCLUDE LZGDFAKTURKOMI...                  " PAI-Modules
