PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDMMT0004X CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDMMT0004X-TYPE .
    FIELD ZGDMMT0004X-ZEILE .
    FIELD ZGDMMT0004X-NOU .
    FIELD ZGDMMT0004X-DESCRIPTION .
    FIELD ZGDMMT0004X-FIELD .
    FIELD ZGDMMT0004X-ZINPUT .
    FIELD ZGDMMT0004X-ZACTIVE .
    FIELD ZGDMMT0004X-PERIOD .
    FIELD ZGDMMT0004X-ZGROUP1 .
    FIELD ZGDMMT0004X-ZEND .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDMMT0004X-TYPE .
    FIELD ZGDMMT0004X-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
