PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDMMT004X CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDMMT004X-ZALNO .
    FIELD ZGDMMT004X-LIFNR .
    FIELD ZGDMMT004X-MATNR .
    FIELD ZGDMMT004X-MAKTX .
    FIELD ZGDMMT004X-NAME1 .
    FIELD ZGDMMT004X-MFRPN .
    FIELD ZGDMMT004X-EBELN .
    FIELD ZGDMMT004X-NETPR .
    FIELD ZGDMMT004X-WAERS .
    FIELD ZGDMMT004X-ETMEN .
    FIELD ZGDMMT004X-BOBOT .
    FIELD ZGDMMT004X-BAMNG .
    FIELD ZGDMMT004X-BAMEI .
    FIELD ZGDMMT004X-KBETR .
    FIELD ZGDMMT004X-MENGE .
    FIELD ZGDMMT004X-KBET1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDMMT004X-ZALNO .
    FIELD ZGDMMT004X-LIFNR .
    FIELD ZGDMMT004X-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
