PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDMMCT0002 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDMMCT0002-EKORG .
    FIELD ZGDMMCT0002-EKGRP .
    FIELD ZGDMMCT0002-BUKRS .
    FIELD ZGDMMCT0002-WERKS .
    FIELD ZGDMMCT0002-BSART .
    FIELD ZGDMMCT0002-MATKL .
    FIELD ZGDMMCT0002-VALUE .
    FIELD ZGDMMCT0002-USER_NAME .
    FIELD ZGDMMCT0002-USER_NAME1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDMMCT0002-EKORG .
    FIELD ZGDMMCT0002-EKGRP .
    FIELD ZGDMMCT0002-BUKRS .
    FIELD ZGDMMCT0002-WERKS .
    FIELD ZGDMMCT0002-BSART .
    FIELD ZGDMMCT0002-MATKL .
    FIELD ZGDMMCT0002-VALUE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
