*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDMMT004BTOP.                    " Global Data
  INCLUDE LZGDMMT004BUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDMMT004BF00                          . " subprograms
  INCLUDE LZGDMMT004BI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDMMT004BF...                    " Subprograms
* INCLUDE LZGDMMT004BO...                    " PBO-Modules
* INCLUDE LZGDMMT004BI...                    " PAI-Modules
