PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDMMT0001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDMMT0001-WERKS .
    FIELD ZGDMMT0001-LGORT .
    FIELD ZGDMMT0001-MBLNR .
    FIELD ZGDMMT0001-MJAHR .
    FIELD ZGDMMT0001-ZEILE .
    FIELD ZGDMMT0001-REQ_NO .
    FIELD ZGDMMT0001-REQ_DATE .
    FIELD ZGDMMT0001-REQ_TIME .
    FIELD ZGDMMT0001-BBK_NO .
    FIELD ZGDMMT0001-BBK_DATE .
    FIELD ZGDMMT0001-BBK_TIME .
    FIELD ZGDMMT0001-MENGE .
    FIELD ZGDMMT0001-VALUE_BLOCKED .
    FIELD ZGDMMT0001-REQUESTER .
    FIELD ZGDMMT0001-STATUS .
    FIELD ZGDMMT0001-PRINT_ID .
    FIELD ZGDMMT0001-SCRAP_NO .
    FIELD ZGDMMT0001-SCRAP_YEAR .
    FIELD ZGDMMT0001-DEL .
    FIELD ZGDMMT0001-DEL_DATE .
    FIELD ZGDMMT0001-DEL_BY .
    FIELD ZGDMMT0001-MEINS .
    FIELD ZGDMMT0001-BAP_NO .
    FIELD ZGDMMT0001-BAP_DATE .
    FIELD ZGDMMT0001-BAP_TIME .
    FIELD ZGDMMT0001-LIFNR .
    FIELD ZGDMMT0001-RELSTATUS .
    FIELD ZGDMMT0001-CLA_NO .
    FIELD ZGDMMT0001-CLA_DATE .
    FIELD ZGDMMT0001-CLA_TIME .
    FIELD ZGDMMT0001-CLA_STS .
    FIELD ZGDMMT0001-ZRECD .
    FIELD ZGDMMT0001-MATNR .
    FIELD ZGDMMT0001-CHARG .
    FIELD ZGDMMT0001-ZFRMTL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDMMT0001-WERKS .
    FIELD ZGDMMT0001-LGORT .
    FIELD ZGDMMT0001-MBLNR .
    FIELD ZGDMMT0001-MJAHR .
    FIELD ZGDMMT0001-ZEILE .
    FIELD ZGDMMT0001-REQ_NO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
