*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDMMT004YTOP.                    " Global Data
  INCLUDE LZGDMMT004YUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDMMT004YF00                          . " subprograms
  INCLUDE LZGDMMT004YI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDMMT004YF...                    " Subprograms
* INCLUDE LZGDMMT004YO...                    " PBO-Modules
* INCLUDE LZGDMMT004YI...                    " PAI-Modules
