*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDMMCT0002ATOP.                  " Global Data
  INCLUDE LZGDMMCT0002AUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDMMCT0002AF00                        . " subprograms
  INCLUDE LZGDMMCT0002AI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDMMCT0002AF...                  " Subprograms
* INCLUDE LZGDMMCT0002AO...                  " PBO-Modules
* INCLUDE LZGDMMCT0002AI...                  " PAI-Modules
