*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDMMT004CTOP.                    " Global Data
  INCLUDE LZGDMMT004CUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDMMT004CF00                          . " subprograms
  INCLUDE LZGDMMT004CI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDMMT004CF...                    " Subprograms
* INCLUDE LZGDMMT004CO...                    " PBO-Modules
* INCLUDE LZGDMMT004CI...                    " PAI-Modules
