PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDMMT004A CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDMMT004A-ZALNO .
    FIELD ZGDMMT004A-ZALDT .
    FIELD ZGDMMT004A-WERKS .
    FIELD ZGDMMT004A-EKGRP .
    FIELD ZGDMMT004A-MJAHR .
    FIELD ZGDMMT004A-QUART .
    FIELD ZGDMMT004A-MATNR .
    FIELD ZGDMMT004A-MAKTX .
    FIELD ZGDMMT004A-KONWA .
    FIELD ZGDMMT004A-BUDGET .
    FIELD ZGDMMT004A-DATLB .
    FIELD ZGDMMT004A-WAERS .
    FIELD ZGDMMT004A-NETPRT .
    FIELD ZGDMMT004A-MENGET .
    FIELD ZGDMMT004A-NAME1 .
    FIELD ZGDMMT004A-MEINS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDMMT004A-ZALNO .
    FIELD ZGDMMT004A-ZALDT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
