*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDMMT0004XTOP.                   " Global Data
  INCLUDE LZGDMMT0004XUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDMMT0004XF00                         . " subprograms
  INCLUDE LZGDMMT0004XI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDMMT0004XF...                   " Subprograms
* INCLUDE LZGDMMT0004XO...                   " PBO-Modules
* INCLUDE LZGDMMT0004XI...                   " PAI-Modules
