PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDMMT004D CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDMMT004D-ZALNO .
    FIELD ZGDMMT004D-LIFNR .
    FIELD ZGDMMT004D-EBELN .
    FIELD ZGDMMT004D-EBELP .
    FIELD ZGDMMT004D-ETENR .
    FIELD ZGDMMT004D-EINDT .
    FIELD ZGDMMT004D-MENGE .
    FIELD ZGDMMT004D-MEINS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDMMT004D-ZALNO .
    FIELD ZGDMMT004D-LIFNR .
    FIELD ZGDMMT004D-EBELN .
    FIELD ZGDMMT004D-EBELP .
    FIELD ZGDMMT004D-ETENR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
