PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDMMT004Y CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDMMT004Y-ZALNO .
    FIELD ZGDMMT004Y-LIFNR .
    FIELD ZGDMMT004Y-BANFN .
    FIELD ZGDMMT004Y-BNFPO .
    FIELD ZGDMMT004Y-LFDAT .
    FIELD ZGDMMT004Y-MEINS .
    FIELD ZGDMMT004Y-MENGE .
    FIELD ZGDMMT004Y-BSMNG .
    FIELD ZGDMMT004Y-FRGDT .
    FIELD ZGDMMT004Y-LGORT .
    FIELD ZGDMMT004Y-EBELN .
    FIELD ZGDMMT004Y-EBELP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDMMT004Y-ZALNO .
    FIELD ZGDMMT004Y-LIFNR .
    FIELD ZGDMMT004Y-BANFN .
    FIELD ZGDMMT004Y-BNFPO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
