PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDMMT004E CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDMMT004E-ZALNO .
    FIELD ZGDMMT004E-LIFNR .
    FIELD ZGDMMT004E-ZROW .
    FIELD ZGDMMT004E-TYPE .
    FIELD ZGDMMT004E-ID .
    FIELD ZGDMMT004E-ZNUMBER .
    FIELD ZGDMMT004E-MESSAGE .
    FIELD ZGDMMT004E-LOG_NO .
    FIELD ZGDMMT004E-LOG_MSG_NO .
    FIELD ZGDMMT004E-MESSAGE_V1 .
    FIELD ZGDMMT004E-MESSAGE_V2 .
    FIELD ZGDMMT004E-MESSAGE_V3 .
    FIELD ZGDMMT004E-MESSAGE_V4 .
    FIELD ZGDMMT004E-FIELD .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDMMT004E-ZALNO .
    FIELD ZGDMMT004E-LIFNR .
    FIELD ZGDMMT004E-ZROW .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
