*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDMMT004ETOP.                    " Global Data
  INCLUDE LZGDMMT004EUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDMMT004EF00                          . " subprograms
  INCLUDE LZGDMMT004EI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDMMT004EF...                    " Subprograms
* INCLUDE LZGDMMT004EO...                    " PBO-Modules
* INCLUDE LZGDMMT004EI...                    " PAI-Modules
