*----------------------------------------------------------------------*
*   INCLUDE ZIBM_REPORT_TEMPTOP                                        *
*----------------------------------------------------------------------*
INCLUDE <icon>.

TABLES: mara,
        caufv, " View Table
        afko, " Order header data PP orders
        aufk, " Order master data
        resb, " Reservation/dependent requirements
        rkpf,
        afpo,
        afpod,  " Structure Table Order item dialog structure
        caufvd,
        mard,
        mast,
        marc,
        makt,
        jest,
        zgdppdt0001.

*----------------------------------------------------------*
* Global Data
*----------------------------------------------------------*

*----------------------------------------------------------*
* Internal Table
*----------------------------------------------------------*
TYPES : BEGIN OF ty_notes,
          gstrp   TYPE caufv-gstrp,
          sgtxt   TYPE resb-sgtxt,
        END OF ty_notes.

TYPES: BEGIN OF ta_zgdppdt0001.
        INCLUDE STRUCTURE zgdppdt0001.
TYPES: END OF ta_zgdppdt0001,
       BEGIN OF ta_aufnr,
            werks LIKE zgdppdt0001-werks,
            aufnr LIKE zgdppdt0001-aufnr,
            mtart LIKE zgdppdt0001-mtart,
            fevor LIKE zgdppdt0001-fevor,
       END OF ta_aufnr,
       BEGIN OF ta_resbstock,
            matnr LIKE resb-matnr,
            bdmng LIKE resb-bdmng,
            mtart LIKE mara-mtart,
       END OF ta_resbstock,
       BEGIN OF ta_caufv,
            aufnr  LIKE caufv-aufnr,
            werks  LIKE caufv-aufnr,
            plnbez LIKE caufv-plnbez,
            gstrp  LIKE caufv-gstrp,
            fevor  LIKE caufv-fevor,
            objnr  LIKE caufv-objnr,
            sttxt  LIKE caufvd-sttxt,
            charg  LIKE afpo-charg,
            loekz  LIKE aufk-loekz,
            idat2  LIKE aufk-idat2,
       END OF ta_caufv,
       BEGIN OF ta_afpo,
           aufnr   LIKE afpo-aufnr,
           matnr   LIKE afpo-matnr,
           charg   LIKE afpo-charg,
           maktx   LIKE makt-maktx,
           mtart  LIKE mara-mtart,
       END OF ta_afpo,
       BEGIN OF ta_resb,
           matnr  LIKE resb-matnr,
           werks  LIKE resb-werks,
           lgort  LIKE resb-lgort,
           rsnum  LIKE resb-rsnum,
           aufnr  LIKE resb-aufnr,
           charg  LIKE resb-charg,
           bdter  LIKE resb-bdter,
           bdmng  LIKE resb-bdmng,
           meins  LIKE resb-meins,
           baugr  LIKE resb-baugr,
           vornr  LIKE resb-vornr,
           maktx  LIKE makt-maktx,
           objnr  LIKE resb-objnr,
           bstrf  LIKE marc-bstrf,
           mtart  LIKE mara-mtart,
           matkl  LIKE mara-matkl,
       END OF ta_resb,
       BEGIN OF ta_itab,
            aufnr  LIKE caufv-aufnr,
            werks  LIKE caufv-aufnr,
            plnbez LIKE caufv-plnbez,
            gstrp  LIKE caufv-gstrp,
            fevor  LIKE caufv-fevor,
            objnr  LIKE caufv-objnr,
            sttxt  LIKE caufvd-sttxt,
            charg   LIKE afpo-charg,
            matname   LIKE makt-maktx,

             rsnum  LIKE resb-rsnum,
             matnr  LIKE resb-aufnr,
             lgort  LIKE resb-lgort,
             bdter  LIKE resb-bdter,
             bdmng  LIKE resb-bdmng,
             meins  LIKE resb-meins,
             baugr  LIKE resb-baugr,
             sgtxt  LIKE resb-sgtxt,
             maktx  LIKE makt-maktx,
             bstrf  LIKE marc-bstrf,
             mtart  LIKE mara-mtart,
             matkl  LIKE mara-matkl,
       END OF ta_itab,
       BEGIN OF ta_itab1,
           chkbox(1),
           icon(4),
           rsnum  LIKE resb-rsnum,
           werks  LIKE resb-werks,
           lgort  LIKE resb-lgort,
           date   LIKE sy-datum,
           name   LIKE sy-uname,
           product(400),
           link(500),
           nomor(10),
*           Material(200),
*           Batch(200),
*           PO_NO(200),
           gstrp  LIKE caufv-gstrp,
           bdter  LIKE resb-bdter,
           matnr  LIKE resb-matnr,
           maktx  LIKE makt-maktx,
           bdmng  LIKE resb-bdmng,
           meins  LIKE resb-meins,
           sgtxt  LIKE resb-sgtxt,
           bstrf  LIKE marc-bstrf,
           mtart  LIKE mara-mtart,
           matkl  LIKE mara-matkl,
           fevor  LIKE caufv-fevor,
           aufnr  LIKE afko-aufnr,
           msg(100),
       END OF ta_itab1,
       BEGIN OF ta_matnr,
           matnr LIKE resb-matnr,
           werks LIKE resb-werks,
           lgort LIKE resb-lgort,
       END OF ta_matnr,
       BEGIN OF ta_marc,
           matnr LIKE marc-matnr,
           werks LIKE marc-werks,
           bstrf LIKE marc-bstrf,
       END OF ta_marc,
       BEGIN OF ta_mard,
           matnr    LIKE resb-matnr,
           werks    LIKE resb-werks,
           lgort    LIKE resb-lgort,
           labst    LIKE mard-labst,
           mtart    LIKE mara-mtart,
           qtymin   LIKE mard-labst,
       END OF ta_mard,
       BEGIN OF ta_makt,
           matnr LIKE makt-matnr,
           maktx LIKE makt-maktx,
           mtart LIKE mara-mtart,
           spras LIKE makt-spras,
       END OF ta_makt,
       BEGIN OF ta_link,
           rsnum  LIKE resb-rsnum,
           link(500),
       END OF ta_link,
       BEGIN OF ta_linkx,
             nomor(10),
             aufnr  LIKE resb-aufnr,
             plnbez LIKE resb-matnr,
             charg LIKE afpo-charg,
             gstrp LIKE caufv-gstrp,
             rsnum  LIKE resb-rsnum,
             maktx  LIKE makt-maktx,
             fevor  LIKE caufv-fevor,
             mtart  LIKE mara-mtart,
       END OF ta_linkx.


DATA:  i_caufv TYPE ta_caufv  OCCURS 0,
       i_afpo  TYPE ta_afpo OCCURS 0,
       i_resb TYPE ta_resb OCCURS 0,
       i_mard TYPE ta_mard OCCURS 0,
       i_matnr TYPE ta_matnr OCCURS 0,
       i_link TYPE ta_link OCCURS 0,
       i_itab TYPE ta_itab OCCURS 0,
       i_zgdppdt0001 TYPE ta_zgdppdt0001 OCCURS 0 WITH HEADER LINE,
       i_itab1 TYPE ta_itab1 OCCURS 0 WITH HEADER LINE,
       i_itab_tmp TYPE ta_itab1 OCCURS 0 WITH HEADER LINE,
       i_itab2 TYPE ta_itab1 OCCURS 0 WITH HEADER LINE,
       i_marc TYPE ta_marc OCCURS 0 WITH HEADER LINE,
       i_makt TYPE ta_makt OCCURS 0 WITH HEADER LINE,
       i_linkx_tmp TYPE ta_linkx OCCURS 0,
       i_aufnr TYPE ta_aufnr OCCURS 0,
       i_resbstock TYPE ta_resbstock OCCURS 0,

       i_status TYPE ta_itab1 OCCURS 0 WITH HEADER LINE,
       i_chgsts TYPE ta_itab1 OCCURS 0 WITH HEADER LINE,

       wa_makt TYPE ta_makt,
       wa_marc TYPE ta_marc,
       wa_caufv TYPE ta_caufv ,
       wa_afpo  TYPE ta_afpo,
       wa_resb TYPE ta_resb,
       wa_mard TYPE ta_mard,
       wa_matnr TYPE ta_matnr,
       wa_link TYPE ta_link ,
       wa_itab TYPE ta_itab ,
       wa_zgdppdt0001 TYPE ta_zgdppdt0001 ,
       wa_itab1 TYPE ta_itab1 ,
       wa_itab2 TYPE ta_itab1  ,
       wa_status TYPE ta_itab,
       wa_aufnr TYPE ta_aufnr,
       wa_resbstock TYPE ta_resbstock,
       v_ind_save(1),  " default space
       va_ctr TYPE i,
       sw(1),
       option TYPE i,

       i_linkx TYPE ta_linkx OCCURS 0,
       wa_linkx TYPE ta_linkx ,

      c1    TYPE i,
      c2    TYPE i,
      c3    TYPE i,
      c4    TYPE i,
      w1    TYPE i,  w2    TYPE i,  w3    TYPE i,  w4    TYPE i,
      w5    TYPE i,  w6    TYPE i,  w7    TYPE i,  w8    TYPE i,
      w9    TYPE i,  w10   TYPE i,  w11   TYPE i,  w12   TYPE i,
      w13   TYPE i,  w14   TYPE i,  w15   TYPE i,  w16   TYPE i,
      w17   TYPE i,  w18   TYPE i,  w19   TYPE i,  w19a  TYPE i,
      w20   TYPE i,  w17a  TYPE i,
      w21   TYPE i,  w22   TYPE i,  w23   TYPE i,  w24   TYPE i,
      w25   TYPE i,  w26   TYPE i,  w27   TYPE i,  w28   TYPE i,
      w29   TYPE i,  w30   TYPE i,  w31   TYPE i,  w32   TYPE i,
      w33   TYPE i,  w34   TYPE i,  w35   TYPE i.

***** Define For ALV
DATA: ta_sort TYPE slis_t_sortinfo_alv.

DATA: "GT_OUTTAB type i_itab occurs 0,
      gs_layout TYPE slis_layout_alv,
      g_exit_caused_by_caller,
      gs_exit_caused_by_user TYPE slis_exit_by_user,
      g_repid LIKE sy-repid.

DATA:
    gt_events      TYPE slis_t_event,
    gt_list_top_of_page TYPE slis_t_listheader,
*    G_STATUS_SET   TYPE SLIS_FORMNAME VALUE 'PF_STATUS_SET',
*    G_USER_COMMAND TYPE SLIS_FORMNAME VALUE 'USER_COMMAND',
*    G_TOP_OF_PAGE  TYPE SLIS_FORMNAME VALUE 'TOP_OF_PAGE',
*    G_TOP_OF_LIST  TYPE SLIS_FORMNAME VALUE 'TOP_OF_LIST',
*    G_END_OF_LIST  TYPE SLIS_FORMNAME VALUE 'END_OF_LIST',
    xit_fieldcat   TYPE slis_t_fieldcat_alv,
    xis_print      TYPE slis_print_alv.
*"Variants
DATA: gs_variant LIKE disvariant,
      g_save.

****  Define Data For BAPI
DATA: wa_bapirkpfc TYPE bapirkpfc,
      i_bapiresbc TYPE bapiresbc OCCURS 0 WITH HEADER LINE,
      wa_bapiresbc TYPE bapiresbc,
      i_bapireturn TYPE bapireturn OCCURS 0 WITH HEADER LINE,
      wa_bapireturn TYPE bapireturn,
      i_bapireturn1 TYPE bapiret2 OCCURS 0 WITH HEADER LINE,
      wa_bapireturn1 TYPE bapiret2.

DATA : gt_afko    TYPE STANDARD TABLE OF afko,
       gt_afvc    TYPE STANDARD TABLE OF afvc.

DATA : gv_subrc   TYPE sy-subrc.

DATA : gt_notes   TYPE STANDARD TABLE OF ty_notes,
       gs_notes   LIKE LINE OF gt_notes.
