*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDPPDT0015TOP.                   " Global Data
  INCLUDE LZGDPPDT0015UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDPPDT0015F00                         . " subprograms
  INCLUDE LZGDPPDT0015I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDPPDT0015F...                   " Subprograms
* INCLUDE LZGDPPDT0015O...                   " PBO-Modules
* INCLUDE LZGDPPDT0015I...                   " PAI-Modules
