PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDPPDT0014 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDPPDT0014-WERKS .
    FIELD ZGDPPDT0014-MATNR .
    FIELD ZGDPPDT0014-CHARG .
    FIELD ZGDPPDT0014-COUNTER .
    FIELD ZGDPPDT0014-UNAME .
    FIELD ZGDPPDT0014-UDATE .
    FIELD ZGDPPDT0014-UTIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDPPDT0014-WERKS .
    FIELD ZGDPPDT0014-MATNR .
    FIELD ZGDPPDT0014-CHARG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
