*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDPPDT0006TOP.                   " Global Data
  INCLUDE LZGDPPDT0006UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDPPDT0006F00                         . " subprograms
  INCLUDE LZGDPPDT0006I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDPPDT0006F...                   " Subprograms
* INCLUDE LZGDPPDT0006O...                   " PBO-Modules
* INCLUDE LZGDPPDT0006I...                   " PAI-Modules
