*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDPPDT0005TOP.                   " Global Data
  INCLUDE LZGDPPDT0005UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDPPDT0005F00                         . " subprograms
  INCLUDE LZGDPPDT0005I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDPPDT0005F...                   " Subprograms
* INCLUDE LZGDPPDT0005O...                   " PBO-Modules
* INCLUDE LZGDPPDT0005I...                   " PAI-Modules
