PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDPPDT0001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDPPDT0001-WERKS .
    FIELD ZGDPPDT0001-RSNUM .
    FIELD ZGDPPDT0001-FEVOR .
    FIELD ZGDPPDT0001-GSTRP .
    FIELD ZGDPPDT0001-MATNR .
    FIELD ZGDPPDT0001-AUFNR .
    FIELD ZGDPPDT0001-MTART .
    FIELD ZGDPPDT0001-LGORT .
    FIELD ZGDPPDT0001-CHARG .
    FIELD ZGDPPDT0001-NCTRL .
    FIELD ZGDPPDT0001-UNAME .
    FIELD ZGDPPDT0001-UDATE .
    FIELD ZGDPPDT0001-UTIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDPPDT0001-WERKS .
    FIELD ZGDPPDT0001-RSNUM .
    FIELD ZGDPPDT0001-FEVOR .
    FIELD ZGDPPDT0001-GSTRP .
    FIELD ZGDPPDT0001-MATNR .
    FIELD ZGDPPDT0001-AUFNR .
    FIELD ZGDPPDT0001-MTART .
    FIELD ZGDPPDT0001-LGORT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
