*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 17.05.2005 at 13:50:50 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDPPDT0001TOP.                   " Global Data
  INCLUDE LZGDPPDT0001UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDPPDT0001F00                         . " subprograms
  INCLUDE LZGDPPDT0001I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDPPDT0001F...                   " Subprograms
* INCLUDE LZGDPPDT0001O...                   " PBO-Modules
* INCLUDE LZGDPPDT0001I...                   " PAI-Modules
