*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDSDKOMERTOP.                    " Global Data
  INCLUDE LZGDSDKOMERUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDSDKOMERF00                          . " subprograms
  INCLUDE LZGDSDKOMERI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDSDKOMERF...                    " Subprograms
* INCLUDE LZGDSDKOMERO...                    " PBO-Modules
* INCLUDE LZGDSDKOMERI...                    " PAI-Modules
