PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDSDKOMER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDSDKOMER-VKORG .
    FIELD ZGDSDKOMER-GJAHR .
    FIELD ZGDSDKOMER-VBELN .
    FIELD ZGDSDKOMER-VBTYP .
    FIELD ZGDSDKOMER-FKDAT .
    FIELD ZGDSDKOMER-XBLNR .
    FIELD ZGDSDKOMER-INVO1 .
    FIELD ZGDSDKOMER-INVO2 .
    FIELD ZGDSDKOMER-ERNAM .
    FIELD ZGDSDKOMER-ERDAT .
    FIELD ZGDSDKOMER-MODBE .
    FIELD ZGDSDKOMER-MODDA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDSDKOMER-VKORG .
    FIELD ZGDSDKOMER-GJAHR .
    FIELD ZGDSDKOMER-VBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
