PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0103 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0103-BRNCH .
    FIELD ZGDTXDT0103-BUSLN .
    FIELD ZGDTXDT0103-GABGR .
    FIELD ZGDTXDT0103-SATGR .
    FIELD ZGDTXDT0103-PKPFL .
    FIELD ZGDTXDT0103-SMTXT .
    FIELD ZGDTXDT0103-SMTXT1 .
    FIELD ZGDTXDT0103-SMTXT2 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0103-BRNCH .
    FIELD ZGDTXDT0103-BUSLN .
    FIELD ZGDTXDT0103-GABGR .
    FIELD ZGDTXDT0103-SATGR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
