PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0025 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0025-KUNNR .
    FIELD ZGDTXDT0025-KIDNO .
    FIELD ZGDTXDT0025-NAME_CO .
    FIELD ZGDTXDT0025-STR_SUPPL1 .
    FIELD ZGDTXDT0025-STR_SUPPL2 .
    FIELD ZGDTXDT0025-STR_SUPPL3 .
    FIELD ZGDTXDT0025-LOCATION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0025-KUNNR .
    FIELD ZGDTXDT0025-KIDNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
