PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGDTXDT0107-SORTL .
    FIELD ZGDTXDT0107-SDESC .
    FIELD ZGDTXDT0107-BUSLN .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGDTXDT0107-SORTL .
  module detail_pai.
 endchain.
