PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGDTXDT0007-FAKTURNO .
    FIELD ZGDTXDT0007-FAKDAT .
    FIELD ZGDTXDT0007-MASATX .
    FIELD ZGDTXDT0007-TEXT1 .
    FIELD ZGDTXDT0007-TEXT2 .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGDTXDT0007-FAKTURNO .
    FIELD ZGDTXDT0007-FAKDAT .
    FIELD ZGDTXDT0007-MASATX .
  module detail_pai.
 endchain.
