*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 02.02.2005 at 14:14:12 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDTXFG002TOP.                    " Global Data
  INCLUDE LZGDTXFG002UXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDTXFG002F00                          . " subprograms
  INCLUDE LZGDTXFG002I00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDTXFG002F...                    " Subprograms
* INCLUDE LZGDTXFG002O...                    " PBO-Modules
* INCLUDE LZGDTXFG002I...                    " PAI-Modules
