PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0005-BUKRS .
    FIELD ZGDTXDT0005-BRNCH .
    FIELD ZGDTXDT0005-MASAFROM .
    FIELD ZGDTXDT0005-VSPO .
    FIELD ZGDTXDT0005-PKPNPWP .
    FIELD ZGDTXDT0005-PKPNPPKP .
    FIELD ZGDTXDT0005-PKPUSE .
    FIELD ZGDTXDT0005-PKPNAME .
    FIELD ZGDTXDT0005-PKPADDRS1 .
    FIELD ZGDTXDT0005-PKPADDRS2 .
    FIELD ZGDTXDT0005-PKPCITY .
    FIELD ZGDTXDT0005-PKPPOSTAL .
    FIELD ZGDTXDT0005-PKPTELP .
    FIELD ZGDTXDT0005-FPONE .
    FIELD ZGDTXDT0005-FPTWO .
    FIELD ZGDTXDT0005-INTERVALNO .
    FIELD ZGDTXDT0005-AKTIF .
    FIELD ZGDTXDT0005-PETUGAS .
    FIELD ZGDTXDT0005-JABAT .
    FIELD ZGDTXDT0005-PETUGAS2 .
    FIELD ZGDTXDT0005-JABAT2 .
    FIELD ZGDTXDT0005-NAMEADM .
    FIELD ZGDTXDT0005-JABATADM .
    FIELD ZGDTXDT0005-NAMECAB .
    FIELD ZGDTXDT0005-JABATCAB .
    FIELD ZGDTXDT0005-SSPWAPU .
    FIELD ZGDTXDT0005-OBJRANGE .
    FIELD ZGDTXDT0005-USERID .
    FIELD ZGDTXDT0005-VKORG .
    FIELD ZGDTXDT0005-GSBER .
    FIELD ZGDTXDT0005-NITKU .
    FIELD ZGDTXDT0005-CORETAX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0005-BUKRS .
    FIELD ZGDTXDT0005-BRNCH .
    FIELD ZGDTXDT0005-MASAFROM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
