PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0006 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0006-BUKRS .
    FIELD ZGDTXDT0006-BRNCH .
    FIELD ZGDTXDT0006-BUSLN .
    FIELD ZGDTXDT0006-FAKTURNO .
    FIELD ZGDTXDT0006-FAKDAT .
    FIELD ZGDTXDT0006-MASATX .
    FIELD ZGDTXDT0006-USERID .
    FIELD ZGDTXDT0006-DATRUB .
    FIELD ZGDTXDT0006-TIMERUB .
    FIELD ZGDTXDT0006-NPWP .
    FIELD ZGDTXDT0006-NAME .
    FIELD ZGDTXDT0006-ADDRS1 .
    FIELD ZGDTXDT0006-ADDRS2 .
    FIELD ZGDTXDT0006-CITY .
    FIELD ZGDTXDT0006-POSTAL .
    FIELD ZGDTXDT0006-WAPU .
    FIELD ZGDTXDT0006-RECTYPE .
    FIELD ZGDTXDT0006-FORM .
    FIELD ZGDTXDT0006-ITEM .
    FIELD ZGDTXDT0006-PKPSTAT .
    FIELD ZGDTXDT0006-VKORG .
    FIELD ZGDTXDT0006-GSBER .
    FIELD ZGDTXDT0006-SPART .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0006-BUKRS .
    FIELD ZGDTXDT0006-BRNCH .
    FIELD ZGDTXDT0006-BUSLN .
    FIELD ZGDTXDT0006-FAKTURNO .
    FIELD ZGDTXDT0006-FAKDAT .
    FIELD ZGDTXDT0006-MASATX .
    FIELD ZGDTXDT0006-USERID .
    FIELD ZGDTXDT0006-DATRUB .
    FIELD ZGDTXDT0006-TIMERUB .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
