PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0011 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0011-BRNCH .
    FIELD ZGDTXDT0011-FAKTURNO .
    FIELD ZGDTXDT0011-MASATX .
    FIELD ZGDTXDT0011-OBJRANGE .
    FIELD ZGDTXDT0011-UNAME .
    FIELD ZGDTXDT0011-GSBER .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0011-BRNCH .
    FIELD ZGDTXDT0011-FAKTURNO .
    FIELD ZGDTXDT0011-MASATX .
    FIELD ZGDTXDT0011-OBJRANGE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
