PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGDTXDT0017-OBJECT .
    FIELD ZGDTXDT0017-NRRANGENR .
    FIELD ZGDTXDT0017-FROMNUMBER .
    FIELD ZGDTXDT0017-TONUMBER .
    FIELD ZGDTXDT0017-NRLEVEL .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGDTXDT0017-OBJECT .
    FIELD ZGDTXDT0017-NRRANGENR .
  module detail_pai.
 endchain.
