PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGDTXDT0103-BRNCH .
    FIELD ZGDTXDT0103-BUSLN .
    FIELD ZGDTXDT0103-GABGR .
    FIELD ZGDTXDT0103-SATGR .
    FIELD ZGDTXDT0103-PKPFL .
    FIELD ZGDTXDT0103-SMTXT .
    FIELD ZGDTXDT0103-SMTXT1 .
    FIELD ZGDTXDT0103-SMTXT2 .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGDTXDT0103-BRNCH .
    FIELD ZGDTXDT0103-BUSLN .
    FIELD ZGDTXDT0103-GABGR .
    FIELD ZGDTXDT0103-SATGR .
  module detail_pai.
 endchain.
