*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDTX_0014TOP.                    " Global Data
  INCLUDE LZGDTX_0014UXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDTX_0014F00                          . " subprograms
  INCLUDE LZGDTX_0014I00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDTX_0014F...                    " Subprograms
* INCLUDE LZGDTX_0014O...                    " PBO-Modules
* INCLUDE LZGDTX_0014I...                    " PAI-Modules
