PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGDTXDT0011-BRNCH .
    FIELD ZGDTXDT0011-FAKTURNO .
    FIELD ZGDTXDT0011-MASATX .
    FIELD ZGDTXDT0011-OBJRANGE .
    FIELD ZGDTXDT0011-UNAME .
    FIELD ZGDTXDT0011-UDATE .
    FIELD ZGDTXDT0011-UTIME .
    FIELD ZGDTXDT0011-GSBER .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGDTXDT0011-BRNCH .
    FIELD ZGDTXDT0011-FAKTURNO .
    FIELD ZGDTXDT0011-MASATX .
    FIELD ZGDTXDT0011-OBJRANGE .
  module detail_pai.
 endchain.
