PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGDTXDT0015-BRNCH .
    FIELD ZGDTXDT0015-BUSLN .
    FIELD ZGDTXDT0015-SEQID .
    FIELD ZGDTXDT0015-HKONTFR .
    FIELD ZGDTXDT0015-HKONTTO .
    FIELD ZGDTXDT0015-ACTYPE .
    FIELD ZGDTXDT0015-SPART .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGDTXDT0015-BRNCH .
    FIELD ZGDTXDT0015-BUSLN .
    FIELD ZGDTXDT0015-SEQID .
  module detail_pai.
 endchain.
