PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0015 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0015-BRNCH .
    FIELD ZGDTXDT0015-BUSLN .
    FIELD ZGDTXDT0015-SEQID .
    FIELD ZGDTXDT0015-HKONTFR .
    FIELD ZGDTXDT0015-HKONTTO .
    FIELD ZGDTXDT0015-ACTYPE .
    FIELD ZGDTXDT0015-SPART .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0015-BRNCH .
    FIELD ZGDTXDT0015-BUSLN .
    FIELD ZGDTXDT0015-SEQID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
