PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0101 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0101-BRNCH .
    FIELD ZGDTXDT0101-BUKRS .
    FIELD ZGDTXDT0101-BDESC .
    FIELD ZGDTXDT0101-HO_IND .
    FIELD ZGDTXDT0101-HCOMPANY .
    FIELD ZGDTXDT0101-PRTNRVO .
    FIELD ZGDTXDT0101-PRTNRVI .
    FIELD ZGDTXDT0101-VOTXCODE .
    FIELD ZGDTXDT0101-VOTXCODE_F .
    FIELD ZGDTXDT0101-VITXCODE .
    FIELD ZGDTXDT0101-VITXCODE_F .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0101-BRNCH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
