*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGDTXDT0025TOP.                   " Global Data
  INCLUDE LZGDTXDT0025UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGDTXDT0025F00                         . " subprograms
  INCLUDE LZGDTXDT0025I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGDTXDT0025F...                   " Subprograms
* INCLUDE LZGDTXDT0025O...                   " PBO-Modules
* INCLUDE LZGDTXDT0025I...                   " PAI-Modules
