PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0003-BUKRS .
    FIELD ZGDTXDT0003-BRNCH .
    FIELD ZGDTXDT0003-BUSLN .
    FIELD ZGDTXDT0003-FAKTURNO .
    FIELD ZGDTXDT0003-MASATX .
    FIELD ZGDTXDT0003-BATAL .
    FIELD ZGDTXDT0003-RETURCOUNT .
    FIELD ZGDTXDT0003-FAKTUR_TYPE .
    FIELD ZGDTXDT0003-NAME .
    FIELD ZGDTXDT0003-NAME2 .
    FIELD ZGDTXDT0003-ADDRS1 .
    FIELD ZGDTXDT0003-ADDRS2 .
    FIELD ZGDTXDT0003-CITY .
    FIELD ZGDTXDT0003-POSTAL .
    FIELD ZGDTXDT0003-NPWP .
    FIELD ZGDTXDT0003-WAPU .
    FIELD ZGDTXDT0003-PKPSTAT .
    FIELD ZGDTXDT0003-FORM .
    FIELD ZGDTXDT0003-FLAGA2 .
    FIELD ZGDTXDT0003-USERID .
    FIELD ZGDTXDT0003-FAKGR .
    FIELD ZGDTXDT0003-PPH22PFLAG .
    FIELD ZGDTXDT0003-VKORG .
    FIELD ZGDTXDT0003-GSBER .
    FIELD ZGDTXDT0003-SPART .
    FIELD ZGDTXDT0003-KUNNR .
    FIELD ZGDTXDT0003-KUNRG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0003-BUKRS .
    FIELD ZGDTXDT0003-BRNCH .
    FIELD ZGDTXDT0003-BUSLN .
    FIELD ZGDTXDT0003-FAKTURNO .
    FIELD ZGDTXDT0003-MASATX .
    FIELD ZGDTXDT0003-BATAL .
    FIELD ZGDTXDT0003-RETURCOUNT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
