PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGDTXDT0101-BRNCH .
    FIELD ZGDTXDT0101-BUKRS .
    FIELD ZGDTXDT0101-BDESC .
    FIELD ZGDTXDT0101-HO_IND .
    FIELD ZGDTXDT0101-HCOMPANY .
    FIELD ZGDTXDT0101-PRTNRVO .
    FIELD ZGDTXDT0101-PRTNRVI .
    FIELD ZGDTXDT0101-VOTXCODE .
    FIELD ZGDTXDT0101-VOTXCODE_F .
    FIELD ZGDTXDT0101-VITXCODE .
    FIELD ZGDTXDT0101-VITXCODE_F .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGDTXDT0101-BRNCH .
  module detail_pai.
 endchain.
