PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0012 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0012-BUKRS .
    FIELD ZGDTXDT0012-BRNCH .
    FIELD ZGDTXDT0012-BUSLN .
    FIELD ZGDTXDT0012-BELNR .
    FIELD ZGDTXDT0012-BUDAT .
    FIELD ZGDTXDT0012-BUZEI .
    FIELD ZGDTXDT0012-GJAHR .
    FIELD ZGDTXDT0012-FAKTURNO .
    FIELD ZGDTXDT0012-FAKDAT .
    FIELD ZGDTXDT0012-MASATX .
    FIELD ZGDTXDT0012-CREDIT .
    FIELD ZGDTXDT0012-NO_BH .
    FIELD ZGDTXDT0012-LIFNR .
    FIELD ZGDTXDT0012-NAME .
    FIELD ZGDTXDT0012-ADRNR .
    FIELD ZGDTXDT0012-NPWP .
    FIELD ZGDTXDT0012-ITEM .
    FIELD ZGDTXDT0012-FORM .
    FIELD ZGDTXDT0012-KETERANGAN .
    FIELD ZGDTXDT0012-USERID .
    FIELD ZGDTXDT0012-VKORG .
    FIELD ZGDTXDT0012-GSBER .
    FIELD ZGDTXDT0012-SPART .
    FIELD ZGDTXDT0012-HKONT .
    FIELD ZGDTXDT0012-YEARTX .
    FIELD ZGDTXDT0012-RECTYPE .
    FIELD ZGDTXDT0012-FILES .
    FIELD ZGDTXDT0012-ZUPOS .
    FIELD ZGDTXDT0012-FAKTURNO_NEW .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0012-BUKRS .
    FIELD ZGDTXDT0012-BRNCH .
    FIELD ZGDTXDT0012-BUSLN .
    FIELD ZGDTXDT0012-BELNR .
    FIELD ZGDTXDT0012-BUDAT .
    FIELD ZGDTXDT0012-BUZEI .
    FIELD ZGDTXDT0012-GJAHR .
    FIELD ZGDTXDT0012-FAKTURNO .
    FIELD ZGDTXDT0012-FAKDAT .
    FIELD ZGDTXDT0012-MASATX .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
