PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0024 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0024-BUKRS .
    FIELD ZGDTXDT0024-BRNCH .
    FIELD ZGDTXDT0024-GSBER .
    FIELD ZGDTXDT0024-FAKTURNO .
    FIELD ZGDTXDT0024-MASATX .
    FIELD ZGDTXDT0024-NAME .
    FIELD ZGDTXDT0024-SHKZG .
    FIELD ZGDTXDT0024-STCEG .
    FIELD ZGDTXDT0024-REMARK .
    FIELD ZGDTXDT0024-ZSTATUS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0024-BUKRS .
    FIELD ZGDTXDT0024-BRNCH .
    FIELD ZGDTXDT0024-GSBER .
    FIELD ZGDTXDT0024-FAKTURNO .
    FIELD ZGDTXDT0024-MASATX .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
