PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGDTXDT0024-BUKRS .
    FIELD ZGDTXDT0024-BRNCH .
    FIELD ZGDTXDT0024-GSBER .
    FIELD ZGDTXDT0024-FAKTURNO .
    FIELD ZGDTXDT0024-MASATX .
    FIELD ZGDTXDT0024-FAKDAT .
    FIELD ZGDTXDT0024-NAME .
    FIELD ZGDTXDT0024-SHKZG .
    FIELD ZGDTXDT0024-STCEG .
    FIELD ZGDTXDT0024-WAERS .
    FIELD ZGDTXDT0024-FAKDPP .
    FIELD ZGDTXDT0024-REMARK .
    FIELD ZGDTXDT0024-ZSTATUS .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGDTXDT0024-BUKRS .
    FIELD ZGDTXDT0024-BRNCH .
    FIELD ZGDTXDT0024-GSBER .
    FIELD ZGDTXDT0024-FAKTURNO .
    FIELD ZGDTXDT0024-MASATX .
  module detail_pai.
 endchain.
