PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGDTXDT0023 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGDTXDT0023-BUKRS .
    FIELD ZGDTXDT0023-BRNCH .
    FIELD ZGDTXDT0023-BUSLN .
    FIELD ZGDTXDT0023-VBELN .
    FIELD ZGDTXDT0023-POSNR .
    FIELD ZGDTXDT0023-GJAHR .
    FIELD ZGDTXDT0023-FKART .
    FIELD ZGDTXDT0023-XBUKZ .
    FIELD ZGDTXDT0023-BELNR .
    FIELD ZGDTXDT0023-ERNAM .
    FIELD ZGDTXDT0023-VKORG .
    FIELD ZGDTXDT0023-GSBER .
    FIELD ZGDTXDT0023-SPART .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGDTXDT0023-BUKRS .
    FIELD ZGDTXDT0023-BRNCH .
    FIELD ZGDTXDT0023-BUSLN .
    FIELD ZGDTXDT0023-VBELN .
    FIELD ZGDTXDT0023-POSNR .
    FIELD ZGDTXDT0023-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
