PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGHMMDT001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGHMMDT001-BUKRS .
    FIELD ZGHMMDT001-WERKS .
    FIELD ZGHMMDT001-QUARTER .
    FIELD ZGHMMDT001-MJAHR .
    FIELD ZGHMMDT001-MENGE .
    FIELD ZGHMMDT001-MEINS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGHMMDT001-BUKRS .
    FIELD ZGHMMDT001-WERKS .
    FIELD ZGHMMDT001-QUARTER .
    FIELD ZGHMMDT001-MJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
