*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGHSD_DOC_SOTOP.                  " Global Data
  INCLUDE LZGHSD_DOC_SOUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGHSD_DOC_SOF00                        . " subprograms
  INCLUDE LZGHSD_DOC_SOI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGHSD_DOC_SOF...                  " Subprograms
* INCLUDE LZGHSD_DOC_SOO...                  " PBO-Modules
* INCLUDE LZGHSD_DOC_SOI...                  " PAI-Modules
