PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGHSD_DOC_SO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGHSD_DOC_SO-VKBUR .
    FIELD ZGHSD_DOC_SO-AUART .
    FIELD ZGHSD_DOC_SO-VBELN .
    FIELD ZGHSD_DOC_SO-NAME1 .
    FIELD ZGHSD_DOC_SO-BNAME .
    FIELD ZGHSD_DOC_SO-UTIME .
    FIELD ZGHSD_DOC_SO-UDATE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGHSD_DOC_SO-VKBUR .
    FIELD ZGHSD_DOC_SO-AUART .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
