*----------------------------------------------------------------------*
*   INCLUDE ZGHSDTOP006                                                *
*----------------------------------------------------------------------*
TABLES : vbak,vbkd,knvv,likp,zsl_monitor,nast,vbap,zsextrec.

DATA : BEGIN OF i_monitor OCCURS 0.
         INCLUDE STRUCTURE zsl_monitor.
         DATA :   bnddt    LIKE  vbak-bnddt,
         vttno    LIKE  vttp-vbeln,
         bzirk    LIKE  vbkd-bzirk,
         extcrdat LIKE zsextrec-crdat,
         extcrtim LIKE zsextrec-crtim,
       END OF i_monitor.

DATA : BEGIN OF i_quot OCCURS 0,
         vbeln  LIKE  vbak-vbeln,
         vkbur  LIKE  vbak-vkbur,
         knkli  LIKE  vbak-knkli,
         auart  LIKE  vbak-auart,
         knumv  LIKE  vbak-knumv,
         bstnk  LIKE  vbak-bstnk,
         bstdk  LIKE  vbak-bstdk,
         erdat  LIKE  vbak-erdat,
         erzet  LIKE  vbak-erzet,
         kvgr2  LIKE  vbak-kvgr2,
         bnddt  LIKE  vbak-bnddt,
         augru  LIKE  vbak-augru,
         kdgrp  LIKE  knvv-kdgrp,
         waerk  LIKE  vbak-waerk,
         bzirk  LIKE  knvv-bzirk,
         vkbur2 LIKE  knvv-vkbur,
       END OF i_quot.

DATA : BEGIN OF i_vbfa OCCURS 0,
         vbelv   LIKE  vbfa-vbelv,
         posnv   LIKE  vbfa-posnv,
         vbeln   LIKE  vbfa-vbeln,
         posnn   LIKE  vbfa-posnn,
         vbtyp_n LIKE vbfa-vbtyp_n,
         erdat   LIKE  vbfa-erdat,
         erzet   LIKE  vbfa-erzet,
         bwart   LIKE  vbfa-bwart,
         mjahr   LIKE  vbfa-mjahr,
       END OF i_vbfa.

DATA : BEGIN OF i_vbuk OCCURS 0,
         vbeln LIKE  vbuk-vbeln,
         abstk LIKE  vbuk-abstk,
       END OF i_vbuk.

DATA : BEGIN OF i_mkpf OCCURS 0,
         mblnr LIKE  mkpf-mblnr,
         mjahr LIKE  mkpf-mjahr,
         cpudt LIKE  mkpf-cpudt,
         cputm LIKE  mkpf-cputm,
       END OF i_mkpf.

DATA : BEGIN OF i_poexd OCCURS 0,
         vbeln LIKE  vbak-vbeln,
         bnddt LIKE  vbak-bnddt,
       END OF i_poexd.

DATA : BEGIN OF i_sales OCCURS 0,
         vbeln LIKE  vbak-vbeln,
         vkbur LIKE  vbak-vkbur,
         knumv LIKE  vbak-knumv,
         erdat LIKE  vbak-erdat,
         erzet LIKE  vbak-erzet,
         vgbel LIKE  vbak-vgbel,
         kvgr2 LIKE  vbak-kvgr2,
         waerk LIKE  vbak-waerk,
         kdgrp LIKE  knvv-kdgrp,
         abstk LIKE  vbuk-abstk,
       END OF i_sales.

DATA : BEGIN OF i_grsls OCCURS 0,
         vbeln LIKE  vbap-vbeln,
         posnr LIKE  vbap-posnr,
         kzwi1 LIKE  vbap-kzwi1,
       END OF i_grsls.

DATA : BEGIN OF i_delv OCCURS 0,
         vbeln LIKE  bsad-zuonr,
         podat LIKE  likp-podat,
         potim LIKE  likp-potim,
         wbstk LIKE  vbuk-wbstk,
         kostk LIKE  vbuk-kostk,
       END OF i_delv.

DATA : BEGIN OF i_cdpos OCCURS 0,
         objectclas LIKE  cdpos-objectclas,
         objectid   LIKE  cdpos-objectid,
         changenr   LIKE  cdpos-changenr,
         tabname    LIKE  cdpos-tabname,
         tabkey     LIKE  cdpos-tabkey,
         fname      LIKE  cdpos-fname,
         chngind    LIKE  cdpos-chngind,
         value_new  LIKE  cdpos-value_new,
       END OF i_cdpos.

DATA : BEGIN OF i_cdhdr OCCURS 0,
         objectclas LIKE  cdhdr-objectclas,
         objectid   LIKE  cdhdr-objectid,
         changenr   LIKE  cdhdr-changenr,
         username   LIKE  cdhdr-username,
         udate      LIKE  cdhdr-udate,
         utime      LIKE  cdhdr-utime,
         tcode      LIKE  cdhdr-tcode,
         fname      LIKE  cdpos-fname,
       END OF i_cdhdr.

DATA: BEGIN OF t_a511 OCCURS 0,
        kschl LIKE a511-kschl,
        vkorg LIKE a511-vkorg,
        vkbur LIKE a511-vkbur,
        kdgrp LIKE a511-kdgrp,
        kunwe LIKE a511-kunwe,
        katr1 LIKE a511-katr1,
        datbi LIKE a511-datbi,
        datab LIKE a511-datab,
        knumh LIKE a511-knumh,
        kbetr LIKE konp-kbetr,
        valtg LIKE konp-valtg.
DATA: zday1 LIKE a511-zday1,
      zday2 LIKE a511-zday2,
      zday3 LIKE a511-zday3,
      zday4 LIKE a511-zday4,
      zday5 LIKE a511-zday5,
      zday6 LIKE a511-zday6.
DATA: END OF t_a511.

*DATA : BEGIN OF i_nast OCCURS 0,
*         objky LIKE nast-objky,
*         kappl LIKE nast-kappl,
*         kschl LIKE nast-kschl,
*         vstat LIKE nast-vstat,
*         datvr LIKE  nast-datvr,
*         uhrvr LIKE  nast-uhrvr,
*       END OF i_nast.

DATA : BEGIN OF i_custrec OCCURS 0,
         vbeln LIKE zmm_cust_rec-vbeln,
         crdat LIKE zmm_cust_rec-crdat,
         crtim LIKE zmm_cust_rec-crtim,
       END OF i_custrec.

DATA : BEGIN OF i_zsextrec OCCURS 0,
         vbeln LIKE zsextrec-vbeln,
         crdat LIKE zsextrec-crdat,
         crtim LIKE zsextrec-crtim,
       END OF i_zsextrec.

DATA : BEGIN OF i_pod OCCURS 0,
         vbeln LIKE likp-vbeln,
         podat LIKE likp-podat,
         potim LIKE likp-potim,
       END OF i_pod.

DATA : BEGIN OF i_vato OCCURS 0,
         zuonr LIKE zfvato-zuonr,
         vatdt LIKE zfvato-vatdt,
         vattm LIKE zfvato-vattm,
         repdt LIKE zfvato-repdt,
         reptm LIKE zfvato-reptm,
         dudat LIKE zfvato-dudat,
       END OF i_vato.

DATA : BEGIN OF i_bsad OCCURS 0,
         zuonr LIKE bsad-zuonr,
         budat LIKE bsad-budat,
         cpudt LIKE bsad-cpudt,
         augdt LIKE bsad-augdt,
         wrbtr LIKE bsad-wrbtr,
         belnr LIKE bsad-belnr,
       END OF i_bsad.

DATA : BEGIN OF i_kna1 OCCURS 0,
         kunnr LIKE kna1-kunnr,
         name1 LIKE kna1-name1,
         name2 LIKE kna1-name2,
         ort01 LIKE kna1-ort01,
         katr1 LIKE kna1-katr1,
       END OF i_kna1.

DATA : BEGIN OF i_vttp OCCURS 0,
         tknum LIKE vttk-tknum,
         tplst LIKE vttk-tplst,
         signi LIKE vttk-signi,
         exti1 LIKE vttk-exti1,
         add04 LIKE vttk-add04,
         datbg LIKE vttk-datbg,
         tpnum LIKE vttp-tpnum,
         vbeln LIKE vttp-vbeln,
         ernam LIKE vttp-ernam,
         erdat LIKE vttp-erdat,
         erzet LIKE vttp-erzet,
       END OF i_vttp.

DATA : BEGIN OF i_zfbi OCCURS 0,
         bukrs  LIKE zfbih-bukrs,
         vkbur  LIKE zfbih-vkbur,
         bbeln  LIKE zfbih-bbeln,
         bidat  LIKE zfbih-bidat,
         ebelp  LIKE zfbid-ebelp,
         vbeln  LIKE zfbid-vbeln,
         gjahr  LIKE zfbid-gjahr,
         zuonr  LIKE zfbid-zuonr,
         fkdat  LIKE zfbid-fkdat,
         kunnr  LIKE zfbid-kunnr,
         bflag  LIKE zfbid-bflag,
         ptype  LIKE zfbid-ptype,
         tglttf LIKE zfbid-tglttf,
       END OF i_zfbi.

DATA : BEGIN OF i_detail OCCURS 0,
         vkbur     LIKE vbak-vkbur,
         vkbur2    LIKE knvv-vkbur,
         kvgr2     LIKE vbak-kvgr2,
         bezei(30),
         kdgrp     LIKE knvv-kdgrp,
         ktext     LIKE t151t-ktext,
         katr1     LIKE kna1-katr1,
         knkli     LIKE vbak-knkli,
         bzirk     LIKE knvv-bzirk,
         name1     LIKE kna1-name1,
         auart     LIKE vbak-auart,
         kwert     LIKE konv-kwert,
*         bstnk  LIKE vbak-bstnk,
         bstnk     TYPE bstkd,
         bstdk     LIKE vbak-bstdk,
         qttim     LIKE vbak-erzet,
         qtno      LIKE vbak-vbeln,
         sono      LIKE vbak-vbeln,
         sodat     LIKE vbak-erdat,
         sotim     LIKE vbak-erzet,
         dono      LIKE likp-vbeln,
         dodat     LIKE likp-erdat,
         dotim     LIKE likp-erzet,
         pkdat     LIKE cdhdr-udate,
         pktim     LIKE cdhdr-utime,
         gidat     LIKE cdhdr-udate,
         gitim     LIKE cdhdr-utime,
         crdat     LIKE zmm_cust_rec-crdat,
         crtim     LIKE zmm_cust_rec-crtim,
         podat     LIKE likp-podat,
         potim     LIKE likp-potim,
         vatdt     LIKE zfvato-vatdt,
         vattm     LIKE zfvato-vattm,
         dudat     LIKE zfvato-dudat,
         pydat     LIKE bsad-budat,
         augdt     LIKE bsad-augdt,
         belnr     LIKE bsad-belnr,
         waerk     LIKE vbak-waerk,
         rejid     LIKE zsl_monitor-rejid,
         rejdt     LIKE likp-erdat,
         rejtm     LIKE likp-erzet,
         objid     LIKE cdpos-objectid,
         bnddt     LIKE vbak-bnddt,
         tknum     LIKE vttp-tknum,
         erdat     LIKE vttp-erdat,
         datbg     LIKE vttk-datbg,
         signi     LIKE vttk-signi,
         add04     LIKE vttk-add04,
         bidat     LIKE zfbih-bidat,
         ptype     LIKE zfbid-ptype,
         tglttf    LIKE zfbid-tglttf,
         cnt01     TYPE i,
         cnt02     TYPE i,
         cnt03     TYPE i,
         cnt04     TYPE i,
         cnt05     TYPE i,
         cnt06     TYPE i,
         cnt07     TYPE i,
         cnt08     TYPE i,
         cnt09     TYPE i,
         cnt10     TYPE i,
         stdin     TYPE p DECIMALS 0,
         stdout    TYPE p DECIMALS 0,
         kbetr     TYPE p DECIMALS 0,
         valtg     TYPE p DECIMALS 0,
         pocr      TYPE p DECIMALS 0,
         coun2     TYPE i,
         coun5     TYPE i,
         coun6     TYPE i,
         extcrdat  LIKE zsextrec-crdat,
         extcrtim  LIKE zsextrec-crtim,
         extcreas  LIKE zsextrec-crexdesc,
         headt(50),
         abrvw     TYPE abrvw,
         hit       TYPE int4,
         nhit      TYPE int4,
       END OF i_detail.

DATA : BEGIN OF i_summary OCCURS 0,
         vkbur     LIKE vbak-vkbur,
         vkbur2    LIKE knvv-vkbur,
         bezei(30),
         kdgrp     LIKE knvv-kdgrp,
         ktext     LIKE t151t-ktext,
         katr1     LIKE kna1-katr1,
         bzirk     LIKE knvv-bzirk,
         target    TYPE p DECIMALS 0,
         cnt01     TYPE i,
         cnt02     TYPE i,
         cnt03     TYPE i,
         cnt04     TYPE i,
         cnt05     TYPE i,
         cnt06     TYPE i,
         cnt07     TYPE i,
         cnt08     TYPE i,
         cnt09     TYPE i,
         cnt10     TYPE i,
         stdin     TYPE p DECIMALS 0,
         stdout    TYPE p DECIMALS 0,
         stdpercen TYPE p DECIMALS 2,
       END OF i_summary.

DATA : BEGIN OF i_summary9 OCCURS 0,
         vkbur     LIKE vbak-vkbur,
         bezei(30),
         qtn       TYPE int4,
         hit       TYPE int4,
         nhit      TYPE int4,
         hit%      TYPE dec8_3,
         nhit%     TYPE dec8_3,
       END OF i_summary9.

DATA : BEGIN OF wa_dataset,
         spmon(6),
         vkbur(4),
         kvgr2(3),
         kdgrp(2),
         knkli(10),
         qtno(10),
         qtdat(8),
         qttim(6),
         auart(4),
         bstnk(20),
         bstdk(8),
         sono(10),
         sodat(8),
         sotim(6),
         dono(10),
         dodat(8),
         dotim(6),
         kwert(13),
         pkdat(8),
         pktim(6),
         gidat(8),
         gitim(6),
         podat(8),
         potim(6),
         zuonr(18),
         waerk(5),
         abstk(1),
         rejid(4),
       END OF wa_dataset.

TYPES : BEGIN OF t_line,
          v_text(1500) TYPE c,
        END OF t_line.
TYPES : t_iline TYPE t_line OCCURS 10.

DATA : itabline    TYPE t_iline,
       wa_itabline TYPE t_line.

DATA: i_so         LIKE i_vbfa OCCURS 0 WITH HEADER LINE,
      i_do         LIKE i_vbfa OCCURS 0 WITH HEADER LINE,
      i_gi         LIKE i_vbfa OCCURS 0 WITH HEADER LINE,
      i_inv        LIKE i_vbfa OCCURS 0 WITH HEADER LINE,
      i_pick       LIKE i_vbfa OCCURS 0 WITH HEADER LINE,
      i_vbkd       TYPE TABLE OF vbkd WITH HEADER LINE,
      i_vbak       TYPE TABLE OF vbak WITH HEADER LINE,
      i_monitortmp LIKE i_monitor OCCURS 0 WITH HEADER LINE.

DATA: i_tvv2t      LIKE tvv2t OCCURS 0 WITH HEADER LINE,
      i_t151t      LIKE t151t OCCURS 0 WITH HEADER LINE,
      i_detail1    LIKE i_detail OCCURS 0 WITH HEADER LINE,
      va_ucomm     LIKE sy-ucomm,
      va_count     TYPE i,
      va_radio2(1),
      va_matkl(1),
      va_radio5(1),
      va_radio6(1),
      va_radio9(1),
      va_radio1(1).

DATA : gt_zsextrec TYPE STANDARD TABLE OF zsextrec INITIAL SIZE 0,
       gt_control  TYPE STANDARD TABLE OF zssl_control INITIAL SIZE 0.

DATA : BEGIN OF gt_footer OCCURS 0,
         type(2),
         katr1   LIKE kna1-katr1,
         total   TYPE p DECIMALS 0,
         hit     TYPE p DECIMALS 0,
       END OF gt_footer.

DATA: BEGIN OF gt_knvv OCCURS 0,
        kunnr LIKE knvv-kunnr,
        vkbur LIKE knvv-vkbur,
      END OF gt_knvv.
