PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHSMMMDT006 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHSMMMDT006-PRGRP .
    FIELD ZHSMMMDT006-SUBMI .
    FIELD ZHSMMMDT006-ZALNO .
    FIELD ZHSMMMDT006-BANFN .
    FIELD ZHSMMMDT006-MATNR .
    FIELD ZHSMMMDT006-ZEILE .
    FIELD ZHSMMMDT006-LFDAT .
    FIELD ZHSMMMDT006-BAMNG .
    FIELD ZHSMMMDT006-BAMEI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHSMMMDT006-PRGRP .
    FIELD ZHSMMMDT006-SUBMI .
    FIELD ZHSMMMDT006-ZALNO .
    FIELD ZHSMMMDT006-BANFN .
    FIELD ZHSMMMDT006-MATNR .
    FIELD ZHSMMMDT006-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
