PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHSMMMDT005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHSMMMDT005-TCODE .
    FIELD ZHSMMMDT005-EKGRP .
    FIELD ZHSMMMDT005-SRNO1 .
    FIELD ZHSMMMDT005-ZEILE .
    FIELD ZHSMMMDT005-FRGCO .
    FIELD ZHSMMMDT005-SMTP_ADDR .
    FIELD ZHSMMMDT005-FRGCT .
    FIELD ZHSMMMDT005-ZTO .
    FIELD ZHSMMMDT005-ZCC .
    FIELD ZHSMMMDT005-OBJECT_NAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHSMMMDT005-TCODE .
    FIELD ZHSMMMDT005-EKGRP .
    FIELD ZHSMMMDT005-SRNO1 .
    FIELD ZHSMMMDT005-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
