PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHSMMMDT007 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHSMMMDT007-PRGRP .
    FIELD ZHSMMMDT007-SUBMI .
    FIELD ZHSMMMDT007-ZALNO .
    FIELD ZHSMMMDT007-LIFNR .
    FIELD ZHSMMMDT007-EBELN .
    FIELD ZHSMMMDT007-MATNR .
    FIELD ZHSMMMDT007-ZEILE .
    FIELD ZHSMMMDT007-BEDAT .
    FIELD ZHSMMMDT007-BSTMG .
    FIELD ZHSMMMDT007-BSTME .
    FIELD ZHSMMMDT007-NETPR .
    FIELD ZHSMMMDT007-PEINH .
    FIELD ZHSMMMDT007-BPRME .
    FIELD ZHSMMMDT007-NETWR .
    FIELD ZHSMMMDT007-WAERS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHSMMMDT007-PRGRP .
    FIELD ZHSMMMDT007-SUBMI .
    FIELD ZHSMMMDT007-ZALNO .
    FIELD ZHSMMMDT007-LIFNR .
    FIELD ZHSMMMDT007-EBELN .
    FIELD ZHSMMMDT007-MATNR .
    FIELD ZHSMMMDT007-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
