PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZKMMPPDT019 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZKMMPPDT019-RSNUM .
    FIELD ZKMMPPDT019-RSPOS .
    FIELD ZKMMPPDT019-AUFNR .
    FIELD ZKMMPPDT019-MATNR .
    FIELD ZKMMPPDT019-POSNR .
    FIELD ZKMMPPDT019-WERKS .
    FIELD ZKMMPPDT019-WEMPF .
    FIELD ZKMMPPDT019-EQUNR .
    FIELD ZKMMPPDT019-SHTXT .
    FIELD ZKMMPPDT019-OPERATOR .
    FIELD ZKMMPPDT019-TARA .
    FIELD ZKMMPPDT019-MEINS .
    FIELD ZKMMPPDT019-ERNAM .
    FIELD ZKMMPPDT019-ERDAT .
    FIELD ZKMMPPDT019-ERTIM .
    FIELD ZKMMPPDT019-PACKQ .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZKMMPPDT019-RSNUM .
    FIELD ZKMMPPDT019-RSPOS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
