PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZKMMPPDT024 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZKMMPPDT024-RSNUM .
    FIELD ZKMMPPDT024-RSPOS .
    FIELD ZKMMPPDT024-AUFNR .
    FIELD ZKMMPPDT024-MATNR .
    FIELD ZKMMPPDT024-POSNR .
    FIELD ZKMMPPDT024-WERKS .
    FIELD ZKMMPPDT024-WEMPF .
    FIELD ZKMMPPDT024-EQUNR .
    FIELD ZKMMPPDT024-SHTXT .
    FIELD ZKMMPPDT024-OPERATOR .
    FIELD ZKMMPPDT024-TARA .
    FIELD ZKMMPPDT024-MEINS .
    FIELD ZKMMPPDT024-ERNAM .
    FIELD ZKMMPPDT024-ERDAT .
    FIELD ZKMMPPDT024-ERTIM .
    FIELD ZKMMPPDT024-SCANFL .
    FIELD ZKMMPPDT024-SCANDT .
    FIELD ZKMMPPDT024-SCANTM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZKMMPPDT024-RSNUM .
    FIELD ZKMMPPDT024-RSPOS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
