PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZKMMPPDT023 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZKMMPPDT023-RSNUM .
    FIELD ZKMMPPDT023-RSPOS .
    FIELD ZKMMPPDT023-RSART .
    FIELD ZKMMPPDT023-ZEILE .
    FIELD ZKMMPPDT023-AUFNR .
    FIELD ZKMMPPDT023-POSNR .
    FIELD ZKMMPPDT023-MATNR .
    FIELD ZKMMPPDT023-WERKS .
    FIELD ZKMMPPDT023-LGORT .
    FIELD ZKMMPPDT023-CHARG .
    FIELD ZKMMPPDT023-ERFMG .
    FIELD ZKMMPPDT023-ERFME .
    FIELD ZKMMPPDT023-VORNR .
    FIELD ZKMMPPDT023-LTXA1 .
    FIELD ZKMMPPDT023-SORTF .
    FIELD ZKMMPPDT023-PHSEQ .
    FIELD ZKMMPPDT023-WBOOTH .
    FIELD ZKMMPPDT023-OPERATOR .
    FIELD ZKMMPPDT023-PENGAWAS .
    FIELD ZKMMPPDT023-ERDAT .
    FIELD ZKMMPPDT023-ERTIM .
    FIELD ZKMMPPDT023-SCANFL .
    FIELD ZKMMPPDT023-SCANDT .
    FIELD ZKMMPPDT023-SCANTM .
    FIELD ZKMMPPDT023-MBLNR .
    FIELD ZKMMPPDT023-MJAHR .
    FIELD ZKMMPPDT023-WEMPF .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZKMMPPDT023-RSNUM .
    FIELD ZKMMPPDT023-RSPOS .
    FIELD ZKMMPPDT023-RSART .
    FIELD ZKMMPPDT023-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
