*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 26.12.2006 at 15:50:15 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZKOMERNRTOP.                      " Global Data
  INCLUDE LZKOMERNRUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZKOMERNRF00                            . " subprograms
  INCLUDE LZKOMERNRI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZKOMERNRF...                      " Subprograms
* INCLUDE LZKOMERNRO...                      " PBO-Modules
* INCLUDE LZKOMERNRI...                      " PAI-Modules
