*&---------------------------------------------------------------------*
*&  Include           ZM_ESTIMASI_STOCK2_002
*&---------------------------------------------------------------------*
DATA BEGIN OF gs_outpl.
INCLUDE STRUCTURE zsac7_tmp.
DATA: vkbur    LIKE s603-vkbur,
      kausf    LIKE marc-kausf,
      ratms    LIKE zsac7_tmp-brems,
      ratid(4),
      final(1),
      region   LIKE adrc-region,
      estsls   LIKE zsac7_tmp-netsamt,
      varsls   LIKE zsac7_tmp-netsamt,
      dnqty    LIKE s619-lfimg,
*        dnval  LIKE s619-grosval,
      dnval    LIKE zsac7_tmp-avamt, "MC_GUKZWI1,
      END OF gs_outpl.

DATA: BEGIN OF gs_dataset,
        werks(4),
        vkbur(4),
        prodh1(5),
        prodh2(5),
        prodh3(8),
        matnr(18),
        maktx(35),
        ummenge(15),
        umkzwi1(17),
        gumenge(15),
        gukzwi1(17),
        netsqty(15),
        netsamt(17),
        brems(13),
        brecv(13),
        bretp(13),
        breit(13),
        breus(13),
        bresp(13),
        bretl(13),
        cwems(13),
        cweit(13),
        cweus(13),
        cwetl(13),
        stval(17),
        avsqt(13),
        doamt(17),
        strat(17),
        basme(3),
        stwae(5),
        x1(13),
        x2(13),
        x3(13),
        x4(13),
        x5(13),
        x6(13),
        avqty(17),
        avamt(17),
        stratio(17),
        nsp(13),
        qdo_ip(15),
        vdo_ip(17),
        qcn_ip(15),
        vcn_ip(17),
        stkdo_ip(13),
        stkcn_ip(13),
        kausf(7),
        ratms(13),
        ratid(4),
        final(1),
        region(3),
        estsls(17),
        dnqty(15),
        dnval(17).
DATA END OF gs_dataset.

DATA: gt_string TYPE zdg2catt0002,
      gs_string TYPE zdg2cast0002.

DATA BEGIN OF i_outpl.
INCLUDE STRUCTURE zsac7_tmp.
DATA: kausf    LIKE marc-kausf,
      ratms    LIKE zsac7_tmp-brems,
      ratid(4),
      final(1),
      region   LIKE adrc-region,
      estsls   LIKE zsac7_tmp-netsamt,
      varsls   LIKE zsac7_tmp-netsamt,
      zeinr    LIKE mara-zeinr,
      peran    LIKE prop-peran,
      END OF i_outpl.

DATA : BEGIN OF i_dataset OCCURS 0,
         werks(4),
         prodh1(5),
         prodh2(5),
         prodh3(8),
         matnr(18),
         maktx(35),
         ummenge(15),
         umkzwi1(17),
         gumenge(15),
         gukzwi1(17),
         netsqty(15),
         netsamt(17),
         brems(13),
         brecv(13),
         bretp(13),
         breit(13),
         breus(13),
         bresp(13),
         bretl(13),
         cwems(13),
         cweit(13),
         cweus(13),
         cwetl(13),
         stval(17),
         avsqt(13),
         doamt(17),
         strat(17),
         basme(3),
         stwae(5),
         x1(13),
         x2(13),
         x3(13),
         x4(13),
         x5(13),
         x6(13),
         avqty(17),
         avamt(17),
         stratio(17),
         nsp(13),
         qdo_ip(15),
         vdo_ip(17),
         qcn_ip(15),
         vcn_ip(17),
         stkdo_ip(13),
         stkcn_ip(13),
         kausf(7),
         ratms(13),
         ratid(4),
         final(1),
         region(3),
         estsls(17).
DATA END OF i_dataset.

DATA : i_zplbc   TYPE TABLE OF zplbc WITH HEADER LINE,
       gv_utd(1).
