*----------------------------------------------------------------------*
*   INCLUDE ZM_OOS_PRODUCTTOP
*----------------------------------------------------------------------*
INCLUDE <icon>.

*----------------------------------------------------------*
* Tables
*----------------------------------------------------------*
TABLES: ekko, ekpo, sscrfields.

TYPES : BEGIN OF ty_likp,
          vbeln TYPE vbeln_vl,
          erdat TYPE erdat,
          lprio TYPE likp-lprio,
        END OF ty_likp.

DATA : BEGIN OF gt_vbfa OCCURS 0,
         vbelv   TYPE vbeln_von,
         posnv   TYPE posnr_von,
         vbeln   TYPE vbeln_nach,
         posnn   TYPE posnr_nach,
         vbtyp_n TYPE vbtyp_n,
       END OF gt_vbfa.

*----------------------------------------------------------*
* Global Data
*----------------------------------------------------------*
DATA: va_range   TYPE q_vorlauf VALUE 3.

*----------------------------------------------------------*
* Internal Table
*----------------------------------------------------------*
DATA: BEGIN OF gt_t156 OCCURS 0,
        bwart TYPE bwart,
        xstbw TYPE xstbw,
      END OF gt_t156.

DATA: BEGIN OF gt_ekko OCCURS 0,
        ebeln TYPE ebeln,
        bukrs TYPE bukrs,
        bsart TYPE esart,
        lifnr TYPE elifn,
        ekorg TYPE ekorg,
        bedat TYPE ebdat,
        aedat TYPE aedat,
      END OF gt_ekko.
DATA: BEGIN OF gt_ekpo OCCURS 0,
        ebeln TYPE ebeln,
        ebelp TYPE ebelp,
        matnr TYPE matnr,
        werks TYPE ewerk,
        menge TYPE bstmg,
        meins TYPE bstme,
        lgort TYPE lgort_d,
        reslo LIKE ekpo-reslo,
        bednr TYPE ekpo-bednr,
        banfn TYPE ekpo-banfn,
        kunnr TYPE ekpo-kunnr,
      END OF gt_ekpo.
DATA: BEGIN OF gt_ekbe OCCURS 0,
        ebeln TYPE ebeln,
        ebelp TYPE ebelp,
        belnr TYPE mblnr,
        buzei TYPE posnr_nach,
        bewtp TYPE bewtp,
        bwart TYPE bwart,
        budat TYPE budat,
        menge TYPE menge_d,
        lgort TYPE lgort_d,
        xblnr TYPE xblnr1,
        lprio TYPE mepo1331-lprio,
        bezei TYPE tprit-bezei,
      END OF gt_ekbe.
DATA: BEGIN OF gt_vercon OCCURS 0,
        ebeln   TYPE ebeln,
        versidn TYPE i,
      END OF gt_vercon.

DATA: BEGIN OF gt_t001l OCCURS 0,
        werks LIKE t001l-werks,
        lgort LIKE t001l-lgort,
        vstel LIKE t001l-vstel,
      END OF gt_t001l.

DATA: BEGIN OF gt_makt OCCURS 0,
        matnr TYPE matnr,
        prdha TYPE prodh_d,
        maktx TYPE maktx,
        extwg TYPE extwg,
      END OF gt_makt.

DATA: BEGIN OF gt_header OCCURS 0,
        werks  TYPE ewerk,
        matnr  TYPE matnr,
        maktx  TYPE maktx,
        prdha  TYPE prodh_d,
        extwg  TYPE extwg,
        ebeln  TYPE ebeln,
        ebelp  TYPE ebelp,
        bedat  TYPE ebdat,
        aedat  TYPE aedat,
        lifnr  TYPE elifn,
        menge  TYPE bstmg,
        meins  TYPE bstme,
        pocar  TYPE bstmg,
        mecar  TYPE bstme,
        lgort  TYPE lgort_d,
        reslo  LIKE ekpo-reslo,
        vstel  LIKE t001l-vstel,
        bednr  TYPE ekpo-bednr,
        tdline TYPE tdline,
        banfn  TYPE banfn,
        kunnr  TYPE kna1-kunnr,
        name1  TYPE kna1-name1,
        vndnm  TYPE lfa1-name1,
        bsart  TYPE ekko-bsart,
      END OF gt_header.

DATA: BEGIN OF gt_vdata OCCURS 0.
        INCLUDE STRUCTURE gt_header.
        DATA:   belnr_gr TYPE mblnr,
        menge_gr TYPE menge_d,
        budat_gr TYPE budat,
        otd      TYPE menge_d,
        belnr_dn TYPE mblnr,
        brgew    TYPE brgew_15,
        gewei    TYPE gewei,
        volum    TYPE volum_15,
        voleh    TYPE voleh,
        menge_dn TYPE menge_d,
        budat_dn TYPE budat,
        belnr_gi TYPE mblnr,
        menge_gi TYPE menge_d,
        budat_gi TYPE budat.
DATA: tknum   TYPE tknum,
      datbg   TYPE datbg,
      erdat   TYPE erdat,
      exti1   TYPE exti1,
      exti2   TYPE exti2,
      signi   TYPE signi,
      tdlnr   TYPE tdlnr,
      gesztd  TYPE kp_gesztdp,
      etdat   TYPE erdat,
      profnm  TYPE lfa1-name1,
      dn_ship TYPE i,
      gi_ship TYPE i,
      ship_gr TYPE i.
DATA: gr_gi     TYPE i,
      gi_dn     TYPE i,
      dn_po_sto TYPE i,
      gr_po_sto TYPE i.
DATA:   versidn     TYPE i.
DATA: mnth_alo(20),
      week_alo      TYPE i,
      mnth_dn(20),
      week_dn       TYPE i,
      mnth_gi(20),
      week_gi       TYPE i,
      mnth_gr(20),
      week_gr       TYPE i,
      mnth_ship(20),
      week_ship     TYPE i,
      nsp           TYPE ekpo-netwr,
      poval         TYPE ekpo-netwr,
      gival         TYPE ekpo-netwr,
      grval         TYPE ekpo-netwr,
      otdval        TYPE ekpo-netwr,
      flg1          TYPE char1,           "SAT/IDM Flag
      lprio         TYPE mepo1331-lprio,
      bezei         TYPE tprit-bezei,
      lprio1        TYPE mepo1331-lprio,
      bezei1        TYPE tprit-bezei,
      END OF gt_vdata.
DATA: gt_detail LIKE gt_vdata OCCURS 0 WITH HEADER LINE.

DATA: BEGIN OF gt_sum_brc OCCURS 0,
        werks   LIKE t001w-werks,
        name1   LIKE t001w-name1,
        stow1   TYPE menge_d,
        stow2   TYPE menge_d,
        stow3   TYPE menge_d,
        stow4   TYPE menge_d,
        stow5   TYPE menge_d,
        stotot  TYPE menge_d,
        dnw1    TYPE menge_d,
        dnw2    TYPE menge_d,
        dnw3    TYPE menge_d,
        dnw4    TYPE menge_d,
        dnw5    TYPE menge_d,
        dntot   TYPE menge_d,
        dnw6    TYPE menge_d,
        dn6tot  TYPE menge_d,
        dngtot  TYPE menge_d,
        dnw1%   TYPE zpercen,
        dnw2%   TYPE zpercen,
        dnw3%   TYPE zpercen,
        dnw4%   TYPE zpercen,
        dnw5%   TYPE zpercen,
        dntot%  TYPE zpercen,
        dnw6%   TYPE zpercen,
        dn6tot% TYPE zpercen,
        dngtot% TYPE zpercen,
        giw1    TYPE menge_d,
        giw2    TYPE menge_d,
        giw3    TYPE menge_d,
        giw4    TYPE menge_d,
        giw5    TYPE menge_d,
        gitot   TYPE menge_d,
        giw6    TYPE menge_d,
        gi6tot  TYPE menge_d,
        gigtot  TYPE menge_d,
        giw1%   TYPE zpercen,
        giw2%   TYPE zpercen,
        giw3%   TYPE zpercen,
        giw4%   TYPE zpercen,
        giw5%   TYPE zpercen,
        gitot%  TYPE zpercen,
        giw6%   TYPE zpercen,
        gi6tot% TYPE zpercen,
        gigtot% TYPE zpercen,
        grw1    TYPE menge_d,
        grw2    TYPE menge_d,
        grw3    TYPE menge_d,
        grw4    TYPE menge_d,
        grw5    TYPE menge_d,
        grtot   TYPE menge_d,
        grw6    TYPE menge_d,
        gr6tot  TYPE menge_d,
        grgtot  TYPE menge_d,
        grw1%   TYPE zpercen,
        grw2%   TYPE zpercen,
        grw3%   TYPE zpercen,
        grw4%   TYPE zpercen,
        grw5%   TYPE zpercen,
        grtot%  TYPE zpercen,
        grw6%   TYPE zpercen,
        gr6tot% TYPE zpercen,
        grgtot% TYPE zpercen,
      END OF gt_sum_brc.

DATA: BEGIN OF gt_sum_brcp OCCURS 0,
        werks   LIKE t001w-werks,
        name1   LIKE t001w-name1,
        prc     TYPE char3,
        prdgp   TYPE char3,
        stow1   TYPE menge_d,
        stow2   TYPE menge_d,
        stow3   TYPE menge_d,
        stow4   TYPE menge_d,
        stow5   TYPE menge_d,
        stotot  TYPE menge_d,
        dnw1    TYPE menge_d,
        dnw2    TYPE menge_d,
        dnw3    TYPE menge_d,
        dnw4    TYPE menge_d,
        dnw5    TYPE menge_d,
        dntot   TYPE menge_d,
        dnw6    TYPE menge_d,
        dn6tot  TYPE menge_d,
        dngtot  TYPE menge_d,
        dnw1%   TYPE zpercen,
        dnw2%   TYPE zpercen,
        dnw3%   TYPE zpercen,
        dnw4%   TYPE zpercen,
        dnw5%   TYPE zpercen,
        dntot%  TYPE zpercen,
        dnw6%   TYPE zpercen,
        dn6tot% TYPE zpercen,
        dngtot% TYPE zpercen,
        giw1    TYPE menge_d,
        giw2    TYPE menge_d,
        giw3    TYPE menge_d,
        giw4    TYPE menge_d,
        giw5    TYPE menge_d,
        gitot   TYPE menge_d,
        giw6    TYPE menge_d,
        gi6tot  TYPE menge_d,
        gigtot  TYPE menge_d,
        giw1%   TYPE zpercen,
        giw2%   TYPE zpercen,
        giw3%   TYPE zpercen,
        giw4%   TYPE zpercen,
        giw5%   TYPE zpercen,
        gitot%  TYPE zpercen,
        giw6%   TYPE zpercen,
        gi6tot% TYPE zpercen,
        gigtot% TYPE zpercen,
        grw1    TYPE menge_d,
        grw2    TYPE menge_d,
        grw3    TYPE menge_d,
        grw4    TYPE menge_d,
        grw5    TYPE menge_d,
        grtot   TYPE menge_d,
        grw6    TYPE menge_d,
        gr6tot  TYPE menge_d,
        grgtot  TYPE menge_d,
        grw1%   TYPE zpercen,
        grw2%   TYPE zpercen,
        grw3%   TYPE zpercen,
        grw4%   TYPE zpercen,
        grw5%   TYPE zpercen,
        grtot%  TYPE zpercen,
        grw6%   TYPE zpercen,
        gr6tot% TYPE zpercen,
        grgtot% TYPE zpercen,
      END OF gt_sum_brcp.

DATA: BEGIN OF gt_sum_prc OCCURS 0,
        prc     TYPE char3,
        prdgp   TYPE char3,
        stow1   TYPE menge_d,
        stow2   TYPE menge_d,
        stow3   TYPE menge_d,
        stow4   TYPE menge_d,
        stow5   TYPE menge_d,
        stotot  TYPE menge_d,
        dnw1    TYPE menge_d,
        dnw2    TYPE menge_d,
        dnw3    TYPE menge_d,
        dnw4    TYPE menge_d,
        dnw5    TYPE menge_d,
        dntot   TYPE menge_d,
        dnw6    TYPE menge_d,
        dn6tot  TYPE menge_d,
        dngtot  TYPE menge_d,
        dnw1%   TYPE zpercen,
        dnw2%   TYPE zpercen,
        dnw3%   TYPE zpercen,
        dnw4%   TYPE zpercen,
        dnw5%   TYPE zpercen,
        dntot%  TYPE zpercen,
        dnw6%   TYPE zpercen,
        dn6tot% TYPE zpercen,
        dngtot% TYPE zpercen,
        giw1    TYPE menge_d,
        giw2    TYPE menge_d,
        giw3    TYPE menge_d,
        giw4    TYPE menge_d,
        giw5    TYPE menge_d,
        gitot   TYPE menge_d,
        giw6    TYPE menge_d,
        gi6tot  TYPE menge_d,
        gigtot  TYPE menge_d,
        giw1%   TYPE zpercen,
        giw2%   TYPE zpercen,
        giw3%   TYPE zpercen,
        giw4%   TYPE zpercen,
        giw5%   TYPE zpercen,
        gitot%  TYPE zpercen,
        giw6%   TYPE zpercen,
        gi6tot% TYPE zpercen,
        gigtot% TYPE zpercen,
        grw1    TYPE menge_d,
        grw2    TYPE menge_d,
        grw3    TYPE menge_d,
        grw4    TYPE menge_d,
        grw5    TYPE menge_d,
        grtot   TYPE menge_d,
        grw6    TYPE menge_d,
        gr6tot  TYPE menge_d,
        grgtot  TYPE menge_d,
        grw1%   TYPE zpercen,
        grw2%   TYPE zpercen,
        grw3%   TYPE zpercen,
        grw4%   TYPE zpercen,
        grw5%   TYPE zpercen,
        grtot%  TYPE zpercen,
        grw6%   TYPE zpercen,
        gr6tot% TYPE zpercen,
        grgtot% TYPE zpercen,
      END OF gt_sum_prc.

DATA : BEGIN OF i_nsp OCCURS 0,
         vkorg LIKE a567-vkorg,
         vkbur LIKE a567-vkbur,
         regio LIKE a567-regio,
         matnr LIKE a567-matnr,
         knumh LIKE a567-knumh,
         datab LIKE a567-datab,
         datbi LIKE a567-datbi,
         kbetr LIKE konp-kbetr.
DATA : END OF i_nsp.

DATA: d_top_of_page      TYPE slis_formname VALUE 'F_TOP_OF_PAGE',
      t_list_top_of_page TYPE slis_t_listheader.
DATA: t_fieldcat TYPE lvc_t_fcat.

DATA: gt_mat_b2b TYPE TABLE OF zsmat_b2b WITH HEADER LINE,
      gv_date1   TYPE datum,
      gv_date2   TYPE datum.

FIELD-SYMBOLS: <ft_tab>  TYPE table,
               <fs_brc>  LIKE gt_sum_brc,
               <fs_brcp> LIKE gt_sum_brcp,
               <fs_prc>  LIKE gt_sum_prc.

DATA : BEGIN OF gt_lips OCCURS 0,
         vbeln TYPE vbeln_vl,
         posnr TYPE posnr_vl,
         matnr TYPE matnr,
         brgew TYPE brgew_15,
         gewei TYPE gewei,
         volum TYPE volum_15,
         voleh TYPE voleh,
       END OF gt_lips.

DATA : BEGIN OF gt_vttp OCCURS 0,
         tknum  TYPE tknum,
         tpnum  TYPE tpnum,
         vbeln  TYPE vbeln_vl,
         vbtyp  TYPE vbtyp,
         shtyp  TYPE shtyp,
         tplst  TYPE tplst,
         ernam  TYPE ernam,
         erdat  TYPE erdat,
         erzet  TYPE erzet,
         exti1  TYPE exti1,
         exti2  TYPE exti2,
         tpbez  TYPE tpbez,
         datbg  TYPE datbg,
         signi  TYPE signi,
         tdlnr  TYPE tdlnr,
         gesztd TYPE kp_gesztdp,
       END OF gt_vttp.

DATA : gt_kna1    TYPE STANDARD TABLE OF kna1 INITIAL SIZE 0.
DATA : gt_lfa1    TYPE TABLE OF lfa1 WITH HEADER LINE.
DATA : gt_lfa2    TYPE TABLE OF lfa1 WITH HEADER LINE.
DATA : gt_eket    TYPE TABLE OF eket WITH HEADER LINE.
DATA : gt_ekpv TYPE TABLE OF ekpv WITH HEADER LINE,
       gt_likp TYPE STANDARD TABLE OF ty_likp.
