PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMAIL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMAIL-PROJECT .
    FIELD ZMAIL-WERKS .
    FIELD ZMAIL-LGORT .
    FIELD ZMAIL-ZEILE .
    FIELD ZMAIL-EMAIL .
    FIELD ZMAIL-ZTO .
    FIELD ZMAIL-CC .
    FIELD ZMAIL-BCC .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMAIL-PROJECT .
    FIELD ZMAIL-WERKS .
    FIELD ZMAIL-LGORT .
    FIELD ZMAIL-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
