*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 07.03.2003 at 15:11:53 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMGRPBWARTTOP.                    " Global Data
  INCLUDE LZMGRPBWARTUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMGRPBWARTF00                          . " subprograms
  INCLUDE LZMGRPBWARTI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMGRPBWARTF...                    " Subprograms
* INCLUDE LZMGRPBWARTO...                    " PBO-Modules
* INCLUDE LZMGRPBWARTI...                    " PAI-Modules
