PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMGUDANG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMGUDANG-WERKS .
    FIELD ZMGUDANG-LGORT .
    FIELD ZMGUDANG-ZSEQ .
    FIELD ZMGUDANG-ZCODE .
    FIELD ZMGUDANG-DBTABNAME .
    FIELD ZMGUDANG-FIELDNAME .
    FIELD ZMGUDANG-ROLLNAME .
    FIELD ZMGUDANG-ZVALUENAME .
    FIELD ZMGUDANG-ZFLAG .
    FIELD ZMGUDANG-DATAB .
    FIELD ZMGUDANG-DATBI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMGUDANG-WERKS .
    FIELD ZMGUDANG-LGORT .
    FIELD ZMGUDANG-ZSEQ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
