*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMGUDANGTOP.                      " Global Data
  INCLUDE LZMGUDANGUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMGUDANGF00                            . " subprograms
  INCLUDE LZMGUDANGI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMGUDANGF...                      " Subprograms
* INCLUDE LZMGUDANGO...                      " PBO-Modules
* INCLUDE LZMGUDANGI...                      " PAI-Modules
