*&---------------------------------------------------------------------*
*& Report  ZMM_AGING_BLOCKED_STOCK
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  zmm_aging_blocked_stock NO STANDARD PAGE HEADING
                                MESSAGE-ID m7.

INCLUDE zmm_abstop.

SELECTION-SCREEN BEGIN OF BLOCK block1 WITH FRAME TITLE text-001.
PARAMETERS pa_bukrs      LIKE t001-bukrs MODIF ID abs OBLIGATORY.
SELECT-OPTIONS so_matnr  FOR mchb-matnr MODIF ID abs.
SELECT-OPTIONS so_werks  FOR t001w-werks MODIF ID abs OBLIGATORY.
*SELECT-OPTIONS so_werks  FOR mchb-werks MODIF ID abs OBLIGATORY.
SELECT-OPTIONS so_lgort  FOR mchb-lgort MODIF ID abs.
SELECT-OPTIONS so_charg  FOR mchb-charg MODIF ID abs.
SELECTION-SCREEN END OF BLOCK block1.

SELECTION-SCREEN BEGIN OF BLOCK block2 WITH FRAME TITLE text-002.
SELECT-OPTIONS so_mtart  FOR mara-mtart MODIF ID abs.
SELECT-OPTIONS so_matkl  FOR mara-matkl MODIF ID abs.
SELECTION-SCREEN END OF BLOCK block2.

SELECTION-SCREEN BEGIN OF BLOCK block3 WITH FRAME TITLE text-003.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS pa_dondv   TYPE xfeld MODIF ID abs.
SELECTION-SCREEN : COMMENT 5(31) text-101 MODIF ID abs FOR FIELD pa_dondv.
SELECTION-SCREEN POSITION 40.
PARAMETERS pa_agqty   TYPE xfeld DEFAULT 'X' MODIF ID abs.
SELECTION-SCREEN : COMMENT 44(31) text-102 MODIF ID abs FOR FIELD pa_agqty.
SELECTION-SCREEN END OF LINE.
*PARAMETERS pa_wtreq   TYPE xfeld DEFAULT 'X' MODIF ID abs.
PARAMETERS pa_wtreq   TYPE xfeld MODIF ID abs.
SELECTION-SCREEN END OF BLOCK block3.

SELECTION-SCREEN BEGIN OF BLOCK block4 WITH FRAME TITLE text-004.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN : COMMENT 1(31) text-005 MODIF ID c01.
PARAMETERS pa_col01   TYPE int4 MODIF ID c01 DEFAULT 30.
SELECTION-SCREEN : COMMENT 44(31) text-100 MODIF ID c01.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN : COMMENT 1(31) text-006 MODIF ID c02.
PARAMETERS pa_col02   TYPE int4 MODIF ID c02 DEFAULT 60.
SELECTION-SCREEN : COMMENT 44(31) text-100 MODIF ID c02.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN : COMMENT 1(31) text-007 MODIF ID c03.
PARAMETERS pa_col03   TYPE int4 MODIF ID c03 DEFAULT 90.
SELECTION-SCREEN : COMMENT 44(31) text-100 MODIF ID c03.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN : COMMENT 1(31) text-008 MODIF ID c04.
PARAMETERS pa_col04   TYPE int4 MODIF ID c04 DEFAULT 120.
SELECTION-SCREEN : COMMENT 44(31) text-100 MODIF ID c04.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN : COMMENT 1(8) text-009 MODIF ID c05.
SELECTION-SCREEN : COMMENT 30(1) text-010 MODIF ID c05.
SELECTION-SCREEN POSITION 33.
PARAMETERS pa_col05   TYPE int4 MODIF ID c05 DEFAULT 120.
SELECTION-SCREEN : COMMENT 44(31) text-100 MODIF ID c05.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK block4.

SELECTION-SCREEN BEGIN OF BLOCK block5 WITH FRAME TITLE text-013.
SELECT-OPTIONS so_reqno   FOR zgdmmt0001-req_no MODIF ID srn.
SELECT-OPTIONS so_reqdt   FOR zgdmmt0001-req_date MODIF ID srd.
SELECT-OPTIONS so_bbkno   FOR zgdmmt0001-bbk_no MODIF ID sbn.
SELECT-OPTIONS so_bbkdt   FOR zgdmmt0001-bbk_date MODIF ID sbd.
PARAMETERS pa_reqno   LIKE zgdmmt0001-req_no MODIF ID prn.
PARAMETERS pa_bapno   LIKE zgdmmt0001-bap_no MODIF ID pba.
PARAMETERS pa_clano   LIKE zgdmmt0001-cla_no MODIF ID cln.
PARAMETERS pa_cladt   LIKE zgdmmt0001-cla_date MODIF ID cld DEFAULT sy-datum.
PARAMETERS pa_leter   TYPE zgdmmt0001-zfrmtl MODIF ID pft.
PARAMETERS pa_scrap   LIKE zgdmmt0001-scrap_no MODIF ID psc.
SELECTION-SCREEN SKIP 1.
PARAMETERS pa_delrq   AS CHECKBOX DEFAULT 'X' MODIF ID pde.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS pa_chk01 AS CHECKBOX MODIF ID bap.
SELECTION-SCREEN : COMMENT 5(20) text-011 FOR FIELD pa_chk01 MODIF ID bap.
SELECTION-SCREEN POSITION 30.
PARAMETERS pa_chk02 AS CHECKBOX MODIF ID bap.
SELECTION-SCREEN : COMMENT 35(20) text-012 FOR FIELD pa_chk02 MODIF ID bap.
SELECTION-SCREEN END OF LINE.
PARAMETERS pa_reprt   AS CHECKBOX MODIF ID prt USER-COMMAND chk.
SELECTION-SCREEN END OF BLOCK block5.

SELECTION-SCREEN BEGIN OF SCREEN 200 TITLE text-111.
PARAMETERS pa_zrecd   LIKE zgdmmt0002-zrecd MODIF ID pre.
SELECTION-SCREEN END OF SCREEN 200.

PARAMETERS pa_abs  RADIOBUTTON GROUP grp1 USER-COMMAND rad DEFAULT 'X' MODIF ID abr.
PARAMETERS pa_crp  RADIOBUTTON GROUP grp1 MODIF ID crp.
PARAMETERS pa_prp  RADIOBUTTON GROUP grp1 MODIF ID prp.
PARAMETERS pa_apr  RADIOBUTTON GROUP grp1 MODIF ID apr.
PARAMETERS pa_bbk  RADIOBUTTON GROUP grp1 MODIF ID bbk.
PARAMETERS pa_cp   RADIOBUTTON GROUP grp1 MODIF ID cp.
PARAMETERS pa_pbap RADIOBUTTON GROUP grp1 MODIF ID pbp.
PARAMETERS pa_mc   RADIOBUTTON GROUP grp1 MODIF ID bmc.
PARAMETERS pa_bbk2 RADIOBUTTON GROUP grp1 MODIF ID bbk.

INCLUDE zmm_abscl1.

INITIALIZATION.
  gv_repid = sy-repid.

AT SELECTION-SCREEN OUTPUT.
  PERFORM f_modify_screen_1000.

AT SELECTION-SCREEN.
  CASE sscrfields-ucomm.
    WHEN 'ONLI'.
      PERFORM f_validate_screen_1000.
    WHEN space.
      PERFORM f_validate_screen_1000.
  ENDCASE.

  IF pa_abs IS NOT INITIAL.
    PERFORM f_check_entry.
    PERFORM f_organisation.
    PERFORM f_check_authorization.
  ENDIF.

  IF pa_prp IS NOT INITIAL.
    PERFORM f_organisation.
    PERFORM f_check_leter_authorization.
  ENDIF.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR so_reqno-low.
  PERFORM f_f4_value_on_request USING   'REQ_NO' 'SO_REQNO-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR so_reqno-high.
  PERFORM f_f4_value_on_request USING   'REQ_NO' 'SO_REQNO-HIGH'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR pa_reqno.
  PERFORM f_f4_value_on_request USING   'REQ_NO' 'PA_REQNO'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR pa_scrap.
  PERFORM f_f4_value_on_request USING   'SCRAP_NO' 'PA_SCRAP'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR pa_bapno.
  PERFORM f_f4_value_on_request USING   'BAP_NO' 'PA_BAPNO'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR so_bbkno-low.
  PERFORM f_f4_value_on_request USING   'BBK_NO' 'SO_BBKNO-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR so_bbkno-high.
  PERFORM f_f4_value_on_request USING   'BBK_NO' 'SO_BBKNO-HIGH'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR pa_clano.
  PERFORM f_f4_value_on_request USING   'CLA_NO' 'PA_CLANO'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR pa_zrecd.
  PERFORM f_f4_value_on_request USING   'ZRECD' 'PA_ZRECD'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR pa_leter.
  PERFORM f_f4_value_on_request USING   'ZFRMTL' 'PA_LETER'.

START-OF-SELECTION.
  PERFORM f_get_data.
  PERFORM f_process_data.
  PERFORM f_authorization.

  IF gv_autho IS INITIAL.
*    PERFORM f_cek_2100.
    PERFORM f_print_data.
  ELSE.
    MESSAGE s000(zab) WITH 'You are not authorized'.
  ENDIF.

  INCLUDE zmm_absf01.
