*&---------------------------------------------------------------------*
*& Report  ZMM_ABC_ANALYSIS
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  zmm_abc_analysis NO STANDARD PAGE HEADING.

INCLUDE zmm_abc_analysistop.

INCLUDE zmm_abc_analysiscl1.

SELECTION-SCREEN BEGIN OF BLOCK object WITH FRAME TITLE text-001.
PARAMETERS pa_backg   AS CHECKBOX.
PARAMETERS pa_werku   AS CHECKBOX.
SELECT-OPTIONS so_vkbur   FOR tvbur-vkbur.
SELECTION-SCREEN END OF BLOCK object.

SELECTION-SCREEN BEGIN OF BLOCK period WITH FRAME TITLE text-002.
PARAMETERS pa_spmon   LIKE s031-spmon MODIF ID spm.
SELECTION-SCREEN END OF BLOCK period.

SELECTION-SCREEN BEGIN OF BLOCK area WITH FRAME TITLE text-003.
SELECT-OPTIONS so_matnr   FOR marc-matnr.
SELECT-OPTIONS so_prod1   FOR prodhs-prodh1.
SELECT-OPTIONS so_prod2   FOR prodhs-prodh2.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS pa_loesc   AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(37) text-101 FOR FIELD pa_loesc.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS pa_lager   AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 5(37) text-102 FOR FIELD pa_lager.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK area.

SELECTION-SCREEN BEGIN OF BLOCK stategy WITH FRAME TITLE text-004.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 33(1) text-103.
SELECTION-SCREEN COMMENT 48(1) text-104.
SELECTION-SCREEN COMMENT 62(1) text-105.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS pa_svp  RADIOBUTTON GROUP grp1 USER-COMMAND rad DEFAULT 'X'.
SELECTION-SCREEN COMMENT 5(28) text-106 FOR FIELD pa_svp.
SELECTION-SCREEN POSITION 33.
PARAMETERS pa_agpa1   LIKE rmcb0-agpra DEFAULT 80 MODIF ID svp.
SELECTION-SCREEN POSITION 48.
PARAMETERS pa_agpb1   LIKE rmcb0-agprb DEFAULT 15 MODIF ID svp.
SELECTION-SCREEN POSITION 62.
PARAMETERS pa_agpc1   LIKE rmcb0-agprc DEFAULT 5 MODIF ID svp.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS pa_svn  RADIOBUTTON GROUP grp1.
SELECTION-SCREEN COMMENT 5(28) text-107 FOR FIELD pa_svn.
SELECTION-SCREEN POSITION 33.
PARAMETERS pa_agaa1   LIKE rmcb0-agaba DEFAULT 50000 MODIF ID svn.
SELECTION-SCREEN POSITION 48.
PARAMETERS pa_agab1   LIKE rmcb0-agabb  DEFAULT 5000 MODIF ID svn.
SELECTION-SCREEN COMMENT 62(10) text-108.
SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS pa_sqp  RADIOBUTTON GROUP grp1.
*SELECTION-SCREEN COMMENT 5(28) text-109 FOR FIELD pa_sqp.
*SELECTION-SCREEN POSITION 33.
*PARAMETERS pa_agpa2   LIKE rmcb0-ampra DEFAULT 70 MODIF ID sqp.
*SELECTION-SCREEN POSITION 48.
*PARAMETERS pa_agpb2   LIKE rmcb0-amprb DEFAULT 20 MODIF ID sqp.
*SELECTION-SCREEN POSITION 62.
*PARAMETERS pa_agpc2   LIKE rmcb0-amprc DEFAULT 10 MODIF ID sqp.
*SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS pa_sqn  RADIOBUTTON GROUP grp1.
*SELECTION-SCREEN COMMENT 5(28) text-110 FOR FIELD pa_sqn.
*SELECTION-SCREEN POSITION 33.
*PARAMETERS pa_agaa2   LIKE rmcb0-amaba DEFAULT 50000 MODIF ID sqn.
*SELECTION-SCREEN POSITION 48.
*PARAMETERS pa_agab2   LIKE rmcb0-amabb DEFAULT 5000 MODIF ID sqn.
*SELECTION-SCREEN COMMENT 62(10) text-108.
*SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK stategy.

INITIALIZATION.
  gv_repid = sy-repid.

*&---------------------------------------------------------------------*
*& SELECTION-SCREEN.
*&---------------------------------------------------------------------*
AT SELECTION-SCREEN.
  CASE sscrfields-ucomm.
    WHEN 'ONLI'.
      PERFORM f_validate_screen_1000.
    WHEN space.
      PERFORM f_validate_screen_1000.
  ENDCASE.

START-OF-SELECTION.

  PERFORM f_get_data.

  PERFORM f_process_data.

  IF pa_backg IS NOT INITIAL.
    PERFORM f_check_authorization.
    IF gv_subrc = 0.
      PERFORM f_save_data.
    ELSE.
      MESSAGE s000(zab) WITH 'You are not authorized' DISPLAY LIKE 'E'.
    ENDIF.
  ELSE.
    PERFORM f_print_data.
  ENDIF.

  INCLUDE zmm_abc_analysisf01.
