*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMMATKLSTOP.                      " Global Data
  INCLUDE LZMMATKLSUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMMATKLSF00                            . " subprograms
  INCLUDE LZMMATKLSI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMMATKLSF...                      " Subprograms
* INCLUDE LZMMATKLSO...                      " PBO-Modules
* INCLUDE LZMMATKLSI...                      " PAI-Modules
