*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMMMVT_CNTRLTOP.                  " Global Data
  INCLUDE LZMMMVT_CNTRLUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMMMVT_CNTRLF00                        . " subprograms
  INCLUDE LZMMMVT_CNTRLI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMMMVT_CNTRLF...                  " Subprograms
* INCLUDE LZMMMVT_CNTRLO...                  " PBO-Modules
* INCLUDE LZMMMVT_CNTRLI...                  " PAI-Modules
