PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMMT0001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMMT0001-VRSIO .
    FIELD ZMMT0001-SPMON .
    FIELD ZMMT0001-WERKS .
    FIELD ZMMT0001-MATNR .
    FIELD ZMMT0001-BASME .
    FIELD ZMMT0001-FCOMW1QTY .
    FIELD ZMMT0001-FCOMW2QTY .
    FIELD ZMMT0001-FCOMW3QTY .
    FIELD ZMMT0001-FCOMW4QTY .
    FIELD ZMMT0001-REMGRW1QTY .
    FIELD ZMMT0001-REMGRW2QTY .
    FIELD ZMMT0001-REMGRW3QTY .
    FIELD ZMMT0001-REMGRW4QTY .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMMT0001-VRSIO .
    FIELD ZMMT0001-SPMON .
    FIELD ZMMT0001-WERKS .
    FIELD ZMMT0001-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
