PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMPROJECT_CTRL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMPROJECT_CTRL-ZPROJECT .
    FIELD ZMPROJECT_CTRL-ZEVENT .
    FIELD ZMPROJECT_CTRL-ZEILE .
    FIELD ZMPROJECT_CTRL-FIELDNAME1 .
    FIELD ZMPROJECT_CTRL-SIGN1 .
    FIELD ZMPROJECT_CTRL-OPTION1 .
    FIELD ZMPROJECT_CTRL-LOW1 .
    FIELD ZMPROJECT_CTRL-HIGH1 .
    FIELD ZMPROJECT_CTRL-DATAB .
    FIELD ZMPROJECT_CTRL-DATBI .
    FIELD ZMPROJECT_CTRL-TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMPROJECT_CTRL-ZPROJECT .
    FIELD ZMPROJECT_CTRL-ZEVENT .
    FIELD ZMPROJECT_CTRL-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
