*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMPROJECT_CTRLTOP.                " Global Data
  INCLUDE LZMPROJECT_CTRLUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMPROJECT_CTRLF00                      . " subprograms
  INCLUDE LZMPROJECT_CTRLI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMPROJECT_CTRLF...                " Subprograms
* INCLUDE LZMPROJECT_CTRLO...                " PBO-Modules
* INCLUDE LZMPROJECT_CTRLI...                " PAI-Modules
