*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMPSIKOR1TOP.                     " Global Data
  INCLUDE LZMPSIKOR1UXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMPSIKOR1F00                           . " subprograms
  INCLUDE LZMPSIKOR1I00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMPSIKOR1F...                     " Subprograms
* INCLUDE LZMPSIKOR1O...                     " PBO-Modules
* INCLUDE LZMPSIKOR1I...                     " PAI-Modules
