PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMPSIKO1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMPSIKO1-BUKRS .
    FIELD ZMPSIKO1-MATNR .
    FIELD ZMPSIKO1-DATAB .
    FIELD ZMPSIKO1-DATBI .
    FIELD ZMPSIKO1-ZDATE .
    FIELD ZMPSIKO1-ZUSER .
    FIELD ZMPSIKO1-ZDATL .
    FIELD ZMPSIKO1-ZUSERL .
    FIELD ZMPSIKO1-ZAKTIF .
    FIELD ZMPSIKO1-ZKUAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMPSIKO1-BUKRS .
    FIELD ZMPSIKO1-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
