*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMPSIKO1TOP.                      " Global Data
  INCLUDE LZMPSIKO1UXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMPSIKO1F00                            . " subprograms
  INCLUDE LZMPSIKO1I00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMPSIKO1F...                      " Subprograms
* INCLUDE LZMPSIKO1O...                      " PBO-Modules
* INCLUDE LZMPSIKO1I...                      " PAI-Modules
