*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMPSIKORTOP.                      " Global Data
  INCLUDE LZMPSIKORUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMPSIKORF00                            . " subprograms
  INCLUDE LZMPSIKORI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMPSIKORF...                      " Subprograms
* INCLUDE LZMPSIKORO...                      " PBO-Modules
* INCLUDE LZMPSIKORI...                      " PAI-Modules
