*&---------------------------------------------------------------------*
*&  Include           ZMR_LISTING_INTRANSIT_NEW1TOP
*&---------------------------------------------------------------------*
*---------------------------------------------------------------------*
* DEFINITION OF TABLES, TYPES & DATA                                  *
*---------------------------------------------------------------------*
TYPE-POOLS: slis.

TABLES : sscrfields,
         mkpf,      "Header: Material Document
         mseg.      "Document Segment: Material

DATA   : BEGIN OF itab OCCURS 0,
           bwart  LIKE  mseg-bwart,
           mblnr  LIKE  mseg-mblnr,
           mjahr  LIKE  mseg-mjahr,
           bldat  LIKE  mkpf-bldat,
           budat  LIKE  mkpf-budat,
           xblnr  LIKE  mkpf-xblnr,
           bktxt  LIKE  mkpf-bktxt,
           umwrk  LIKE  mseg-umwrk,
           umlgo  LIKE  mseg-umlgo,
           werks  LIKE  mseg-werks,
           lgort  LIKE  mseg-lgort,
           ebeln  LIKE  mseg-ebeln,
           ebelp  LIKE  mseg-ebelp,
           sgtxt  LIKE  mseg-sgtxt,
           matnr  LIKE  mseg-matnr,
           maktx  LIKE  makt-maktx,
           menge  LIKE  mseg-menge,
           dmbtr  LIKE  mseg-dmbtr,
           nsp    LIKE  mseg-dmbtr,
           bwart1 LIKE  mseg-bwart,
           mblnr1 LIKE  mseg-mblnr,
           matnr1 LIKE  mseg-matnr,
           maktx1 LIKE  makt-maktx,
           menge1 LIKE  mseg-menge,
           dmbtr1 LIKE  mseg-dmbtr,
           kunnr  LIKE  mseg-kunnr,
           name3  LIKE  kna1-name3,
           bbkno  LIKE  zpoittc-bbkno,
           tknum  LIKE  vttp-tknum,
           cpudt1 LIKE  mkpf-cpudt,
           budat1 LIKE  mkpf-budat,
           leadt  TYPE  i,
           erdat  LIKE vttp-erdat,
           etdat  LIKE vttp-erdat,
           ablad  LIKE mepo1331-ablad,
           exti1  TYPE exti1,
           exti2  TYPE exti2,
           tdlnr  TYPE vttk-tdlnr,
           vndnam TYPE lfa1-name1,
           cuspo  TYPE ekunnr,
           cusnam TYPE kna1-name1,
           lprio  TYPE mepo1331-lprio,
           bezei  TYPE tprit-bezei,
           lprio1 TYPE mepo1331-lprio,
           bezei1 TYPE tprit-bezei,
         END OF itab.

DATA   : BEGIN OF i_mkpf OCCURS 0,
           mblnr  LIKE  mkpf-mblnr,
           mjahr  LIKE  mkpf-mjahr,
           bldat  LIKE  mkpf-bldat,
           budat  LIKE  mkpf-budat,
           xblnr  LIKE  mkpf-xblnr,
           bktxt  LIKE  mkpf-bktxt,
           umwrk  LIKE  mseg-umwrk,
           umlgo  LIKE  mseg-umlgo,
           werks  LIKE  mseg-werks,
           lgort  LIKE  mseg-umlgo,
           bwart  LIKE  mseg-bwart,
           ebeln  LIKE  mseg-ebeln,
           ebelp  LIKE  mseg-ebelp,
           kunnr  LIKE  mseg-kunnr,
           tknum  LIKE  vttp-tknum,
           erdat  LIKE  vttp-erdat,
           gesztd LIKE  vttk-gesztd,
           exti1  TYPE exti1,
           exti2  TYPE exti2,
           tdlnr  TYPE vttk-tdlnr,
           vndnam TYPE lfa1-name1,
           cuspo  TYPE ekunnr,
           cusnam TYPE kna1-name1,
         END OF i_mkpf.

DATA   : BEGIN OF i303641 OCCURS 0,
           bwart  LIKE  mseg-bwart,
           mblnr  LIKE  mseg-mblnr,
           matnr  LIKE  mseg-matnr,
           menge  LIKE  mseg-menge,
           dmbtr  LIKE  mseg-dmbtr,
           zeile  LIKE  mseg-zeile,
           ebeln  LIKE  mseg-ebeln,
           ebelp  LIKE  mseg-ebelp,
           lgort  LIKE  mseg-lgort,
         END OF i303641.

DATA   : BEGIN OF i_305 OCCURS 0,
           bwart  LIKE  mseg-bwart,
           sgtxt  LIKE  mseg-sgtxt,
           matnr  LIKE  mseg-matnr,
           mblnr  LIKE  mseg-mblnr,
           menge  LIKE  mseg-menge,
           dmbtr  LIKE  mseg-dmbtr,
           cpudt  LIKE  mkpf-cpudt,
           budat  LIKE  mkpf-budat,
         END OF i_305.

DATA   : BEGIN OF i_305_detail OCCURS 0,
           bwart  LIKE  mseg-bwart,
           sgtxt  LIKE  mseg-sgtxt,
           matnr  LIKE  mseg-matnr,
           mjahr  LIKE  mseg-mjahr,
           mblnr  LIKE  mseg-mblnr,
           zeile  LIKE  mseg-zeile,
           menge  LIKE  mseg-menge,
           dmbtr  LIKE  mseg-dmbtr,
         END OF i_305_detail.

DATA   : BEGIN OF i_351 OCCURS 0,
           bwart  LIKE  mseg-bwart,
           xblnr  LIKE  mkpf-xblnr,
           matnr  LIKE  mseg-matnr,
           mblnr  LIKE  mseg-mblnr,
           menge  LIKE  mseg-menge,
           dmbtr  LIKE  mseg-dmbtr,
           cpudt  LIKE  mkpf-cpudt,
           budat  LIKE  mkpf-budat,
           ablad  LIKE  mseg-ablad,
         END OF i_351.

DATA   : BEGIN OF i_351_detail OCCURS 0,
           bwart  LIKE  mseg-bwart,
           xblnr  LIKE  mkpf-xblnr,
           matnr  LIKE  mseg-matnr,
           mjahr  LIKE  mseg-mjahr,
           mblnr  LIKE  mseg-mblnr,
           zeile  LIKE  mseg-zeile,
           menge  LIKE  mseg-menge,
           dmbtr  LIKE  mseg-dmbtr,
           ablad  LIKE  mseg-ablad,
         END OF i_351_detail.

DATA   : BEGIN OF i_315 OCCURS 0,
           bwart  LIKE  mseg-bwart,
           sgtxt  LIKE  mseg-sgtxt,
           matnr  LIKE  mseg-matnr,
           mblnr  LIKE  mseg-mblnr,
           menge  LIKE  mseg-menge,
           dmbtr  LIKE  mseg-dmbtr,
           cpudt  LIKE  mkpf-cpudt,
           budat  LIKE  mkpf-budat,
         END OF i_315.

DATA   : BEGIN OF i_315_detail OCCURS 0,
           bwart  LIKE  mseg-bwart,
           sgtxt  LIKE  mseg-sgtxt,
           matnr  LIKE  mseg-matnr,
           mjahr  LIKE  mseg-mjahr,
           mblnr  LIKE  mseg-mblnr,
           zeile  LIKE  mseg-zeile,
           menge  LIKE  mseg-menge,
           dmbtr  LIKE  mseg-dmbtr,
         END OF i_315_detail.

DATA   : BEGIN OF i_101 OCCURS 0,
           bwart  LIKE  ekbe-bwart,
           xblnr  LIKE  mkpf-xblnr,
           matnr  LIKE  ekbe-matnr,
           belnr  LIKE  ekbe-belnr,
           menge  LIKE  ekbe-menge,
           dmbtr  LIKE  ekbe-dmbtr,
           cpudt  LIKE  mkpf-cpudt,
           budat  LIKE  mkpf-budat,
           ebeln  LIKE  ekbe-ebeln,
           ebelp  LIKE  mseg-ebelp,
         END OF i_101.

DATA   : BEGIN OF i_101_detail OCCURS 0,
           bwart  LIKE  ekbe-bwart,
           xblnr  LIKE  mkpf-xblnr,
           matnr  LIKE  ekbe-matnr,
           gjahr  LIKE  ekbe-gjahr,
           belnr  LIKE  ekbe-belnr,
           buzei  LIKE  ekbe-buzei,
           menge  LIKE  ekbe-menge,
           dmbtr  LIKE  ekbe-dmbtr,
           ebeln  LIKE  ekbe-ebeln,
           ebelp  LIKE  mseg-ebelp,
         END OF i_101_detail.

DATA   : BEGIN OF i_kunnr OCCURS 0,
           kunnr  LIKE  mseg-kunnr,
         END OF i_kunnr.

DATA   : BEGIN OF i_kna1 OCCURS 0,
           kunnr  LIKE  kna1-kunnr,
           name3  LIKE  kna1-name3,
         END OF i_kna1.

DATA   : i_zplbc LIKE zplbc OCCURS 0 WITH HEADER LINE,
         i_v_t001l_l LIKE v_t001l_l OCCURS 0 WITH HEADER LINE,
         v_name1 LIKE t001w-name1,
         v_line TYPE i,
         wa_305  LIKE i_305,
         wa_315  LIKE i_315,
         wa_351  LIKE i_351,
         wa_101  LIKE i_101.

DATA: gr_kunnr TYPE RANGE OF kunnr WITH HEADER LINE.

DATA:       disvariant   LIKE disvariant,
            eventcat     TYPE slis_t_event,
            va_wbwbest   LIKE s032-wbwbest,
            va_mbwbest   LIKE s032-mbwbest,
            va_lgort     LIKE s032-lgort,
            sw TYPE i,
            va_verpr LIKE mbew-verpr,
            va_peinh LIKE mbew-peinh,
            va_nsp  LIKE konp-kbetr,
            v_mblnr LIKE mseg-mblnr,
            eventcat_ln  LIKE LINE OF eventcat,
            fieldcat     TYPE slis_t_fieldcat_alv WITH HEADER LINE,
            ihead        TYPE slis_t_listheader,
            ifoot        TYPE slis_t_listheader,
            ihead_ln     TYPE slis_listheader,
            evtab        TYPE slis_t_event,
            evtab_ln     TYPE slis_alv_event,
            keyinfo      TYPE slis_keyinfo_alv,
            layout       TYPE slis_layout_alv,
            printcat     TYPE slis_print_alv,
            sortcat      TYPE slis_t_sortinfo_alv,
            sortcat_ln   LIKE LINE OF sortcat,
            it_text_ln   TYPE lvc_t_txtp,
            it_text      TYPE lvc_t_txtp WITH HEADER LINE.

DATA:        e_save(1) TYPE c,
             er_fieldcat TYPE slis_t_fieldcat_alv,
             er_layout   TYPE slis_layout_alv,
             er_sp_group TYPE slis_t_sp_group_alv,
             er_events   TYPE slis_t_event,
             e_default(1) TYPE c,
             e_exit(1) TYPE c,g_repid LIKE sy-repid,
             er_variant LIKE disvariant,
             e_variant LIKE disvariant,
             l_dataset(50),
             e_status TYPE slis_formname VALUE 'STANDARD_ER01',
             e_user_command TYPE slis_formname VALUE 'USER_COMMAND',
             e_top_of_page  TYPE slis_formname VALUE 'TOP_OF_PAGE',
             g_exit_caused_by_caller,
             gs_exit_caused_by_user TYPE slis_exit_by_user.

*DATA: GT_EVENTS      TYPE SLIS_T_EVENT,
*      GT_LIST_TOP_OF_PAGE TYPE SLIS_T_LISTHEADER,
*      G_STATUS_SET   TYPE SLIS_FORMNAME VALUE 'PF_STATUS_SET',
*      G_TOP_OF_PAGE  TYPE SLIS_FORMNAME VALUE 'TOP_OF_PAGE',
*      G_TOP_OF_LIST  TYPE SLIS_FORMNAME VALUE 'TOP_OF_LIST',
*      G_END_OF_LIST  TYPE SLIS_FORMNAME VALUE 'END_OF_LIST',
*      XIT_FIELDCAT   TYPE SLIS_T_FIELDCAT_ALV,
*      XIS_PRINT      TYPE SLIS_PRINT_ALV.
