*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMSHPHISTRTOP.                    " Global Data
  INCLUDE LZMSHPHISTRUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMSHPHISTRF00                          . " subprograms
  INCLUDE LZMSHPHISTRI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMSHPHISTRF...                    " Subprograms
* INCLUDE LZMSHPHISTRO...                    " PBO-Modules
* INCLUDE LZMSHPHISTRI...                    " PAI-Modules
