PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMSUTDT005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMSUTDT005-BUKRS .
    FIELD ZMSUTDT005-MATNR .
    FIELD ZMSUTDT005-MEINS .
    FIELD ZMSUTDT005-ZAUN .
    FIELD ZMSUTDT005-UMREZ .
    FIELD ZMSUTDT005-UMREN .
    FIELD ZMSUTDT005-ZDATE .
    FIELD ZMSUTDT005-ZUSER .
    FIELD ZMSUTDT005-ZDATL .
    FIELD ZMSUTDT005-ZUSERL .
    FIELD ZMSUTDT005-DATAB .
    FIELD ZMSUTDT005-DATBI .
    FIELD ZMSUTDT005-LVORM .
    FIELD ZMSUTDT005-ZDLO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMSUTDT005-BUKRS .
    FIELD ZMSUTDT005-MATNR .
    FIELD ZMSUTDT005-MEINS .
    FIELD ZMSUTDT005-ZAUN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
