*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMSUTDT005TOP.                    " Global Data
  INCLUDE LZMSUTDT005UXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMSUTDT005F00                          . " subprograms
  INCLUDE LZMSUTDT005I00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMSUTDT005F...                    " Subprograms
* INCLUDE LZMSUTDT005O...                    " PBO-Modules
* INCLUDE LZMSUTDT005I...                    " PAI-Modules
