*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMTNT_SCOR_ALOCTOP.               " Global Data
  INCLUDE LZMTNT_SCOR_ALOCUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMTNT_SCOR_ALOCF00                     . " subprograms
  INCLUDE LZMTNT_SCOR_ALOCI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMTNT_SCOR_ALOCF...               " Subprograms
* INCLUDE LZMTNT_SCOR_ALOCO...               " PBO-Modules
* INCLUDE LZMTNT_SCOR_ALOCI...               " PAI-Modules
