*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 12.01.2007 at 09:05:42 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZNRMAPTOP.                        " Global Data
  INCLUDE LZNRMAPUXX.                        " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZNRMAPF00                              . " subprograms
  INCLUDE LZNRMAPI00                              . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZNRMAPF...                        " Subprograms
* INCLUDE LZNRMAPO...                        " PBO-Modules
* INCLUDE LZNRMAPI...                        " PAI-Modules
