*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 23.08.2006 at 17:01:28 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPBFTOP.                          " Global Data
  INCLUDE LZPBFUXX.                          " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPBFF00                                . " subprograms
  INCLUDE LZPBFI00                                . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPBFF...                          " Subprograms
* INCLUDE LZPBFO...                          " PBO-Modules
* INCLUDE LZPBFI...                          " PAI-Modules
