PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPLBC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPLBC-BUKRS .
    FIELD ZPLBC-WERKS .
    FIELD ZPLBC-LGORT .
    FIELD ZPLBC-LEGACY_BRANCH .
    FIELD ZPLBC-LIVE .
    FIELD ZPLBC-LIVE1 .
    FIELD ZPLBC-VATBR .
    FIELD ZPLBC-MIXLIVE .
    FIELD ZPLBC-NEWGLLIVE .
    FIELD ZPLBC-B2BLIVE .
    FIELD ZPLBC-BATCHINT .
    FIELD ZPLBC-ZS01LIVE .
    FIELD ZPLBC-ZSUBBRANCH .
    FIELD ZPLBC-RESWK .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPLBC-BUKRS .
    FIELD ZPLBC-WERKS .
    FIELD ZPLBC-LGORT .
    FIELD ZPLBC-LEGACY_BRANCH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
