*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPLBCTOP.                         " Global Data
  INCLUDE LZPLBCUXX.                         " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPLBCF00                               . " subprograms
  INCLUDE LZPLBCI00                               . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPLBCF...                         " Subprograms
* INCLUDE LZPLBCO...                         " PBO-Modules
* INCLUDE LZPLBCI...                         " PAI-Modules
