*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPOITTCTOP.                       " Global Data
  INCLUDE LZPOITTCUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPOITTCF00                             . " subprograms
  INCLUDE LZPOITTCI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPOITTCF...                       " Subprograms
* INCLUDE LZPOITTCO...                       " PBO-Modules
* INCLUDE LZPOITTCI...                       " PAI-Modules
