PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPOITTC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPOITTC-WERKS .
    FIELD ZPOITTC-LGORT .
    FIELD ZPOITTC-VTART .
    FIELD ZPOITTC-MJAHR .
    FIELD ZPOITTC-XBLNR .
    FIELD ZPOITTC-POSNR .
    FIELD ZPOITTC-ZGROUP .
    FIELD ZPOITTC-DIVCOD .
    FIELD ZPOITTC-BBKNO .
    FIELD ZPOITTC-MATNR .
    FIELD ZPOITTC-MENGE .
    FIELD ZPOITTC-MEINS .
    FIELD ZPOITTC-UMWRK .
    FIELD ZPOITTC-UMLGO .
    FIELD ZPOITTC-BKTXT .
    FIELD ZPOITTC-FILENAME .
    FIELD ZPOITTC-COMPL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPOITTC-WERKS .
    FIELD ZPOITTC-LGORT .
    FIELD ZPOITTC-VTART .
    FIELD ZPOITTC-MJAHR .
    FIELD ZPOITTC-XBLNR .
    FIELD ZPOITTC-POSNR .
    FIELD ZPOITTC-ZGROUP .
    FIELD ZPOITTC-DIVCOD .
    FIELD ZPOITTC-BBKNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
