*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPPRESB_ADDTOP.                   " Global Data
  INCLUDE LZPPRESB_ADDUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPPRESB_ADDF00                         . " subprograms
  INCLUDE LZPPRESB_ADDI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPPRESB_ADDF...                   " Subprograms
* INCLUDE LZPPRESB_ADDO...                   " PBO-Modules
* INCLUDE LZPPRESB_ADDI...                   " PAI-Modules
