PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPPRESB_ADD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPPRESB_ADD-AUFNR .
    FIELD ZPPRESB_ADD-MATNR .
    FIELD ZPPRESB_ADD-POSNR .
    FIELD ZPPRESB_ADD-WERKS .
    FIELD ZPPRESB_ADD-WBOOTH .
    FIELD ZPPRESB_ADD-EQUNR .
    FIELD ZPPRESB_ADD-SHTXT .
    FIELD ZPPRESB_ADD-LTXA1 .
    FIELD ZPPRESB_ADD-OPERATOR .
    FIELD ZPPRESB_ADD-PENGAWAS .
    FIELD ZPPRESB_ADD-ISTAD .
    FIELD ZPPRESB_ADD-ISTAU .
    FIELD ZPPRESB_ADD-DATUM .
    FIELD ZPPRESB_ADD-UZEIT .
    FIELD ZPPRESB_ADD-TARA .
    FIELD ZPPRESB_ADD-MEINS .
    FIELD ZPPRESB_ADD-VORNR .
    FIELD ZPPRESB_ADD-SORTF .
    FIELD ZPPRESB_ADD-PHSEQ .
    FIELD ZPPRESB_ADD-SCANFL .
    FIELD ZPPRESB_ADD-SCANDT .
    FIELD ZPPRESB_ADD-SCANTM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPPRESB_ADD-AUFNR .
    FIELD ZPPRESB_ADD-MATNR .
    FIELD ZPPRESB_ADD-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
