PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRATETR001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRATETR001-BUKRS .
    FIELD ZRATETR001-GJAHR .
    FIELD ZRATETR001-REVTYP .
    FIELD ZRATETR001-RATETYP .
    FIELD ZRATETR001-RATETXT .
    FIELD ZRATETR001-TARIFPHM .
    FIELD ZRATETR001-TARIFCC .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRATETR001-BUKRS .
    FIELD ZRATETR001-GJAHR .
    FIELD ZRATETR001-REVTYP .
    FIELD ZRATETR001-RATETYP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
