PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZREVTR001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZREVTR001-BUKRS .
    FIELD ZREVTR001-GJAHR .
    FIELD ZREVTR001-LINNO .
    FIELD ZREVTR001-ZGRP .
    FIELD ZREVTR001-FACTORY .
    FIELD ZREVTR001-KATEGORI .
    FIELD ZREVTR001-MATNR .
    FIELD ZREVTR001-MATTX .
    FIELD ZREVTR001-MATKL .
    FIELD ZREVTR001-REVTYP .
    FIELD ZREVTR001-RATETYP .
    FIELD ZREVTR001-ZQTY .
    FIELD ZREVTR001-ZSHARE .
    FIELD ZREVTR001-SPMON .
    FIELD ZREVTR001-KETERANGAN .
    FIELD ZREVTR001-INVNO .
    FIELD ZREVTR001-INVDT .
    FIELD ZREVTR001-KUNNR .
    FIELD ZREVTR001-NAME1 .
    FIELD ZREVTR001-INVNO2 .
    FIELD ZREVTR001-TARIF .
    FIELD ZREVTR001-AMOUNT .
    FIELD ZREVTR001-WAERK .
    FIELD ZREVTR001-RATETYP_ACT .
    FIELD ZREVTR001-TARIF_ACT .
    FIELD ZREVTR001-AMOUNT_ACT .
    FIELD ZREVTR001-TIMLN .
    FIELD ZREVTR001-NET_AMOUNT .
    FIELD ZREVTR001-WRK01 .
    FIELD ZREVTR001-WRK02 .
    FIELD ZREVTR001-WRK03 .
    FIELD ZREVTR001-APR01 .
    FIELD ZREVTR001-APR02 .
    FIELD ZREVTR001-APR03 .
    FIELD ZREVTR001-SIGN01 .
    FIELD ZREVTR001-SIGN02 .
    FIELD ZREVTR001-SIGN03 .
    FIELD ZREVTR001-ZFLG .
    FIELD ZREVTR001-FAKTURNO .
    FIELD ZREVTR001-BKTXT .
    FIELD ZREVTR001-POSTDOC .
    FIELD ZREVTR001-POSTYEAR .
    FIELD ZREVTR001-POSTNAME .
    FIELD ZREVTR001-POSTDATE .
    FIELD ZREVTR001-SUBDT .
    FIELD ZREVTR001-APRDT .
    FIELD ZREVTR001-RATETXT .
    FIELD ZREVTR001-LINE .
    FIELD ZREVTR001-FAKTURNO_TNT .
    FIELD ZREVTR001-BKTXT_TNT .
    FIELD ZREVTR001-POSTDOC_TNT .
    FIELD ZREVTR001-POSTYEAR_TNT .
    FIELD ZREVTR001-POSTNAME_TNT .
    FIELD ZREVTR001-POSTDATE_TNT .
    FIELD ZREVTR001-DATE_APPROVAL .
    FIELD ZREVTR001-AENAM .
    FIELD ZREVTR001-AEDAT .
    FIELD ZREVTR001-AEZET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZREVTR001-BUKRS .
    FIELD ZREVTR001-GJAHR .
    FIELD ZREVTR001-LINNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
