*----------------------------------------------------------------------*
*   INCLUDE ZGHMMTOP002                                                *
*----------------------------------------------------------------------*
TABLES : vbak,vbap,likp,lips,makt,tvko,kna1,vbkd,tvagt,knvv.

DATA: BEGIN OF t_cust OCCURS 0.
        INCLUDE STRUCTURE zmm_cust_rec.
DATA: END OF t_cust.

DATA : BEGIN OF i_quot OCCURS 0,
         vbeln  LIKE  vbak-vbeln,
         knkli  LIKE  vbak-knkli,
         kunnr  LIKE  vbak-kunnr,
         vkbur  LIKE  vbak-vkbur,
         vkorg  LIKE  vbak-vkorg,
         vtweg  LIKE  vbak-vtweg,
         spart  LIKE  vbak-spart,
       END OF i_quot.

DATA : BEGIN OF i_kna1 OCCURS 0,
         kunnr  LIKE  kna1-kunnr,
         name1  LIKE  kna1-name1,
       END OF i_kna1.

DATA : BEGIN OF i_makt OCCURS 0,
         matnr  LIKE  makt-matnr,
         maktx  LIKE  makt-maktx,
       END OF i_makt.

DATA : BEGIN OF i_vbkd OCCURS 0,
         vbeln  LIKE  vbkd-vbeln,
         bsark  LIKE  vbkd-bsark,
       END OF i_vbkd.

DATA : BEGIN OF i_sales OCCURS 0,
         vbeln  LIKE  vbak-vbeln,
       END OF i_sales.

DATA : BEGIN OF i_delv OCCURS 0,
         vbeln  LIKE  vbrk-zuonr,
       END OF i_delv.

DATA : BEGIN OF i_bill OCCURS 0,
         vbeln  LIKE  vbrk-vbeln,
         zuonr  LIKE  vbrk-zuonr,
         erdat  LIKE  vbrk-erdat,
       END OF i_bill.

DATA : gt_fix   TYPE STANDARD TABLE OF zsdfixpo INITIAL SIZE 0.

DATA : BEGIN OF i_detquot OCCURS 0,
         vkbur  LIKE  vbak-vkbur,
         kukla  LIKE  kna1vv-kukla,
         knkli  LIKE  vbak-knkli,
         bstnk  LIKE  vbak-bstnk,
         fixpo(10),
         matnr  LIKE  vbap-matnr,
         vbeln  LIKE  vbak-vbeln,
         bstdk  LIKE  vbak-bstdk,
         kvgr4  LIKE  knvv-kvgr4,
*         kdgrp  LIKE  vbkd-kdgrp,
         name1  LIKE  kna1-name1,
         erdat  LIKE  vbak-erdat,
         posnr  LIKE  vbap-posnr,
         kdmat  LIKE  vbap-kdmat,
         matkl  LIKE  vbap-matkl,
         maktx  LIKE  makt-maktx,
         bsark  LIKE  vbkd-bsark,
         pstyv  LIKE  vbap-pstyv,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         abgru  LIKE  vbap-abgru,
         princ  LIKE  zsprlsom-princ,
       END OF i_detquot.

DATA : BEGIN OF i_detquot2 OCCURS 0,
         kvgr4  LIKE  knvv-kvgr4,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         vkbur  LIKE  vbak-vkbur,
         knkli  LIKE  vbak-knkli,
         bstnk  LIKE  vbak-bstnk,
         bstdk  LIKE  vbak-bstdk,
*         kdgrp  LIKE  vbkd-kdgrp,
         name1  LIKE  kna1-name1,
         vbeln  LIKE  vbak-vbeln,
         erdat  LIKE  vbak-erdat,
         posnr  LIKE  vbap-posnr,
         kdmat  LIKE  vbap-kdmat,
         bsark  LIKE  vbkd-bsark,
         pstyv  LIKE  vbap-pstyv,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         abgru  LIKE  vbap-abgru,
       END OF i_detquot2.

DATA : BEGIN OF i_detquot3 OCCURS 0,
         vkbur  LIKE  vbak-vkbur,
         kvgr4  LIKE  knvv-kvgr4,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         knkli  LIKE  vbak-knkli,
         bstnk  LIKE  vbak-bstnk,
         bstdk  LIKE  vbak-bstdk,
*         kdgrp  LIKE  vbkd-kdgrp,
         name1  LIKE  kna1-name1,
         vbeln  LIKE  vbak-vbeln,
         erdat  LIKE  vbak-erdat,
         posnr  LIKE  vbap-posnr,
         kdmat  LIKE  vbap-kdmat,
         bsark  LIKE  vbkd-bsark,
         pstyv  LIKE  vbap-pstyv,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         abgru  LIKE  vbap-abgru,
       END OF i_detquot3.

DATA : BEGIN OF i_detquot4 OCCURS 0,
         vkbur  LIKE  vbak-vkbur,
         knkli  LIKE  vbak-knkli,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         kvgr4  LIKE  knvv-kvgr4,
         maktx  LIKE  makt-maktx,
         bstnk  LIKE  vbak-bstnk,
         bstdk  LIKE  vbak-bstdk,
*         kdgrp  LIKE  vbkd-kdgrp,
         name1  LIKE  kna1-name1,
         vbeln  LIKE  vbak-vbeln,
         erdat  LIKE  vbak-erdat,
         posnr  LIKE  vbap-posnr,
         kdmat  LIKE  vbap-kdmat,
         bsark  LIKE  vbkd-bsark,
         pstyv  LIKE  vbap-pstyv,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         abgru  LIKE  vbap-abgru,
       END OF i_detquot4.

DATA : BEGIN OF i_detquot5 OCCURS 0,
         matkl  LIKE  vbap-matkl,
         kvgr4  LIKE  knvv-kvgr4,
         vkbur  LIKE  vbak-vkbur,
         knkli  LIKE  vbak-knkli,
         name1  LIKE  kna1-name1,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         bstnk  LIKE  vbak-bstnk,
         bstdk  LIKE  vbak-bstdk,
*         kdgrp  LIKE  vbkd-kdgrp,
         vbeln  LIKE  vbak-vbeln,
         erdat  LIKE  vbak-erdat,
         posnr  LIKE  vbap-posnr,
         kdmat  LIKE  vbap-kdmat,
         bsark  LIKE  vbkd-bsark,
         pstyv  LIKE  vbap-pstyv,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         abgru  LIKE  vbap-abgru,
       END OF i_detquot5.

DATA : BEGIN OF i_detquot6 OCCURS 0,
         princ  LIKE  zsprlsom-princ,
         kvgr4  LIKE  knvv-kvgr4,
         vkbur  LIKE  vbak-vkbur,
         knkli  LIKE  vbak-knkli,
         name1  LIKE  kna1-name1,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         bstnk  LIKE  vbak-bstnk,
         bstdk  LIKE  vbak-bstdk,
*         kdgrp  LIKE  vbkd-kdgrp,
         vbeln  LIKE  vbak-vbeln,
         erdat  LIKE  vbak-erdat,
         posnr  LIKE  vbap-posnr,
         kdmat  LIKE  vbap-kdmat,
         bsark  LIKE  vbkd-bsark,
         pstyv  LIKE  vbap-pstyv,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         abgru  LIKE  vbap-abgru,
         matkl  LIKE  vbap-matkl,
       END OF i_detquot6.

DATA : BEGIN OF i_detquot7 OCCURS 0,
         vkbur  LIKE  vbak-vkbur,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         kvgr4  LIKE  knvv-kvgr4,
         knkli  LIKE  vbak-knkli,
         bstnk  LIKE  vbak-bstnk,
         bstdk  LIKE  vbak-bstdk,
*         kdgrp  LIKE  vbkd-kdgrp,
         name1  LIKE  kna1-name1,
         vbeln  LIKE  vbak-vbeln,
         erdat  LIKE  vbak-erdat,
         posnr  LIKE  vbap-posnr,
         kdmat  LIKE  vbap-kdmat,
         bsark  LIKE  vbkd-bsark,
         pstyv  LIKE  vbap-pstyv,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         abgru  LIKE  vbap-abgru,
       END OF i_detquot7.

DATA : BEGIN OF i_detsales OCCURS 0,
         vbeln  LIKE  vbak-vbeln,
         erdat  LIKE  vbak-erdat,
         posnr  LIKE  vbap-posnr,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         pstyv  LIKE  vbap-pstyv,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         abgru  LIKE  vbap-abgru,
         vgbel  LIKE  vbak-vgbel,
         vgpos  LIKE  vbap-vgpos,
       END OF i_detsales.

DATA : BEGIN OF i_detdelv OCCURS 0,
         vbeln      LIKE  likp-vbeln,
         erdat      LIKE  likp-erdat,
         wadat_ist  LIKE  likp-wadat_ist,
         posnr      LIKE  lips-posnr,
         matnr      LIKE  lips-matnr,
         maktx      LIKE  makt-maktx,
         lfimg      LIKE  lips-lfimg,
         kzwi1      LIKE  lips-kzwi1,
         vgbel      LIKE  lips-vgbel,
         vgpos      LIKE  lips-vgpos,
       END OF i_detdelv.

* Output Type 1
DATA : BEGIN OF i_output1 OCCURS 0,
*** PO
         vkbur  LIKE  vbak-vkbur,
         vkburt LIKE  tvkbt-bezei,
         knkli  LIKE  vbak-knkli,
         name1  LIKE  kna1-name1,
         bstnk  LIKE  vbak-bstnk,
         bstdk  LIKE  vbak-bstdk,
         fixpo(10),
         kdmat  LIKE  vbap-kdmat,
         kukla  LIKE  kna1vv-kukla,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
         vbeln  LIKE  vbak-vbeln,
         abgru  LIKE  vbap-abgru,
         bezei  LIKE  tvagt-bezei,
*** DO
         dlnum  LIKE  lips-vbeln,
         dldat  LIKE  lips-erdat,
         gidat  LIKE  likp-wadat_ist,
         dlpos  LIKE  lips-posnr,
         dlmat  LIKE  lips-matnr,
         dlmatx  LIKE  makt-maktx,
         dlqty  LIKE  lips-lfimg,
         dlval  LIKE  lips-kzwi1,
*** OTH
         percen(10) TYPE p DECIMALS 2,
         crdat  LIKE zmm_cust_rec-crdat,
         unqty  LIKE  vbap-kwmeng,
         unval  LIKE  vbap-kzwi1,
         unprc(10) TYPE p DECIMALS 2,
         lead1q LIKE  vbap-kwmeng,
         lead1  LIKE  vbap-kzwi1,
         lead1%(10) TYPE p DECIMALS 2,
         lead2q LIKE  vbap-kwmeng,
         lead2  LIKE  vbap-kzwi1,
         lead2%(10) TYPE p DECIMALS 2,
         lead3q LIKE  vbap-kwmeng,
         lead3  LIKE  vbap-kzwi1,
         lead3%(10) TYPE p DECIMALS 2,
         lead4q LIKE  vbap-kwmeng,
         lead4  LIKE  vbap-kzwi1,
         lead4%(10) TYPE p DECIMALS 2,
         lead5q LIKE  vbap-kwmeng,
         lead5  LIKE  vbap-kzwi1,
         lead5%(10) TYPE p DECIMALS 2,
         lead6q LIKE  vbap-kwmeng,
         lead6  LIKE  vbap-kzwi1,
         lead6%(10) TYPE p DECIMALS 2,
         stkoutq LIKE  vbap-kwmeng,
         stkout LIKE  vbap-kzwi1,
         stkout%(10) TYPE p DECIMALS 2,
         cltopq LIKE  vbap-kwmeng,
         cltop  LIKE  vbap-kzwi1,
         cltop%(10) TYPE p DECIMALS 2,
         salahq LIKE  vbap-kwmeng,
         salah  LIKE  vbap-kzwi1,
         salah%(10) TYPE p DECIMALS 2,
         otherq LIKE  vbap-kwmeng,
         other  LIKE  vbap-kzwi1,
         other%(10) TYPE p DECIMALS 2,
         poqty  LIKE  vbap-kwmeng,
         pooutq LIKE  vbap-kwmeng,
         poout  LIKE  vbap-kzwi1,
         poout%(10) TYPE p DECIMALS 2,
         btqty  LIKE  vbap-kwmeng,
         btamt  LIKE  vbap-kzwi1,
         btprc%(10) TYPE p DECIMALS 2,
*** Reason for rejection
         qty1   LIKE  vbap-kwmeng,
         val1   LIKE  vbap-kzwi1,
         prc1(10) TYPE p DECIMALS 2,
         qty2   LIKE  vbap-kwmeng,
         val2   LIKE  vbap-kzwi1,
         prc2(10) TYPE p DECIMALS 2,
         qty3   LIKE  vbap-kwmeng,
         val3   LIKE  vbap-kzwi1,
         prc3(10) TYPE p DECIMALS 2,
         qty4   LIKE  vbap-kwmeng,
         val4   LIKE  vbap-kzwi1,
         prc4(10) TYPE p DECIMALS 2,
         qty5   LIKE  vbap-kwmeng,
         val5   LIKE  vbap-kzwi1,
         prc5(10) TYPE p DECIMALS 2,
         qty6   LIKE  vbap-kwmeng,
         val6   LIKE  vbap-kzwi1,
         prc6(10) TYPE p DECIMALS 2,
         qty7   LIKE  vbap-kwmeng,
         val7   LIKE  vbap-kzwi1,
         prc7(10) TYPE p DECIMALS 2,
         qty8   LIKE  vbap-kwmeng,
         val8   LIKE  vbap-kzwi1,
         prc8(10) TYPE p DECIMALS 2,
         qty9   LIKE  vbap-kwmeng,
         val9   LIKE  vbap-kzwi1,
         prc9(10) TYPE p DECIMALS 2,
         qty10   LIKE  vbap-kwmeng,
         val10   LIKE  vbap-kzwi1,
         prc10(10) TYPE p DECIMALS 2,
         qty11   LIKE  vbap-kwmeng,
         val11   LIKE  vbap-kzwi1,
         prc11(10) TYPE p DECIMALS 2,
         qty12   LIKE  vbap-kwmeng,
         val12   LIKE  vbap-kzwi1,
         prc12(10) TYPE p DECIMALS 2,
         qty13   LIKE  vbap-kwmeng,
         val13   LIKE  vbap-kzwi1,
         prc13(10) TYPE p DECIMALS 2,
         qty14   LIKE  vbap-kwmeng,
         val14   LIKE  vbap-kzwi1,
         prc14(10) TYPE p DECIMALS 2,
         qty15   LIKE  vbap-kwmeng,
         val15   LIKE  vbap-kzwi1,
         prc15(10) TYPE p DECIMALS 2,
         qty16   LIKE  vbap-kwmeng,
         val16   LIKE  vbap-kzwi1,
         prc16(10) TYPE p DECIMALS 2,
         qty17   LIKE  vbap-kwmeng,
         val17   LIKE  vbap-kzwi1,
         prc17(10) TYPE p DECIMALS 2,
         qty18   LIKE  vbap-kwmeng,
         val18   LIKE  vbap-kzwi1,
         prc18(10) TYPE p DECIMALS 2,
         qty19   LIKE  vbap-kwmeng,
         val19   LIKE  vbap-kzwi1,
         prc19(10) TYPE p DECIMALS 2,
         qty20   LIKE  vbap-kwmeng,
         val20   LIKE  vbap-kzwi1,
         prc20(10) TYPE p DECIMALS 2,
         leadt  TYPE  i,
         deci   TYPE  i,
         info(3),
         curr(5),
         sort1(1),
         sort2(1),
         sort3(1),
       END OF i_output1.

DATA : BEGIN OF i_reason1 OCCURS 0,
         vkbur  LIKE  vbak-vkbur,
         knkli  LIKE  vbak-knkli,
         abgru  LIKE  vbap-abgru,
         bezei  LIKE  tvagt-bezei,
         unqty  LIKE  vbap-kwmeng,
         unval  LIKE  vbap-kzwi1,
         percen(10) TYPE p DECIMALS 2,
       END OF i_reason1.

* Output Type 2
DATA : BEGIN OF i_output2 OCCURS 0,
*** PO
         index(2) TYPE c,
         prinx  LIKE  zsprlsom-princ,
         matkx  LIKE  vbap-matkl,
         kvgr4  LIKE  knvv-kvgr4,
         bezei  LIKE  tvv4t-bezei,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
*** DO
         dlqty  LIKE  lips-lfimg,
         dlval  LIKE  lips-kzwi1,
         dlval%(10) TYPE p DECIMALS 2,
*** OTH
         unqty  LIKE  vbap-kwmeng,
         unval  LIKE  vbap-kzwi1,
         unprc(10) TYPE p DECIMALS 2,
         lead1q LIKE  vbap-kwmeng,
         lead1  LIKE  vbap-kzwi1,
         lead1%(10) TYPE p DECIMALS 2,
         lead2q LIKE  vbap-kwmeng,
         lead2  LIKE  vbap-kzwi1,
         lead2%(10) TYPE p DECIMALS 2,
         lead3q LIKE  vbap-kwmeng,
         lead3  LIKE  vbap-kzwi1,
         lead3%(10) TYPE p DECIMALS 2,
         lead4q LIKE  vbap-kwmeng,
         lead4  LIKE  vbap-kzwi1,
         lead4%(10) TYPE p DECIMALS 2,
         lead5q LIKE  vbap-kwmeng,
         lead5  LIKE  vbap-kzwi1,
         lead5%(10) TYPE p DECIMALS 2,
         lead6q LIKE  vbap-kwmeng,
         lead6  LIKE  vbap-kzwi1,
         lead6%(10) TYPE p DECIMALS 2,
         stkoutq LIKE  vbap-kwmeng,
         stkout LIKE  vbap-kzwi1,
         stkout%(10) TYPE p DECIMALS 2,
         cltopq LIKE  vbap-kwmeng,
         cltop  LIKE  vbap-kzwi1,
         cltop%(10) TYPE p DECIMALS 2,
         salahq LIKE  vbap-kwmeng,
         salah  LIKE  vbap-kzwi1,
         salah%(10) TYPE p DECIMALS 2,
         otherq LIKE  vbap-kwmeng,
         other  LIKE  vbap-kzwi1,
         other%(10) TYPE p DECIMALS 2,
         rejectq LIKE  vbap-kwmeng,
         reject LIKE  vbap-kzwi1,
         reject%(10) TYPE p DECIMALS 2,
         pooutq LIKE  vbap-kwmeng,
         poout  LIKE  vbap-kzwi1,
         poout%(10) TYPE p DECIMALS 2,
         btqty LIKE  vbap-kwmeng,
         btamt  LIKE  vbap-kzwi1,
         btprc%(10) TYPE p DECIMALS 2,
*** Reason for rejection
         qty1   LIKE  vbap-kwmeng,
         val1   LIKE  vbap-kzwi1,
         prc1(10) TYPE p DECIMALS 2,
         qty2   LIKE  vbap-kwmeng,
         val2   LIKE  vbap-kzwi1,
         prc2(10) TYPE p DECIMALS 2,
         qty3   LIKE  vbap-kwmeng,
         val3   LIKE  vbap-kzwi1,
         prc3(10) TYPE p DECIMALS 2,
         qty4   LIKE  vbap-kwmeng,
         val4   LIKE  vbap-kzwi1,
         prc4(10) TYPE p DECIMALS 2,
         qty5   LIKE  vbap-kwmeng,
         val5   LIKE  vbap-kzwi1,
         prc5(10) TYPE p DECIMALS 2,
         qty6   LIKE  vbap-kwmeng,
         val6   LIKE  vbap-kzwi1,
         prc6(10) TYPE p DECIMALS 2,
         qty7   LIKE  vbap-kwmeng,
         val7   LIKE  vbap-kzwi1,
         prc7(10) TYPE p DECIMALS 2,
         qty8   LIKE  vbap-kwmeng,
         val8   LIKE  vbap-kzwi1,
         prc8(10) TYPE p DECIMALS 2,
         qty9   LIKE  vbap-kwmeng,
         val9   LIKE  vbap-kzwi1,
         prc9(10) TYPE p DECIMALS 2,
         qty10   LIKE  vbap-kwmeng,
         val10   LIKE  vbap-kzwi1,
         prc10(10) TYPE p DECIMALS 2,
         qty11   LIKE  vbap-kwmeng,
         val11   LIKE  vbap-kzwi1,
         prc11(10) TYPE p DECIMALS 2,
         qty12   LIKE  vbap-kwmeng,
         val12   LIKE  vbap-kzwi1,
         prc12(10) TYPE p DECIMALS 2,
         qty13   LIKE  vbap-kwmeng,
         val13   LIKE  vbap-kzwi1,
         prc13(10) TYPE p DECIMALS 2,
         qty14   LIKE  vbap-kwmeng,
         val14   LIKE  vbap-kzwi1,
         prc14(10) TYPE p DECIMALS 2,
         qty15   LIKE  vbap-kwmeng,
         val15   LIKE  vbap-kzwi1,
         prc15(10) TYPE p DECIMALS 2,
         qty16   LIKE  vbap-kwmeng,
         val16   LIKE  vbap-kzwi1,
         prc16(10) TYPE p DECIMALS 2,
         qty17   LIKE  vbap-kwmeng,
         val17   LIKE  vbap-kzwi1,
         prc17(10) TYPE p DECIMALS 2,
         qty18   LIKE  vbap-kwmeng,
         val18   LIKE  vbap-kzwi1,
         prc18(10) TYPE p DECIMALS 2,
         qty19   LIKE  vbap-kwmeng,
         val19   LIKE  vbap-kzwi1,
         prc19(10) TYPE p DECIMALS 2,
         qty20   LIKE  vbap-kwmeng,
         val20   LIKE  vbap-kzwi1,
         prc20(10) TYPE p DECIMALS 2,
         leadt  TYPE  i,
         info(3),
         curr(5),
         deci(6),
       END OF i_output2.

* Output Type 3
DATA : BEGIN OF i_output3 OCCURS 0,
*** PO
         prinx  LIKE  zsprlsom-princ,
         matkx  LIKE  vbap-matkl,
         index(2) TYPE c,
         vkbur  LIKE  vbak-vkbur,
         vkburt LIKE  tvkbt-bezei,
         kvgr4  LIKE  knvv-kvgr4,
         bezei  LIKE  tvv4t-bezei,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
*** DO
         dlqty  LIKE  lips-lfimg,
         dlval  LIKE  lips-kzwi1,
         dlval%(10) TYPE p DECIMALS 2,
*** OTH
         unqty  LIKE  vbap-kwmeng,
         unval  LIKE  vbap-kzwi1,
         unprc(10) TYPE p DECIMALS 2,
         lead1q LIKE  vbap-kwmeng,
         lead1  LIKE  vbap-kzwi1,
         lead1%(10) TYPE p DECIMALS 2,
         lead2q LIKE  vbap-kwmeng,
         lead2  LIKE  vbap-kzwi1,
         lead2%(10) TYPE p DECIMALS 2,
         lead3q LIKE  vbap-kwmeng,
         lead3  LIKE  vbap-kzwi1,
         lead3%(10) TYPE p DECIMALS 2,
         lead4q LIKE  vbap-kwmeng,
         lead4  LIKE  vbap-kzwi1,
         lead4%(10) TYPE p DECIMALS 2,
         lead5q LIKE  vbap-kwmeng,
         lead5  LIKE  vbap-kzwi1,
         lead5%(10) TYPE p DECIMALS 2,
         lead6q LIKE  vbap-kwmeng,
         lead6  LIKE  vbap-kzwi1,
         lead6%(10) TYPE p DECIMALS 2,
         stkoutq LIKE  vbap-kwmeng,
         stkout LIKE  vbap-kzwi1,
         stkout%(10) TYPE p DECIMALS 2,
         cltopq LIKE  vbap-kwmeng,
         cltop  LIKE  vbap-kzwi1,
         cltop%(10) TYPE p DECIMALS 2,
         salahq LIKE  vbap-kwmeng,
         salah  LIKE  vbap-kzwi1,
         salah%(10) TYPE p DECIMALS 2,
         otherq LIKE  vbap-kwmeng,
         other  LIKE  vbap-kzwi1,
         other%(10) TYPE p DECIMALS 2,
         rejectq LIKE  vbap-kwmeng,
         reject LIKE  vbap-kzwi1,
         reject%(10) TYPE p DECIMALS 2,
         pooutq LIKE  vbap-kwmeng,
         poout  LIKE  vbap-kzwi1,
         poout%(10) TYPE p DECIMALS 2,
         btqty LIKE  vbap-kwmeng,
         btamt  LIKE  vbap-kzwi1,
         btprc%(10) TYPE p DECIMALS 2,
*** Reason for rejection
         qty1   LIKE  vbap-kwmeng,
         val1   LIKE  vbap-kzwi1,
         prc1(10) TYPE p DECIMALS 2,
         qty2   LIKE  vbap-kwmeng,
         val2   LIKE  vbap-kzwi1,
         prc2(10) TYPE p DECIMALS 2,
         qty3   LIKE  vbap-kwmeng,
         val3   LIKE  vbap-kzwi1,
         prc3(10) TYPE p DECIMALS 2,
         qty4   LIKE  vbap-kwmeng,
         val4   LIKE  vbap-kzwi1,
         prc4(10) TYPE p DECIMALS 2,
         qty5   LIKE  vbap-kwmeng,
         val5   LIKE  vbap-kzwi1,
         prc5(10) TYPE p DECIMALS 2,
         qty6   LIKE  vbap-kwmeng,
         val6   LIKE  vbap-kzwi1,
         prc6(10) TYPE p DECIMALS 2,
         qty7   LIKE  vbap-kwmeng,
         val7   LIKE  vbap-kzwi1,
         prc7(10) TYPE p DECIMALS 2,
         qty8   LIKE  vbap-kwmeng,
         val8   LIKE  vbap-kzwi1,
         prc8(10) TYPE p DECIMALS 2,
         qty9   LIKE  vbap-kwmeng,
         val9   LIKE  vbap-kzwi1,
         prc9(10) TYPE p DECIMALS 2,
         qty10   LIKE  vbap-kwmeng,
         val10   LIKE  vbap-kzwi1,
         prc10(10) TYPE p DECIMALS 2,
         qty11   LIKE  vbap-kwmeng,
         val11   LIKE  vbap-kzwi1,
         prc11(10) TYPE p DECIMALS 2,
         qty12   LIKE  vbap-kwmeng,
         val12   LIKE  vbap-kzwi1,
         prc12(10) TYPE p DECIMALS 2,
         qty13   LIKE  vbap-kwmeng,
         val13   LIKE  vbap-kzwi1,
         prc13(10) TYPE p DECIMALS 2,
         qty14   LIKE  vbap-kwmeng,
         val14   LIKE  vbap-kzwi1,
         prc14(10) TYPE p DECIMALS 2,
         qty15   LIKE  vbap-kwmeng,
         val15   LIKE  vbap-kzwi1,
         prc15(10) TYPE p DECIMALS 2,
         qty16   LIKE  vbap-kwmeng,
         val16   LIKE  vbap-kzwi1,
         prc16(10) TYPE p DECIMALS 2,
         qty17   LIKE  vbap-kwmeng,
         val17   LIKE  vbap-kzwi1,
         prc17(10) TYPE p DECIMALS 2,
         qty18   LIKE  vbap-kwmeng,
         val18   LIKE  vbap-kzwi1,
         prc18(10) TYPE p DECIMALS 2,
         qty19   LIKE  vbap-kwmeng,
         val19   LIKE  vbap-kzwi1,
         prc19(10) TYPE p DECIMALS 2,
         qty20   LIKE  vbap-kwmeng,
         val20   LIKE  vbap-kzwi1,
         prc20(10) TYPE p DECIMALS 2,
         leadt  TYPE  i,
         info(3),
         curr(5),
         deci(6),
       END OF i_output3.

* Output Type 4
DATA : BEGIN OF i_output4 OCCURS 0,
*** PO
         index(2) TYPE c,
         prinx  LIKE  zsprlsom-princ,
         matkx  LIKE  vbap-matkl,
         vkbur  LIKE  vbak-vkbur,
         vkburt LIKE  tvkbt-bezei,
         knkli  LIKE  vbak-knkli,
         name1  LIKE  kna1-name1,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
*** DO
         dlqty  LIKE  lips-lfimg,
         dlval  LIKE  lips-kzwi1,
         dlval%(10) TYPE p DECIMALS 2,
*** OTH
         unqty  LIKE  vbap-kwmeng,
         unval  LIKE  vbap-kzwi1,
         unprc(10) TYPE p DECIMALS 2,
         lead1q LIKE  vbap-kwmeng,
         lead1  LIKE  vbap-kzwi1,
         lead1%(10) TYPE p DECIMALS 2,
         lead2q LIKE  vbap-kwmeng,
         lead2  LIKE  vbap-kzwi1,
         lead2%(10) TYPE p DECIMALS 2,
         lead3q LIKE  vbap-kwmeng,
         lead3  LIKE  vbap-kzwi1,
         lead3%(10) TYPE p DECIMALS 2,
         lead4q LIKE  vbap-kwmeng,
         lead4  LIKE  vbap-kzwi1,
         lead4%(10) TYPE p DECIMALS 2,
         lead5q LIKE  vbap-kwmeng,
         lead5  LIKE  vbap-kzwi1,
         lead5%(10) TYPE p DECIMALS 2,
         lead6q LIKE  vbap-kwmeng,
         lead6  LIKE  vbap-kzwi1,
         lead6%(10) TYPE p DECIMALS 2,
         stkoutq LIKE  vbap-kwmeng,
         stkout LIKE  vbap-kzwi1,
         stkout%(10) TYPE p DECIMALS 2,
         cltopq LIKE  vbap-kwmeng,
         cltop  LIKE  vbap-kzwi1,
         cltop%(10) TYPE p DECIMALS 2,
         salahq LIKE  vbap-kwmeng,
         salah  LIKE  vbap-kzwi1,
         salah%(10) TYPE p DECIMALS 2,
         otherq LIKE  vbap-kwmeng,
         other  LIKE  vbap-kzwi1,
         other%(10) TYPE p DECIMALS 2,
         rejectq LIKE  vbap-kwmeng,
         reject LIKE  vbap-kzwi1,
         reject%(10) TYPE p DECIMALS 2,
         pooutq LIKE  vbap-kwmeng,
         poout  LIKE  vbap-kzwi1,
         poout%(10) TYPE p DECIMALS 2,
         btqty LIKE  vbap-kwmeng,
         btamt  LIKE  vbap-kzwi1,
         btprc%(10) TYPE p DECIMALS 2,
*** Reason for rejection
         qty1   LIKE  vbap-kwmeng,
         val1   LIKE  vbap-kzwi1,
         prc1(10) TYPE p DECIMALS 2,
         qty2   LIKE  vbap-kwmeng,
         val2   LIKE  vbap-kzwi1,
         prc2(10) TYPE p DECIMALS 2,
         qty3   LIKE  vbap-kwmeng,
         val3   LIKE  vbap-kzwi1,
         prc3(10) TYPE p DECIMALS 2,
         qty4   LIKE  vbap-kwmeng,
         val4   LIKE  vbap-kzwi1,
         prc4(10) TYPE p DECIMALS 2,
         qty5   LIKE  vbap-kwmeng,
         val5   LIKE  vbap-kzwi1,
         prc5(10) TYPE p DECIMALS 2,
         qty6   LIKE  vbap-kwmeng,
         val6   LIKE  vbap-kzwi1,
         prc6(10) TYPE p DECIMALS 2,
         qty7   LIKE  vbap-kwmeng,
         val7   LIKE  vbap-kzwi1,
         prc7(10) TYPE p DECIMALS 2,
         qty8   LIKE  vbap-kwmeng,
         val8   LIKE  vbap-kzwi1,
         prc8(10) TYPE p DECIMALS 2,
         qty9   LIKE  vbap-kwmeng,
         val9   LIKE  vbap-kzwi1,
         prc9(10) TYPE p DECIMALS 2,
         qty10   LIKE  vbap-kwmeng,
         val10   LIKE  vbap-kzwi1,
         prc10(10) TYPE p DECIMALS 2,
         qty11   LIKE  vbap-kwmeng,
         val11   LIKE  vbap-kzwi1,
         prc11(10) TYPE p DECIMALS 2,
         qty12   LIKE  vbap-kwmeng,
         val12   LIKE  vbap-kzwi1,
         prc12(10) TYPE p DECIMALS 2,
         qty13   LIKE  vbap-kwmeng,
         val13   LIKE  vbap-kzwi1,
         prc13(10) TYPE p DECIMALS 2,
         qty14   LIKE  vbap-kwmeng,
         val14   LIKE  vbap-kzwi1,
         prc14(10) TYPE p DECIMALS 2,
         qty15   LIKE  vbap-kwmeng,
         val15   LIKE  vbap-kzwi1,
         prc15(10) TYPE p DECIMALS 2,
         qty16   LIKE  vbap-kwmeng,
         val16   LIKE  vbap-kzwi1,
         prc16(10) TYPE p DECIMALS 2,
         qty17   LIKE  vbap-kwmeng,
         val17   LIKE  vbap-kzwi1,
         prc17(10) TYPE p DECIMALS 2,
         qty18   LIKE  vbap-kwmeng,
         val18   LIKE  vbap-kzwi1,
         prc18(10) TYPE p DECIMALS 2,
         qty19   LIKE  vbap-kwmeng,
         val19   LIKE  vbap-kzwi1,
         prc19(10) TYPE p DECIMALS 2,
         qty20   LIKE  vbap-kwmeng,
         val20   LIKE  vbap-kzwi1,
         prc20(10) TYPE p DECIMALS 2,
         leadt  TYPE  i,
         info(3),
         curr(5),
         deci(6),
       END OF i_output4.

* Output Type 5
DATA : BEGIN OF i_output5 OCCURS 0,
*** PO
         index(2) TYPE c,
         vkbux  LIKE  vbak-vkbur,
         matkl  LIKE  vbap-matkl,
         kvgr4  LIKE  knvv-kvgr4,
         bezei  LIKE  tvv4t-bezei,
         vkbur  LIKE  vbak-vkbur,
         vkburt LIKE  tvkbt-bezei,
         knkli  LIKE  vbak-knkli,
         name1  LIKE  kna1-name1,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
*** DO
         dlqty  LIKE  lips-lfimg,
         dlval  LIKE  lips-kzwi1,
         dlval%(10) TYPE p DECIMALS 2,
*** OTH
         unqty  LIKE  vbap-kwmeng,
         unval  LIKE  vbap-kzwi1,
         unprc(10) TYPE p DECIMALS 2,
         lead1q LIKE  vbap-kwmeng,
         lead1  LIKE  vbap-kzwi1,
         lead1%(10) TYPE p DECIMALS 2,
         lead2q LIKE  vbap-kwmeng,
         lead2  LIKE  vbap-kzwi1,
         lead2%(10) TYPE p DECIMALS 2,
         lead3q LIKE  vbap-kwmeng,
         lead3  LIKE  vbap-kzwi1,
         lead3%(10) TYPE p DECIMALS 2,
         lead4q LIKE  vbap-kwmeng,
         lead4  LIKE  vbap-kzwi1,
         lead4%(10) TYPE p DECIMALS 2,
         lead5q LIKE  vbap-kwmeng,
         lead5  LIKE  vbap-kzwi1,
         lead5%(10) TYPE p DECIMALS 2,
         lead6q LIKE  vbap-kwmeng,
         lead6  LIKE  vbap-kzwi1,
         lead6%(10) TYPE p DECIMALS 2,
         stkoutq LIKE  vbap-kwmeng,
         stkout LIKE  vbap-kzwi1,
         stkout%(10) TYPE p DECIMALS 2,
         cltopq LIKE  vbap-kwmeng,
         cltop  LIKE  vbap-kzwi1,
         cltop%(10) TYPE p DECIMALS 2,
         salahq LIKE  vbap-kwmeng,
         salah  LIKE  vbap-kzwi1,
         salah%(10) TYPE p DECIMALS 2,
         otherq LIKE  vbap-kwmeng,
         other  LIKE  vbap-kzwi1,
         other%(10) TYPE p DECIMALS 2,
         rejectq LIKE  vbap-kwmeng,
         reject LIKE  vbap-kzwi1,
         reject%(10) TYPE p DECIMALS 2,
         pooutq LIKE  vbap-kwmeng,
         poout  LIKE  vbap-kzwi1,
         poout%(10) TYPE p DECIMALS 2,
         btqty LIKE  vbap-kwmeng,
         btamt  LIKE  vbap-kzwi1,
         btprc%(10) TYPE p DECIMALS 2,
*** Reason for rejection
         qty1   LIKE  vbap-kwmeng,
         val1   LIKE  vbap-kzwi1,
         prc1(10) TYPE p DECIMALS 2,
         qty2   LIKE  vbap-kwmeng,
         val2   LIKE  vbap-kzwi1,
         prc2(10) TYPE p DECIMALS 2,
         qty3   LIKE  vbap-kwmeng,
         val3   LIKE  vbap-kzwi1,
         prc3(10) TYPE p DECIMALS 2,
         qty4   LIKE  vbap-kwmeng,
         val4   LIKE  vbap-kzwi1,
         prc4(10) TYPE p DECIMALS 2,
         qty5   LIKE  vbap-kwmeng,
         val5   LIKE  vbap-kzwi1,
         prc5(10) TYPE p DECIMALS 2,
         qty6   LIKE  vbap-kwmeng,
         val6   LIKE  vbap-kzwi1,
         prc6(10) TYPE p DECIMALS 2,
         qty7   LIKE  vbap-kwmeng,
         val7   LIKE  vbap-kzwi1,
         prc7(10) TYPE p DECIMALS 2,
         qty8   LIKE  vbap-kwmeng,
         val8   LIKE  vbap-kzwi1,
         prc8(10) TYPE p DECIMALS 2,
         qty9   LIKE  vbap-kwmeng,
         val9   LIKE  vbap-kzwi1,
         prc9(10) TYPE p DECIMALS 2,
         qty10   LIKE  vbap-kwmeng,
         val10   LIKE  vbap-kzwi1,
         prc10(10) TYPE p DECIMALS 2,
         qty11   LIKE  vbap-kwmeng,
         val11   LIKE  vbap-kzwi1,
         prc11(10) TYPE p DECIMALS 2,
         qty12   LIKE  vbap-kwmeng,
         val12   LIKE  vbap-kzwi1,
         prc12(10) TYPE p DECIMALS 2,
         qty13   LIKE  vbap-kwmeng,
         val13   LIKE  vbap-kzwi1,
         prc13(10) TYPE p DECIMALS 2,
         qty14   LIKE  vbap-kwmeng,
         val14   LIKE  vbap-kzwi1,
         prc14(10) TYPE p DECIMALS 2,
         qty15   LIKE  vbap-kwmeng,
         val15   LIKE  vbap-kzwi1,
         prc15(10) TYPE p DECIMALS 2,
         qty16   LIKE  vbap-kwmeng,
         val16   LIKE  vbap-kzwi1,
         prc16(10) TYPE p DECIMALS 2,
         qty17   LIKE  vbap-kwmeng,
         val17   LIKE  vbap-kzwi1,
         prc17(10) TYPE p DECIMALS 2,
         qty18   LIKE  vbap-kwmeng,
         val18   LIKE  vbap-kzwi1,
         prc18(10) TYPE p DECIMALS 2,
         qty19   LIKE  vbap-kwmeng,
         val19   LIKE  vbap-kzwi1,
         prc19(10) TYPE p DECIMALS 2,
         qty20   LIKE  vbap-kwmeng,
         val20   LIKE  vbap-kzwi1,
         prc20(10) TYPE p DECIMALS 2,
         leadt  TYPE  i,
         info(3),
         curr(5),
         deci(6),
       END OF i_output5.

* Output Type 6
DATA : BEGIN OF i_output6 OCCURS 0,
*** PO
         index(2) TYPE c,
         vkbux  LIKE  vbak-vkbur,
         princ  LIKE  zsprlsom-princ,
         kvgr4  LIKE  knvv-kvgr4,
         bezei  LIKE  tvv4t-bezei,
         vkbur  LIKE  vbak-vkbur,
         vkburt LIKE  tvkbt-bezei,
         knkli  LIKE  vbak-knkli,
         name1  LIKE  kna1-name1,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
*** DO
         dlqty  LIKE  lips-lfimg,
         dlval  LIKE  lips-kzwi1,
         dlval%(10) TYPE p DECIMALS 2,
*** OTH
         unqty  LIKE  vbap-kwmeng,
         unval  LIKE  vbap-kzwi1,
         unprc(10) TYPE p DECIMALS 2,
         lead1q LIKE  vbap-kwmeng,
         lead1  LIKE  vbap-kzwi1,
         lead1%(10) TYPE p DECIMALS 2,
         lead2q LIKE  vbap-kwmeng,
         lead2  LIKE  vbap-kzwi1,
         lead2%(10) TYPE p DECIMALS 2,
         lead3q LIKE  vbap-kwmeng,
         lead3  LIKE  vbap-kzwi1,
         lead3%(10) TYPE p DECIMALS 2,
         lead4q LIKE  vbap-kwmeng,
         lead4  LIKE  vbap-kzwi1,
         lead4%(10) TYPE p DECIMALS 2,
         lead5q LIKE  vbap-kwmeng,
         lead5  LIKE  vbap-kzwi1,
         lead5%(10) TYPE p DECIMALS 2,
         lead6q LIKE  vbap-kwmeng,
         lead6  LIKE  vbap-kzwi1,
         lead6%(10) TYPE p DECIMALS 2,
         stkoutq LIKE  vbap-kwmeng,
         stkout LIKE  vbap-kzwi1,
         stkout%(10) TYPE p DECIMALS 2,
         cltopq LIKE  vbap-kwmeng,
         cltop  LIKE  vbap-kzwi1,
         cltop%(10) TYPE p DECIMALS 2,
         salahq LIKE  vbap-kwmeng,
         salah  LIKE  vbap-kzwi1,
         salah%(10) TYPE p DECIMALS 2,
         otherq LIKE  vbap-kwmeng,
         other  LIKE  vbap-kzwi1,
         other%(10) TYPE p DECIMALS 2,
         rejectq LIKE  vbap-kwmeng,
         reject LIKE  vbap-kzwi1,
         reject%(10) TYPE p DECIMALS 2,
         pooutq LIKE  vbap-kwmeng,
         poout  LIKE  vbap-kzwi1,
         poout%(10) TYPE p DECIMALS 2,
         btqty LIKE  vbap-kwmeng,
         btamt  LIKE  vbap-kzwi1,
         btprc%(10) TYPE p DECIMALS 2,
*** Reason for rejection
         qty1   LIKE  vbap-kwmeng,
         val1   LIKE  vbap-kzwi1,
         prc1(10) TYPE p DECIMALS 2,
         qty2   LIKE  vbap-kwmeng,
         val2   LIKE  vbap-kzwi1,
         prc2(10) TYPE p DECIMALS 2,
         qty3   LIKE  vbap-kwmeng,
         val3   LIKE  vbap-kzwi1,
         prc3(10) TYPE p DECIMALS 2,
         qty4   LIKE  vbap-kwmeng,
         val4   LIKE  vbap-kzwi1,
         prc4(10) TYPE p DECIMALS 2,
         qty5   LIKE  vbap-kwmeng,
         val5   LIKE  vbap-kzwi1,
         prc5(10) TYPE p DECIMALS 2,
         qty6   LIKE  vbap-kwmeng,
         val6   LIKE  vbap-kzwi1,
         prc6(10) TYPE p DECIMALS 2,
         qty7   LIKE  vbap-kwmeng,
         val7   LIKE  vbap-kzwi1,
         prc7(10) TYPE p DECIMALS 2,
         qty8   LIKE  vbap-kwmeng,
         val8   LIKE  vbap-kzwi1,
         prc8(10) TYPE p DECIMALS 2,
         qty9   LIKE  vbap-kwmeng,
         val9   LIKE  vbap-kzwi1,
         prc9(10) TYPE p DECIMALS 2,
         qty10   LIKE  vbap-kwmeng,
         val10   LIKE  vbap-kzwi1,
         prc10(10) TYPE p DECIMALS 2,
         qty11   LIKE  vbap-kwmeng,
         val11   LIKE  vbap-kzwi1,
         prc11(10) TYPE p DECIMALS 2,
         qty12   LIKE  vbap-kwmeng,
         val12   LIKE  vbap-kzwi1,
         prc12(10) TYPE p DECIMALS 2,
         qty13   LIKE  vbap-kwmeng,
         val13   LIKE  vbap-kzwi1,
         prc13(10) TYPE p DECIMALS 2,
         qty14   LIKE  vbap-kwmeng,
         val14   LIKE  vbap-kzwi1,
         prc14(10) TYPE p DECIMALS 2,
         qty15   LIKE  vbap-kwmeng,
         val15   LIKE  vbap-kzwi1,
         prc15(10) TYPE p DECIMALS 2,
         qty16   LIKE  vbap-kwmeng,
         val16   LIKE  vbap-kzwi1,
         prc16(10) TYPE p DECIMALS 2,
         qty17   LIKE  vbap-kwmeng,
         val17   LIKE  vbap-kzwi1,
         prc17(10) TYPE p DECIMALS 2,
         qty18   LIKE  vbap-kwmeng,
         val18   LIKE  vbap-kzwi1,
         prc18(10) TYPE p DECIMALS 2,
         qty19   LIKE  vbap-kwmeng,
         val19   LIKE  vbap-kzwi1,
         prc19(10) TYPE p DECIMALS 2,
         qty20   LIKE  vbap-kwmeng,
         val20   LIKE  vbap-kzwi1,
         prc20(10) TYPE p DECIMALS 2,
         leadt  TYPE  i,
         info(3),
         curr(5),
         deci(6),
       END OF i_output6.

* Output Type 7
DATA : BEGIN OF i_output7 OCCURS 0,
*** PO
         prinx  LIKE  zsprlsom-princ,
         matkx  LIKE  vbap-matkl,
         index(2) TYPE c,
         vkbur  LIKE  vbak-vkbur,
         vkburt LIKE  tvkbt-bezei,
         princ  LIKE  zsprlsom-princ,
         matkl  LIKE  vbap-matkl,
         matnr  LIKE  vbap-matnr,
         maktx  LIKE  makt-maktx,
         kwmeng LIKE  vbap-kwmeng,
         kzwi1  LIKE  vbap-kzwi1,
*** DO
         dlqty  LIKE  lips-lfimg,
         dlval  LIKE  lips-kzwi1,
         dlval%(10) TYPE p DECIMALS 2,
*** OTH
         unqty  LIKE  vbap-kwmeng,
         unval  LIKE  vbap-kzwi1,
         unprc(10) TYPE p DECIMALS 2,
         lead1q LIKE  vbap-kwmeng,
         lead1  LIKE  vbap-kzwi1,
         lead1%(10) TYPE p DECIMALS 2,
         lead2q LIKE  vbap-kwmeng,
         lead2  LIKE  vbap-kzwi1,
         lead2%(10) TYPE p DECIMALS 2,
         lead3q LIKE  vbap-kwmeng,
         lead3  LIKE  vbap-kzwi1,
         lead3%(10) TYPE p DECIMALS 2,
         lead4q LIKE  vbap-kwmeng,
         lead4  LIKE  vbap-kzwi1,
         lead4%(10) TYPE p DECIMALS 2,
         lead5q LIKE  vbap-kwmeng,
         lead5  LIKE  vbap-kzwi1,
         lead5%(10) TYPE p DECIMALS 2,
         lead6q LIKE  vbap-kwmeng,
         lead6  LIKE  vbap-kzwi1,
         lead6%(10) TYPE p DECIMALS 2,
         stkoutq LIKE  vbap-kwmeng,
         stkout LIKE  vbap-kzwi1,
         stkout%(10) TYPE p DECIMALS 2,
         cltopq LIKE  vbap-kwmeng,
         cltop  LIKE  vbap-kzwi1,
         cltop%(10) TYPE p DECIMALS 2,
         salahq LIKE  vbap-kwmeng,
         salah  LIKE  vbap-kzwi1,
         salah%(10) TYPE p DECIMALS 2,
         otherq LIKE  vbap-kwmeng,
         other  LIKE  vbap-kzwi1,
         other%(10) TYPE p DECIMALS 2,
         rejectq LIKE  vbap-kwmeng,
         reject LIKE  vbap-kzwi1,
         reject%(10) TYPE p DECIMALS 2,
         pooutq LIKE  vbap-kwmeng,
         poout  LIKE  vbap-kzwi1,
         poout%(10) TYPE p DECIMALS 2,
         btqty LIKE  vbap-kwmeng,
         btamt  LIKE  vbap-kzwi1,
         btprc%(10) TYPE p DECIMALS 2,
*** Reason for rejection
         qty1   LIKE  vbap-kwmeng,
         val1   LIKE  vbap-kzwi1,
         prc1(10) TYPE p DECIMALS 2,
         qty2   LIKE  vbap-kwmeng,
         val2   LIKE  vbap-kzwi1,
         prc2(10) TYPE p DECIMALS 2,
         qty3   LIKE  vbap-kwmeng,
         val3   LIKE  vbap-kzwi1,
         prc3(10) TYPE p DECIMALS 2,
         qty4   LIKE  vbap-kwmeng,
         val4   LIKE  vbap-kzwi1,
         prc4(10) TYPE p DECIMALS 2,
         qty5   LIKE  vbap-kwmeng,
         val5   LIKE  vbap-kzwi1,
         prc5(10) TYPE p DECIMALS 2,
         qty6   LIKE  vbap-kwmeng,
         val6   LIKE  vbap-kzwi1,
         prc6(10) TYPE p DECIMALS 2,
         qty7   LIKE  vbap-kwmeng,
         val7   LIKE  vbap-kzwi1,
         prc7(10) TYPE p DECIMALS 2,
         qty8   LIKE  vbap-kwmeng,
         val8   LIKE  vbap-kzwi1,
         prc8(10) TYPE p DECIMALS 2,
         qty9   LIKE  vbap-kwmeng,
         val9   LIKE  vbap-kzwi1,
         prc9(10) TYPE p DECIMALS 2,
         qty10   LIKE  vbap-kwmeng,
         val10   LIKE  vbap-kzwi1,
         prc10(10) TYPE p DECIMALS 2,
         qty11   LIKE  vbap-kwmeng,
         val11   LIKE  vbap-kzwi1,
         prc11(10) TYPE p DECIMALS 2,
         qty12   LIKE  vbap-kwmeng,
         val12   LIKE  vbap-kzwi1,
         prc12(10) TYPE p DECIMALS 2,
         qty13   LIKE  vbap-kwmeng,
         val13   LIKE  vbap-kzwi1,
         prc13(10) TYPE p DECIMALS 2,
         qty14   LIKE  vbap-kwmeng,
         val14   LIKE  vbap-kzwi1,
         prc14(10) TYPE p DECIMALS 2,
         qty15   LIKE  vbap-kwmeng,
         val15   LIKE  vbap-kzwi1,
         prc15(10) TYPE p DECIMALS 2,
         qty16   LIKE  vbap-kwmeng,
         val16   LIKE  vbap-kzwi1,
         prc16(10) TYPE p DECIMALS 2,
         qty17   LIKE  vbap-kwmeng,
         val17   LIKE  vbap-kzwi1,
         prc17(10) TYPE p DECIMALS 2,
         qty18   LIKE  vbap-kwmeng,
         val18   LIKE  vbap-kzwi1,
         prc18(10) TYPE p DECIMALS 2,
         qty19   LIKE  vbap-kwmeng,
         val19   LIKE  vbap-kzwi1,
         prc19(10) TYPE p DECIMALS 2,
         qty20   LIKE  vbap-kwmeng,
         val20   LIKE  vbap-kzwi1,
         prc20(10) TYPE p DECIMALS 2,
         leadt  TYPE  i,
         info(3),
         curr(5),
         deci(6),
       END OF i_output7.

DATA : wa_stot1 LIKE i_output1,
       wa_stot2 LIKE i_output1,
       wa_stot3 LIKE i_output1,
       wa_gtot LIKE i_output1,
       wa_stot21 LIKE i_output2,
       wa_stot22 LIKE i_output2,
       wa_stot23 LIKE i_output2,
       wa_gtot2 LIKE i_output2,
       wa_stot31 LIKE i_output3,
       wa_stot32 LIKE i_output3,
       wa_stot33 LIKE i_output3,
       wa_stot34 LIKE i_output3,
       wa_gtot3 LIKE i_output3,
       wa_stot41 LIKE i_output4,
       wa_stot42 LIKE i_output4,
       wa_stot43 LIKE i_output4,
       wa_stot44 LIKE i_output4,
       wa_gtot4 LIKE i_output4,
       wa_stot51 LIKE i_output5,
       wa_stot52 LIKE i_output5,
       wa_stot53 LIKE i_output5,
       wa_gtot5 LIKE i_output5,
       wa_stot61 LIKE i_output6,
       wa_stot62 LIKE i_output6,
       wa_stot63 LIKE i_output6,
       wa_gtot6 LIKE i_output6,
       wa_stot71 LIKE i_output7,
       wa_stot72 LIKE i_output7,
       wa_stot73 LIKE i_output7,
       wa_gtot7 LIKE i_output7,
       v_dlnum  LIKE  lips-vbeln,
       v_vkbur  LIKE  vbak-vkbur,
       v_knkli  LIKE  vbak-knkli,
       v_kzwi1  LIKE  vbap-kzwi1,
       v_btamt  LIKE  vbap-kzwi1,
       va_text(15).

DATA : i_zmm_cust_rec TYPE TABLE OF zmm_cust_rec WITH HEADER LINE,
       i_tvagt TYPE TABLE OF tvagt WITH HEADER LINE,
       i_tvkbt TYPE TABLE OF tvkbt WITH HEADER LINE,
       i_tvv4t TYPE TABLE OF tvv4t WITH HEADER LINE.

DATA:       disvariant   LIKE disvariant,
            eventcat     TYPE slis_t_event,
            va_wbwbest   LIKE s032-wbwbest,
            va_mbwbest   LIKE s032-mbwbest,
            va_lgort     LIKE s032-lgort,
            sw TYPE i,
            va_verpr LIKE mbew-verpr,
            va_peinh LIKE mbew-peinh,
            va_nsp  LIKE konp-kbetr,
            va_total TYPE i,
            eventcat_ln  LIKE LINE OF eventcat,
            fieldcat     TYPE slis_t_fieldcat_alv WITH HEADER LINE,
            ihead        TYPE slis_t_listheader,
            ifoot        TYPE slis_t_listheader,
            ihead_ln     TYPE slis_listheader,
            evtab        TYPE slis_t_event WITH HEADER LINE,
            evtab_ln     TYPE slis_alv_event,
            keyinfo      TYPE slis_keyinfo_alv,
            layout       TYPE slis_layout_alv,
            printcat     TYPE slis_print_alv,
            sortcat      TYPE slis_t_sortinfo_alv WITH HEADER LINE,
            sortcat_ln   LIKE LINE OF sortcat,
            it_text_ln   TYPE lvc_t_txtp,
            it_text      TYPE lvc_t_txtp WITH HEADER LINE.

DATA:        e_save(1) TYPE c,
             er_fieldcat TYPE slis_t_fieldcat_alv,
             er_layout   TYPE slis_layout_alv,
             er_sp_group TYPE slis_t_sp_group_alv,
             er_events   TYPE slis_t_event,
             e_default(1) TYPE c,
             e_exit(1) TYPE c,g_repid LIKE sy-repid,
             er_variant LIKE disvariant,
             e_variant LIKE disvariant,
             l_dataset(50),
             e_status TYPE slis_formname VALUE 'STANDARD_ER01',
             e_user_command TYPE slis_formname VALUE 'USER_COMMAND',
*             e_top_of_page  TYPE slis_formname VALUE 'TOP_OF_PAGE',
             g_exit_caused_by_caller,
             gs_exit_caused_by_user TYPE slis_exit_by_user.

DATA  BEGIN OF t_abgru OCCURS 1.
        INCLUDE STRUCTURE zsd_abgru2.
DATA  END   OF t_abgru.

DATA: t_abgru_ori LIKE t_abgru OCCURS 0 WITH HEADER LINE.
