PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSB2B_ERRLOG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSB2B_ERRLOG-ZPONO .
    FIELD ZSB2B_ERRLOG-ZLINENO .
    FIELD ZSB2B_ERRLOG-BEDAT .
    FIELD ZSB2B_ERRLOG-FKDAT .
    FIELD ZSB2B_ERRLOG-ERNAM .
    FIELD ZSB2B_ERRLOG-KVGR4 .
    FIELD ZSB2B_ERRLOG-ZMESSAGE .
    FIELD ZSB2B_ERRLOG-FILENAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSB2B_ERRLOG-ZPONO .
    FIELD ZSB2B_ERRLOG-ZLINENO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
