*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSB2B_ERRLOGTOP.                  " Global Data
  INCLUDE LZSB2B_ERRLOGUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSB2B_ERRLOGF00                        . " subprograms
  INCLUDE LZSB2B_ERRLOGI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSB2B_ERRLOGF...                  " Subprograms
* INCLUDE LZSB2B_ERRLOGO...                  " PBO-Modules
* INCLUDE LZSB2B_ERRLOGI...                  " PAI-Modules
