*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 03.01.2003 at 14:04:14 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSCL_RANGETOP.                    " Global Data
  INCLUDE LZSCL_RANGEUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSCL_RANGEF00                          . " subprograms
  INCLUDE LZSCL_RANGEI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSCL_RANGEF...                    " Subprograms
* INCLUDE LZSCL_RANGEO...                    " PBO-Modules
* INCLUDE LZSCL_RANGEI...                    " PAI-Modules
