*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSCL_CLASSTOP.                    " Global Data
  INCLUDE LZSCL_CLASSUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSCL_CLASSF00                          . " subprograms
  INCLUDE LZSCL_CLASSI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSCL_CLASSF...                    " Subprograms
* INCLUDE LZSCL_CLASSO...                    " PBO-Modules
* INCLUDE LZSCL_CLASSI...                    " PAI-Modules
