*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSCL_USERTOP.                     " Global Data
  INCLUDE LZSCL_USERUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSCL_USERF00                           . " subprograms
  INCLUDE LZSCL_USERI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSCL_USERF...                     " Subprograms
* INCLUDE LZSCL_USERO...                     " PBO-Modules
* INCLUDE LZSCL_USERI...                     " PAI-Modules
