PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSCL_USER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSCL_USER-ZCLASS .
    FIELD ZSCL_USER-ZRANGE .
    FIELD ZSCL_USER-ZLEVEL .
    FIELD ZSCL_USER-USRGROUP .
    FIELD ZSCL_USER-ZPERCENTAGE .
    FIELD ZSCL_USER-ZSTATUS .
    FIELD ZSCL_USER-ZPATNER .
    FIELD ZSCL_USER-ZTOP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSCL_USER-ZCLASS .
    FIELD ZSCL_USER-ZRANGE .
    FIELD ZSCL_USER-ZLEVEL .
    FIELD ZSCL_USER-USRGROUP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
