PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSCR_CONTROL01 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSCR_CONTROL01-KDGRP .
    FIELD ZSCR_CONTROL01-AUART .
    FIELD ZSCR_CONTROL01-USRGROUP .
    FIELD ZSCR_CONTROL01-STATUS .
    FIELD ZSCR_CONTROL01-KKBER .
    FIELD ZSCR_CONTROL01-ZHEXTRA2 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSCR_CONTROL01-KDGRP .
    FIELD ZSCR_CONTROL01-AUART .
    FIELD ZSCR_CONTROL01-USRGROUP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
