*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSCR_CONTROLTOP.                  " Global Data
  INCLUDE LZSCR_CONTROLUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSCR_CONTROLF00                        . " subprograms
  INCLUDE LZSCR_CONTROLI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSCR_CONTROLF...                  " Subprograms
* INCLUDE LZSCR_CONTROLO...                  " PBO-Modules
* INCLUDE LZSCR_CONTROLI...                  " PAI-Modules
