PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSCR_CONTROL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSCR_CONTROL-AUART .
    FIELD ZSCR_CONTROL-FKART .
    FIELD ZSCR_CONTROL-STATUS .
    FIELD ZSCR_CONTROL-DIVCOD .
    FIELD ZSCR_CONTROL-STAT1 .
    FIELD ZSCR_CONTROL-STAT2 .
    FIELD ZSCR_CONTROL-ZTERM .
    FIELD ZSCR_CONTROL-KKBER .
    FIELD ZSCR_CONTROL-ZHEXTRA2 .
    FIELD ZSCR_CONTROL-STAT3 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSCR_CONTROL-AUART .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
