*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 24.06.2004 at 18:58:15 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSCUST_OPPTOP.                    " Global Data
  INCLUDE LZSCUST_OPPUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSCUST_OPPF00                          . " subprograms
  INCLUDE LZSCUST_OPPI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSCUST_OPPF...                    " Subprograms
* INCLUDE LZSCUST_OPPO...                    " PBO-Modules
* INCLUDE LZSCUST_OPPI...                    " PAI-Modules
