PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSCUST_OPP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSCUST_OPP-VKORG .
    FIELD ZSCUST_OPP-VTWEG .
    FIELD ZSCUST_OPP-SPMON .
    FIELD ZSCUST_OPP-VKBUR .
    FIELD ZSCUST_OPP-KUNNR .
    FIELD ZSCUST_OPP-MATNR .
    FIELD ZSCUST_OPP-MVGR2 .
    FIELD ZSCUST_OPP-MVGR3 .
    FIELD ZSCUST_OPP-WAERK .
    FIELD ZSCUST_OPP-CLASS .
    FIELD ZSCUST_OPP-TGT_QTY .
    FIELD ZSCUST_OPP-ZVALTGT .
    FIELD ZSCUST_OPP-FREQ .
    FIELD ZSCUST_OPP-GROWTH .
    FIELD ZSCUST_OPP-SPTAG .
    FIELD ZSCUST_OPP-USERID .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSCUST_OPP-VKORG .
    FIELD ZSCUST_OPP-VTWEG .
    FIELD ZSCUST_OPP-SPMON .
    FIELD ZSCUST_OPP-VKBUR .
    FIELD ZSCUST_OPP-KUNNR .
    FIELD ZSCUST_OPP-MATNR .
    FIELD ZSCUST_OPP-MVGR2 .
    FIELD ZSCUST_OPP-MVGR3 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
