*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSCUST_CONTROLTOP.                " Global Data
  INCLUDE LZSCUST_CONTROLUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSCUST_CONTROLF00                      . " subprograms
  INCLUDE LZSCUST_CONTROLI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSCUST_CONTROLF...                " Subprograms
* INCLUDE LZSCUST_CONTROLO...                " PBO-Modules
* INCLUDE LZSCUST_CONTROLI...                " PAI-Modules

INCLUDE LZSCUST_CONTROLF01.
