PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSD_PO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSD_PO-BUKRS .
    FIELD ZSD_PO-WERKS .
    FIELD ZSD_PO-LGORT .
    FIELD ZSD_PO-LEGACY_BRANCH .
    FIELD ZSD_PO-PONUM .
    FIELD ZSD_PO-POITM .
    FIELD ZSD_PO-PODAT .
    FIELD ZSD_PO-POEXP .
    FIELD ZSD_PO-KUNNR .
    FIELD ZSD_PO-SORTL .
    FIELD ZSD_PO-MATNR .
    FIELD ZSD_PO-MENGE .
    FIELD ZSD_PO-MEINS .
    FIELD ZSD_PO-DNNUM .
    FIELD ZSD_PO-DNDAT .
    FIELD ZSD_PO-REACOD .
    FIELD ZSD_PO-FILENM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSD_PO-BUKRS .
    FIELD ZSD_PO-WERKS .
    FIELD ZSD_PO-LGORT .
    FIELD ZSD_PO-LEGACY_BRANCH .
    FIELD ZSD_PO-PONUM .
    FIELD ZSD_PO-POITM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
