PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSD_B2B CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSD_B2B-ZNOB2B .
    FIELD ZSD_B2B-EBELP .
    FIELD ZSD_B2B-MATNR .
    FIELD ZSD_B2B-MATERIAL .
    FIELD ZSD_B2B-MENGE .
    FIELD ZSD_B2B-MEINS .
    FIELD ZSD_B2B-NETWR .
    FIELD ZSD_B2B-WAERS .
    FIELD ZSD_B2B-KZWI1 .
    FIELD ZSD_B2B-KZWI2 .
    FIELD ZSD_B2B-KZWI3 .
    FIELD ZSD_B2B-QTYBX .
    FIELD ZSD_B2B-QTYPC .
    FIELD ZSD_B2B-CONVE .
    FIELD ZSD_B2B-BRTWR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSD_B2B-ZNOB2B .
    FIELD ZSD_B2B-EBELP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
