PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSD_SERTIFIKASI CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSD_SERTIFIKASI-VKBUR .
    FIELD ZSD_SERTIFIKASI-OBJTYP .
    FIELD ZSD_SERTIFIKASI-STR01 .
    FIELD ZSD_SERTIFIKASI-STR02 .
    FIELD ZSD_SERTIFIKASI-STR03 .
    FIELD ZSD_SERTIFIKASI-STR04 .
    FIELD ZSD_SERTIFIKASI-STR05 .
    FIELD ZSD_SERTIFIKASI-ED01 .
    FIELD ZSD_SERTIFIKASI-ED02 .
    FIELD ZSD_SERTIFIKASI-ED03 .
    FIELD ZSD_SERTIFIKASI-ED04 .
    FIELD ZSD_SERTIFIKASI-ED05 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSD_SERTIFIKASI-VKBUR .
    FIELD ZSD_SERTIFIKASI-OBJTYP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
