*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSD_B2BTOP.                       " Global Data
  INCLUDE LZSD_B2BUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSD_B2BF00                             . " subprograms
  INCLUDE LZSD_B2BI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSD_B2BF...                       " Subprograms
* INCLUDE LZSD_B2BO...                       " PBO-Modules
* INCLUDE LZSD_B2BI...                       " PAI-Modules
