*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSDFIXPOTOP.                      " Global Data
  INCLUDE LZSDFIXPOUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSDFIXPOF00                            . " subprograms
  INCLUDE LZSDFIXPOI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSDFIXPOF...                      " Subprograms
* INCLUDE LZSDFIXPOO...                      " PBO-Modules
* INCLUDE LZSDFIXPOI...                      " PAI-Modules
