PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDFIXPO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDFIXPO-VKORG .
    FIELD ZSDFIXPO-VKBUR .
    FIELD ZSDFIXPO-KVGR4 .
    FIELD ZSDFIXPO-EBELN .
    FIELD ZSDFIXPO-MONAT .
    FIELD ZSDFIXPO-GJAHR .
    FIELD ZSDFIXPO-ZWEEK .
    FIELD ZSDFIXPO-LFDAT .
    FIELD ZSDFIXPO-ZUPLDT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDFIXPO-VKORG .
    FIELD ZSDFIXPO-VKBUR .
    FIELD ZSDFIXPO-KVGR4 .
    FIELD ZSDFIXPO-EBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
