PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSERR_B2B CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSERR_B2B-ZNOB2B .
    FIELD ZSERR_B2B-MJAHR .
    FIELD ZSERR_B2B-LINE .
    FIELD ZSERR_B2B-EBELN .
    FIELD ZSERR_B2B-Z_UPLOD .
    FIELD ZSERR_B2B-TYPE .
    FIELD ZSERR_B2B-MESSAGE .
    FIELD ZSERR_B2B-LOG_NO .
    FIELD ZSERR_B2B-LOG_MSG_NO .
    FIELD ZSERR_B2B-MESSAGE_V1 .
    FIELD ZSERR_B2B-MESSAGE_V2 .
    FIELD ZSERR_B2B-MESSAGE_V3 .
    FIELD ZSERR_B2B-MESSAGE_V4 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSERR_B2B-ZNOB2B .
    FIELD ZSERR_B2B-MJAHR .
    FIELD ZSERR_B2B-LINE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
