*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSERR_B2BTOP.                     " Global Data
  INCLUDE LZSERR_B2BUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSERR_B2BF00                           . " subprograms
  INCLUDE LZSERR_B2BI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSERR_B2BF...                     " Subprograms
* INCLUDE LZSERR_B2BO...                     " PBO-Modules
* INCLUDE LZSERR_B2BI...                     " PAI-Modules
