*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSEXTRECREASTOP.                  " Global Data
  INCLUDE LZSEXTRECREASUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSEXTRECREASF00                        . " subprograms
  INCLUDE LZSEXTRECREASI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSEXTRECREASF...                  " Subprograms
* INCLUDE LZSEXTRECREASO...                  " PBO-Modules
* INCLUDE LZSEXTRECREASI...                  " PAI-Modules
