*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSEXTRECTOP.                      " Global Data
  INCLUDE LZSEXTRECUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSEXTRECF00                            . " subprograms
  INCLUDE LZSEXTRECI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSEXTRECF...                      " Subprograms
* INCLUDE LZSEXTRECO...                      " PBO-Modules
* INCLUDE LZSEXTRECI...                      " PAI-Modules
