PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSFFPPDT002 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSFFPPDT002-RSNUM .
    FIELD ZSFFPPDT002-RSPOS .
    FIELD ZSFFPPDT002-RSART .
    FIELD ZSFFPPDT002-ZEILE .
    FIELD ZSFFPPDT002-AUFNR .
    FIELD ZSFFPPDT002-POSNR .
    FIELD ZSFFPPDT002-MATNR .
    FIELD ZSFFPPDT002-WERKS .
    FIELD ZSFFPPDT002-LGORT .
    FIELD ZSFFPPDT002-CHARG .
    FIELD ZSFFPPDT002-ERFMG .
    FIELD ZSFFPPDT002-ERFME .
    FIELD ZSFFPPDT002-VORNR .
    FIELD ZSFFPPDT002-LTXA1 .
    FIELD ZSFFPPDT002-SORTF .
    FIELD ZSFFPPDT002-PHSEQ .
    FIELD ZSFFPPDT002-WBOOTH .
    FIELD ZSFFPPDT002-OPERATOR .
    FIELD ZSFFPPDT002-PENGAWAS .
    FIELD ZSFFPPDT002-ERDAT .
    FIELD ZSFFPPDT002-ERTIM .
    FIELD ZSFFPPDT002-SCANFL .
    FIELD ZSFFPPDT002-SCANDT .
    FIELD ZSFFPPDT002-SCANTM .
    FIELD ZSFFPPDT002-MBLNR .
    FIELD ZSFFPPDT002-MJAHR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSFFPPDT002-RSNUM .
    FIELD ZSFFPPDT002-RSPOS .
    FIELD ZSFFPPDT002-RSART .
    FIELD ZSFFPPDT002-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
