PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSFFPPDT004 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSFFPPDT004-AUFNR .
    FIELD ZSFFPPDT004-MATNR .
    FIELD ZSFFPPDT004-POSNR .
    FIELD ZSFFPPDT004-WERKS .
    FIELD ZSFFPPDT004-WBOOTH .
    FIELD ZSFFPPDT004-EQUNR .
    FIELD ZSFFPPDT004-SHTXT .
    FIELD ZSFFPPDT004-LTXA1 .
    FIELD ZSFFPPDT004-OPERATOR .
    FIELD ZSFFPPDT004-PENGAWAS .
    FIELD ZSFFPPDT004-ISTAD .
    FIELD ZSFFPPDT004-ISTAU .
    FIELD ZSFFPPDT004-DATUM .
    FIELD ZSFFPPDT004-UZEIT .
    FIELD ZSFFPPDT004-TARA .
    FIELD ZSFFPPDT004-MEINS .
    FIELD ZSFFPPDT004-VORNR .
    FIELD ZSFFPPDT004-SORTF .
    FIELD ZSFFPPDT004-PHSEQ .
    FIELD ZSFFPPDT004-SCANFL .
    FIELD ZSFFPPDT004-SCANDT .
    FIELD ZSFFPPDT004-SCANTM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSFFPPDT004-AUFNR .
    FIELD ZSFFPPDT004-MATNR .
    FIELD ZSFFPPDT004-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
