PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSFFPPDT003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSFFPPDT003-AUFNR .
    FIELD ZSFFPPDT003-VORNR .
    FIELD ZSFFPPDT003-POSNR .
    FIELD ZSFFPPDT003-ZEILE .
    FIELD ZSFFPPDT003-MATNR .
    FIELD ZSFFPPDT003-CHARG .
    FIELD ZSFFPPDT003-WERKS .
    FIELD ZSFFPPDT003-BDMNG .
    FIELD ZSFFPPDT003-ERFMG .
    FIELD ZSFFPPDT003-ERFME .
    FIELD ZSFFPPDT003-MEINS .
    FIELD ZSFFPPDT003-FACTOR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSFFPPDT003-AUFNR .
    FIELD ZSFFPPDT003-VORNR .
    FIELD ZSFFPPDT003-POSNR .
    FIELD ZSFFPPDT003-ZEILE .
    FIELD ZSFFPPDT003-MATNR .
    FIELD ZSFFPPDT003-CHARG .
    FIELD ZSFFPPDT003-WERKS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
