FUNCTION-POOL zsff_weight.                  "MESSAGE-ID ..

TYPES: BEGIN OF ts_fp_pgi,
         aufnr    TYPE c LENGTH 12,
         werks    TYPE c LENGTH 4,
         rmscn    TYPE c LENGTH 30,
         matnr    TYPE c LENGTH 18,
         maktx    TYPE c LENGTH 40,
         charg    TYPE c LENGTH 10,
         packs    TYPE p LENGTH 8 DECIMALS 3,
         packt    TYPE p LENGTH 8 DECIMALS 3,
         operator TYPE c LENGTH 30,
         pengawas TYPE c LENGTH 30,
         plnbez   TYPE c LENGTH 18,
         fmaktx   TYPE c LENGTH 40,
         fcharg   TYPE c LENGTH 10,
         mblnr    TYPE c LENGTH 10,
         mjahr    TYPE c LENGTH 4,
         ipno     TYPE c LENGTH 18,
         hazcom   TYPE c LENGTH 30,
         name1    TYPE c LENGTH 35,
       END OF ts_fp_pgi .

TYPES: BEGIN OF ts_fp_pgi2,
         aufnr    TYPE c LENGTH 12,
         werks    TYPE c LENGTH 4,
         rmscn    TYPE c LENGTH 30,
         matnr    TYPE c LENGTH 18,
         maktx    TYPE c LENGTH 40,
         charg    TYPE c LENGTH 10,
         packs    TYPE c LENGTH 10,
         packt    TYPE c LENGTH 10,
         operator TYPE c LENGTH 40,
         pengawas TYPE c LENGTH 40,
         plnbez   TYPE c LENGTH 18,
         fmaktx   TYPE c LENGTH 40,
         fcharg   TYPE c LENGTH 10,
         mblnr    TYPE c LENGTH 10,
         mjahr    TYPE c LENGTH 4,
         ipno     TYPE c LENGTH 18,
         hazcom   TYPE c LENGTH 30,
         name1    TYPE c LENGTH 35,
       END OF ts_fp_pgi2 .

TYPES: BEGIN OF ts_wh_print,
         aufnr    TYPE c LENGTH 12,
         werks    TYPE c LENGTH 4,
         matnr    TYPE c LENGTH 18,
         maktx    TYPE c LENGTH 40,
         vornr    TYPE c LENGTH 4,
         posnr    TYPE c LENGTH 4,
         ltxa1    TYPE c LENGTH 40,
         rsnum    TYPE c LENGTH 10,
         rspos    TYPE c LENGTH 4,
         wb       TYPE c LENGTH 10,
         equnr    TYPE c LENGTH 18,
         eqktx    TYPE c LENGTH 40,
         operator TYPE c LENGTH 40,
         pengawas TYPE c LENGTH 40,
         plnbez   TYPE c LENGTH 18,
         fmaktx   TYPE c LENGTH 40,
         fcharg   TYPE c LENGTH 10,
         hazcom   TYPE c LENGTH 30,
         name1    TYPE c LENGTH 35,
         netto    TYPE c LENGTH 12,
         tara     TYPE c LENGTH 12,
         bruto    TYPE c LENGTH 12,
         erfme    TYPE c LENGTH 3,
         qrcode   TYPE c LENGTH 100,
         datum    TYPE c LENGTH 30,
       END OF ts_wh_print.

TYPES: BEGIN OF ts_wh_pgi,
         aufnr  TYPE c LENGTH 12,
         vornr  TYPE c LENGTH 4,
         oprtyp TYPE c LENGTH 10,
         mblnr  TYPE c LENGTH 10,
       END OF ts_wh_pgi.

TYPES: BEGIN OF ts_wh_material_scan_dtl,
         aufnr TYPE c LENGTH 12,
         charg TYPE c LENGTH 10,
         clabs TYPE c LENGTH 12,
         meins TYPE c LENGTH 3,
         bdmng TYPE c LENGTH 10,
         erfme TYPE c LENGTH 3,
         erfmg TYPE c LENGTH 10,
         weime TYPE c LENGTH 3,
         meanv TYPE c LENGTH 22,
       END OF ts_wh_material_scan_dtl .

TYPES: BEGIN OF ts_wh_mat_scan,
         aufnr              TYPE c LENGTH 12,
         werks              TYPE c LENGTH 4,
         rmscn              TYPE c LENGTH 30,
         matnr              TYPE c LENGTH 18,
         maktx              TYPE c LENGTH 40,
         vornr              TYPE c LENGTH 4,
         posnr              TYPE c LENGTH 4,
         rsnum              TYPE c LENGTH 10,
         rspos              TYPE c LENGTH 4,
         lgort              TYPE c LENGTH 4,
         aufpl              TYPE c LENGTH 10,
         ltxa1              TYPE c LENGTH 40,
         plnbez             TYPE c LENGTH 18,
         fgbatch            TYPE c LENGTH 10,
         print              TYPE c LENGTH 1,
         equnr              TYPE c LENGTH 18,
         wh_materialscannav TYPE TABLE OF ts_wh_material_scan_dtl WITH DEFAULT KEY,
       END OF ts_wh_mat_scan .

DATA: gt_resb_insert TYPE STANDARD TABLE OF resb,
      gt_resb_update TYPE STANDARD TABLE OF resb,
      gt_onr00       TYPE STANDARD TABLE OF onr00,
      gt_jest        TYPE STANDARD TABLE OF jest,
      gt_jsto        TYPE STANDARD TABLE OF jsto,
      gt_add         TYPE STANDARD TABLE OF zppresb_add,
      gt_zsffppdt003 TYPE STANDARD TABLE OF zsffppdt003,
      gt_zsffppdt004 TYPE STANDARD TABLE OF zsffppdt004,
      gs_onr00       LIKE LINE OF gt_onr00,
      gs_jest        LIKE LINE OF gt_jest,
      gs_jsto        LIKE LINE OF gt_jsto.

DATA: gs_wh_print TYPE ts_wh_print,
      gs_wh_pgi   TYPE ts_wh_pgi.
