PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSH_B2B CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSH_B2B-ZNOB2B .
    FIELD ZSH_B2B-MJAHR .
    FIELD ZSH_B2B-EBELN .
    FIELD ZSH_B2B-VBELN .
    FIELD ZSH_B2B-BEDAT .
    FIELD ZSH_B2B-BNDDT .
    FIELD ZSH_B2B-PATNER .
    FIELD ZSH_B2B-VKORG .
    FIELD ZSH_B2B-VKBUR .
    FIELD ZSH_B2B-KUNNR .
    FIELD ZSH_B2B-NETWR .
    FIELD ZSH_B2B-BRTWR .
    FIELD ZSH_B2B-MWSBK .
    FIELD ZSH_B2B-TDISA .
    FIELD ZSH_B2B-TDISB .
    FIELD ZSH_B2B-WAERS .
    FIELD ZSH_B2B-FKDAT .
    FIELD ZSH_B2B-AEDAT .
    FIELD ZSH_B2B-ERNAM .
    FIELD ZSH_B2B-FILENAME .
    FIELD ZSH_B2B-Z_UPLOD .
    FIELD ZSH_B2B-QTQUO .
    FIELD ZSH_B2B-STLGC .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSH_B2B-ZNOB2B .
    FIELD ZSH_B2B-MJAHR .
    FIELD ZSH_B2B-EBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
