*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 20.08.2002 at 22:29:57 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSIGN_BMTOP.                      " Global Data
  INCLUDE LZSIGN_BMUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSIGN_BMF00                            . " subprograms
  INCLUDE LZSIGN_BMI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSIGN_BMF...                      " Subprograms
* INCLUDE LZSIGN_BMO...                      " PBO-Modules
* INCLUDE LZSIGN_BMI...                      " PAI-Modules
