PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSL_HSALES CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSL_HSALES-VKORG .
    FIELD ZSL_HSALES-PLANT .
    FIELD ZSL_HSALES-VKBUR .
    FIELD ZSL_HSALES-GJAHR .
    FIELD ZSL_HSALES-VBELN .
    FIELD ZSL_HSALES-VBTYP .
    FIELD ZSL_HSALES-Z_UPLOD .
    FIELD ZSL_HSALES-FKDAT .
    FIELD ZSL_HSALES-ACCOUNT_NO .
    FIELD ZSL_HSALES-COGS_J .
    FIELD ZSL_HSALES-STAACC .
    FIELD ZSL_HSALES-STAFJK .
    FIELD ZSL_HSALES-STASIS .
    FIELD ZSL_HSALES-TAX_STATUS .
    FIELD ZSL_HSALES-KUNNR .
    FIELD ZSL_HSALES-TXDAT .
    FIELD ZSL_HSALES-BLDAT .
    FIELD ZSL_HSALES-FKART .
    FIELD ZSL_HSALES-VRTNR .
    FIELD ZSL_HSALES-SLCOD .
    FIELD ZSL_HSALES-VRTGP .
    FIELD ZSL_HSALES-AUGRU .
    FIELD ZSL_HSALES-PYTYP .
    FIELD ZSL_HSALES-SPDOT .
    FIELD ZSL_HSALES-KUNDE .
    FIELD ZSL_HSALES-CURR .
    FIELD ZSL_HSALES-GRSWR .
    FIELD ZSL_HSALES-NETWR .
    FIELD ZSL_HSALES-MWSBP .
    FIELD ZSL_HSALES-DISVOL .
    FIELD ZSL_HSALES-COD .
    FIELD ZSL_HSALES-PPN_BTM .
    FIELD ZSL_HSALES-STCOR .
    FIELD ZSL_HSALES-SISDATE .
    FIELD ZSL_HSALES-FILENAME .
    FIELD ZSL_HSALES-KIR .
    FIELD ZSL_HSALES-BUDAT .
    FIELD ZSL_HSALES-ZTOP .
    FIELD ZSL_HSALES-TAXCODE .
    FIELD ZSL_HSALES-STATUS .
    FIELD ZSL_HSALES-TIMECOR .
    FIELD ZSL_HSALES-SONR .
    FIELD ZSL_HSALES-ACCT_REF .
    FIELD ZSL_HSALES-BUDAT_ACC .
    FIELD ZSL_HSALES-COGS_REF .
    FIELD ZSL_HSALES-BUDAT_COGS .
    FIELD ZSL_HSALES-SIS_REF .
    FIELD ZSL_HSALES-BUDAT_SIS .
    FIELD ZSL_HSALES-VAT_REF .
    FIELD ZSL_HSALES-BUDAT_VAT .
    FIELD ZSL_HSALES-UPL_CANCEL .
    FIELD ZSL_HSALES-MESSAGE .
    FIELD ZSL_HSALES-NOSSP .
    FIELD ZSL_HSALES-TGLSSP .
    FIELD ZSL_HSALES-BELNRSSP .
    FIELD ZSL_HSALES-BUDATSSP .
    FIELD ZSL_HSALES-SSP_REF .
    FIELD ZSL_HSALES-TGLSSP_REF .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSL_HSALES-VKORG .
    FIELD ZSL_HSALES-PLANT .
    FIELD ZSL_HSALES-VKBUR .
    FIELD ZSL_HSALES-GJAHR .
    FIELD ZSL_HSALES-VBELN .
    FIELD ZSL_HSALES-VBTYP .
    FIELD ZSL_HSALES-Z_UPLOD .
    FIELD ZSL_HSALES-FKDAT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
