*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSL_DSALESTOP.                    " Global Data
  INCLUDE LZSL_DSALESUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSL_DSALESF00                          . " subprograms
  INCLUDE LZSL_DSALESI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSL_DSALESF...                    " Subprograms
* INCLUDE LZSL_DSALESO...                    " PBO-Modules
* INCLUDE LZSL_DSALESI...                    " PAI-Modules
