PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSL_DSALES CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSL_DSALES-VBELN .
    FIELD ZSL_DSALES-GJAHR .
    FIELD ZSL_DSALES-POSNR .
    FIELD ZSL_DSALES-VBTYP .
    FIELD ZSL_DSALES-Z_UPLOD .
    FIELD ZSL_DSALES-MATNR .
    FIELD ZSL_DSALES-STAGI .
    FIELD ZSL_DSALES-GINO .
    FIELD ZSL_DSALES-FKIMG .
    FIELD ZSL_DSALES-NSP .
    FIELD ZSL_DSALES-STAX .
    FIELD ZSL_DSALES-PPN .
    FIELD ZSL_DSALES-DISA .
    FIELD ZSL_DSALES-DISB .
    FIELD ZSL_DSALES-DISC .
    FIELD ZSL_DSALES-DISD .
    FIELD ZSL_DSALES-DISDC .
    FIELD ZSL_DSALES-DISE .
    FIELD ZSL_DSALES-DISF .
    FIELD ZSL_DSALES-DISSP .
    FIELD ZSL_DSALES-DISVOL .
    FIELD ZSL_DSALES-COD .
    FIELD ZSL_DSALES-ZPMP .
    FIELD ZSL_DSALES-STCOR .
    FIELD ZSL_DSALES-GI_REF .
    FIELD ZSL_DSALES-BUDAT_GI .
    FIELD ZSL_DSALES-UPMAT .
    FIELD ZSL_DSALES-ZUPQTY .
    FIELD ZSL_DSALES-AUGRU_LGC .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSL_DSALES-VBELN .
    FIELD ZSL_DSALES-GJAHR .
    FIELD ZSL_DSALES-POSNR .
    FIELD ZSL_DSALES-VBTYP .
    FIELD ZSL_DSALES-Z_UPLOD .
    FIELD ZSL_DSALES-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
