*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSL_HSALESTOP.                    " Global Data
  INCLUDE LZSL_HSALESUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSL_HSALESF00                          . " subprograms
  INCLUDE LZSL_HSALESI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSL_HSALESF...                    " Subprograms
* INCLUDE LZSL_HSALESO...                    " PBO-Modules
* INCLUDE LZSL_HSALESI...                    " PAI-Modules
