*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 06.02.2003 at 11:20:41 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSLOCKANVASTOP.                   " Global Data
  INCLUDE LZSLOCKANVASUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSLOCKANVASF00                         . " subprograms
  INCLUDE LZSLOCKANVASI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSLOCKANVASF...                   " Subprograms
* INCLUDE LZSLOCKANVASO...                   " PBO-Modules
* INCLUDE LZSLOCKANVASI...                   " PAI-Modules
