PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSMAP_B2B CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSMAP_B2B-VKBUR .
    FIELD ZSMAP_B2B-PATNER .
    FIELD ZSMAP_B2B-MATERIAL .
    FIELD ZSMAP_B2B-MATNR .
    FIELD ZSMAP_B2B-QTY_P .
    FIELD ZSMAP_B2B-MEINS_P .
    FIELD ZSMAP_B2B-QTY .
    FIELD ZSMAP_B2B-MEINS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSMAP_B2B-VKBUR .
    FIELD ZSMAP_B2B-PATNER .
    FIELD ZSMAP_B2B-MATERIAL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
