*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSMAPPING_AUGRUTOP.               " Global Data
  INCLUDE LZSMAPPING_AUGRUUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSMAPPING_AUGRUF00                     . " subprograms
  INCLUDE LZSMAPPING_AUGRUI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSMAPPING_AUGRUF...               " Subprograms
* INCLUDE LZSMAPPING_AUGRUO...               " PBO-Modules
* INCLUDE LZSMAPPING_AUGRUI...               " PAI-Modules
