PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSMAT2_B2B CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSMAT2_B2B-ZMATNR .
    FIELD ZSMAT2_B2B-KVGR4 .
    FIELD ZSMAT2_B2B-VALID_TO .
    FIELD ZSMAT2_B2B-VALID_FR .
    FIELD ZSMAT2_B2B-MATNR .
    FIELD ZSMAT2_B2B-LVORM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSMAT2_B2B-ZMATNR .
    FIELD ZSMAT2_B2B-KVGR4 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
