*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSMOV2TOP.                        " Global Data
  INCLUDE LZSMOV2UXX.                        " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSMOV2F00                              . " subprograms
  INCLUDE LZSMOV2I00                              . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSMOV2F...                        " Subprograms
* INCLUDE LZSMOV2O...                        " PBO-Modules
* INCLUDE LZSMOV2I...                        " PAI-Modules
