*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSMOVTOP.                         " Global Data
  INCLUDE LZSMOVUXX.                         " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSMOVF00                               . " subprograms
  INCLUDE LZSMOVI00                               . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSMOVF...                         " Subprograms
* INCLUDE LZSMOVO...                         " PBO-Modules
* INCLUDE LZSMOVI...                         " PAI-Modules
