*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSNSTATTOP.                       " Global Data
  INCLUDE LZSNSTATUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSNSTATF00                             . " subprograms
  INCLUDE LZSNSTATI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSNSTATF...                       " Subprograms
* INCLUDE LZSNSTATO...                       " PBO-Modules
* INCLUDE LZSNSTATI...                       " PAI-Modules
