PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSPAKET_CONTROL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSPAKET_CONTROL-VKORG .
    FIELD ZSPAKET_CONTROL-PAKET .
    FIELD ZSPAKET_CONTROL-FIELD_NAME .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE2 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE3 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE4 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE5 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE6 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE7 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE8 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE9 .
    FIELD ZSPAKET_CONTROL-DATAB .
    FIELD ZSPAKET_CONTROL-DATBI .
    FIELD ZSPAKET_CONTROL-ERNAM .
    FIELD ZSPAKET_CONTROL-ERDAT .
    FIELD ZSPAKET_CONTROL-ERZET .
    FIELD ZSPAKET_CONTROL-TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSPAKET_CONTROL-VKORG .
    FIELD ZSPAKET_CONTROL-PAKET .
    FIELD ZSPAKET_CONTROL-FIELD_NAME .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE2 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE3 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE4 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE5 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE6 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE7 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE8 .
    FIELD ZSPAKET_CONTROL-FIELD_VALUE9 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
