*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSPAKET_DISCTOP.                  " Global Data
  INCLUDE LZSPAKET_DISCUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSPAKET_DISCF00                        . " subprograms
  INCLUDE LZSPAKET_DISCI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSPAKET_DISCF...                  " Subprograms
* INCLUDE LZSPAKET_DISCO...                  " PBO-Modules
* INCLUDE LZSPAKET_DISCI...                  " PAI-Modules

INCLUDE LZSPAKET_DISCF01.
