*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSPARAMETERTOP.                   " Global Data
  INCLUDE LZSPARAMETERUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSPARAMETERF00                         . " subprograms
  INCLUDE LZSPARAMETERI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSPARAMETERF...                   " Subprograms
* INCLUDE LZSPARAMETERO...                   " PBO-Modules
* INCLUDE LZSPARAMETERI...                   " PAI-Modules
