PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSPARAMETER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSPARAMETER-VKORG .
    FIELD ZSPARAMETER-PAKET .
    FIELD ZSPARAMETER-TYPE .
    FIELD ZSPARAMETER-DATBI .
    FIELD ZSPARAMETER-DATAB .
    FIELD ZSPARAMETER-GROWTH .
    FIELD ZSPARAMETER-MINTGT .
    FIELD ZSPARAMETER-MAXTGT .
    FIELD ZSPARAMETER-PERCEN .
    FIELD ZSPARAMETER-PBAGI .
    FIELD ZSPARAMETER-STRIKE .
    FIELD ZSPARAMETER-ACHIVE .
    FIELD ZSPARAMETER-WAERK .
    FIELD ZSPARAMETER-DESCTYP .
    FIELD ZSPARAMETER-GJAHR .
    FIELD ZSPARAMETER-SMESTER .
    FIELD ZSPARAMETER-MONFR .
    FIELD ZSPARAMETER-MONTO .
    FIELD ZSPARAMETER-PERCEN1 .
    FIELD ZSPARAMETER-PERCEN2 .
    FIELD ZSPARAMETER-PERCEN_MIN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSPARAMETER-VKORG .
    FIELD ZSPARAMETER-PAKET .
    FIELD ZSPARAMETER-TYPE .
    FIELD ZSPARAMETER-DATBI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
