PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSPAKET_DISC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSPAKET_DISC-VKORG .
    FIELD ZSPAKET_DISC-KSCHL .
    FIELD ZSPAKET_DISC-KONDA .
    FIELD ZSPAKET_DISC-ZGRPACK .
    FIELD ZSPAKET_DISC-PAKET .
    FIELD ZSPAKET_DISC-DATBI .
    FIELD ZSPAKET_DISC-DATAB .
    FIELD ZSPAKET_DISC-DESCR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSPAKET_DISC-VKORG .
    FIELD ZSPAKET_DISC-KSCHL .
    FIELD ZSPAKET_DISC-KONDA .
    FIELD ZSPAKET_DISC-ZGRPACK .
    FIELD ZSPAKET_DISC-PAKET .
    FIELD ZSPAKET_DISC-DATBI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
