*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSPAKET_CONTROLTOP.               " Global Data
  INCLUDE LZSPAKET_CONTROLUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSPAKET_CONTROLF00                     . " subprograms
  INCLUDE LZSPAKET_CONTROLI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSPAKET_CONTROLF...               " Subprograms
* INCLUDE LZSPAKET_CONTROLO...               " PBO-Modules
* INCLUDE LZSPAKET_CONTROLI...               " PAI-Modules

INCLUDE LZSPAKET_CONTROLF01.
