*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 19.07.2005 at 15:57:43 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSPRLSOMTOP.                      " Global Data
  INCLUDE LZSPRLSOMUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSPRLSOMF00                            . " subprograms
  INCLUDE LZSPRLSOMI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSPRLSOMF...                      " Subprograms
* INCLUDE LZSPRLSOMO...                      " PBO-Modules
* INCLUDE LZSPRLSOMI...                      " PAI-Modules
