*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 31.08.2004 at 20:30:03 by user TDS_DEV01
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSRANGETOP.                       " Global Data
  INCLUDE LZSRANGEUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSRANGEF00                             . " subprograms
  INCLUDE LZSRANGEI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSRANGEF...                       " Subprograms
* INCLUDE LZSRANGEO...                       " PBO-Modules
* INCLUDE LZSRANGEI...                       " PAI-Modules
