*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSRANGE_SOTOP.                    " Global Data
  INCLUDE LZSRANGE_SOUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSRANGE_SOF00                          . " subprograms
  INCLUDE LZSRANGE_SOI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSRANGE_SOF...                    " Subprograms
* INCLUDE LZSRANGE_SOO...                    " PBO-Modules
* INCLUDE LZSRANGE_SOI...                    " PAI-Modules
