PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZSRANGE-VKBUR .
    FIELD ZSRANGE-NUMKI_QTN .
    FIELD ZSRANGE-NUMKI_SO .
    FIELD ZSRANGE-NUMKI_DO .
    FIELD ZSRANGE-NUMKI_BILL .
    FIELD ZSRANGE-NUMKI_SO1 .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZSRANGE-VKBUR .
  module detail_pai.
 endchain.
