PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSSUTDT022 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSSUTDT022-VKORG .
    FIELD ZSSUTDT022-VTWEG .
    FIELD ZSSUTDT022-SPART .
    FIELD ZSSUTDT022-KUNNR .
    FIELD ZSSUTDT022-VKBUR .
    FIELD ZSSUTDT022-KUNN2 .
    FIELD ZSSUTDT022-PERNR .
    FIELD ZSSUTDT022-SUN1 .
    FIELD ZSSUTDT022-MON1 .
    FIELD ZSSUTDT022-TUE1 .
    FIELD ZSSUTDT022-WED1 .
    FIELD ZSSUTDT022-THU1 .
    FIELD ZSSUTDT022-FRI1 .
    FIELD ZSSUTDT022-SAT1 .
    FIELD ZSSUTDT022-SUN2 .
    FIELD ZSSUTDT022-MON2 .
    FIELD ZSSUTDT022-TUE2 .
    FIELD ZSSUTDT022-WED2 .
    FIELD ZSSUTDT022-THU2 .
    FIELD ZSSUTDT022-FRI2 .
    FIELD ZSSUTDT022-SAT2 .
    FIELD ZSSUTDT022-SUN3 .
    FIELD ZSSUTDT022-MON3 .
    FIELD ZSSUTDT022-TUE3 .
    FIELD ZSSUTDT022-WED3 .
    FIELD ZSSUTDT022-THU3 .
    FIELD ZSSUTDT022-FRI3 .
    FIELD ZSSUTDT022-SAT3 .
    FIELD ZSSUTDT022-SUN4 .
    FIELD ZSSUTDT022-MON4 .
    FIELD ZSSUTDT022-TUE4 .
    FIELD ZSSUTDT022-WED4 .
    FIELD ZSSUTDT022-THU4 .
    FIELD ZSSUTDT022-FRI4 .
    FIELD ZSSUTDT022-SAT4 .
    FIELD ZSSUTDT022-SUN5 .
    FIELD ZSSUTDT022-MON5 .
    FIELD ZSSUTDT022-TUE5 .
    FIELD ZSSUTDT022-WED5 .
    FIELD ZSSUTDT022-THU5 .
    FIELD ZSSUTDT022-FRI5 .
    FIELD ZSSUTDT022-SAT5 .
    FIELD ZSSUTDT022-ZUSER .
    FIELD ZSSUTDT022-ZDATUM .
    FIELD ZSSUTDT022-COUNTER .
    FIELD ZSSUTDT022-XKUNN2 .
    FIELD ZSSUTDT022-XPERNR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSSUTDT022-VKORG .
    FIELD ZSSUTDT022-VTWEG .
    FIELD ZSSUTDT022-SPART .
    FIELD ZSSUTDT022-KUNNR .
    FIELD ZSSUTDT022-VKBUR .
    FIELD ZSSUTDT022-KUNN2 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
