PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSSUTDT006 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSSUTDT006-VBELN .
    FIELD ZSSUTDT006-GJAHR .
    FIELD ZSSUTDT006-POSNR .
    FIELD ZSSUTDT006-VBTYP .
    FIELD ZSSUTDT006-Z_UPLOD .
    FIELD ZSSUTDT006-MATNR .
    FIELD ZSSUTDT006-FKIMG .
    FIELD ZSSUTDT006-NSP .
    FIELD ZSSUTDT006-STAX .
    FIELD ZSSUTDT006-PPN .
    FIELD ZSSUTDT006-DISA .
    FIELD ZSSUTDT006-DISB .
    FIELD ZSSUTDT006-DISC .
    FIELD ZSSUTDT006-DISD .
    FIELD ZSSUTDT006-DISDC .
    FIELD ZSSUTDT006-DISE .
    FIELD ZSSUTDT006-DISF .
    FIELD ZSSUTDT006-DISSP .
    FIELD ZSSUTDT006-DISVOL .
    FIELD ZSSUTDT006-COD .
    FIELD ZSSUTDT006-ZPMP .
    FIELD ZSSUTDT006-STCOR .
    FIELD ZSSUTDT006-GI_REF .
    FIELD ZSSUTDT006-BUDAT_GI .
    FIELD ZSSUTDT006-UPMAT .
    FIELD ZSSUTDT006-ZUPQTY .
    FIELD ZSSUTDT006-ZCOSTS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSSUTDT006-VBELN .
    FIELD ZSSUTDT006-GJAHR .
    FIELD ZSSUTDT006-POSNR .
    FIELD ZSSUTDT006-VBTYP .
    FIELD ZSSUTDT006-Z_UPLOD .
    FIELD ZSSUTDT006-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
