PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSSUTDT025 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSSUTDT025-VKORG .
    FIELD ZSSUTDT025-VKBUR .
    FIELD ZSSUTDT025-PERNR .
    FIELD ZSSUTDT025-UMJAH .
    FIELD ZSSUTDT025-SDATE .
    FIELD ZSSUTDT025-STATUS .
    FIELD ZSSUTDT025-AEDAT .
    FIELD ZSSUTDT025-AENAM .
    FIELD ZSSUTDT025-DAILY_CALL_NUM .
    FIELD ZSSUTDT025-ZRELEASE .
    FIELD ZSSUTDT025-ZPRINT .
    FIELD ZSSUTDT025-STR_DCP_DAT .
    FIELD ZSSUTDT025-END_DCP_DAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSSUTDT025-VKORG .
    FIELD ZSSUTDT025-VKBUR .
    FIELD ZSSUTDT025-PERNR .
    FIELD ZSSUTDT025-UMJAH .
    FIELD ZSSUTDT025-SDATE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
