PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSSUTDT005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSSUTDT005-VKORG .
    FIELD ZSSUTDT005-PLANT .
    FIELD ZSSUTDT005-VKBUR .
    FIELD ZSSUTDT005-GJAHR .
    FIELD ZSSUTDT005-VBELN .
    FIELD ZSSUTDT005-VBTYP .
    FIELD ZSSUTDT005-Z_UPLOD .
    FIELD ZSSUTDT005-FKDAT .
    FIELD ZSSUTDT005-ACCOUNT_NO .
    FIELD ZSSUTDT005-COGS_J .
    FIELD ZSSUTDT005-STAACC .
    FIELD ZSSUTDT005-STAFJK .
    FIELD ZSSUTDT005-STASIS .
    FIELD ZSSUTDT005-GINO .
    FIELD ZSSUTDT005-TAX_STATUS .
    FIELD ZSSUTDT005-KUNNR .
    FIELD ZSSUTDT005-TXDAT .
    FIELD ZSSUTDT005-BLDAT .
    FIELD ZSSUTDT005-FKART .
    FIELD ZSSUTDT005-VRTNR .
    FIELD ZSSUTDT005-SLCOD .
    FIELD ZSSUTDT005-VRTGP .
    FIELD ZSSUTDT005-AUGRU .
    FIELD ZSSUTDT005-PYTYP .
    FIELD ZSSUTDT005-SPDOT .
    FIELD ZSSUTDT005-KUNDE .
    FIELD ZSSUTDT005-CURR .
    FIELD ZSSUTDT005-GRSWR .
    FIELD ZSSUTDT005-NETWR .
    FIELD ZSSUTDT005-MWSBP .
    FIELD ZSSUTDT005-DISVOL .
    FIELD ZSSUTDT005-COD .
    FIELD ZSSUTDT005-PPN_BTM .
    FIELD ZSSUTDT005-STCOR .
    FIELD ZSSUTDT005-SISDATE .
    FIELD ZSSUTDT005-FILENAME .
    FIELD ZSSUTDT005-KIR .
    FIELD ZSSUTDT005-BUDAT .
    FIELD ZSSUTDT005-ZTOP .
    FIELD ZSSUTDT005-TAXCODE .
    FIELD ZSSUTDT005-STATUS .
    FIELD ZSSUTDT005-TIMECOR .
    FIELD ZSSUTDT005-SONR .
    FIELD ZSSUTDT005-ACCT_REF .
    FIELD ZSSUTDT005-BUDAT_ACC .
    FIELD ZSSUTDT005-GINO_REF .
    FIELD ZSSUTDT005-COGS_REF .
    FIELD ZSSUTDT005-BUDAT_GI .
    FIELD ZSSUTDT005-SIS_REF .
    FIELD ZSSUTDT005-BUDAT_SIS .
    FIELD ZSSUTDT005-VAT_REF .
    FIELD ZSSUTDT005-BUDAT_VAT .
    FIELD ZSSUTDT005-UPL_CANCEL .
    FIELD ZSSUTDT005-MESSAGE .
    FIELD ZSSUTDT005-NOSSP .
    FIELD ZSSUTDT005-TGLSSP .
    FIELD ZSSUTDT005-BELNRSSP .
    FIELD ZSSUTDT005-BUDATSSP .
    FIELD ZSSUTDT005-SSP_REF .
    FIELD ZSSUTDT005-TGLSSP_REF .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSSUTDT005-VKORG .
    FIELD ZSSUTDT005-PLANT .
    FIELD ZSSUTDT005-VKBUR .
    FIELD ZSSUTDT005-GJAHR .
    FIELD ZSSUTDT005-VBELN .
    FIELD ZSSUTDT005-VBTYP .
    FIELD ZSSUTDT005-Z_UPLOD .
    FIELD ZSSUTDT005-FKDAT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
