PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSSUTDT021 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSSUTDT021-VKORG .
    FIELD ZSSUTDT021-VTWEG .
    FIELD ZSSUTDT021-SPART .
    FIELD ZSSUTDT021-VKBUR .
    FIELD ZSSUTDT021-ANSVH .
    FIELD ZSSUTDT021-BEGDA .
    FIELD ZSSUTDT021-KVGR5 .
    FIELD ZSSUTDT021-FCALL .
    FIELD ZSSUTDT021-FCALLTY .
    FIELD ZSSUTDT021-OUTMIN .
    FIELD ZSSUTDT021-OUTMAX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSSUTDT021-VKORG .
    FIELD ZSSUTDT021-VTWEG .
    FIELD ZSSUTDT021-SPART .
    FIELD ZSSUTDT021-VKBUR .
    FIELD ZSSUTDT021-ANSVH .
    FIELD ZSSUTDT021-BEGDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
