PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZST_POINT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZST_POINT-WERKS .
    FIELD ZST_POINT-LGORT .
    FIELD ZST_POINT-MJAHR .
    FIELD ZST_POINT-MBLNR .
    FIELD ZST_POINT-BLDAT .
    FIELD ZST_POINT-DIVCOD .
    FIELD ZST_POINT-ZGROUP .
    FIELD ZST_POINT-BBKNO .
    FIELD ZST_POINT-UMWRK .
    FIELD ZST_POINT-UMLGO .
    FIELD ZST_POINT-BBMNO .
    FIELD ZST_POINT-FILENAME .
    FIELD ZST_POINT-STATUS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZST_POINT-WERKS .
    FIELD ZST_POINT-LGORT .
    FIELD ZST_POINT-MJAHR .
    FIELD ZST_POINT-MBLNR .
    FIELD ZST_POINT-BLDAT .
    FIELD ZST_POINT-DIVCOD .
    FIELD ZST_POINT-ZGROUP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
