*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSTARGET_CONTROLTOP.              " Global Data
  INCLUDE LZSTARGET_CONTROLUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSTARGET_CONTROLF00                    . " subprograms
  INCLUDE LZSTARGET_CONTROLI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSTARGET_CONTROLF...              " Subprograms
* INCLUDE LZSTARGET_CONTROLO...              " PBO-Modules
* INCLUDE LZSTARGET_CONTROLI...              " PAI-Modules

INCLUDE LZSTARGET_CONTROLF01.
