PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSTARGET CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSTARGET-VKORG .
    FIELD ZSTARGET-VTWEG .
    FIELD ZSTARGET-GJAHR .
    FIELD ZSTARGET-SPMON .
    FIELD ZSTARGET-VKBUR .
    FIELD ZSTARGET-KUNNR .
    FIELD ZSTARGET-MATNR .
    FIELD ZSTARGET-MVGR2 .
    FIELD ZSTARGET-MVGR3 .
    FIELD ZSTARGET-KONDA .
    FIELD ZSTARGET-WAERK .
    FIELD ZSTARGET-CLASS .
    FIELD ZSTARGET-ZQTXOLD .
    FIELD ZSTARGET-TGT_QTY .
    FIELD ZSTARGET-ZVALTGT .
    FIELD ZSTARGET-ZVALTGT_X .
    FIELD ZSTARGET-FREQ .
    FIELD ZSTARGET-GROWTH .
    FIELD ZSTARGET-SPTAG .
    FIELD ZSTARGET-USERID .
    FIELD ZSTARGET-ERZET .
    FIELD ZSTARGET-ZSTS .
    FIELD ZSTARGET-USERID_HO .
    FIELD ZSTARGET-USERDT_HO .
    FIELD ZSTARGET-USERTM_HO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSTARGET-VKORG .
    FIELD ZSTARGET-VTWEG .
    FIELD ZSTARGET-GJAHR .
    FIELD ZSTARGET-SPMON .
    FIELD ZSTARGET-VKBUR .
    FIELD ZSTARGET-KUNNR .
    FIELD ZSTARGET-MATNR .
    FIELD ZSTARGET-MVGR2 .
    FIELD ZSTARGET-MVGR3 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
