PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSTARGET_CONTROL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSTARGET_CONTROL-VKORG .
    FIELD ZSTARGET_CONTROL-PAKET .
    FIELD ZSTARGET_CONTROL-FIELD_NAME .
    FIELD ZSTARGET_CONTROL-KUNNR .
    FIELD ZSTARGET_CONTROL-FIELD_VALUE1 .
    FIELD ZSTARGET_CONTROL-FIELD_VALUE2 .
    FIELD ZSTARGET_CONTROL-FIELD_VALUE3 .
    FIELD ZSTARGET_CONTROL-FIELD_VALUE4 .
    FIELD ZSTARGET_CONTROL-DATAB .
    FIELD ZSTARGET_CONTROL-DATBI .
    FIELD ZSTARGET_CONTROL-ERNAM .
    FIELD ZSTARGET_CONTROL-ERDAT .
    FIELD ZSTARGET_CONTROL-ERZET .
    FIELD ZSTARGET_CONTROL-TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSTARGET_CONTROL-VKORG .
    FIELD ZSTARGET_CONTROL-PAKET .
    FIELD ZSTARGET_CONTROL-FIELD_NAME .
    FIELD ZSTARGET_CONTROL-KUNNR .
    FIELD ZSTARGET_CONTROL-FIELD_VALUE1 .
    FIELD ZSTARGET_CONTROL-FIELD_VALUE2 .
    FIELD ZSTARGET_CONTROL-FIELD_VALUE3 .
    FIELD ZSTARGET_CONTROL-FIELD_VALUE4 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
