PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSUOM_B2B CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSUOM_B2B-ZMATNR .
    FIELD ZSUOM_B2B-KVGR4 .
    FIELD ZSUOM_B2B-BSTME .
    FIELD ZSUOM_B2B-POQTY .
    FIELD ZSUOM_B2B-DOQTY .
    FIELD ZSUOM_B2B-VRKME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSUOM_B2B-ZMATNR .
    FIELD ZSUOM_B2B-KVGR4 .
    FIELD ZSUOM_B2B-BSTME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
