*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTDNFIDT005TOP.                   " Global Data
  INCLUDE LZTDNFIDT005UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTDNFIDT005F00                         . " subprograms
  INCLUDE LZTDNFIDT005I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTDNFIDT005F...                   " Subprograms
* INCLUDE LZTDNFIDT005O...                   " PBO-Modules
* INCLUDE LZTDNFIDT005I...                   " PAI-Modules
