PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTDNMMDT002 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTDNMMDT002-LGNUM .
    FIELD ZTDNMMDT002-ZPERID .
    FIELD ZTDNMMDT002-CNAME .
    FIELD ZTDNMMDT002-ZPERSTS .
    FIELD ZTDNMMDT002-ZOUTSRC .
    FIELD ZTDNMMDT002-ACTVT .
    FIELD ZTDNMMDT002-BEGDA .
    FIELD ZTDNMMDT002-SPRPS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTDNMMDT002-LGNUM .
    FIELD ZTDNMMDT002-ZPERID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
