*----------------------------------------------------------------------*
***INCLUDE LZTDN_APIF03 .
*----------------------------------------------------------------------*

FORM send_email_evoucher  USING p_message p_table TYPE ANY TABLE..

  DATA: send_request   TYPE REF TO cl_bcs,
        lv_sent_to_all TYPE os_boolean,
        mailsubject    TYPE so_obj_des,
        mailtext       TYPE bcsy_text,
        document       TYPE REF TO cl_document_bcs,
        sender         TYPE REF TO cl_cam_address_bcs,
        recipient_to   TYPE REF TO cl_cam_address_bcs,
        recipient_cc   TYPE REF TO cl_cam_address_bcs,
        recipient_bcc  TYPE REF TO cl_cam_address_bcs,
        bcs_exception  TYPE REF TO cx_bcs.
  DATA: lv_message(150).
  DATA: lv_email TYPE ad_smtpadr. " ADR6-SMTP_ADDR.
  DATA: lt_tvarvc TYPE STANDARD TABLE OF tvarvc WITH HEADER LINE.
  DATA: lt_body TYPE TABLE OF ztdnsddt011 WITH HEADER LINE.

  lt_body[] = p_table[].

  TRY.
      SELECT * INTO CORRESPONDING FIELDS OF TABLE lt_tvarvc FROM tvarvc WHERE name = 'ZTM_EVOUCHER'.
      send_request = cl_bcs=>create_persistent( ).
      mailsubject = '[Tempomart]-Create eVoucher'.
      lv_message = '<br>Error Proses eVoucher TempoMart </br>'.
      APPEND lv_message TO mailtext.
      "      lv_message = p_message.
      CONCATENATE '<br> Order no. ' p_message '</br>' INTO lv_message.
      APPEND lv_message TO mailtext.
      LOOP AT lt_body.
        CONDENSE lt_body-message.
        CONCATENATE '<br>' lt_body-logno lt_body-logit lt_body-message '</br>' INTO lv_message.
        "        lv_message = lt_body-pesan.
        APPEND lv_message TO mailtext.
      ENDLOOP.
      IF lt_tvarvc[] IS INITIAL.
        lv_message = '<br></br><br></br><br>NB: </br>'.
        APPEND lv_message TO mailtext.
        lv_message = '<br>     Penerima email dapat dimaintance di table TVARVC </br>'.
        APPEND lv_message TO mailtext.
        lv_message = '<br>          TVARVC-Name = ZTM_EVOUCHER </br>'.
        APPEND lv_message TO mailtext.
        lv_message = '<br>          TVARVC-opti diisi dengan TO/CC/BC </br>'.
        APPEND lv_message TO mailtext.
        lv_message = '<br>          TVARVC-Low diisi dengan email penerima </br>'.
        APPEND lv_message TO mailtext.
      ENDIF.

      lv_message = '<br></br><br></br><br>Terima kasih </br>'.
      APPEND lv_message TO mailtext.
      CONCATENATE '<br></br><br></br><br> Email Auto Generated by System </br> <br> </br> <br> </br> <br>' sy-uname  '</br></P>' INTO lv_message SEPARATED BY space.
      APPEND lv_message TO mailtext.


      document = cl_document_bcs=>create_document(
       i_type = 'HTM'
       i_text = mailtext
       i_subject = mailsubject ).
      send_request->set_document( document ).

      send_request->set_document( document ).
      sender = cl_cam_address_bcs=>create_internet_address( 'hendrian@TheTempoGroup.com' ).
      send_request->set_sender( sender ).

      LOOP AT lt_tvarvc WHERE opti = 'TO'.
        lv_email = lt_tvarvc-low.
        recipient_to = cl_cam_address_bcs=>create_internet_address( lv_email ).
        send_request->add_recipient( i_recipient = recipient_to ).
      ENDLOOP.

      LOOP AT lt_tvarvc WHERE opti = 'CC'.
        lv_email = lt_tvarvc-low.
        recipient_cc = cl_cam_address_bcs=>create_internet_address( lv_email ).
        send_request->add_recipient( i_recipient = recipient_cc
        i_copy = 'X' ).
      ENDLOOP.

      LOOP AT lt_tvarvc WHERE opti = 'BC'.
        lv_email = lt_tvarvc-low.
        recipient_bcc = cl_cam_address_bcs=>create_internet_address( lv_email ).
        send_request->add_recipient( i_recipient = recipient_bcc
        i_blind_copy = 'X' ).
      ENDLOOP.


      IF lt_tvarvc[] IS INITIAL.
        recipient_to = cl_cam_address_bcs=>create_internet_address( 'Support.Center@TheTempoGroup.com' ). "'budi.p@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_to ).
        recipient_cc = cl_cam_address_bcs=>create_internet_address( 'nurul.azhar@thetempogroup.com' ).
        send_request->add_recipient( i_recipient = recipient_cc
        i_copy = 'X' ).
        recipient_cc = cl_cam_address_bcs=>create_internet_address( 'amalia.darmayanti@thetempogroup.com' ).
        send_request->add_recipient( i_recipient = recipient_cc
        i_copy = 'X' ).

        recipient_bcc = cl_cam_address_bcs=>create_internet_address( 'hendrian@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_bcc
        i_copy = 'X' ).

        recipient_bcc = cl_cam_address_bcs=>create_internet_address( 'p.nainggolan@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_bcc
        i_copy = 'X' ).

      ENDIF.

      lv_sent_to_all = send_request->send( ).
      IF lv_sent_to_all = 'X'.
        "       WRITE: / 'Email sent to all recipients'.
      ELSE.
        "       WRITE: / 'Email could not be sent to all recipients!'.
      ENDIF.

      COMMIT WORK.

    CATCH cx_bcs INTO bcs_exception.
      "    WRITE: 'Error occurred while sending email: Error Type', bcs_exception->error_type.
  ENDTRY.

ENDFORM.                    " SEND_EMAIL


*&---------------------------------------------------------------------*
*&      Form  F_CONVERT_JSON_VOUCHER
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_GV_STR  text
*      <--P_GT_AWBIMAGE  text
*----------------------------------------------------------------------*
FORM f_convert_json_voucher  USING p_str TYPE string
                         CHANGING p_voucher TYPE ty_order.

  DATA:   lv_json_data     TYPE string. ",
  lv_json_data = p_str.
  zcl_json=>deserialize(
        EXPORTING
          json             = lv_json_data
        CHANGING
          data             = p_voucher ).
ENDFORM.                    " F_CONVERT_JSON_VOUCHER
*&---------------------------------------------------------------------*
*&      Form  F_SAVE_TO_VOUCHER
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_GS_EVOCUHER  text
*----------------------------------------------------------------------*
FORM f_save_to_voucher  USING    p_evocuher TYPE ty_order CHANGING p_return.
  DATA: gt_upload       LIKE TABLE OF ztdnsdst004.
  DATA: gw_upload       LIKE LINE OF  gt_upload.
  DATA: lv_message TYPE bapi_msg.
  DATA: lv_json_data     TYPE string.
  DATA: lv_text(10).
  DATA: lv_name(15).
  DATA: lv_amount LIKE ztdnsddt010-vcramt.
  DATA: gt_ztdnsddt010  LIKE TABLE OF ztdnsddt010 WITH HEADER LINE.
  DATA: gt_mara         TYPE TABLE OF mara  WITH HEADER LINE.
  DATA: l_len TYPE i.
  CLEAR: gt_upload[], gw_upload, gs_items, p_return.
  LOOP AT gs_evoucher-items INTO gs_items.
    gw_upload-name_cust = gs_evoucher-nama_cust.
    gw_upload-email_cust = gs_evoucher-email_cust.
    gw_upload-order_id = gs_evoucher-order_id.
    gw_upload-bukrs     = '8380'.
    gw_upload-matnr     = gs_items-material.
    gw_upload-vcrno  = gs_items-vcrno.
    "    l_len = STRLEN( gs_items-vcrgenerate ).
    gw_upload-vcr_encrp = gs_items-vcrgenerate.
    gw_upload-vcramt = gs_items-vcramt.
    lv_text = gs_items-vcrexp.
    gw_upload-vcrexp = gs_items-vcrexp.
    gw_upload-pay_date = gs_evoucher-transaction_date.
    gw_upload-pay_metod = gs_evoucher-method.
    APPEND gw_upload TO gt_upload.
  ENDLOOP.
  IF gt_upload[] IS INITIAL.
    PERFORM f_insert_log_itab USING gw_upload
                                    'No Data'.
    gv_message = 'No Data'.
    p_return = 'E'.
    RETURN.
  ELSE.
    SELECT * INTO TABLE gt_ztdnsddt010
      FROM ztdnsddt010 FOR ALL ENTRIES IN gt_upload
      WHERE bukrs = gt_upload-bukrs
        AND matnr = gt_upload-matnr
        AND vcr_encrp = gt_upload-vcr_encrp.
    SELECT matnr bismt
      INTO CORRESPONDING FIELDS OF TABLE gt_mara
      FROM mara FOR ALL ENTRIES IN gt_upload
      WHERE matnr = gt_upload-matnr.
  ENDIF.

  DATA: lv_vcr_encrp LIKE gw_upload-vcr_encrp.

  SORT gt_upload BY bukrs matnr.
  SORT gt_ztdnsddt010 BY bukrs matnr.
  CLEAR: lv_amount.
  LOOP AT gt_upload INTO gw_upload.
    READ TABLE gt_mara WITH KEY matnr = gw_upload-matnr.
    IF sy-subrc NE 0.
      CONCATENATE 'Material' gw_upload-matnr 'does not exist' INTO lv_message SEPARATED BY space.
      PERFORM f_insert_log_itab USING gw_upload
                                      lv_message. "'Material does not exist'.
      p_return = 'E'.
    ELSE.
      CLEAR lv_vcr_encrp.
      lv_vcr_encrp = gw_upload-vcr_encrp.
      IF lv_vcr_encrp IS INITIAL.
        CONCATENATE gw_upload-vcr_encrp 'Encryption failed' INTO lv_message SEPARATED BY space.
        PERFORM f_insert_log_itab USING gw_upload
                                        lv_message. "'Encryption failed'.
        p_return = 'E'.
      ELSE.
        READ TABLE gt_ztdnsddt010 WITH KEY bukrs = gw_upload-bukrs
                                           matnr = gw_upload-matnr
                                           vcr_encrp = lv_vcr_encrp
                                           TRANSPORTING NO FIELDS.
        IF sy-subrc = 0.
          CONCATENATE 'Material' gw_upload-matnr 'Duplication record' INTO lv_message SEPARATED BY space.
          PERFORM f_insert_log_itab USING gw_upload
                                          lv_message. "'Duplication record'.
          p_return = 'E'.
        ELSE.
          APPEND INITIAL LINE TO gt_out ASSIGNING <fs_out>.
          MOVE-CORRESPONDING gw_upload TO <fs_out>.
          CLEAR <fs_out>-vcr_encrp.
          <fs_out>-vcr_encrp = lv_vcr_encrp.
          CLEAR: <fs_out>-vcrexp.
          CONCATENATE gw_upload-vcrexp+6(4) gw_upload-vcrexp+3(2) gw_upload-vcrexp(2)
            INTO <fs_out>-vcrexp.
          CLEAR <fs_out>-vcramt.
          <fs_out>-vcramt = gt_mara-bismt.
          DIVIDE <fs_out>-vcramt BY 100.
          <fs_out>-waers = 'IDR'.
          <fs_out>-ernam = sy-uname.
          <fs_out>-erdat = sy-datum.
          <fs_out>-ertim = sy-uzeit.
          <fs_out>-email_cust = gw_upload-email_cust.
          <fs_out>-name_cust = gw_upload-name_cust.
          <fs_out>-pay_date = gw_upload-pay_date.
          TRANSLATE gw_upload-pay_metod TO UPPER CASE.
          <fs_out>-pay_metod = gw_upload-pay_metod.
          lv_amount = lv_amount + <fs_out>-vcramt.
**          PERFORM f_insert_log_itab USING gw_upload
**                                          'Successfully...'.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDLOOP.

  IF gt_out[] IS NOT INITIAL.
    "Write to table
    MODIFY ztdnsddt010 FROM TABLE gt_out.

    "Flag itab for posting FI
    gt_out-flag = 'X'.
    MODIFY gt_out TRANSPORTING flag
                  WHERE flag = space.
  ENDIF.
  "  FIELD-SYMBOLS: <fs_out1> LIKE ztdnsddt010.
  DATA: ls_out LIKE ztdnsddt010.
  DATA: lv_item TYPE i.
  IF p_return NE 'E'.
    PERFORM f_posting_document_fi CHANGING p_return ls_out-belnr.
  ENDIF.
  IF p_return EQ 'E'.
    READ TABLE gt_out INTO ls_out INDEX 1.
    IF ls_out-logno IS INITIAL.
      PERFORM f_get_error_log CHANGING ls_out.
    ENDIF.
    CLEAR: lv_item.
    SORT gt_error BY logit.
    LOOP AT gt_error ASSIGNING <fs_err>. " WHERE type = 'E'.
      lv_item = <fs_err>-logit.
    ENDLOOP.
    LOOP AT gt_outlog ASSIGNING <fs_out>. " WHERE type = 'E'.
      APPEND INITIAL LINE TO gt_error ASSIGNING <fs_err>.
      ADD 1 TO lv_item.
      <fs_err>-bukrs = <fs_out>-bukrs.
      <fs_err>-logno = ls_out-logno.
      <fs_err>-logit = lv_item.
      <fs_err>-message = <fs_out>-vcr_encrp.
      MODIFY ztdnsddt011 FROM <fs_err>.
    ENDLOOP.
    PERFORM send_email_evoucher USING gs_evoucher-order_id gt_error[].
    UPDATE ztdnsddt010 SET logno = <fs_err>-logno
                       WHERE bukrs = <fs_err>-bukrs
                          AND order_id = gs_evoucher-order_id.

    COMMIT WORK AND WAIT.
**    PERFORM f_write_error_log TABLES return
**                              USING <fs_out>.
  ENDIF.

ENDFORM.                    " F_SAVE_TO_VOUCHER
*&---------------------------------------------------------------------*
*&      Form  F_INSERT_LOG_ITAB
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_GW_UPLOAD  text
*      -->P_0301   text
*----------------------------------------------------------------------*
FORM f_insert_log_itab  USING    fu_upload STRUCTURE ztdnsdst004
                                 fu_text.
  MOVE-CORRESPONDING fu_upload TO gt_outlog.

  CLEAR gt_outlog-vcr_encrp.
  gt_outlog-vcr_encrp = fu_text.

  CLEAR: gt_outlog-vcrexp.
  CONCATENATE fu_upload-vcrexp+6(4) fu_upload-vcrexp+3(2) fu_upload-vcrexp(2)
    INTO gt_outlog-vcrexp.

  APPEND gt_outlog.
ENDFORM.                    " F_INSERT_LOG_ITAB
*&---------------------------------------------------------------------*
*&      Form  F_POSTING_DOCUMENT_FI
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM f_posting_document_fi CHANGING p_status p_belnr  TYPE vbeln.
  DATA : obj_type   TYPE bapiache09-obj_type.

  DATA : documentheader TYPE bapiache09,
         accountgl      TYPE STANDARD TABLE OF bapiacgl09,
         currencyamount TYPE STANDARD TABLE OF bapiaccr09,
         extension1     TYPE STANDARD TABLE OF bapiacextc,
         return         TYPE STANDARD TABLE OF bapiret2,
         ls_gl          LIKE LINE OF accountgl,
         ls_ca          LIKE LINE OF currencyamount,
         ls_ex          LIKE LINE OF extension1,
         ls_return      LIKE LINE OF return.
  DATA: lv_order LIKE ztdnsddt010-order_id.
  DATA : lv_buzei     TYPE mseg-buzei,
         lv_netwr     TYPE eine-netpr,
         lv_belnr     LIKE ztdnsddt010-belnr,
         lv_gjahr     LIKE ztdnsddt010-gjahr,
         lv_value(20),
         lv_iderr(40).
  DATA: lv_amount  LIKE gt_out-vcramt.
  DATA: pa_hkont   TYPE bseg-hkont.
  pa_hkont = '0122370000'. " '0113101030'. "
  "  lv_order = gv_no_order.
  CLEAR: p_status, lv_amount, lv_buzei.
  lv_buzei = 1.
  p_status = 'E'.
  CLEAR: documentheader,accountgl[],currencyamount[],
         extension1,return,gt_error[].
**  LOOP AT gt_out ASSIGNING <fs_out>
**                 WHERE flag = 'X'
**                   AND belnr = space
**                   AND gjahr = '0000'.
**    lv_order = <fs_out>-order_id.
**
**  ENDLOOP.
  LOOP AT gt_out ASSIGNING <fs_out>
                 WHERE flag = 'X'
                   AND belnr = space
                   AND gjahr = '0000'.
    "and order_id = no_order.

    CLEAR: lv_netwr,lv_value,lv_iderr.

    obj_type = 'BKPF'.

    documentheader-bus_act     = 'RFBU'.
    documentheader-username    = sy-uname.
    documentheader-comp_code   = <fs_out>-bukrs.
    IF <fs_out>-pay_date IS INITIAL.
      <fs_out>-pay_date  = sy-datum.
    ENDIF.
    documentheader-doc_date    = <fs_out>-pay_date. "sy-datum. "pa_budat.
    documentheader-pstng_date  = <fs_out>-pay_date. "sy-datum. "pa_budat.
    documentheader-doc_type    = 'SA'.
    documentheader-ref_doc_no  = <fs_out>-order_id. "'VOUCHER'.
    documentheader-header_txt  = <fs_out>-order_id. "vcrno.

    ADD 1 TO lv_buzei.
    ls_gl-itemno_acc            = lv_buzei.
    ls_gl-gl_account            = '0399990000'.
    ls_gl-bus_area              = '3800'.
    ls_gl-tax_code              = ''.
    ls_gl-trade_id              = 'OTHERS'.
    ls_gl-alloc_nmbr            = <fs_out>-vcrno.
    CONCATENATE 'VOUCHER' <fs_out>-vcrno INTO ls_gl-item_text
      SEPARATED BY ' - '.
*    ls_gl-material              = <fs_out>-matnr.
*    ls_gl-quantity              = <fs_out>-vcramt.
*    ls_gl-base_uom              = <fs_out>-waers.
    APPEND ls_gl TO accountgl.
    lv_netwr                    = <fs_out>-vcramt.
    lv_amount = lv_amount + <fs_out>-vcramt.
    lv_value                    = lv_netwr.
    TRANSLATE lv_value USING '. '.
    TRANSLATE lv_value USING ',.'.
    CONDENSE lv_value NO-GAPS.

    ls_ca-itemno_acc            = lv_buzei.
    ls_ca-curr_type             = '00'.
    ls_ca-currency              = 'IDR'.
    ls_ca-exch_rate             = ''.
    ls_ca-amt_doccur            = lv_value * -1.
    APPEND ls_ca TO currencyamount.

    ls_ex(3)                = lv_buzei.
    ls_ex+3(2)              = '50'.
    APPEND ls_ex TO extension1.
    lv_order = <fs_out>-order_id.
  ENDLOOP.

  lv_buzei = 1.
  "    ADD 1 TO lv_buzei.
  ls_gl-itemno_acc            = lv_buzei.
  ls_gl-gl_account            = pa_hkont.
  ls_gl-bus_area              = '3800'.
  ls_gl-tax_code              = ''.
  ls_gl-trade_id              = 'OTHERS'.
  ls_gl-alloc_nmbr            = lv_order.
  ls_gl-item_text  = lv_order.
  APPEND ls_gl TO accountgl.

  ls_ca-itemno_acc            = lv_buzei.
  ls_ca-curr_type             = '00'.
  ls_ca-currency              = 'IDR'.
  ls_ca-exch_rate             = ''.
  lv_netwr                    = lv_amount.
  lv_value                    = lv_netwr.
  TRANSLATE lv_value USING '. '.
  TRANSLATE lv_value USING ',.'.
  CONDENSE lv_value NO-GAPS.
  ls_ca-amt_doccur            = lv_value.
  APPEND ls_ca TO currencyamount.

  ls_ex(3)                = lv_buzei.
  ls_ex+3(2)              = '40'.
  APPEND ls_ex TO extension1.

  CALL FUNCTION 'BAPI_ACC_DOCUMENT_POST'
    EXPORTING
      documentheader = documentheader
    IMPORTING
      obj_type       = obj_type
    TABLES
      accountgl      = accountgl
      currencyamount = currencyamount
      extension1     = extension1
      return         = return.

  READ TABLE return INTO ls_return WITH KEY type = 'E'.

  IF sy-subrc = 0.
    PERFORM f_get_error_log CHANGING <fs_out>.
    PERFORM f_write_error_log TABLES return
                              USING <fs_out>.
    p_status = 'E'.
  ELSE.
    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
      EXPORTING
        wait = 'X'.
    CLEAR: p_status.
    READ TABLE return INTO ls_return WITH KEY type   = 'S'
                                              id     = 'RW'
                                              number = '605'.
    TRY.
        lv_belnr = ls_return-message_v2.
        lv_gjahr = ls_return-message_v2+14(4).
        gv_belnr = lv_belnr.
      CATCH cx_sy_dynamic_osql_error.
        MESSAGE `Error in update!` TYPE 'I'.
        p_status = 'E'.
    ENDTRY.
  ENDIF.
  IF  p_status NE 'E'.
    UPDATE ztdnsddt010 SET belnr = lv_belnr
                           gjahr = lv_gjahr
                           logno = <fs_out>-logno
                       WHERE bukrs = <fs_out>-bukrs
                          AND order_id = lv_order.
    "                         AND matnr = <fs_out>-matnr
    "                         AND vcrno = <fs_out>-vcrno
    "                         AND vcr_encrp = <fs_out>-vcr_encrp.
**  ELSE.
**    UPDATE ztdnsddt010 SET logno = <fs_out>-logno
**                       WHERE bukrs = <fs_out>-bukrs
**                          AND order_id = lv_order.

  ENDIF.
ENDFORM.                    " F_POSTING_DOCUMENT_FI

*&---------------------------------------------------------------------*
*&      Form  F_GET_ERROR_LOG
*&---------------------------------------------------------------------*
FORM f_get_error_log  CHANGING fu_out STRUCTURE ztdnsddt010.
  CALL FUNCTION 'NUMBER_GET_NEXT'
    EXPORTING
      nr_range_nr             = '01'
      object                  = 'ZTDNERRLOG'
    IMPORTING
      number                  = fu_out-logno
    EXCEPTIONS
      interval_not_found      = 1
      number_range_not_intern = 2
      object_not_found        = 3
      quantity_is_0           = 4
      quantity_is_not_1       = 5
      interval_overflow       = 6
      buffer_overflow         = 7
      OTHERS                  = 8.
  IF sy-subrc <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CLEAR: fu_out-belnr,fu_out-gjahr.
ENDFORM.                    " F_GET_ERROR_LOG

*&---------------------------------------------------------------------*
*&      Form  F_WRITE_ERROR_LOG
*&---------------------------------------------------------------------*
FORM f_write_error_log  TABLES   ft_return STRUCTURE bapiret2
                        USING    fu_out STRUCTURE ztdnsddt010.
  DATA: ls_return LIKE bapiret2,
        lv_item   TYPE zdg2cade0020.

  LOOP AT ft_return INTO ls_return WHERE type = 'E'.
    APPEND INITIAL LINE TO gt_error ASSIGNING <fs_err>.
    ADD 1 TO lv_item.
    <fs_err>-bukrs = fu_out-bukrs.
    <fs_err>-logno = fu_out-logno.
    <fs_err>-logit = lv_item.
    <fs_err>-message = ls_return-message.
  ENDLOOP.

  INSERT ztdnsddt011 FROM TABLE gt_error.
ENDFORM.                    " F_WRITE_ERROR_LOG
