*----------------------------------------------------------------------*
***INCLUDE LZTDN_APIF05 .
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Form  SEND_EMAIL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_P_SUBMI  text
*----------------------------------------------------------------------*
FORM send_email_tempomart  USING p_message p_table TYPE ANY TABLE..

  DATA: send_request   TYPE REF TO cl_bcs,
        lv_sent_to_all TYPE os_boolean,
        mailsubject    TYPE so_obj_des,
        mailtext       TYPE bcsy_text,
        document       TYPE REF TO cl_document_bcs,
        sender         TYPE REF TO cl_cam_address_bcs,
        recipient_to   TYPE REF TO cl_cam_address_bcs,
        recipient_cc   TYPE REF TO cl_cam_address_bcs,
        recipient_bcc  TYPE REF TO cl_cam_address_bcs,
        bcs_exception  TYPE REF TO cx_bcs.
  DATA: lv_message(150).
  DATA: lv_email TYPE ad_smtpadr. " ADR6-SMTP_ADDR.
  DATA: lt_tvarvc TYPE STANDARD TABLE OF tvarvc WITH HEADER LINE.
  DATA: BEGIN OF lt_body OCCURS 0,
          pesan(100),
        END OF lt_body.
  lt_body[] = p_table[].

  TRY.
      SELECT * INTO CORRESPONDING FIELDS OF TABLE lt_tvarvc FROM tvarvc WHERE name = 'ZTEMPOMART_SHIP'.
      send_request = cl_bcs=>create_persistent( ).
      mailsubject = '[Tempomart-SD]-Shipment start'.
      lv_message = '<br>Error Proses Shimpent Start TempoMart </br>'.
      APPEND lv_message TO mailtext.
      "      lv_message = p_message.
      CONCATENATE '<br>' p_message '</br>' INTO lv_message.
      APPEND lv_message TO mailtext.
      LOOP AT lt_body.
        CONCATENATE '<br>' lt_body-pesan '</br>' INTO lv_message.
        "        lv_message = lt_body-pesan.
        APPEND lv_message TO mailtext.
      ENDLOOP.

      IF lt_tvarvc[] IS INITIAL.
        lv_message = '<br></br><br></br><br>NB: </br>'.
        APPEND lv_message TO mailtext.
        lv_message = '<br>     Penerima email dapat dimaintance di table TVARVC </br>'.
        APPEND lv_message TO mailtext.
        lv_message = '<br>          TVARVC-Name = ZTEMPOMART_SHIP </br>'.
        APPEND lv_message TO mailtext.
        lv_message = '<br>          TVARVC-opti diisi dengan TO/CC/BC </br>'.
        APPEND lv_message TO mailtext.
        lv_message = '<br>          TVARVC-Low diisi dengan email penerima </br>'.
        APPEND lv_message TO mailtext.
      ENDIF.

      lv_message = '<br></br><br></br><br>Terima kasih </br>'.
      APPEND lv_message TO mailtext.
      CONCATENATE '<br></br><br></br><br> Email Auto Generated by System </br> <br> </br> <br> </br> <br>' sy-uname  '</br></P>' INTO lv_message SEPARATED BY space.
      APPEND lv_message TO mailtext.

      document = cl_document_bcs=>create_document(
       i_type = 'HTM'
       i_text = mailtext
       i_subject = mailsubject ).
      send_request->set_document( document ).

      send_request->set_document( document ).
      sender = cl_cam_address_bcs=>create_internet_address( 'hendrian@TheTempoGroup.com' ).
      send_request->set_sender( sender ).

      LOOP AT lt_tvarvc WHERE opti = 'TO'.
        lv_email = lt_tvarvc-low.
        recipient_to = cl_cam_address_bcs=>create_internet_address( lv_email ). "'budi.p@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_to ).
      ENDLOOP.

      LOOP AT lt_tvarvc WHERE opti = 'CC'.
        lv_email = lt_tvarvc-low.
        recipient_cc = cl_cam_address_bcs=>create_internet_address( lv_email ).
        send_request->add_recipient( i_recipient = recipient_cc
        i_copy = 'X' ).
      ENDLOOP.

      LOOP AT lt_tvarvc WHERE opti = 'BC'.
        lv_email = lt_tvarvc-low.
        recipient_bcc = cl_cam_address_bcs=>create_internet_address( lv_email ).
        send_request->add_recipient( i_recipient = recipient_bcc
        i_blind_copy = 'X' ).
      ENDLOOP.


      IF lt_tvarvc[] IS INITIAL.
        recipient_to = cl_cam_address_bcs=>create_internet_address( 'Support.Center@TheTempoGroup.com' ). "'budi.p@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_to ).
        recipient_cc = cl_cam_address_bcs=>create_internet_address( 'nurul.azhar@thetempogroup.com' ).
        send_request->add_recipient( i_recipient = recipient_cc
        i_copy = 'X' ).
        recipient_cc = cl_cam_address_bcs=>create_internet_address( 'amalia.darmayanti@thetempogroup.com' ).
        send_request->add_recipient( i_recipient = recipient_cc
        i_copy = 'X' ).

        recipient_bcc = cl_cam_address_bcs=>create_internet_address( 'hendrian@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_bcc
        i_copy = 'X' ).

      ENDIF.

      lv_sent_to_all = send_request->send( ).
      IF lv_sent_to_all = 'X'.
        "       WRITE: / 'Email sent to all recipients'.
      ELSE.
        "       WRITE: / 'Email could not be sent to all recipients!'.
      ENDIF.

      COMMIT WORK.

    CATCH cx_bcs INTO bcs_exception.
      "    WRITE: 'Error occurred while sending email: Error Type', bcs_exception->error_type.
  ENDTRY.

ENDFORM.                    " SEND_EMAIL



*&---------------------------------------------------------------------*
*&      Form  f_write_message
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_RETURN   text
*      -->P_MESSAGE  text
*----------------------------------------------------------------------*
FORM f_write_message  USING p_return TYPE bapiret2
      CHANGING p_message.
  MESSAGE ID p_return-id TYPE p_return-type
                         NUMBER p_return-number
                           WITH p_return-message_v1
                                p_return-message_v2
                                p_return-message_v3
                                p_return-message_v4
                           INTO p_message.

ENDFORM.                    " WRITE_MESSAGE

*&---------------------------------------------------------------------*
*&      Form  F_CONVERT_JSON_SHIPMENT_START
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_LV_STR  text
*      <--P_GV_STATUS  text
*      <--P_GV_MESSAGE  text
*----------------------------------------------------------------------*
FORM f_convert_json_shipment_start  USING    p_str
                                    CHANGING p_status
                                             p_message.
  TYPES: BEGIN OF ty_list_dn,
           no_shipment_sap TYPE string, ": "5420033970",
           tgl_start       TYPE string, ": "20240805",
           jam_start       TYPE string,                     ": "102050"
         END OF ty_list_dn.
  TYPES: BEGIN OF ty_ship,
           no_shipment_tdn TYPE string,                     ": "1417",
           list_dn         TYPE STANDARD TABLE OF ty_list_dn WITH DEFAULT KEY,
         END OF ty_ship.
  TYPES: BEGIN OF ty_ship_send,
           noshipment       TYPE string,                    ": "1417",
           shipmentstart(1),
         END OF ty_ship_send.

  DATA: ls_ship TYPE ty_ship.
  DATA: ls_ship_send TYPE ty_ship_send.
  DATA: lv_json_data     TYPE string. ",
  DATA: cl_json_data TYPE REF TO zcl_trex_json_serializer.
  DATA: lv_json     TYPE string. ",
  DATA: lv_str TYPE string.
  DATA: ls_list_dn TYPE ty_list_dn.
  DATA: headerdata       LIKE bapishipmentheader,
        headerdataaction LIKE bapishipmentheaderaction,
        return           LIKE bapiret2 OCCURS 0 WITH HEADER LINE,
        ls_return        TYPE bapiret2.
  DATA: lv_nama(15), lv_text(10).
  DATA: lv_message(100).
  DATA: BEGIN OF lt_table OCCURS 0,
          pesan(100),
        END OF lt_table.

  lv_json_data = p_str.
  zcl_json=>deserialize(
        EXPORTING
          json             = lv_json_data
        CHANGING
          data             = ls_ship ).

  CLEAR: p_status, p_message.
  p_status = 'S'.
  CLEAR lt_table[].
  IF ls_ship-no_shipment_tdn IS INITIAL.
    p_message = 'Data tidak ditemukan'.
    p_status = 'E'.
    CONCATENATE 'Shipment no. ' ls_ship-no_shipment_tdn 'tidak ditemukan' INTO lv_message SEPARATED BY space.
    lt_table-pesan = lv_message.
    APPEND lt_table.
    PERFORM send_email_tempomart USING lv_message lt_table[].
  ELSE.
    CONCATENATE 'Shipment TDN no. ' ls_ship-no_shipment_tdn INTO lv_message SEPARATED BY space.
    LOOP AT ls_ship-list_dn INTO ls_list_dn.
      CLEAR: headerdata, headerdataaction, return[], return.
      headerdata-shipment_num = ls_list_dn-no_shipment_sap.
      headerdata-status_shpmnt_start = 'X'.
      headerdataaction-shipment_num = 'X'.
      headerdataaction-status_shpmnt_start = 'C'.
      CALL FUNCTION 'BAPI_SHIPMENT_CHANGE'
        EXPORTING
          headerdata       = headerdata
          headerdataaction = headerdataaction
        TABLES
          return           = return.
      DELETE return[] WHERE type = 'S'.
      CLEAR: lt_table[].
      LOOP AT return INTO ls_return.
        IF ls_return-type = 'E' OR ls_return-type = 'A'.
          IF ls_return-message IS NOT INITIAL.
            p_message = ls_return-message.
            p_status = ls_return-type.
            lt_table-pesan = ls_return-message..
            APPEND lt_table.
          ENDIF.
        ENDIF.
      ENDLOOP.
      CLEAR: ls_ship_send, lv_str.
      ls_ship_send-noshipment = ls_list_dn-no_shipment_sap.
      IF lt_table[] IS NOT INITIAL.
        PERFORM send_email_tempomart USING lv_message lt_table[].
        ls_ship_send-shipmentstart = 'E'.
      ELSE.
        ls_ship_send-shipmentstart = 'X'.
      ENDIF.

      CREATE OBJECT cl_json_data
        EXPORTING
          data = ls_ship_send.
      cl_json_data->serialize( ).
      lv_json = cl_json_data->get_data( ).
      PERFORM f_post_data_json(ztdsit_i001) USING lv_json 'TMART_SHIPSTART' sy-subrc lv_str.
      lv_nama = ls_ship_send-noshipment.
      CONCATENATE 'POST_' lv_nama INTO lv_nama.
      PERFORM f_create_text_json(ztdsit_i001) USING lv_json lv_nama '/inbound/TDN/' 'TMART_SHIPSTART'.
    ENDLOOP.
  ENDIF.
  lv_nama = ls_ship-no_shipment_tdn.
  CONCATENATE 'Sh_TM_' lv_nama INTO lv_nama.
  PERFORM f_create_text_json(ztdsit_i001) USING p_str lv_nama '/inbound/TDN/' 'TMART_SHIPSTART'.
ENDFORM.                    " F_CONVERT_JSON_SHIPMENT_START
