PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTDNSDDT022 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTDNSDDT022-BSTKD .
    FIELD ZTDNSDDT022-KODE_MP .
    FIELD ZTDNSDDT022-KODE_SHOP .
    FIELD ZTDNSDDT022-ZNOTRANS .
    FIELD ZTDNSDDT022-VBELN .
    FIELD ZTDNSDDT022-ZPAGE .
    FIELD ZTDNSDDT022-NO_AWB .
    FIELD ZTDNSDDT022-ERDAT .
    FIELD ZTDNSDDT022-ERZET .
    FIELD ZTDNSDDT022-ERNAM .
    FIELD ZTDNSDDT022-ZMESSAGE .
    FIELD ZTDNSDDT022-STATUS .
    FIELD ZTDNSDDT022-NOSPOOL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTDNSDDT022-BSTKD .
    FIELD ZTDNSDDT022-KODE_MP .
    FIELD ZTDNSDDT022-KODE_SHOP .
    FIELD ZTDNSDDT022-ZNOTRANS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
