PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTDNFIDT005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTDNFIDT005-NO_ORDER .
    FIELD ZTDNFIDT005-KDACCT .
    FIELD ZTDNFIDT005-ORDER_DATE .
    FIELD ZTDNFIDT005-ERDAT .
    FIELD ZTDNFIDT005-ERZET .
    FIELD ZTDNFIDT005-ORDER_TYPE .
    FIELD ZTDNFIDT005-BAYAR_VIA .
    FIELD ZTDNFIDT005-PAY_DATE .
    FIELD ZTDNFIDT005-AMOUNT_VALUE .
    FIELD ZTDNFIDT005-NO_DN .
    FIELD ZTDNFIDT005-NO_BILL .
    FIELD ZTDNFIDT005-BELNR1 .
    FIELD ZTDNFIDT005-BUDAT .
    FIELD ZTDNFIDT005-BELNR2 .
    FIELD ZTDNFIDT005-AUGDT .
    FIELD ZTDNFIDT005-STATUS .
    FIELD ZTDNFIDT005-ZUONR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTDNFIDT005-NO_ORDER .
    FIELD ZTDNFIDT005-KDACCT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
