FUNCTION ztdsit_f0003.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(MAILSUBJECT) TYPE  SO_OBJ_DES
*"     VALUE(VARIANNAME) TYPE  RVARI_VNAM
*"     REFERENCE(EMAILSENDER) TYPE  SO_REC_EXT
*"  TABLES
*"      BODY_MAIL STRUCTURE  SOLI OPTIONAL
*"----------------------------------------------------------------------

  DATA: send_request TYPE REF TO cl_bcs,
        lv_sent_to_all TYPE os_boolean,
        lv_mailsubject TYPE so_obj_des,
        lv_mailtext TYPE bcsy_text,
        document TYPE REF TO cl_document_bcs,
        sender TYPE REF TO cl_cam_address_bcs,
        recipient_to TYPE REF TO cl_cam_address_bcs,
        recipient_cc TYPE REF TO cl_cam_address_bcs,
        recipient_bcc TYPE REF TO cl_cam_address_bcs,
        bcs_exception TYPE REF TO cx_bcs.
  DATA: lv_email TYPE ad_smtpadr. " ADR6-SMTP_ADDR.

  DATA: lv_message(150).
  "  DATA: lv_email TYPE ad_smtpadr. " ADR6-SMTP_ADDR.
  DATA: lt_tvarvc TYPE STANDARD TABLE OF tvarvc WITH HEADER LINE.
  DATA: lt_body TYPE STANDARD TABLE OF soli WITH HEADER LINE.

  lt_body[] = body_mail[].

  TRY.
      SELECT * INTO CORRESPONDING FIELDS OF TABLE lt_tvarvc FROM tvarvc WHERE name = varianname.
      send_request = cl_bcs=>create_persistent( ).
      lv_mailsubject = mailsubject.
      LOOP AT lt_body.
        CONCATENATE '<br>' lt_body-line '</br>' INTO lv_message.
        APPEND lv_message TO lv_mailtext.
      ENDLOOP.

      IF lt_tvarvc[] IS INITIAL.
        lv_message = '<br></br><br></br><br>NB: </br>'.
        APPEND lv_message TO lv_mailtext.
        lv_message = '<br>     Penerima email dapat dimaintance di table TVARVC </br>'.
        APPEND lv_message TO lv_mailtext.
        CONCATENATE '<br>          TVARVC-Name = ' varianname '</br>' INTO lv_message SEPARATED BY space.
        APPEND lv_message TO lv_mailtext.
        lv_message = '<br>          TVARVC-opti diisi dengan TO/CC/BC </br>'.
        APPEND lv_message TO lv_mailtext.
        lv_message = '<br>          TVARVC-Low diisi dengan email penerima </br>'.
        APPEND lv_message TO lv_mailtext.
      ENDIF.
      lv_message = '<br></br><br></br><br>Terima kasih </br>'.
      APPEND lv_message TO lv_mailtext.
      CONCATENATE '<br></br><br></br><br> Email Auto Generated by System </br> <br> </br> <br> </br> <br>' sy-uname  '</br></P>' INTO lv_message SEPARATED BY space.
      APPEND lv_message TO lv_mailtext.

      document = cl_document_bcs=>create_document(
       i_type = 'HTM'
       i_text = lv_mailtext
       i_subject = lv_mailsubject ).
      IF emailsender IS INITIAL.
        lv_email = 'Support.Center@TheTempoGroup.com'.
      ELSE.
        lv_email = emailsender.
      ENDIF.
      send_request->set_document( document ).
      send_request->set_document( document ).
      sender = cl_cam_address_bcs=>create_internet_address( lv_email ).
      send_request->set_sender( sender ).
      LOOP AT lt_tvarvc WHERE opti = 'TO'.
        lv_email = lt_tvarvc-low.
        recipient_to = cl_cam_address_bcs=>create_internet_address( lv_email ). "'budi.p@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_to ).
      ENDLOOP.
      LOOP AT lt_tvarvc WHERE opti = 'CC'.
        lv_email = lt_tvarvc-low.
        recipient_cc = cl_cam_address_bcs=>create_internet_address( lv_email ).
        send_request->add_recipient( i_recipient = recipient_cc
        i_copy = 'X' ).
      ENDLOOP.
      LOOP AT lt_tvarvc WHERE opti = 'BC'.
        lv_email = lt_tvarvc-low.
        recipient_bcc = cl_cam_address_bcs=>create_internet_address( lv_email ).
        send_request->add_recipient( i_recipient = recipient_bcc
        i_blind_copy = 'X' ).
      ENDLOOP.
      IF lt_tvarvc[] IS INITIAL.
        recipient_to = cl_cam_address_bcs=>create_internet_address( 'Support.Center@TheTempoGroup.com' ). "'budi.p@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_to ).
        recipient_cc = cl_cam_address_bcs=>create_internet_address( 'Support.Center@TheTempoGroup.com' ).
        send_request->add_recipient( i_recipient = recipient_cc
        i_copy = 'X' ).
      ENDIF.
      lv_sent_to_all = send_request->send( ).
      IF lv_sent_to_all = 'X'.
      ELSE.
      ENDIF.
      COMMIT WORK.
    CATCH cx_bcs INTO bcs_exception.
      "    WRITE: 'Error occurred while sending email: Error Type', bcs_exception->error_type.
  ENDTRY.

ENDFUNCTION.
