*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTGTSLSTOP.                       " Global Data
  INCLUDE LZTGTSLSUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTGTSLSF00                             . " subprograms
  INCLUDE LZTGTSLSI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTGTSLSF...                       " Subprograms
* INCLUDE LZTGTSLSO...                       " PBO-Modules
* INCLUDE LZTGTSLSI...                       " PAI-Modules
