*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTKMSDDT002TOP.                   " Global Data
  INCLUDE LZTKMSDDT002UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTKMSDDT002F00                         . " subprograms
  INCLUDE LZTKMSDDT002I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTKMSDDT002F...                   " Subprograms
* INCLUDE LZTKMSDDT002O...                   " PBO-Modules
* INCLUDE LZTKMSDDT002I...                   " PAI-Modules

INCLUDE LZTKMSDDT002I01.
