PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTNPWM001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTNPWM001-LGNUM .
    FIELD ZTNPWM001-TANUM .
    FIELD ZTNPWM001-TAPOS .
    FIELD ZTNPWM001-MATNR .
    FIELD ZTNPWM001-CHARG .
    FIELD ZTNPWM001-MEINS .
    FIELD ZTNPWM001-NISTA .
    FIELD ZTNPWM001-NDIFM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTNPWM001-LGNUM .
    FIELD ZTNPWM001-TANUM .
    FIELD ZTNPWM001-TAPOS .
    FIELD ZTNPWM001-MATNR .
    FIELD ZTNPWM001-CHARG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
