*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTNPWM001TOP.                     " Global Data
  INCLUDE LZTNPWM001UXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTNPWM001F00                           . " subprograms
  INCLUDE LZTNPWM001I00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTNPWM001F...                     " Subprograms
* INCLUDE LZTNPWM001O...                     " PBO-Modules
* INCLUDE LZTNPWM001I...                     " PAI-Modules
