*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTR_RATE_MSTTOP.                  " Global Data
  INCLUDE LZTR_RATE_MSTUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTR_RATE_MSTF00                        . " subprograms
  INCLUDE LZTR_RATE_MSTI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTR_RATE_MSTF...                  " Subprograms
* INCLUDE LZTR_RATE_MSTO...                  " PBO-Modules
* INCLUDE LZTR_RATE_MSTI...                  " PAI-Modules
