*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTR_REVENUE_MSTTOP.               " Global Data
  INCLUDE LZTR_REVENUE_MSTUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTR_REVENUE_MSTF00                     . " subprograms
  INCLUDE LZTR_REVENUE_MSTI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTR_REVENUE_MSTF...               " Subprograms
* INCLUDE LZTR_REVENUE_MSTO...               " PBO-Modules
* INCLUDE LZTR_REVENUE_MSTI...               " PAI-Modules
