*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTSPFIDT02TOP.                    " Global Data
  INCLUDE LZTSPFIDT02UXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTSPFIDT02F00                          . " subprograms
  INCLUDE LZTSPFIDT02I00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTSPFIDT02F...                    " Subprograms
* INCLUDE LZTSPFIDT02O...                    " PBO-Modules
* INCLUDE LZTSPFIDT02I...                    " PAI-Modules
