PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPPPDT003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPPPDT003-AUFNR .
    FIELD ZTSPPPDT003-PLNBEZ .
    FIELD ZTSPPPDT003-FCHARG .
    FIELD ZTSPPPDT003-RSNUM .
    FIELD ZTSPPPDT003-RSPOS .
    FIELD ZTSPPPDT003-MATNR .
    FIELD ZTSPPPDT003-CHARG .
    FIELD ZTSPPPDT003-VORNR .
    FIELD ZTSPPPDT003-WERKS .
    FIELD ZTSPPPDT003-LGORT .
    FIELD ZTSPPPDT003-BDMNG .
    FIELD ZTSPPPDT003-MEINS .
    FIELD ZTSPPPDT003-SHKZG .
    FIELD ZTSPPPDT003-ENMNG .
    FIELD ZTSPPPDT003-KZEAR .
    FIELD ZTSPPPDT003-OPERATOR .
    FIELD ZTSPPPDT003-ERDAT .
    FIELD ZTSPPPDT003-ERZET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPPPDT003-AUFNR .
    FIELD ZTSPPPDT003-PLNBEZ .
    FIELD ZTSPPPDT003-FCHARG .
    FIELD ZTSPPPDT003-RSNUM .
    FIELD ZTSPPPDT003-RSPOS .
    FIELD ZTSPPPDT003-MATNR .
    FIELD ZTSPPPDT003-CHARG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
