*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTSPPPDT007DTOP.                  " Global Data
  INCLUDE LZTSPPPDT007DUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTSPPPDT007DF00                        . " subprograms
  INCLUDE LZTSPPPDT007DI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTSPPPDT007DF...                  " Subprograms
* INCLUDE LZTSPPPDT007DO...                  " PBO-Modules
* INCLUDE LZTSPPPDT007DI...                  " PAI-Modules
