*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTSPMDHAZCOMTOP.                  " Global Data
  INCLUDE LZTSPMDHAZCOMUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTSPMDHAZCOMF00                        . " subprograms
  INCLUDE LZTSPMDHAZCOMI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTSPMDHAZCOMF...                  " Subprograms
* INCLUDE LZTSPMDHAZCOMO...                  " PBO-Modules
* INCLUDE LZTSPMDHAZCOMI...                  " PAI-Modules
