PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPPPDT011 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPPPDT011-RSNUM .
    FIELD ZTSPPPDT011-RSPOS .
    FIELD ZTSPPPDT011-RSART .
    FIELD ZTSPPPDT011-ZEILE .
    FIELD ZTSPPPDT011-AUFNR .
    FIELD ZTSPPPDT011-POSNR .
    FIELD ZTSPPPDT011-MATNR .
    FIELD ZTSPPPDT011-WERKS .
    FIELD ZTSPPPDT011-LGORT .
    FIELD ZTSPPPDT011-CHARG .
    FIELD ZTSPPPDT011-ERFMG .
    FIELD ZTSPPPDT011-ERFME .
    FIELD ZTSPPPDT011-VORNR .
    FIELD ZTSPPPDT011-LTXA1 .
    FIELD ZTSPPPDT011-SORTF .
    FIELD ZTSPPPDT011-PHSEQ .
    FIELD ZTSPPPDT011-WBOOTH .
    FIELD ZTSPPPDT011-OPERATOR .
    FIELD ZTSPPPDT011-PENGAWAS .
    FIELD ZTSPPPDT011-ERDAT .
    FIELD ZTSPPPDT011-ERTIM .
    FIELD ZTSPPPDT011-SCANFL .
    FIELD ZTSPPPDT011-SCANDT .
    FIELD ZTSPPPDT011-SCANTM .
    FIELD ZTSPPPDT011-MBLNR .
    FIELD ZTSPPPDT011-MJAHR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPPPDT011-RSNUM .
    FIELD ZTSPPPDT011-RSPOS .
    FIELD ZTSPPPDT011-RSART .
    FIELD ZTSPPPDT011-ZEILE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
