PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPPPDT007 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPPPDT007-WERKS .
    FIELD ZTSPPPDT007-AFIND .
    FIELD ZTSPPPDT007-AFINU .
    FIELD ZTSPPPDT007-MATNR .
    FIELD ZTSPPPDT007-MAKTX .
    FIELD ZTSPPPDT007-CHARG .
    FIELD ZTSPPPDT007-WBOOTH .
    FIELD ZTSPPPDT007-EQUNR .
    FIELD ZTSPPPDT007-SHTXT .
    FIELD ZTSPPPDT007-ASTAD .
    FIELD ZTSPPPDT007-ASTAU .
    FIELD ZTSPPPDT007-BRUTO .
    FIELD ZTSPPPDT007-TARA .
    FIELD ZTSPPPDT007-NETTO .
    FIELD ZTSPPPDT007-MEINS .
    FIELD ZTSPPPDT007-LGORT .
    FIELD ZTSPPPDT007-AUFNR .
    FIELD ZTSPPPDT007-PHSEQ .
    FIELD ZTSPPPDT007-OPERATOR .
    FIELD ZTSPPPDT007-PENGAWAS .
    FIELD ZTSPPPDT007-WGTTXT .
    FIELD ZTSPPPDT007-VORNR .
    FIELD ZTSPPPDT007-SCANFL .
    FIELD ZTSPPPDT007-SCANDT .
    FIELD ZTSPPPDT007-SCANTM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPPPDT007-WERKS .
    FIELD ZTSPPPDT007-AFIND .
    FIELD ZTSPPPDT007-AFINU .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
