PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPPPDT007D CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPPPDT007D-WERKS .
    FIELD ZTSPPPDT007D-AFIND .
    FIELD ZTSPPPDT007D-AFINU .
    FIELD ZTSPPPDT007D-POSNR .
    FIELD ZTSPPPDT007D-CHARG .
    FIELD ZTSPPPDT007D-NETTO .
    FIELD ZTSPPPDT007D-MEINS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPPPDT007D-WERKS .
    FIELD ZTSPPPDT007D-AFIND .
    FIELD ZTSPPPDT007D-AFINU .
    FIELD ZTSPPPDT007D-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
