PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPPPDT014 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPPPDT014-AUFNR .
    FIELD ZTSPPPDT014-VORNR .
    FIELD ZTSPPPDT014-ACTWH .
    FIELD ZTSPPPDT014-WADAH .
    FIELD ZTSPPPDT014-EQUNR .
    FIELD ZTSPPPDT014-ARBPL .
    FIELD ZTSPPPDT014-BRUTO .
    FIELD ZTSPPPDT014-TARA .
    FIELD ZTSPPPDT014-NETTO .
    FIELD ZTSPPPDT014-MEINS .
    FIELD ZTSPPPDT014-TEMPT .
    FIELD ZTSPPPDT014-TEMME .
    FIELD ZTSPPPDT014-MOIST .
    FIELD ZTSPPPDT014-MOIME .
    FIELD ZTSPPPDT014-EXPDT .
    FIELD ZTSPPPDT014-EXPTM .
    FIELD ZTSPPPDT014-OPERATOR .
    FIELD ZTSPPPDT014-PENGAWAS .
    FIELD ZTSPPPDT014-ERDAT .
    FIELD ZTSPPPDT014-ERTIM .
    FIELD ZTSPPPDT014-TWADAH .
    FIELD ZTSPPPDT014-SCANFL .
    FIELD ZTSPPPDT014-ROOMS .
    FIELD ZTSPPPDT014-DATEF .
    FIELD ZTSPPPDT014-TIMEF .
    FIELD ZTSPPPDT014-LOTNR .
    FIELD ZTSPPPDT014-SCANDT .
    FIELD ZTSPPPDT014-SCANTM .
    FIELD ZTSPPPDT014-FLGHO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPPPDT014-AUFNR .
    FIELD ZTSPPPDT014-VORNR .
    FIELD ZTSPPPDT014-ACTWH .
    FIELD ZTSPPPDT014-WADAH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
