*&---------------------------------------------------------------------*
*&  Include           ZTSPPP_EX01TOP
*&---------------------------------------------------------------------*
TYPES : BEGIN OF ty_order,
          werks     TYPE aufk-werks,
          plnbez    TYPE afko-plnbez,
          fcharg    TYPE resb-charg,
          gstrp     TYPE afko-gstrp,
          aufnr     TYPE afko-aufnr,
          objnr     TYPE aufk-objnr,
          posnr     TYPE afpo-posnr,
          cmatnr(100),
          matnr     TYPE resb-matnr,
          charg     TYPE resb-charg,
          count(20),
          qty(20),
          maktx     TYPE makt-maktx,
          rmein     TYPE mara-meins,
          packq     TYPE resb-bdmng,
          clabs     TYPE mchb-clabs,
          sisa      TYPE mchb-clabs,
          total     TYPE mchb-clabs,
          bdmng     TYPE resb-bdmng,
          from      TYPE rspos,
          to        TYPE rspos,
          select    TYPE rspos,
          message(125),
        END OF ty_order.

TYPES : BEGIN OF ty_operation,
          aufnr     TYPE afko-aufnr,
          rsnum     TYPE resb-rsnum,
          rspos     TYPE resb-rspos,
          matnr     TYPE resb-matnr,
          charg     TYPE resb-charg,
          lgort     TYPE resb-lgort,
          vornr     TYPE resb-vornr,
          ltxa1     TYPE afvc-ltxa1,
          clabs     TYPE mchb-clabs,
          meins     TYPE resb-meins,
          bdmng     TYPE resb-bdmng,
          erfmg     TYPE resb-erfmg,
        END OF ty_operation.

TYPES : BEGIN OF ty_weight,
          operator(50),
          pengawas(50),
          aufnr   TYPE caufv-aufnr,
          werks   TYPE caufv-werks,
          fgmat   TYPE mara-matnr,
          fgktx   TYPE makt-maktx,
          charg   TYPE mch1-charg,
          equnr   TYPE equi-equnr,
          shtxt   TYPE itob-shtxt,
          rmmat   TYPE mara-matnr,
          rmktx   TYPE makt-maktx,
          meins   TYPE mara-meins,
          vornr   TYPE resb-vornr,
          posnr   TYPE resb-posnr,
          ltxa1   TYPE afvc-ltxa1,
          bdmng   TYPE resb-bdmng,
          vrkme   TYPE resb-meins,
          scandt  TYPE datum,
          scantm  TYPE uzeit,
          strdat  TYPE datum,
          strtim  TYPE uzeit,
          findat  TYPE datum,
          fintim  TYPE uzeit,
          valdat  TYPE datum,
          valtim  TYPE uzeit,
          matdat  TYPE datum,
          mattim  TYPE uzeit,
          start   TYPE char20,
          finish  TYPE char20,
          lastmat TYPE char40,
          lastbat TYPE char10,
          matdes  TYPE char50,
          santol  TYPE char50,
          wb(100),
          material(100),
          message(100),
        END OF ty_weight.

TYPES : BEGIN OF ty_rawmat,
          rsnum   TYPE resb-rsnum,
          rspos   TYPE resb-rspos,
          matnr   TYPE mara-matnr,
          charg   TYPE mch1-charg,
          meins   TYPE mara-meins,
          clabs   TYPE mard-labst,
          bdmng   TYPE resb-bdmng,
          enmng   TYPE resb-enmng,
          enmng2  TYPE resb-enmng,
          bdmng2  TYPE resb-bdmng,
          meanval TYPE bapi2045d2-mean_value,
          meantyp(1),
        END OF ty_rawmat.

DATA : gs_weight         TYPE ty_weight,
       gt_component      TYPE STANDARD TABLE OF resb,
       gt_mchb           TYPE STANDARD TABLE OF mchb,
       gt_mch1           TYPE STANDARD TABLE OF mch1,
       gt_002            TYPE STANDARD TABLE OF ztnpppdt002,
       gt_003            TYPE STANDARD TABLE OF ztspppdt003,
       gt_006            TYPE STANDARD TABLE OF ztspppdt006,
       gt_rawmat         TYPE STANDARD TABLE OF ty_rawmat,
       gs_rawmat         LIKE LINE OF gt_rawmat,
       gt_marm           TYPE STANDARD TABLE OF marm.

DATA : idx   TYPE i,
       line  TYPE i,
       lines TYPE i,
       limit TYPE i,
       c     TYPE i,
       n1    TYPE i VALUE 1,
       n2    TYPE i.

DATA : ok_code          TYPE sy-ucomm,
       gv_uri_addr      TYPE adr12-uri_addr,
       gv_print_dest    TYPE adr10-print_dest,
       gv_eqfnr         TYPE iloa-eqfnr,
       gv_remark        TYPE adrt-remark,
       gv_matnr         TYPE mch1-matnr,
       gv_charg         TYPE mch1-charg,
       gv_lgort         TYPE resb-lgort,
       gv_bruto         TYPE resb-bdmng,
       gv_tara          TYPE resb-bdmng,
       gv_netto         TYPE resb-bdmng,
       gv_tmein         TYPE mara-meins,
       gv_nmein         TYPE mara-meins,
       gv_meins         TYPE mara-meins,
       gv_weight,
       gv_index         TYPE i,
       gv_print, gv_minmax,
       gv_char          TYPE zchar1500,
       gv_reprint,
       gv_meanval       TYPE bapi2045d2-mean_value,
*       gv_ppifa,
       gv_order         TYPE i,
       gv_authorization,
       gv_istad         TYPE sy-datum,
       gv_istau         TYPE sy-uzeit,
       gv_meanval2      TYPE bapi2045d2-mean_value.

DATA : gt_order         TYPE STANDARD TABLE OF ty_order,
       gt_xorder        TYPE STANDARD TABLE OF ty_order,
       gt_resb          TYPE STANDARD TABLE OF resb,
       gt_xresb         TYPE STANDARD TABLE OF resb,
       gt_yresb         TYPE STANDARD TABLE OF resb,
       gs_order         LIKE LINE OF gt_order,
       gt_afpo          TYPE STANDARD TABLE OF afpo,
       gt_afvc          TYPE STANDARD TABLE OF afvc,
       gs_head          TYPE ty_order,
       gt_operation     TYPE STANDARD TABLE OF ty_operation,
       gt_xoperation    TYPE STANDARD TABLE OF ty_operation,
       gs_operation     LIKE LINE OF gt_operation,
       gt_label         TYPE STANDARD TABLE OF ztspppst004,
       gt_batch         TYPE STANDARD TABLE OF ztspppst004,
       gt_mard          TYPE STANDARD TABLE OF mard,
       gt_item          TYPE STANDARD TABLE OF ty_operation,
       gt_stpo          TYPE STANDARD TABLE OF stpo.

DATA : gt_iresb         TYPE STANDARD TABLE OF resb,
       gt_uresb         TYPE STANDARD TABLE OF resb,
       gt_onr00         TYPE STANDARD TABLE OF onr00,
       gt_jest          TYPE STANDARD TABLE OF jest,
       gt_jsto          TYPE STANDARD TABLE OF jsto.

DATA : gr_sttxt         TYPE RANGE OF sttxt.

DATA : gv_operator(100),
       gv_ouser(100),
       gv_oname(30),
       gv_onrp(30),
       gv_opass(6),
       gv_pengawas(100),
       gv_wuser(100),
       gv_wname(30),
       gv_wnrp(30),
       gv_wpass(6),
       gv_ocheck,
       gv_wcheck,
       gv_message(100),
       gv_subrc     TYPE sy-subrc,
       gv_pass,
       gv_261       TYPE resb-bwart VALUE '261'.

DATA : gv_pengawass(100),
       gv_wusers(100),
       gv_wnames(30),
       gv_wnrps(30),
       gv_wpasss(6).

DATA : gv_npass,
       gv_dispw,
       gv_nweig.

"Sanitasi
DATA : gs_weights       TYPE ty_weight,
       gt_sanitasi      TYPE STANDARD TABLE OF ztspppst004,
       gs_sanitasi      LIKE LINE OF gt_sanitasi,
       gt_ztspppdt009   TYPE STANDARD TABLE OF ztspppdt009,
       gs_ztspppdt009   LIKE LINE OF gt_ztspppdt009,
       gs_ztspppdt007   LIKE ztspppdt007,
       gs_zppresb_add   LIKE zppresb_add,
       gv_valid         TYPE i VALUE 72,
       gv_mat_sanitasi  TYPE char100,
       gv_err_sanitasi  TYPE char100,
       gv_sanitasi, gv_tools.
