PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPPPDT009 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPPPDT009-WERKS .
    FIELD ZTSPPPDT009-AFIND .
    FIELD ZTSPPPDT009-AFINU .
    FIELD ZTSPPPDT009-EQUNR .
    FIELD ZTSPPPDT009-SHTXT .
    FIELD ZTSPPPDT009-WBOOTH .
    FIELD ZTSPPPDT009-MATNR .
    FIELD ZTSPPPDT009-MAKTX .
    FIELD ZTSPPPDT009-CHARG .
    FIELD ZTSPPPDT009-ASTAD .
    FIELD ZTSPPPDT009-ASTAU .
    FIELD ZTSPPPDT009-AVALD .
    FIELD ZTSPPPDT009-AVALU .
    FIELD ZTSPPPDT009-OPERATOR .
    FIELD ZTSPPPDT009-PENGAWAS .
    FIELD ZTSPPPDT009-AUFNR .
    FIELD ZTSPPPDT009-LTXA1 .
    FIELD ZTSPPPDT009-SANTX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPPPDT009-WERKS .
    FIELD ZTSPPPDT009-AFIND .
    FIELD ZTSPPPDT009-AFINU .
    FIELD ZTSPPPDT009-EQUNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
