PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPMMDT006 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPMMDT006-WERKS .
    FIELD ZTSPMMDT006-LGORT .
    FIELD ZTSPMMDT006-IVNUM .
    FIELD ZTSPMMDT006-IVPOS .
    FIELD ZTSPMMDT006-MATNR .
    FIELD ZTSPMMDT006-CHARG .
    FIELD ZTSPMMDT006-MEINS .
    FIELD ZTSPMMDT006-LABST .
    FIELD ZTSPMMDT006-MENGE .
    FIELD ZTSPMMDT006-KZNUL .
    FIELD ZTSPMMDT006-PIDRES .
    FIELD ZTSPMMDT006-MBLNR .
    FIELD ZTSPMMDT006-MJAHR .
    FIELD ZTSPMMDT006-QDATU .
    FIELD ZTSPMMDT006-QZEIT .
    FIELD ZTSPMMDT006-QNAME .
    FIELD ZTSPMMDT006-APDAT .
    FIELD ZTSPMMDT006-APZET .
    FIELD ZTSPMMDT006-APNAM .
    FIELD ZTSPMMDT006-RJDAT .
    FIELD ZTSPMMDT006-RJZET .
    FIELD ZTSPMMDT006-RJNAM .
    FIELD ZTSPMMDT006-LOEKZ .
    FIELD ZTSPMMDT006-STKTYP .
    FIELD ZTSPMMDT006-CINSM .
    FIELD ZTSPMMDT006-CSPEM .
    FIELD ZTSPMMDT006-NOTGI .
    FIELD ZTSPMMDT006-QTY311 .
    FIELD ZTSPMMDT006-APDAT_PRDM .
    FIELD ZTSPMMDT006-APZET_PRDM .
    FIELD ZTSPMMDT006-APNAM_PRDM .
    FIELD ZTSPMMDT006-RJDAT_PRDM .
    FIELD ZTSPMMDT006-RJZET_PRDM .
    FIELD ZTSPMMDT006-RJNAM_PRDM .
    FIELD ZTSPMMDT006-GJAHR .
    FIELD ZTSPMMDT006-DOCTYP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPMMDT006-WERKS .
    FIELD ZTSPMMDT006-LGORT .
    FIELD ZTSPMMDT006-IVNUM .
    FIELD ZTSPMMDT006-IVPOS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
