*&---------------------------------------------------------------------*
*&  Include           ZTSPMM_E004TOP
*&---------------------------------------------------------------------*
TABLES : vttk, ztspmmdt006, sscrfields.

TYPES : BEGIN OF ty_out,
          mark,
          icon(4),
          apr_prdm(4),
          appro(4),
          werks       TYPE ztspmmdt006-werks,
          lgort       TYPE ztspmmdt006-lgort,
          ivnum       TYPE ztspmmdt006-ivnum,
          ivpos       TYPE ztspmmdt006-ivpos,
          matnr       TYPE ztspmmdt006-matnr,
          maktx       TYPE makt-maktx,
          charg       TYPE ztspmmdt006-charg,
          qdatu       TYPE ztspmmdt006-qdatu,
          meins       TYPE ztspmmdt006-meins,
          labst       TYPE ztspmmdt006-labst,
          menge       TYPE ztspmmdt006-menge,
          kznul       TYPE ztspmmdt006-kznul,
          pidres      TYPE ztspmmdt007-pidres,
          pidtxt      TYPE ztspmmdt007-pidtxt,
          mblnr       TYPE ztspmmdt006-mblnr,
          mjahr       TYPE ztspmmdt006-mjahr,
          zeile       TYPE mseg-zeile,
          budat       TYPE mkpf-budat,
          diffm       TYPE ztspmmdt006-menge,
          diffp       TYPE ztspmmdt006-menge,
          3meng       TYPE mseg-menge,
          7meng       TYPE mseg-menge,
          pmeng       TYPE p DECIMALS 2,
          value       TYPE ztspmmdt006-menge,   "mbew-stprs,
          waers       TYPE t001-waers,
          datum       TYPE sy-datum,
          uname       TYPE sy-uname,
          shkzg       TYPE mseg-shkzg,
          stktyp      TYPE char10,
          notgi       TYPE ztspmmdt006-notgi,
          total       TYPE ztspmmdt006-notgi,
          qty311      TYPE ztspmmdt006-qty311,
          qty311%     TYPE zpercen,
          gjahr       TYPE gjahr,
          doctyp      TYPE zdoctyp,
          style       TYPE lvc_t_styl,
          color       TYPE lvc_t_scol,
        END OF ty_out.

CLASS : lcl_application DEFINITION DEFERRED.

DATA : ok_code          TYPE sy-ucomm,
       gs_exclude       TYPE ui_functions,
       g_customcont     TYPE REF TO cl_gui_custom_container,
       g_splitter       TYPE REF TO cl_gui_splitter_container,
       g_splitter1      TYPE REF TO cl_gui_splitter_container,
       g_contain01      TYPE REF TO cl_gui_container,
       g_tabgrid        TYPE REF TO cl_gui_alv_grid,
       event_receiver   TYPE REF TO lcl_application,
       selected         VALUE 'X',
       gv_repid         LIKE sy-repid,
       gs_variant       LIKE disvariant,
       gs_layout_alv    TYPE lvc_s_layo,
       gt_main_sort     TYPE lvc_t_sort WITH HEADER LINE,
       gt_main_fieldcat TYPE lvc_t_fcat,
       gs_stable        TYPE lvc_s_stbl,
       gs_toolbar       TYPE stb_button,
       gr_hierseq       TYPE REF TO cl_salv_hierseq_table,
       gr_table         TYPE REF TO cl_salv_table,
       g_handle_alv     TYPE i,
       gt_bapiret2      TYPE STANDARD TABLE OF bapiret2.

DATA : gt_out        TYPE STANDARD TABLE OF ty_out,
       gt_post       TYPE STANDARD TABLE OF ty_out,
       gt_appr       TYPE STANDARD TABLE OF ty_out,
       gt_rjct       TYPE STANDARD TABLE OF ty_out,
       gt_006        TYPE STANDARD TABLE OF ztspmmdt006,
       gt_007        TYPE STANDARD TABLE OF ztspmmdt007,
       gv_usergroup  TYPE bapigroups-usergroup,
       gt_values_tab TYPE STANDARD TABLE OF dd07v,
       gt_pid        TYPE STANDARD TABLE OF ty_out,
       gt_mail       TYPE STANDARD TABLE OF zmail,
       gt_makt       TYPE STANDARD TABLE OF makt,
       gt_mbew       TYPE STANDARD TABLE OF mbew,
       gt_mkpf       TYPE STANDARD TABLE OF mkpf,
       gt_mseg       TYPE STANDARD TABLE OF mseg,
       gt_mseg312    TYPE STANDARD TABLE OF mseg,
       gt_iseg       TYPE STANDARD TABLE OF iseg,
       gt_mchb       TYPE STANDARD TABLE OF mchb.

DATA : gt_bmerge TYPE swww_t_merge_table,
       gt_fmerge TYPE swww_t_merge_table,
       gt_body   TYPE swww_t_html_table,
       gt_foot   TYPE swww_t_html_table,
       gt_html   TYPE STANDARD TABLE OF w3html.

DATA : gv_waers TYPE t001-waers,
       gv_mjahr TYPE sy-datum.
