PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPPPDT015 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPPPDT015-AUFNR .
    FIELD ZTSPPPDT015-VORNR .
    FIELD ZTSPPPDT015-ACTWH .
    FIELD ZTSPPPDT015-WADAH .
    FIELD ZTSPPPDT015-TDNAME .
    FIELD ZTSPPPDT015-EQUNR .
    FIELD ZTSPPPDT015-ARBPL .
    FIELD ZTSPPPDT015-BRUTO .
    FIELD ZTSPPPDT015-TARA .
    FIELD ZTSPPPDT015-NETTO .
    FIELD ZTSPPPDT015-MEINS .
    FIELD ZTSPPPDT015-TEMPT .
    FIELD ZTSPPPDT015-TEMME .
    FIELD ZTSPPPDT015-MOIST .
    FIELD ZTSPPPDT015-MOIME .
    FIELD ZTSPPPDT015-EXPDT .
    FIELD ZTSPPPDT015-EXPTM .
    FIELD ZTSPPPDT015-OPERATOR .
    FIELD ZTSPPPDT015-PENGAWAS .
    FIELD ZTSPPPDT015-ERDAT .
    FIELD ZTSPPPDT015-ERTIM .
    FIELD ZTSPPPDT015-TWADAH .
    FIELD ZTSPPPDT015-SCANFL .
    FIELD ZTSPPPDT015-ROOMS .
    FIELD ZTSPPPDT015-DATEF .
    FIELD ZTSPPPDT015-TIMEF .
    FIELD ZTSPPPDT015-LOTNR .
    FIELD ZTSPPPDT015-SCANDT .
    FIELD ZTSPPPDT015-SCANTM .
    FIELD ZTSPPPDT015-FLGHO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPPPDT015-AUFNR .
    FIELD ZTSPPPDT015-VORNR .
    FIELD ZTSPPPDT015-ACTWH .
    FIELD ZTSPPPDT015-WADAH .
    FIELD ZTSPPPDT015-TDNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
