*&---------------------------------------------------------------------*
*&  Include           ZTSPPP_E005NTOP
*&---------------------------------------------------------------------*
TABLES sscrfields.

TYPES : BEGIN OF ty_order,
          check,
          werks     TYPE aufk-werks,
          plnbez    TYPE afko-plnbez,
          fcharg    TYPE resb-charg,
          gstrp     TYPE afko-gstrp,
          aufnr     TYPE afko-aufnr,
          objnr     TYPE aufk-objnr,
          posnr     TYPE afpo-posnr,
          cmatnr(100),
          rspos     TYPE resb-rspos,
          matnr     TYPE resb-matnr,
          charg     TYPE resb-charg,
          count(20),
          qty(20),
          maktx     TYPE makt-maktx,
          rmein     TYPE mara-meins,
          mtart     TYPE mara-mtart,
          packq     TYPE resb-bdmng,
          clabs     TYPE mchb-clabs,
          sisa      TYPE mchb-clabs,
          total     TYPE mchb-clabs,
          bdmng     TYPE resb-bdmng,
          message(125),
          title01(50),
        END OF ty_order.

TYPES : BEGIN OF ty_operation,
          aufnr     TYPE afko-aufnr,
          rsnum     TYPE resb-rsnum,
          rspos     TYPE resb-rspos,
          matnr     TYPE resb-matnr,
          charg     TYPE resb-charg,
          lgort     TYPE resb-lgort,
          vornr     TYPE resb-vornr,
          ltxa1     TYPE afvc-ltxa1,
          usr00     TYPE afvu-usr00,
          clabs     TYPE mchb-clabs,
          meins     TYPE resb-meins,
          bdmng     TYPE resb-bdmng,
          erfmg     TYPE resb-erfmg,
          posnr     TYPE resb-posnr,
          vmeng     TYPE resb-vmeng,
        END OF ty_operation.

TYPES : BEGIN OF ty_material,
          rspos      TYPE resb-rspos,
          matnr      TYPE resb-matnr,
          maktx      TYPE makt-maktx,
        END OF ty_material.

DATA : idx   TYPE i,
       line  TYPE i,
       lines TYPE i,
       limit TYPE i,
       c1    TYPE i,
       n1    TYPE i VALUE 1,
       n2    TYPE i,
       c2    TYPE i,
       n3    TYPE i VALUE 1,
       n4    TYPE i,
       c3    TYPE i,
       n5    TYPE i VALUE 1,
       n6    TYPE i,
       c4    TYPE i,
       n7    TYPE i VALUE 1,
       n8    TYPE i.

DATA : phase          TYPE STANDARD TABLE OF afvc,
       component      TYPE STANDARD TABLE OF resb.

DATA : goodsmvt_header     TYPE bapi2017_gm_head_01,
       goodsmvt_code       TYPE bapi2017_gm_code,
       goodsmvt_headret    TYPE bapi2017_gm_head_ret,
       goodsmvt_item       TYPE STANDARD TABLE OF bapi2017_gm_item_create.

DATA : gt_order       TYPE STANDARD TABLE OF ty_order,
       gs_order       LIKE LINE OF gt_order,
       gt_afpo        TYPE STANDARD TABLE OF afpo,
       gs_head        TYPE ty_order,
       gt_operation   TYPE STANDARD TABLE OF ty_operation,
       gs_operation   LIKE LINE OF gt_operation,
       gt_batch       TYPE STANDARD TABLE OF ty_operation,
       gs_batch       LIKE LINE OF gt_batch,
       gt_material    TYPE STANDARD TABLE OF ty_material,
       gs_material    LIKE LINE OF gt_material,
       gt_label       TYPE STANDARD TABLE OF ztspppst004,
       gt_component   TYPE STANDARD TABLE OF resb,    "bapi_order_component,
       gt_resb        TYPE STANDARD TABLE OF resb,
       gt_yresb       TYPE STANDARD TABLE OF resb,
       gt_xresb       TYPE STANDARD TABLE OF resb,
       gt_afvc        TYPE STANDARD TABLE OF afvc,
       gt_temp        TYPE STANDARD TABLE OF ty_operation,
       gt_mara        TYPE STANDARD TABLE OF resb,
       gt_makt        TYPE STANDARD TABLE OF makt,
       gt_ymara       TYPE STANDARD TABLE OF ty_material,
       gt_mseg        TYPE STANDARD TABLE OF mseg,
       gt_marc        TYPE STANDARD TABLE OF marc.

DATA : ok_code    TYPE sy-ucomm,
       gv_post,
       gv_stock,
       gv_total   TYPE resb-bdmng,
       gv_authorization,
       gv_duplicate,
       gr_lgort   TYPE RANGE OF lgort_d,
       default    TYPE bapidefaul,
       return     TYPE STANDARD TABLE OF bapiret2,
       gv_bdmng   TYPE resb-bdmng,
       gv_nfull   TYPE i,
       gv_mara    TYPE i,
       gv_matnr   TYPE mara-matnr,
       gv_lines   TYPE i,
       gv_confirm,
       gv_meins   TYPE mara-meins,
       gv_print,
       gv_261     TYPE resb-bwart VALUE '261'.

DATA : gr_sttxt   TYPE RANGE OF sttxt.
