PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTSPMMDT002 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTSPMMDT002-WERKS .
    FIELD ZTSPMMDT002-MATNR .
    FIELD ZTSPMMDT002-NIE .
    FIELD ZTSPMMDT002-BTK_SEDIA .
    FIELD ZTSPMMDT002-KOMPOSISI .
    FIELD ZTSPMMDT002-KEKUATAN_SEDIA .
    FIELD ZTSPMMDT002-KEMASAN .
    FIELD ZTSPMMDT002-LIFNR .
    FIELD ZTSPMMDT002-DATAB .
    FIELD ZTSPMMDT002-DATBI .
    FIELD ZTSPMMDT002-TRANDTRC .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTSPMMDT002-WERKS .
    FIELD ZTSPMMDT002-MATNR .
    FIELD ZTSPMMDT002-NIE .
    FIELD ZTSPMMDT002-BTK_SEDIA .
    FIELD ZTSPMMDT002-KOMPOSISI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
