PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTUSFIDT001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTUSFIDT001-BUKRS .
    FIELD ZTUSFIDT001-GSBER .
    FIELD ZTUSFIDT001-LAUFD .
    FIELD ZTUSFIDT001-LAUFI .
    FIELD ZTUSFIDT001-LIFNR .
    FIELD ZTUSFIDT001-ERNAM .
    FIELD ZTUSFIDT001-ERDAT .
    FIELD ZTUSFIDT001-ERZET .
    FIELD ZTUSFIDT001-PAY_DATE .
    FIELD ZTUSFIDT001-BANK_NAME .
    FIELD ZTUSFIDT001-CEK_NUMBER .
    FIELD ZTUSFIDT001-BANK_AC .
    FIELD ZTUSFIDT001-AENAM .
    FIELD ZTUSFIDT001-AEDAT .
    FIELD ZTUSFIDT001-AEZET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTUSFIDT001-BUKRS .
    FIELD ZTUSFIDT001-GSBER .
    FIELD ZTUSFIDT001-LAUFD .
    FIELD ZTUSFIDT001-LAUFI .
    FIELD ZTUSFIDT001-LIFNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
