PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZWMDT001X CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZWMDT001X-MATNR .
    FIELD ZWMDT001X-LGNUM .
    FIELD ZWMDT001X-LGTYP .
    FIELD ZWMDT001X-LGPLA .
    FIELD ZWMDT001X-LPMIN .
    FIELD ZWMDT001X-LPMAX .
    FIELD ZWMDT001X-NSMNG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZWMDT001X-MATNR .
    FIELD ZWMDT001X-LGNUM .
    FIELD ZWMDT001X-LGTYP .
    FIELD ZWMDT001X-LGPLA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
