*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMDT001XTOP.                     " Global Data
  INCLUDE LZWMDT001XUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWMDT001XF00                           . " subprograms
  INCLUDE LZWMDT001XI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMDT001XF...                     " Subprograms
* INCLUDE LZWMDT001XO...                     " PBO-Modules
* INCLUDE LZWMDT001XI...                     " PAI-Modules
