*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMDT001ATOP.                     " Global Data
  INCLUDE LZWMDT001AUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWMDT001AF00                           . " subprograms
  INCLUDE LZWMDT001AI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMDT001AF...                     " Subprograms
* INCLUDE LZWMDT001AO...                     " PBO-Modules
* INCLUDE LZWMDT001AI...                     " PAI-Modules
