PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZWMDT001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZWMDT001-MATNR .
    FIELD ZWMDT001-LGNUM .
    FIELD ZWMDT001-LGTYP .
    FIELD ZWMDT001-LGPLA01 .
    FIELD ZWMDT001-LGPLA02 .
    FIELD ZWMDT001-LGPLA03 .
    FIELD ZWMDT001-LGPLA04 .
    FIELD ZWMDT001-LGPLA05 .
    FIELD ZWMDT001-LPMIN .
    FIELD ZWMDT001-LPMAX .
    FIELD ZWMDT001-NSMNG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZWMDT001-MATNR .
    FIELD ZWMDT001-LGNUM .
    FIELD ZWMDT001-LGTYP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
