PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZWMDT007 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZWMDT007-LGNUM .
    FIELD ZWMDT007-TANUM .
    FIELD ZWMDT007-CATYP .
    FIELD ZWMDT007-GSTRI .
    FIELD ZWMDT007-EBELN .
    FIELD ZWMDT007-EBELP .
    FIELD ZWMDT007-LZNUM .
    FIELD ZWMDT007-MATNR .
    FIELD ZWMDT007-CHARG .
    FIELD ZWMDT007-LFSNR .
    FIELD ZWMDT007-MENGE .
    FIELD ZWMDT007-MEINS .
    FIELD ZWMDT007-MENGE_L .
    FIELD ZWMDT007-MENGE_K .
    FIELD ZWMDT007-MENGE_R .
    FIELD ZWMDT007-NEWCH .
    FIELD ZWMDT007-ZERO .
    FIELD ZWMDT007-RUSAK .
    FIELD ZWMDT007-USNAM .
    FIELD ZWMDT007-GSUZI .
    FIELD ZWMDT007-GLTRI .
    FIELD ZWMDT007-GLUZI .
    FIELD ZWMDT007-MBLNR101 .
    FIELD ZWMDT007-MJAHR101 .
    FIELD ZWMDT007-BASTNO .
    FIELD ZWMDT007-ZCMPLT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZWMDT007-LGNUM .
    FIELD ZWMDT007-TANUM .
    FIELD ZWMDT007-CATYP .
    FIELD ZWMDT007-GSTRI .
    FIELD ZWMDT007-EBELN .
    FIELD ZWMDT007-EBELP .
    FIELD ZWMDT007-LZNUM .
    FIELD ZWMDT007-MATNR .
    FIELD ZWMDT007-CHARG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
