PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZWMDT004 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZWMDT004-LGNUM .
    FIELD ZWMDT004-TKNUM .
    FIELD ZWMDT004-VBELN .
    FIELD ZWMDT004-POSNR .
    FIELD ZWMDT004-LZNUM .
    FIELD ZWMDT004-MATNR .
    FIELD ZWMDT004-CHARG .
    FIELD ZWMDT004-TANUM .
    FIELD ZWMDT004-LFIMG .
    FIELD ZWMDT004-VRKME .
    FIELD ZWMDT004-NEWCH .
    FIELD ZWMDT004-ZERO .
    FIELD ZWMDT004-RUSAK .
    FIELD ZWMDT004-NEWBC .
    FIELD ZWMDT004-NEWSN .
    FIELD ZWMDT004-ZNMULD .
    FIELD ZWMDT004-ZDTSUL .
    FIELD ZWMDT004-ZUZSUL .
    FIELD ZWMDT004-ZDTEUL .
    FIELD ZWMDT004-ZUZEUL .
    FIELD ZWMDT004-MBLNR101 .
    FIELD ZWMDT004-MJAHR101 .
    FIELD ZWMDT004-MBLNR303 .
    FIELD ZWMDT004-MJAHR303 .
    FIELD ZWMDT004-MBLNR343 .
    FIELD ZWMDT004-MJAHR343 .
    FIELD ZWMDT004-MBLNR344 .
    FIELD ZWMDT004-MJAHR344 .
    FIELD ZWMDT004-BASTNO .
    FIELD ZWMDT004-ZCMPLT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZWMDT004-LGNUM .
    FIELD ZWMDT004-TKNUM .
    FIELD ZWMDT004-VBELN .
    FIELD ZWMDT004-POSNR .
    FIELD ZWMDT004-LZNUM .
    FIELD ZWMDT004-MATNR .
    FIELD ZWMDT004-CHARG .
    FIELD ZWMDT004-TANUM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
