PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZWMDT001A CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZWMDT001A-LGNUM .
    FIELD ZWMDT001A-NLTYP .
    FIELD ZWMDT001A-VLTYP01 .
    FIELD ZWMDT001A-VLTYP02 .
    FIELD ZWMDT001A-VLTYP03 .
    FIELD ZWMDT001A-VLTYP04 .
    FIELD ZWMDT001A-VLTYP05 .
    FIELD ZWMDT001A-VLTYP06 .
    FIELD ZWMDT001A-VLTYP07 .
    FIELD ZWMDT001A-VLTYP08 .
    FIELD ZWMDT001A-VLTYP09 .
    FIELD ZWMDT001A-VLTYP10 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZWMDT001A-LGNUM .
    FIELD ZWMDT001A-NLTYP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
