PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZWMPALVND CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZWMPALVND-LGNUM .
    FIELD ZWMPALVND-MATNR .
    FIELD ZWMPALVND-LIFNR .
    FIELD ZWMPALVND-ZLEVEL .
    FIELD ZWMPALVND-LPTYP .
    FIELD ZWMPALVND-LEQTY .
    FIELD ZWMPALVND-MEINS .
    FIELD ZWMPALVND-LETYP .
    FIELD ZWMPALVND-TARAW .
    FIELD ZWMPALVND-GEWEI .
    FIELD ZWMPALVND-FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZWMPALVND-LGNUM .
    FIELD ZWMPALVND-MATNR .
    FIELD ZWMPALVND-LIFNR .
    FIELD ZWMPALVND-ZLEVEL .
    FIELD ZWMPALVND-LPTYP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
