*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMPALVNDTOP.                     " Global Data
  INCLUDE LZWMPALVNDUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWMPALVNDF00                           . " subprograms
  INCLUDE LZWMPALVNDI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMPALVNDF...                     " Subprograms
* INCLUDE LZWMPALVNDO...                     " PBO-Modules
* INCLUDE LZWMPALVNDI...                     " PAI-Modules
